### ISSUE TITLE
Fresher ASN data, utilized better

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1008]
[cymru](https://www.team-cymru.org/IP-ASN-mapping.html) has some excellent links to the sources of their IP to ASN data. With a little bit of cleverness and elbow grease, that data could be used to:

* generate a DB of all ASNs (~60,000 announced at any given time, plenty more)
* use CIDR-report, SWIP, and rwhois to cross reference ASNs to organizations
* cross reference `asn_all_bad` hits against organizations and proactively penalize all the ASNs that are allocated to organizations currently detected spamming.

**Comment by smfreegard** [comment]
How are you going to overcome the rate limiting and ban on automated queries for SWIP and rwhois?

BTW - here's another ASN source that provides better data than the existing:

$ host -t TXT 231.122.223.63.origin.asn.shadowserver.org
231.122.223.63.origin.asn.shadowserver.org descriptive text "3491" "|" "63.223.64.0/18" "|" "BTN-ASN" "|" "US" "|" "comcastbusiness.net" "|" "Private" "Customer"

**Comment by msimerson** [comment]
> How are you going to overcome the rate limiting and ban on automated queries for SWIP and rwhois?
> 
The same way I'm doing it now (different project), never make more than one request per second to any given server. There aren't that many active ASNs so the number of whois queries is going to be pretty small.

Matt

**Comment by msimerson** [comment]
Moved to [idea](https://github.com/haraka/Haraka/wiki) section of the wiki.
