### ISSUE TITLE
Content Scanning Server

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1032]
Having recently tested AVG, and started testing ESET, and with Kaspersky testing on my TODO list, it occurred to me that a Reasonably Good Idea would be a little node.js http server that:

1. accepts a HTTP request (params in HTTP headers, email message in HTTP body)
2. runs that message past as many content scanners as are requested (default: all) or as many are configured.
3. Returns a JSON result with the scan results from each scanner

### Pros
* Haraka would need only a very simple data_post plugin
* Scan the message against many scanners concurrently (default: 1 per CPU). This would be faster than Haraka plugins which execute serially, or SMTP pipelines.
* Other MTAs could use this
* Faster and more efficient: rather than streaming the message via TCP to each content scanner (once for SA, once for ClamAV, once for ....), this would stream the content once via TCP, and then this little server would use the file system or Unix Domain Sockets to pass the message to each content scanner.
* Haraka could load balance requests to a pool of these scanning hosts.

### Cons
* requires time and effort

### Planned Initial Content Scanner Support
* ClamAV
* AVG
* ESET
* Kaspersky
* SpamAssassin

### Potential Future Additions
* dcc
* messagesniffer
* dspam
* VirusTotal (see also #1124)

**Comment by msimerson** [comment]
* Requests can be run according to preferences:
    * async.each: most efficient, as soon as any scanner says "junk," end processing
    * async.parallel: best for raw speed and measuring scanner efficacy (all scanners get run, compare results of each)

**Comment by Dexus** [comment]
Hey, if you have a repository i will help you. I can help to add other av services etc.

**Comment by msimerson** [comment]
@Dexus , I created [the repo here](https://github.com/haraka/haraka-content-scanning-server). Thanks for helping!

**Comment by Dexus** [comment]
@msimerson Do you already have a project initialization performed? Or can I start directly and make an init commit?

**Comment by msimerson** [comment]
not yet, go ahead.

**Comment by msimerson** [comment]
This idea [is growing over here](https://www.github.com/cloud-css/ess/)

![web ui](https://cloud.githubusercontent.com/assets/261635/11041232/6828a726-86c5-11e5-8203-68e1968e05d6.png)
