### ISSUE TITLE
TLS in outbound: make it configurable

### ISSUE THREAD

**Issue by celesteking** [haraka/Haraka#1054]
```
outbound	Looking up A records for: j.mx.utoronto.ca
outbound	Ongoing connection failed to 128.100.132.12:25 : Error: 140665633523680:error:14082174:SSL routines:SSL3_CHECK_CERT_AND_ALGORITHM:dh key too small:s3_clnt.c:3331:
```

We need to:
* Have configurable list of TLS disabled hosts/subnets (like in tls.ini?)
* Maybe don't screw the session if host didn't negotiate TLS, but fallback to plain text (should be configurable)
* add DH and cipher params, possibly with per-host/subnet option

**Comment by celesteking** [comment]
Actually, this now seems like a serious issue. Our clients are losing mail because recent openssl doesn't want to negotiate DH with keys <= 512 bits. Thus, with TLS in outbound enabled, clients getting bounce notices with "Failure Reason: Error: Too many failures (Tried all MXs)".

**Comment by smfreegard** [comment]
> Have configurable list of TLS disabled hosts/subnets (like in tls.ini?)

You mean like this? https://github.com/baudehlo/Haraka/blob/master/docs/plugins/tls.md#no_tls_hosts

> Maybe don't screw the session if host didn't negotiate TLS, but fallback to plain text (should be configurable)

This isn't possible; if negotiation fails; both ends are in an unknown state.

> add DH and cipher params, possibly with per-host/subnet option

You mean like this?  https://github.com/baudehlo/Haraka/blob/master/docs/plugins/tls.md#ciphers

**Comment by celesteking** [comment]
That would be the first step. I'd like to see per-host/subnet options available.

**Comment by celesteking** [comment]
Come on, guys, don't you use TLS in outbound? If so, you've got hell lot of mail staying in queue and ultimately failing.

**Comment by baudehlo** [comment]
The options Steve pointed out are for inbound. We need to read that config
for outbound too.

**Comment by celesteking** [comment]
A clear testcase would be sending mail to **any@null.fused.ws** . Try it.

**Comment by celesteking** [comment]
And yet again... How does that commit prevent outbound from making repeated STARTTLS to remote MTA? ```redis.disable_for_failed_hosts``` won't be consulted.

**Comment by baudehlo** [comment]
It won't. Who said I was fixing that?

**Comment by celesteking** [comment]
Implemented in https://github.com/celesteking/Haraka/pull/2
0 production testing so far.
