### ISSUE TITLE
Strange behaviour when spooling to disk

### ISSUE THREAD

**Issue by barthinho** [haraka/Haraka#1083]
Hi,

if i am using spooling to disk, all messages haraka sends are broken (attachment is missing).

As far as see it right know, the message (body) is not getting fully read. Am i missing something or did anyone else experienced a simliar issue?

thx in advance

**Comment by smfreegard** [comment]
No - it should 'just work'.   I haven't tested the spool to disk functionality for some time, so it could be that it's gotten broken somehow.   I'll try and take a look at it when I have a bit more time.

**Comment by bnusunny** [comment]
I have the same problem. The message is not fully read if spooled to disk. However this does not happend to all  spooled messages. It is random in my case. 

Please do help to look at this issue as we don't want to take this risk in the production.

**Comment by baudehlo** [comment]
We need more configuration information to test this. Plugins enabled, including custom plugins source code.

**Comment by baudehlo** [comment]
Since we never got more info, I'm closing this.
