### ISSUE TITLE
Add support for tls.TLSSocket

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#1099]
Currently we use tls_socket.js which is a bit of a hack to allow the upgrade of a regular socket to a TLS encrypted socket when STARTTLS is called.

In Node 0.12 or greater and in io.js you can call `new tls.TLSSocket(socket, options)` where `socket` is an instance of `net.Socket` to upgrade the socket to a TLSSocket.  See https://iojs.org/api/tls.html#tls_class_tls_tlssocket

**Comment by msimerson** [comment]
fixed by #1672
