### ISSUE TITLE
GMail Blocked My IP

### ISSUE THREAD

**Issue by hardiyanto33** [haraka/Haraka#1204]
I am newbie on mail server. I try to use Haraka as SMTP server. I could send testing mail with swaks to my GMX mail, but I could not send to my Gmail. 

Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] C: EHLO vmHaraka
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250-mx.google.com at your service, 

[202.152.24.146]\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250-SIZE 35882577\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250-8BITMIME\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250-STARTTLS\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250-ENHANCEDSTATUSCODES\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250-PIPELINING\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250-CHUNKING\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250 SMTPUTF8\r\n
Oct  7 05:49:53 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] C: MAIL FROM:<hardi@mydomain.id>
Oct  7 05:49:54 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250 2.1.0 OK ue10si56445525pbc.215 - gsmtp\r\n
Oct  7 05:49:54 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] C: RCPT TO:<myaccount@gmail.com>
Oct  7 05:49:54 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 250 2.1.5 OK ue10si56445525pbc.215 - gsmtp\r\n
Oct  7 05:49:54 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] C: DATA
Oct  7 05:49:54 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 354  Go ahead ue10si56445525pbc.215 - gsmtp\r\n
Oct  7 05:49:54 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] C: .
Oct  7 05:49:57 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 550-5.7.1 [202.152.24.146       1] Our system has 

detected an unusual rate of\r\n
Oct  7 05:49:57 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 550-5.7.1 unsolicited mail originating from your 

IP address. To protect our\r\n
Oct  7 05:49:57 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 550-5.7.1 users from spam, mail sent from your IP 

address has been blocked.\r\n
Oct  7 05:49:57 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 550-5.7.1 Please visit\r\n
Oct  7 05:49:57 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 550-5.7.1  

https://support.google.com/mail/answer/81126 to review our Bulk Email\r\n
Oct  7 05:49:57 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] S: 550 5.7.1 Senders Guidelines. 

ue10si56445525pbc.215 - gsmtp\r\n
Oct  7 05:49:57 vmHaraka haraka[2438]: [PROTOCOL] [12E7D567-F712-4AC4-88F2-A9ABED95AB8F.1.1] [outbound] C: QUIT

Please help.
Thanks.

**Comment by Dexus** [comment]
Hi,
do you read https://support.google.com/mail/answer/81126?

Are you sending via IPv6? Or only IPv4?
What is with your rDNS of the used IP? Do you use SPF and DKIM?
A other point you don't set your hostname right... vmHaraka is not the right hostname for use... `vmharaka.yourdomain.com` will be a better and recommend value.

**Comment by hardiyanto33** [comment]
I use IP4 only and didn't use SPF and DKIM. I already have another mail server that running well and Google didn't blocked my IP. I built it with ISPconfig, include Postfix and Dovecot.
I don't know about Haraka. What configuration that needed to be a mail server properly. I choose Haraka because we can customized the application with JS.

**Comment by hardiyanto33** [comment]
From this information, https://github.com/haraka/Haraka/issues/4, Haraka doesn't do queueing of outbound mails. So I forward to another mail server, but I didn't receive the email.

[INFO] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] forwarding to 192.168.1.240:25
[INFO] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] dispense() clients=1 available=0
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] createResource() - creating obj - count=1 min=0 max=1000
[DEBUG] [-] [core] [smtp_client_pool] uuid=E78FF41C-F5DB-4B9B-B549-4F8CEAC29124 host=192.168.1.240 port=25 pool_timeout=300 created
[DEBUG] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] Got smtp_client: E78FF41C-F5DB-4B9B-B549-4F8CEAC29124
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 220 domain.id SMTP Server (JAMES SMTP Server 2.3.2) ready Thu, 8 Oct 2015 12:23:59 +0700 (WIB)\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] C: EHLO vmHaraka
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250-skywave.id Hello vmHaraka (192.168.1.241 [192.168.1.241])\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250-AUTH LOGIN PLAIN\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250-AUTH=LOGIN PLAIN\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250-PIPELINING\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250 ENHANCEDSTATUSCODES\r\n
[DEBUG] [-] [core] [smtp_client_pool] uuid=E78FF41C-F5DB-4B9B-B549-4F8CEAC29124 authenticating as "hardi"
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] C: AUTH PLAIN aGFyZGkAaGFyZGkAaGFyZGl5YW50bw==
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 235 Authentication Successful\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] C: MAIL FROM:<hardi@domain.id>
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250 2.1.0 Sender <hardi@domain.id> OK\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] C: RCPT TO:<hardiyanto@client.id>
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250 2.1.5 Recipient <hardiyanto@client.id> OK\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] C: DATA
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 354 Ok Send data ending with <CRLF>.<CRLF>\r\n
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [queue/smtp_forward] S: 250 2.6.0 Message received\r\n
[INFO] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] hook=queue_outbound plugin=queue/smtp_forward function=hook_queue_outbound params="" retval=OK msg="2.6.0 Message received (1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1)"
[DEBUG] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] running queue_ok hooks
[NOTICE] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] queue_ok code=CONT msg="2.6.0 Message received (1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1)"
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] S: 250 2.6.0 Message received (1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1)
[DEBUG] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] running reset_transaction hooks
[DEBUG] [-] [core] [smtp_client_pool] E78FF41C-F5DB-4B9B-B549-4F8CEAC29124 resetting, state=2
[DEBUG] [-] [core] [smtp_client_pool] E78FF41C-F5DB-4B9B-B549-4F8CEAC29124 releasing, state=3
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] timeout: 1444282143116
[INFO] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] dispense() clients=0 available=1
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] availableObjects.length=1
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] availableObjects.length=1
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] C: QUIT state=1
[DEBUG] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] running quit hooks
[PROTOCOL] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] S: 221 vmHaraka closing connection. Have a jolly good day.
[DEBUG] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] running disconnect hooks
[NOTICE] [1ABE124E-44A0-42DA-BA3D-44FA25936BBD.1] [core] disconnect ip=192.168.1.211 rdns="DNSERROR" helo="vmbackupwin2" relay=Y early=N esmtp=Y tls=N pipe=N txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=2824 lr="" time=2.722
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] availableObjects.length=1
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] availableObjects.length=1
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] availableObjects.length=1
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] availableObjects.length=1
[DEBUG] [-] [core] [smtp_client_pool] [25:192.168.1.240:300] availableObjects.length=1

**Comment by Dexus** [comment]
any logs from the other mail server? 
And please use pastebin or gist for your logs, or insert in an markdown code block (see: https://guides.github.com/features/mastering-markdown/)

**Comment by hardiyanto33** [comment]
Log from other mail server is relay denied. I've fixed this. Now everything is okay, although my email on Gmail is stored in Spam folder.
So for outbound mail, we should forward it to another MTA? Haraka couldn't do it by it self.

**Comment by smfreegard** [comment]
Haraka can do it by itself.  All you need to do is remove queue/smtp_forward from your config/plugins file and it will queue and deliver mail to the destination MX as you would expect.

As for hitting GMail's spam folder - you should set-up SPF for your domain as Google does not treat unauthenticated connections very well.   See https://googleonlinesecurity.blogspot.co.uk/2013/12/internet-wide-efforts-to-fight-email.html

**Comment by smfreegard** [comment]
Oh - and set-up a proper hostname for your machine.   It should be an FQDN and it should match the PTR record of the external IP address.

**Comment by hardiyanto33** [comment]
All my issues already fixed. Thank you all.
