### ISSUE TITLE
Auth - Support SCRAM-*

### ISSUE THREAD

**Issue by Dexus** [haraka/Haraka#1214]
Support the SCRAM-SHA-1(-PLUS), SCRAM-SHA-256(-PLUS) etc.

Infos:
https://tools.ietf.org/html/rfc5802
https://datatracker.ietf.org/doc/draft-hansen-scram-sha256/
http://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml

**Comment by msimerson** [comment]
migrated to [wiki](https://github.com/haraka/Haraka/wiki)

**Comment by Neustradamus** [comment]
Any news for SCRAM?

SCRAM-SHA-1 and SCRAM-SHA-1-PLUS:
- https://tools.ietf.org/html/rfc5802

SCRAM-SHA-256 and SCRAM-SHA-256-PLUS:
- https://tools.ietf.org/html/rfc7677
