### ISSUE TITLE
Plugin command line mode

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#1220]
This would optionally allow a plugin to implement command-line functions for manual testing and additional utilities.

Via  `haraka -c /etc/haraka --plugin-cli <plugin name> <args>`

e.g.

```
$ haraka -c /etc/haraka --plugin-cli check_mx
Usage: check_mx [--debug] <domain> 
$

$ haraka -c /etc/haraka --plugin-cli check_mx fsl.com
82.69.13.196    (home.freegard.name)
23.21.188.50    (mail1-ec2.fsl.com)
```

Or

```
$ haraka -c /etc/haraka --plugin dkim_verify
Usage: dkim_verify [--debug] <file>
$

$ haraka -c /etc/haraka --plugin-cli dkim_verify /tmp/foo.msg
identity="@facebookmail.com" domain="facebookmail.com" selector="s1024-2013-q3" result=pass
$
```

```
$ haraka -c /etc/haraka --plugin spamassassin
Error: plugin 'spamassassin' does not implement --plugin-cli
```

**Comment by soundslocke** [comment]
:+1:

**Comment by Dexus** [comment]
:+1:

**Comment by msimerson** [comment]
Closed by #925

**Comment by msimerson** [comment]
Another way to test plugins now is via the end-to-end tests in server.js. It uses the test files in `test/config` instead. Either by rewriting that `test/config/plugins`, or by making it easier to overload the list of plugins, we could test a single plugin at a time, in a live haraka instance.

**Comment by smfreegard** [comment]
That's not really what this was about.   This was more about exposing useful command-line utilities using the plugins functionality.   e.g. like checking SPF, DNSBL lookups etc. etc.

**Comment by msimerson** [comment]
Migrated to [wiki](https://github.com/haraka/Haraka/wiki)
