### ISSUE TITLE
Haproxy  In haraka

### ISSUE THREAD

**Issue by vivek779** [haraka/Haraka#1223]
hey all 
I was working  Haproxy for creating load balancer i have read the documentation
https://github.com/haraka/Haraka/blob/master/docs/HAProxy.md
With help of these i started with creating two server master with all haproxy configuration and slave on whom haproxy will send  for load balancing so  i edited configuration file of haproxy   like this

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    20s
    timeout queue           84600
    timeout connect         84600
    timeout client          84600
    timeout server          84600
    timeout http-keep-alive 84600
    timeout check           84600
    maxconn                 50000
listen smtp :25
mode tcp
option tcplog
option tcp-check
balance roundrobin
server haraka1 x.x.x.150:25
then i created  a haproxy_hosts file add the ip in it
x.x.x.150:25
when  i run the master server it ok nothing new is shown
bt when i start the slave server it gives errors like this

[PROTOCOL] [0C51DD7B-D27A-4EF1-B017-6EA894459029] [core] S: 220 net.wayhome.in ESMTP Haraka 2.7.0 ready
[PROTOCOL] [0C51DD7B-D27A-4EF1-B017-6EA894459029] [core] C: PROXY TCP4  168.235.86.150 45584 25 state=1
[PROTOCOL] [0C51DD7B-D27A-4EF1-B017-6EA894459029] [core] S: 421 PROXY not allowed from 168.235.86.150
[
so I created a haproxy_hosts file in slave server and mention the  master haproxy error
it shows error like thease
[PROTOCOL] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] C: PROXY TCP4 168.235.86.221 168.235.86.150 51015 25 state=1
[INFO] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] HAProxy: proto=TCP4 src_ip=168.235.86.221:51015 dst_ip=168.235.86.150:25
[DEBUG] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] running connect_init hooks
[DEBUG] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] running connect_init_respond
[DEBUG] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] running lookup_rdns hooks
[DEBUG] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] running connect hooks
[PROTOCOL] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] S: 220 net.wayhome.in ESMTP Haraka 2.7.0 ready
[PROTOCOL] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] C: HELO localhost state=1
[DEBUG] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] running helo hooks
[PROTOCOL] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] S: 250 net.wayhome.in Hello [168.235.86.221], Haraka is at your service.
[INFO] [1C068BCB-DD7A-4AC5-A91A-B3D8FE85F3D3] [core] client [168.235.86.221] connection error: Error: read ECONNRESET
 i read the document carefully and find that we have to use option tcp_checkl  so i edited and use tcp-check instead of tcp_chk  in master haproxy configuration bt i shows only 

                                 DEBUG] [282E3109-E2A5-4B29-B2F4-8D783F2C1651] [core] setupClient got no IP address for this connection!

please guide me what mistakes i am doing

**Comment by vivek779** [comment]
Hello haraka team I was working on haproxy  is there any way to use authentication before sending proxy .
what i want authentication of user and pasword is done by haproxy and mail sending part is done slave haraka server please guide

**Comment by Dexus** [comment]
As i know its not possible. But you can use nginx as mail proxy and do the auth stuff with it and a external script.

**Comment by vivek779** [comment]
yes i am using nginx also as a load balancer bt not able to figure it how to apply authentication could you please guide where i should look

**Comment by Dexus** [comment]
Please read the docs from nginx! There are working examples. 

Von meinem iPhone gesendet
