### ISSUE TITLE
Rate Limit For Single user and Total limit

### ISSUE THREAD

**Issue by Manojkumar09** [haraka/Haraka#1224]
Hi all
I am trying to set rate limit for single user. I have 2 users in my file-

manoj
hsmt

I have installed rate limit plugin and i see that there is limit for some things like 
domian limit for particular interval of time 

I am running this plugin successfully but this is not i want. I want to limit max connections for manoj and for hsmt different-2.

Like Manoj can send 100 emails and hsmt can send 200 emails from any sender id  or domain id they want but limit should not exceed from 100 and 200.

And i would be  able to set total limit for user not days wise limit ar hour wise limit

**Comment by Dexus** [comment]
hey,

okay the user auth against port 587 as manoj or hsmt right?

And you will that each user have it's own "One-Time" limit for outbound mails. Also you will limit the max connections for each user.

I'm so far right?

**Comment by Manojkumar09** [comment]
Hello dexus,
Yes you have got my point i want to set limit for each user against auth.

**Comment by ruandao** [comment]
@Manojkumar09   may be you can manual write plugin to do that,  https://haraka.github.io/manual/Tutorial.html

**Comment by Manojkumar09** [comment]
Thanks for suggestion @ruandao . I tried my best  to write the plugin i use the base code rate_limit.js  and tried to modify  it for my requirement bt couldn't get the results i am not a good node.js developer that's why i requested for help and add bounty on it .
