### ISSUE TITLE
the way to deploy haraka?

### ISSUE THREAD

**Issue by ruandao** [haraka/Haraka#1227]
How to deploy haraka on ubuntu?

direct run `sudo haraka -c /path/to/project`
or use `contrib/ubuntu-upstart/haraka.conf`
or use some else?

Should i collect the crash log?

**Comment by Dexus** [comment]
Please see: https://github.com/haraka/Haraka/wiki/Ubuntu-14.04

**Comment by ruandao** [comment]
thank you.

**Comment by ruandao** [comment]
when install [http-server](https://github.com/haraka/Haraka/wiki/Ubuntu-14.04#http-server)  
I found that the [Haraka/http-server](https://raw.githubusercontent.com/msimerson/Haraka/http-server) was lost

**Comment by Dexus** [comment]
the http-server ist build in, you need to listen on port 80 to see it. also you need plugins that use http-server.
read our docs for more informations. If you have any question @msimerson will your partner for http questions.

**Comment by ruandao** [comment]
thank you
