### ISSUE TITLE
Logos for Haraka

### ISSUE THREAD

**Issue by Dexus** [haraka/Haraka#1233]
Here some logos, that a good friend made, what do you think?

__1)__
![harakamail01](https://cloud.githubusercontent.com/assets/1674289/10715099/4c155222-7b09-11e5-8485-a294f09df64e.png)
__2)__
![harakamail02](https://cloud.githubusercontent.com/assets/1674289/10715100/4c1e1cf4-7b09-11e5-9e2e-908a4c411e36.png)
__3)__
![harakamail03](https://cloud.githubusercontent.com/assets/1674289/10715098/4c151e56-7b09-11e5-9b7e-76ac1980835f.png)

[Logos_Haraka_Mail_Pfade_finale.pdf](https://github.com/haraka/Haraka/files/20233/Logos_Haraka_Mail_Pfade_finale.pdf)

**Comment by smfreegard** [comment]
I think my favourite is 1, I like 2 though, not so keen on 3.

**Comment by msimerson** [comment]
Nice @Dexus , not only do we finally have a logo, we get to choose from three! 

I don't like that 1 is so reminiscent of the Thunderbird and FireFox logos, and I'd avoid it for that reason alone. I like 2 better than 3, mainly for versatility. Move the words around a little and voila, a square logo \ for favicon and other places where that's necessary.

**Comment by Dexus** [comment]
number 2 like:

![harakamail02a](https://cloud.githubusercontent.com/assets/1674289/10737764/50c27ba4-7c14-11e5-8ff7-9a2a07c01c50.png)

i like 1 and 2, maybe 2 little bit more than 1 ('cause the same minds @msimerson)

btw thanks @msimerson its not frome me - its from a friends, that i help some time - now he was the helped guy.

__Current Result:__
For 2 = 3 Votes
For 1 = 3 Votes (baudehlo in #haraka Chan)

**Comment by Infern1** [comment]
My favorite order:
2 , 1, 3

**Comment by niieani** [comment]
My order  2, 1, 3.

**Comment by msimerson** [comment]
I have adopted 2 as the preferred logo and updated the npm haraka user (gravatar) with the logo as well as our [GitHub account](https://github.com/haraka) picture.

Thanks again @Dexus
