### ISSUE TITLE
How to modify Content-Type header inside a multipart/alternative email?

### ISSUE THREAD

**Issue by melimanrique** [haraka/Haraka#1236]
I have a plugin that modifies the Content-Type header in order to ensure ``UTF-8`` encoding in all emails. Like this: 
```js
//Removing text plain header
connection.transaction.remove_header("Content-Type");

//Applying text/html header
connection.transaction.add_header("Content-Type", 'text/html; charset="utf-8"');
```

However, this works for ``text/html`` or ``text/plain`` emails only. But with ``multipart/alternative`` emails I have to change the header inside every children. Does anyone know how can I modify children's headers?

**Comment by melimanrique** [comment]
@Dexus @baudehlo @smfreegard

**Comment by baudehlo** [comment]
You can't, because providing the ability to do so would require us
re-writing every email every time. We only re-write the (main) headers.

**Comment by melimanrique** [comment]
@baudehlo 
Oh okay :disappointed: 
What about using something like ``add_body_filter()`` but for filtering children's headers in order to modify them? Is there something like that?
