### ISSUE TITLE
Identify a header in data event

### ISSUE THREAD

**Issue by melimanrique** [haraka/Haraka#1237]
I have a plugin that needs to identify a header to use it in data event but ``connection.transaction.header.get("Content-Type");`` doesn't retrieve anything. 

Is there a way to get that header in data or previously?

Thanks!

**Comment by baudehlo** [comment]
No, it hasn't been sent yet. We haven't mastered time travel yet :)

**Comment by melimanrique** [comment]
@baudehlo Oh I didn't know that! Thanks 

Now, I have the need to modify parts of the body using ``add_body_filter()`` according to some information that's included in a header. 

Could you help me to figure out in which event should I do so?

**Comment by msimerson** [comment]
@melimanrique, are you still needing assistance here?

**Comment by msimerson** [comment]
If so, reopen.
