### ISSUE TITLE
Should dnsbl allow authenticated requests?

### ISSUE THREAD

**Issue by tino** [haraka/Haraka#1241]
Right now the default for dnsbl is `reject=true`, this means even the STARTTLS command of my mail program is dropped with a `554 host [14.169.41.47] is blacklisted by zen.spamhaus.org` when I a try to send mail from my local computer through my own server.

Spamhaus states about this blacklisting:

> Help! My IP address is on the PBL! What should I do?
Nothing, in most cases. Read through this FAQ for further explanations.
>
> The first thing to know is: THE PBL IS NOT A BLACKLIST. You are not listed for spamming or for anything you have done. The PBL is simply a list of all of the world's dynamic IP space, i.e: IP ranges normally assigned to ISP broadband customers (DSL, DHCP, PPP, cable, dialup). It is perfectly normal for dynamic IP addresses to be listed on the PBL. In fact all dynamic IP addresses in the world should be on the PBL. Even static IPs which do not send mail should be listed in the PBL. 
>
> PBL listings do not prevent you sending email unless your email program is not authenticating properly when it connects to your ISP or to your company's mail server. This can happen if you have forgotten to turn on 'SMTP Authentication' or if you have switched 'SMTP Authentication' off by mistake. 
>
> If you are using a normal email program such as Outlook, Entourage, Thunderbird or Apple Mail and you are being blocked by a Spamhaus PBL listing when you try to send email, the reason is simply that YOU NEED TO TURN ON 'SMTP AUTHENTICATION' in your email program's account settings. That will solve the problem for you. See: How do I turn on SMTP Authentication? 
> 
> Server admins who need help with SMTP AUTH can find lots of information for most servers such as Sendmail, Postfix, Exim, Qmail, Exchange, etc.

So in my opinion, dnsbl should only work on non-authenticated requests.

**Comment by Dexus** [comment]
Hi, 
Please dont send mails to port 25, listen also to 587 and send via this port.


Von meinem iPhone gesendet

**Comment by tino** [comment]
Ah, your right. Apple Mail kept changing my connection to 25 automatically...
