### ISSUE TITLE
dkim_sign and case sensitiveness in From: Header

### ISSUE THREAD

**Issue by canau** [haraka/Haraka#1250]
The manual says to create the dir "example.org" to setup the dkim files for the domain.
If the user domain in the From: header doesn't match the same case of the directory name I get the error:

[dkim_sign] skipped: missing dkim private key

The strace output (domain dir is "canau.eu"):

[pid 11602] stat("/opt/haraka-outbound/config/dkim/Canau.EU", 0x2563988) = -1 ENOENT (No such file or directory)
[pid 11599] stat("/opt/haraka-outbound/config/dkim/EU",  <unfinished ...>

(follows the logic in dkim_sign.js).

Even if following/forcing some RFC in case usage, I think that the user From: must be protected and dealt with -or- the manual page should reflect the case logic.

Thank you.
Canau

**Comment by msimerson** [comment]
Hi @canau , can you please test the changes in #1251 and verify they resolve this issue?

**Comment by canau** [comment]
@msimerson tested and verified. Thanks!
