### ISSUE TITLE
`hook_rcpt` from in_host_list plugin returns without calling next

### ISSUE THREAD

**Issue by dminkovsky** [haraka/Haraka#1253]
Hi, 

Very new to this codebase, so I am sorry if this is a false flag, which it probably is.

But, I noticed [this line](https://github.com/haraka/Haraka/blame/fa6b06129e5f5f7355fd401ce3201cf205dce58d/plugins/rcpt_to.in_host_list.js#L23) returns from a plugin without calling `next()`. 

Is this a bug? If not, what's the point of doing this?

Thanks you.

**Comment by baudehlo** [comment]
There are some situations where the transaction can go away while in a
hook. It's a bit weird and we should probably protect against it elsewhere,
but this is just a safety check. Once this happens and this situation
arises there's no point calling next().

**Comment by dminkovsky** [comment]
Does it make sense for it to be `next(ERR)` where `ERR` is some error code? If the check fails, won't the `return` without `next()` cause a wait until hook time expires?

**Comment by baudehlo** [comment]
Maybe. I'm not really sure of the consequences at this point.

**Comment by dminkovsky** [comment]
Cool! Thanks.
