### ISSUE TITLE
Login Failed after sending 10 mails

### ISSUE THREAD

**Issue by vivek779** [haraka/Haraka#1260]
Hello i was working authorization  plugin  which uses database to fetch users and password but after sending 10 mails it shows 
[CRIT] [9899600D-EDA0-4675-B1BA-9CD36D1AFB07] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback

I am not bale to figure it out how to solve this problem please guide me 
Here it is my code http://pastebin.com/jdxHtVED

**Comment by Dexus** [comment]
hey, i think your mysql connection is gone. try to "ping" the connection with a interval (if ping fail reconnect) or create and close the connection to mysql each login...

**Comment by Dexus** [comment]
I think i can close it. If not, write here and dont open a new issue.
