### ISSUE TITLE
Mails queuing fails with 5xx when there is no disk space

### ISSUE THREAD

**Issue by abhas** [haraka/Haraka#1263]
When Haraka is receiving incoming mails for delivery and there is not disk space on the partition to store the mail in the queue, Haraka returns a 5xx error to the sending MTA which results in a permanent rejection of the mails.

Instead it should return a 4xx erorr code so that once the prolem is fixed, the sending MTA will retry sending mails to Haraka.

Due to disk issues on a server, I had Haraka permanently reject emails to the senders citing queuing failures.

**Comment by smfreegard** [comment]
I ran into this myself yesterday - not disk space, but permissions on the queue directory.  I'll be working on a fix first thing tomorrow.

**Comment by abhas** [comment]
Thanks a lot @smfreegard!

**Comment by vivek779** [comment]
hello i was working on haraka 
how do we set different queue for different users ? for eg If i set different users in auth_flat_file and  whenever I  tries to send mails from that user credentials the undelivered mails are stored in different users queue right now all mails  is stored in an common queue in queue folder please guide me for like which conf file i should look ar anything i should focused
