### ISSUE TITLE
xclient plugin configuration file

### ISSUE THREAD

**Issue by garnieretienne** [haraka/Haraka#1265]
Hi, 

In the doc of the plugin and in the sample config files, the config file for the xclient plugin is called `xclient.hosts.ini`.

I can only have it working when its named `xclient.hosts` (see: https://github.com/haraka/Haraka/blob/master/plugins/xclient.js#L25).

I can create a pull request to update the plugin doc and sample config file if you confirm it's a bug and not an error on my deployment.

**Comment by msimerson** [comment]
That's definitely a bug and a PR that updates the docs would be great.
