### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by pjebs** [haraka/Haraka#1283]
Is it possible to use haraka to create an email forwarding service where the incoming address is mapped to the forwarding address which are all stored in MySQL and can change as more addresses are added to the database.

If so, how can I do it?

**Comment by Dexus** [comment]
Yes its possible you need only create your own plugin for your needs

Von meinem iPhone gesendet

**Comment by pjebs** [comment]
Do you think it would be difficult to create a plugin?
I'd assume that it is common enough that there might already be a plugin somewhere.

**Comment by pjebs** [comment]
Does this look like it:

https://github.com/mazelab/haraka-plugins

https://github.com/jcowgar/haraka-plugins

**Comment by pjebs** [comment]
Would I need to use Postfix to perform the actual forwarding (i.e. resend the incoming emails to new address or is different to 'relaying')?

**Comment by baudehlo** [comment]
No you can just set the transaction to relaying and Haraka will forward them for you.

In a way it's similar to how the mailing list software works. See the source on github. It talks to Postgres not MySQL but same difference really.

**Comment by pjebs** [comment]
Is relaying equivalent to haraka receiving email and then re sending the email to the forwarding email address?

Or does it just 'transfer' through rather than resending ?

**Comment by pjebs** [comment]
Am I on the right track with the relay plugin?

**Comment by baudehlo** [comment]
Relaying is safe in that it uses outbound mechanisms (including retrying on failure).

That might not be what you're asking so you may want to try and rephrase.

**Comment by baudehlo** [comment]
No write your own plugin from scratch. It's not that hard.
