### ISSUE TITLE
Different outbound server based on user

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1284]
Hey. I use Haraka as intermediate server. It receives an email, modify it, and send it back to the server of the company. I would need to use different outbound sever based on each user.

Any advices?

Thank you :)

**Comment by msimerson** [comment]
You want to send the modified email back to the sender?

Have a look at the rcpt_to.routes.js plugin, which sets up SMTP routes based on the recipient. You can modify it to instead look up SMTP routes based on the sender.

**Comment by ricardopolo** [comment]
No back to sender, to the recepitment.  Imagine add a banner.

**Comment by ricardopolo** [comment]
I will do it using the get_mx hook. Thank you
