### ISSUE TITLE
Memory leak with transaction.notes

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1291]
I want to write the attachments content in the notes of the transaction. I know I can save the path in the notes instead of the full content but I prefer it this way, because I prefer to use the automatic clean option of the `tmp` library. If not I would need delete the file for myself later..

So I do something like these in the `data` event:
````js
exports.save_attachments = function(next, connection){
  var transaction = connection.transaction;
  transaction.notes.attachments = [];
  transaction.attachment_hooks(
    function (ct, fn, body, stream) {
      stream.connection = connection; // Allow backpressure
      stream.pause();
      tmp.file(function (tmp_err, path, fd, cleanupCallback) {
        var ws = fs.createWriteStream(path);
        stream.pipe(ws);
        stream.resume();
        ws.on('close', function () {
          fs.readFile(path, function(readfile_err, data) {
            transaction.notes.attachments.push({ content_type: ct, filename: fn, content: data, body : body});
            // Close the tmp file descriptor
            fs.close(fd, function(){});
            cleanupCallback();
          });
        });
      });
    }
  );
  return next();
}
````

It works. And the temp file is deleted and the content saved in the notes.

But I expected the RAM consumption only increases during the transaction, and after the email is sent the RAM goes down again. This is not the case. The memory consumption grows up as the attachment comes, but after the email is send it does not decrease.
I thought the transaction was fully deleted after the email is send, so the notes ram consumption should disappear.

I see this because I run Haraka inside a Docker container and the container starts to increase RAM usage with every new email with attachemnt.

<img width="913" alt="screen shot 2016-01-07 at 3 02 52 pm" src="https://cloud.githubusercontent.com/assets/1263856/12181374/c45319a6-b54f-11e5-9632-26a9839edd21.png">

**Comment by ricardopolo** [comment]
@smfreegard @Dexus @msimerson @baudehlo any idea please?

**Comment by baudehlo** [comment]
You need to pause the connection again.

Add in stream.on('end', function () { connection.pause() });

And then resume it when you're all done.

**Comment by ricardopolo** [comment]
@baudehlo it does not work. I tried something like

````js
    function (ct, fn, body, stream) {
      stream.connection = connection; // Allow backpressure
      stream.pause();
      tmp.file(function (tmp_err, path, fd, cleanupCallback) {
        var ws = fs.createWriteStream(path);
        stream.pipe(ws);
        stream.resume();
        ws.on('close', function () {
          fs.readFile(path, function(readfile_err, data) {
            transaction.notes.attachments.push({ content_type: ct, filename: fn, content: data, body : body});
            // Close the tmp file descriptor
            fs.close(fd, function(){});
            stream.pause();
            cleanupCallback();
          });
        });
      });
    }
````

And the same RAM increase

**Comment by baudehlo** [comment]
You can't pause the stream again. That's irrelevant. You need to pause the
connection.

**Comment by ricardopolo** [comment]
@baudehlo 

Sorry i am not understanding well.  Why pausing the connection stops memory leaks?

I tried modifying my original code whit something like this
````js
  transaction.attachment_hooks(
    function (ct, fn, body, stream) {
      stream.connection = connection; // Allow backpressure
      stream.pause();
      tmp.file(function (tmp_err, path, fd, cleanupCallback) {
        var ws = fs.createWriteStream(path);
        stream.pipe(ws);
        stream.resume();
        ws.on('close', function () {
          fs.readFile(path, function(readfile_err, data) {
            connection.pause();
            transaction.notes.attachments.push({ content_type: ct, filename: fn, content: data, body : body});
            // Close the tmp file descriptor
            fs.close(fd, function(){});
            cleanupCallback();
          });
        });
      });
      connection.resume();
    }
  );
````

It does not work in emails with multiple attachments. Thanks for your help!

**Comment by baudehlo** [comment]
If you keep ignoring the code I gave you I'll have to just close the issue.

**Comment by ricardopolo** [comment]
@baudehlo sorry, I was not seeing your code, as I said I was not understanding very well why pause the connection and the continuing it will fix the like

Anyway I tried the code you gave to me 

````js
  transaction.attachment_hooks(
    function (ct, fn, body, stream) {
      stream.connection = connection; // Allow backpressure
      stream.pause();
      tmp.file(function (tmp_err, path, fd, cleanupCallback) {
        var ws = fs.createWriteStream(path);
        ws.on('close', function () {
          fs.readFile(path, function(readfile_err, data) {
            transaction.notes.attachments.push({ content_type: ct, filename: fn, content: data, body : body});
            // Close the tmp file descriptor
            fs.close(fd, function(){});
            cleanupCallback();
          });
        });
        stream.on('end', function() {
          connection.pause();
        });
        stream.pipe(ws);
        stream.resume();
        connection.resume();
      });
    }
  );
````

I doesn't work.  Thank you for you help!

**Comment by baudehlo** [comment]
You need to resume somewhere. As I said, after you're done with the contents completely.

**Comment by ricardopolo** [comment]
We tried resuming everywhere we know it could work but does not work, always have the memory leak. Anyway we decided to go back to store the data in disk, so I am closing the issue. 

Thanks @baudehlo
