### ISSUE TITLE
manipulating client headers

### ISSUE THREAD

**Issue by astutesoftware** [haraka/Haraka#1294]
I am looking to do the following.
1. let the client authenticate with my custom haraka mailserver
   username/pass + whitelisted ip will be allowed to connect and send a mail
2. I want to add custom headers to the mail and forward it to another mailerserver

What i am typically trying to achieve is to build a billing layer on top of this so based on customer credits i can deduct credits or deny connections when insufficient credits.

Also custom headers so i can map the billing and do a sender (sent via) type messages.

Is it possible with this ?

**Comment by ricardopolo** [comment]
Yes it is, just create a pluging using the `data_post` hook and modify the headers using `transaction.add_header(key, value)` and `transaction.remove_header(key, value)`.
