### ISSUE TITLE
smtp_forward/smtp_proxy - hook_queue and hook_queue_outbound

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#1307]
smtp_forward and smtp_proxy work differently regarding outbound mail.   The difference is my fault looking at 'Blame'.   smtp_forward sets `exports.hook_queue_outbound = exports.hook_queue` whereas smtp_proxy does not.

My reasoning for smtp_forward was because I wanted all mail to go to the forwarder - I didn't want outbound to handle it at all.

We've had a number of people hit the same issue with smtp_proxy and I just dealt with another one today on IRC.   They expect queue/smtp_proxy to proxy irrespective of queue .vs. queue_outbound.

Either we need to add a common configuration option to enable the plugins to handle both hooks or we should add a config item to smtp.ini to do it globally across all queue/* plugins.

Thoughts?

**Comment by msimerson** [comment]
>  They expect queue/smtp_proxy to proxy irrespective of queue .vs. queue_outbound.

I agree with them, I think that *should* be the default.

I'd suggest having them both hook queue_outbound by default (that whole, POLA thing) and then having an option in smtp_forward.ini and smtp_proxy.ini that..... blah, it took less time to create a PR (#1308) than to explain with English.
