### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by pjebs** [haraka/Haraka#1309]
is v3develop ready to use. When will it be merged to master?
if it's not ready for production, when is it estimated to be ready?

**Comment by smfreegard** [comment]
It's not released - therefore not production ready.  It's likely to be a moving target for some time yet and we don't have a solid plan for a release date.

What exactly is it you want from v3 that isn't in the current release?

**Comment by pjebs** [comment]
It's just that I paid someone to do some Haraka work since I don't know node.js.
I was just a bit concerned that the contractor was using version 2.7.2 when I knew that v3 would be released soon.

Would it be easy to upgrade from 2.7.2. to v3 if you don't know node.js but no other programming languages and can generally figure stuff out in?

**Comment by smfreegard** [comment]
There aren't any big changes in it yet - but expect v3 to contain some breaking changes when it is finally released.   We'll obviously post detailed documentation on what those changes are and what might need to be changed and how to upgrade at the time.

I wouldn't worry too much - it's not being released any time soon.

**Comment by msimerson** [comment]
> I wouldn't worry too much - it's not being released any time soon.

Exactly. It's a ways off, and when it happens, we'll update the [UPGRADE](https://github.com/haraka/Haraka/blob/master/UPGRADE) document.
