### ISSUE TITLE
RFC Outbound queuing plugin using rabbit

### ISSUE THREAD

**Issue by pvandijk** [haraka/Haraka#1311]
## Summary
In line with some of the stated project goals, particularly in reference to being able to one day provide similar capabilities to products such as PMTA, I believe that one of the steps toward facilitating high volume outbound mail is to enable a non-smtp based worker for injecting mail into the outbound queue.

Given that outbound already provides an interface to do this programatically, it should be fairly simple to provide a message interface (for rabbit or any given message based queue) to feed messages into outbound.

In my opinion this would open some doors around handling behavior such as "Virtual MTAs" by giving more structure to the outbound process by formalising the interface between the outside world and Haraka itself.

## Plugin Goals 
- To provide a standard & maintained messaging interface for injecting email into the outbound queue without relying on smtp

## Other Goals
- I'm trying to use this as an excuse to better understand how to implement VMTA style behavior at a high level into Haraka
- The next step after this plugin would be working on enhanced per-domain control for outbound delivery to facilitate higher delivery rates and better deliverability control.

## Implementation
- Regardless of the existing plugin infrastructure, this will be maintained as a separate repo, as to be honest, i plan to work on this regardless of the Haraka project itself, and i think this is a better approach as i dont have huge amounts of time to work on it
- The actual implementation should be fairly straight forward - simply create a configurable number of workers which dequeue from rabbit and inject into outbound
- I've been wondering if i could then use this behavior to treat rabbit queues as i would a VMTA, and be able to vary the outbound configuration based on how it's routed, but this isnt something i'm going to tackle initially.

## Questions
- Has anyone else looked into queuing outbound from rabbit before?
- I havent really come to terms with how the per-domain settings will be implemented in Haraka, but i remember reading that (i think @msimerson ) mentioned that it was going to be "hard" - is anyone actively looking into this side of things?

I'm happy to get feedback on this, good bad or ugly, so don't hold back :)

**Comment by msimerson** [comment]
> I havent really come to terms with how the per-domain settings will be implemented in Haraka, but i remember reading that (i think @msimerson ) mentioned that it was going to be "hard" 

If I were asked, I'd have expected myself to point at a plugin I wrote, [rcpt_to.routes](https://github.com/haraka/Haraka/blob/master/plugins/rcpt_to.routes.js), that added per-email address email routing, by implementing the get_mx hook. Per-domain MX routing is even easier, but as you mention, will require some rate limiting / concurrency / backoff mechanisms.

**Comment by baudehlo** [comment]
My biggest issue with this sort of thing is what happens with large emails? Are you sending them over the queue? Always a bad idea.

Also many many queues have no failure guarantees, and email does. If power goes out do you lose an email? If network partitions happen, do you lose emails? We need to not lose those guarantees.

**Comment by pvandijk** [comment]
> My biggest issue with this sort of thing is what happens with large emails? Are you sending them over the queue? Always a bad idea.

Fair point. I'm not sure what you'd consider large, though rabbit can usually handle whatever people throw at it.

> Also many many queues have no failure guarantees, and email does. If power goes out do you lose an email? If network partitions happen, do you lose emails? We need to not lose those guarantees.

Definitely worth considering, though this depends on how you decide the queue interaction more than anything.

So let's say we have a high volume of email to send, there's kinda 2 options:
- Keep a large volume of messages in the queue (rabbit)
- Keep a large volume of messages in a queue in Haraka

Then i start conceptualising it as:
- Do i want to use rabbit to handle all the queuing so i dont have to build anything, or,
- Do i want to build something into Haraka which can handle high volume / large queues, including reliability, backing to a block device, etc

I'm hoping i'm going to understand it more as i go, though i think to summarize:
Queue everything in rabbit - scale it out based on what you need to send, then i think Haraka simply consumes the messages as fast as it's prepared to. By doing it this way you save having to have complicated queuing inside Haraka itself which would be required if you were handling massive volumes.

**Comment by baudehlo** [comment]
What's significant to consider is whether it keeps the contents in memory.
A 2GB email (trust me, they happen) has the possibility of really ruining
your day if you have to process everything in RAM.

**Comment by pvandijk** [comment]
> A 2GB email (trust me, they happen) has the possibility of really ruining
your day if you have to process everything in RAM

I can definitely understand why, though i'd be curious as to how well anything would handle this (thinking, sendmail, postfix, etc). Rabbit does handle fragmentation of massive message fairly gracefully from what I understand of it, though your example would be pushing it to the limit.

In regards to what I'm going to attempt to do, I'm coming from more the standpoint of layering applications on top of it rather than as a general purpose smtp server, so my concerns are a little different in that regard. I'm more worried about 2 billion messages (figuratively) in a queue than a single 2GB message.

**Comment by baudehlo** [comment]
Sendmail and postfix handle it just fine. Like Haraka they stream it to local disk.

But yes I understand there are multiple different requirements. I just want to make sure we handle these cases in the default mode.

**Comment by msimerson** [comment]
>> My biggest issue with this sort of thing is what happens with large emails? Are you sending them over the queue? Always a bad idea.

> Fair point. I'm not sure what you'd consider large, though rabbit can usually handle whatever people throw at it.

In the case of messages with large attachments, spool them attachments to storage (local disk / S3 / whatever) and insert references that path/inode/uri into the message. This prevents the edge cases (mail messages > 512k with many recipients) from plugging your high speed message queue.

When the little worker bees are delivering that 2MB attachment, they scan for references and then stream the files from storage. It's a little more complicated than passing along big messages but you avoid the "message queues fail in novel ways with Really Big Messages" problem and one can scale a system like that to insane levels.

**Comment by baudehlo** [comment]
Right but then they also need to know what server they are on.

**Comment by msimerson** [comment]
> Right but then they also need to know what server they are on.

Correct, which is where a URI (included in the list above) is handy. :)

**Comment by msimerson** [comment]
Moved idea/feature request to [wiki](https://github.com/haraka/Haraka/wiki)
