### ISSUE TITLE
npm owner of haraka projects as user 'haraka'

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1313]
To simplify publishing of haraka, haraka modules, and haraka plugins on npm by the @haraka/core team, I have created a npm user called [haraka](https://www.npmjs.com/~haraka). I suggest that all of the Haraka repos add this user as an owner of that group, using the `cd $repo; npm owner add haraka` syntax.

# repos

* [x] haraka-nosql
* [x] haraka-tld
* [x] haraka-plugin-graph
* [x] address-rfc2821
* [x] address-rfc2822
* [x] haraka

# Shared access

All @haraka/core members need access to the account. I suggest:

* [x] setting the email address to a role account (haraka.mail@gmail.com) that forwards the email to all the owners.
* [x] share the npm account password among all @haraka/core (contact me privately).

**Comment by baudehlo** [comment]
test
