### ISSUE TITLE
Mail forwarding

### ISSUE THREAD

**Issue by pjebs** [haraka/Haraka#1317]
I'm creating an email forwarder plugin where incoming email to haraka has its TO address changed and resent to the new address.

In config/plugin, I have smtp_forward queue.

I think to use that, you must configure the ini file????

...but I don't actually want to use something like AWS SES. I want haraka to directly send email. How can I do that?

**Comment by smfreegard** [comment]
>  I want haraka to directly send email. How can I do that?

Use this: https://gist.github.com/smfreegard/ff79d02aeb94b9065359 as your queue plugin.  It will use Haraka's outbound queueing to send the mail.

**Comment by pjebs** [comment]
Is this equivalent to me commenting out smtp_forward in configure/plugins and having no queue?

Would haraka just automatically send the email

**Comment by smfreegard** [comment]
No - currently a plugin on hook_queue is required otherwise the message will be rejected.
