### ISSUE TITLE
Migrate to Streams3

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#1323]
Currently Haraka implements SMTP by reading data from an incoming socket using the old stream 'data' event and parsing it line-by-line and dispatching the commands as they are read, then when the DATA command is sent, a secondary stream is created (message_stream) to buffer the headers and message data that plugins can then read from.

For 3.0 - we should migrate this to a Streams3 stream EventEmitter and run the plugins from the emitted events.

Due to the plugin architecture - I've been thinking that it might be best to create 'spool' files similar to how qpsmtpd works e.g. when we go into DATA mode, we write message to a transport file.   The transport file could be placed on tmpfs for speed.  When a plugin pipes the stream, we would output the current headers from memory, followed by the message body from transport file.   We would use transform streams for plugins like clamav which require special formatting.

**Comment by msimerson** [comment]
I think in 3.0 we ought to be dropping support for Node 0.10 (maintenance ends 2016-10-01) and thus with it Streams2.  If we support only Node 4 LTS and up, then we'll be going straight to Streams3.

**Comment by smfreegard** [comment]
Ooops - yeah.  Streams3 it is.

**Comment by msimerson** [comment]
migrated to [wiki](https://github.com/haraka/Haraka/wiki)
