### ISSUE TITLE
Update reseed_rng to use seedrandom 2.4.2?

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1356]
A [much newer](https://github.com/davidbau/seedrandom) version of seedrandom is available upstream. Should we update?

**Comment by msimerson** [comment]
Also, we can depend on the newer version with `npm install seedrandom`.

**Comment by baudehlo** [comment]
Has the API changed enough that we need to change the code? We don't depend on it in package.json.

**Comment by msimerson** [comment]
We have it included (inline) in `plugins/reseed_rng.js`. Maybe that plugin is a good candidate to make an npm module, and instead of having the code inline, it can depend on seedrandom.

**Comment by baudehlo** [comment]
Given there are no tests for it, I think it 100% deserves to be an npm module.

**Comment by baudehlo** [comment]
Looking at this, it honestly looks like we should just change this code to do: `Math.seedrandom(crypto.randomBytes(256).toString('hex'))`. I don't see a benefit to trying to do rng generation in JS.

I'll do a PR.
