### ISSUE TITLE
Response 334 after AUTH PLAIN

### ISSUE THREAD

**Issue by mokhito** [haraka/Haraka#1366]
Hello,

Using Opera Mail (possibly affecting other clients too) I could not authenticate. After reviewing the logs, I noticed that this client does not send the username in the AUTH PLAIN request but afterwards. Haraka is supposed to [handle this case](https://github.com/haraka/Haraka/blob/master/plugins/auth/auth_base.js#L169). But the 334 response is never actually sent to the client because it contains only a whitespace. It looks like [this test](https://github.com/haraka/Haraka/blob/master/connection.js#L466) is to blame.

**Comment by celesteking** [comment]
Never seen any clients doing that, but nevertheless, it seems that's a legitimate dialog.

**Comment by erickpece** [comment]
I've seen this with a customer of ours using a home built application as well.

**Comment by baudehlo** [comment]
Seems like a legit fix would be that only the first line is allowed to be
blank.

Anyone willing to submit a PR?
