### ISSUE TITLE
Support "Plus Adressing"

### ISSUE THREAD

**Issue by BananaAcid** [haraka/Haraka#1367]
Support "Plus Adressing"

_Plus addressing means any email sent to username+whateveryoulike@domain.tld is still delivered to your account. The part of the email address between the "+" and the "@" is ignored for determining which account it belongs to. This allows you to create limitless variations on your email address to give out to different people, sites or mailing lists._ [FastMail](https://www.fastmail.com/help/receive/addressing.html)

Does not seem to be RFC'ed anywhere, but broadly supported by mail servers.

https://support.google.com/mail/answer/12096?hl=en
https://www.fastmail.com/help/receive/addressing.html

**Comment by msimerson** [comment]
Haraka already **does** support address extensions via the `rcpt_to.qmail-deliverable` plugin, when qmail is the destination MTA. Ultimately, it's not up to Haraka but instead the recipient validation plugin to determine whether any given address is valid or not.

**Comment by baudehlo** [comment]
To further emphasize the point: plus addressing isn't something we need to "support". It just works with Haraka. It's the job of the MDA or storage engine to do the right thing.
