### ISSUE TITLE
provide default ini config file for every plugin

### ISSUE THREAD

**Issue by celesteking** [haraka/Haraka#1376]
please

**Comment by msimerson** [comment]
Why?

Unless you have some good reason which didn't come up in #1339, and which also somehow avoids the "how do we keep installed/config up-to-date," we are likely to decline this request.

**Comment by celesteking** [comment]
There's no clamd config in haraka dir either.

The reason is to see what are the default options and what options are available. (quick list without the need of documentation scan)

**Comment by celesteking** [comment]
That is, I don't need the config to be installed, I need a quick list of all options and their default values.

**Comment by msimerson** [comment]
We have already [provided exactly that](https://github.com/haraka/Haraka/blob/master/docs/plugins/clamd.md#configuration).

**Comment by baudehlo** [comment]
I do think default options should be put into the core config file now, not
just documented.

**Comment by celesteking** [comment]
Yes, that might work, but would require going through documentation and fishing out parameters. 
for ex https://github.com/haraka/Haraka/blob/master/docs/plugins/limit.md  or https://github.com/haraka/Haraka/blob/master/docs/plugins/relay.md -- a lot of text. 
access.md is much better , though.

**Comment by baudehlo** [comment]
This should be turned into a bigger ticket, something along the lines of:
"Now config is not copied over, every plugin with INI config should have a
default config file showing the defaults".

**Comment by msimerson** [comment]
> Now [that] config is not copied over, every plugin with INI config should have a
default config file showing the defaults

+1

**Comment by msimerson** [comment]
I'd also like to remove *all* of the config sections from the .md files, instead putting them inline (with comments) in the .ini files, and just adding a reference with a URL in the documentation.

**Comment by baudehlo** [comment]
That will not be very nice for people reading on the web site.

**Comment by msimerson** [comment]
> That will not be very nice for people reading on the web site.

It could actually be a nicer experience. The easy not-so-great experience is a link to the .ini file, which is dead simple. The much-nicer-experience would be for the web site to include the `.ini` file inline, nicely formatted like GitHub does for .ini code blocks (ie, much better than a `<pre>` tag).

**Comment by smfreegard** [comment]
No all plugins use the .ini format, so comments would be an issue in those cases.

IMO - this is a retrograde step, people will be less likely to read the docs if the .ini has everything in-line and therefore we'll end up doing more support for people who can't be arsed to read the docs.

**Comment by msimerson** [comment]
> people will be less likely to read the docs if the .ini has everything in-line 

People have no choice but to read the docs, as we no longer install default config files.

The question is a matter of imposing a development and maintenance burden on developers, having to  maintain configuration documentation in the config file **and** the docs, or just in the config files themselves.

**Comment by sumpton** [comment]
I gag on concepts like "people will be less likely to read the docs if the .ini has everything in-line"

**Comment by baudehlo** [comment]
I'd love to see some love given to the haraka.github.com repository that
supported this kind of thing. Meanwhile fix the document titles code which
is massively broken.

**Comment by msimerson** [comment]
> I found getting started with Haraka challenging, and have needed to research lots of inconsistencies, and drill down into code to find out how it works, or if there is a pattern I am missing. It took days instead of hours.

We hear you. In the meantime, there are two install guides [on the wiki](https://github.com/haraka/Haraka/wiki).

> I would like to see Redis used consistently, and supporting ioredis, because our primary Redis store is a Cluster.

We are nearly there. Last year, we had 5 plugins each with duplicated redis functions. Now all the redis-using plugins inherit from the redis plugin. It's now a SMOP to update the redis plugin and add a config setting which chooses which redis driver to load. PRs are welcome.

**Comment by sumpton** [comment]
What a nice response; thanks. I appreciate the effort and super pleased that this project is active.

I did enjoy the benefits of the wiki and got a very basic system running, including relaying. One typical use of some systems is to check for an existing alias and not just the domain. I could do this easily now, but it looks pretty obscure when I started.

I also found it confusing how to pass messages between stages, and where to rewrite mail_from (mailFrom :) ). Everything became easy when I understood that several hooks could be in one script -- obvious once you see it, and as I said, others reach enlightenment faster -- I wasn't comfortable using notes. As it is, I reverted to how we typically message between async stages with a locals object ({}). Now that I have a better understanding of a "connection" and "transaction" things are pretty clear.

My suggestion is to have one or two plugins that represent best practices, but not overwhelming, with rich comments. The comments could point to documentation, but also act as reminders for the second and third pass through the code. One example could have several hooks, registering them at the top, and perhaps comments at the function definition showing the alternative registering the hook directly -- or making that clear. The other would be one hook example.

My point is that even knowing one script is an example to follow, with notations, makes all the other scripts easier to understand. For me it was a starting point. I forget which one I decided I would use as a guide, but that is how I jumped in for my own custom plugin.

My points of confusion included:
* Where to rewrite and how
* Learning that removing headers used regex anchored to the beginning (^nice)
* Learning where to kill an event
* Best practices for Redis -- I am using server.notes.redis currently, for development, but thought I would have to use ioredis directly in our plugin.
* Turn console back on -- handy crutch -- but plugin.log[info | debug | ...] is great

There was more that, but my point is that looking back, all this is pretty simple and the code base is amazing. I just struggled a lot initially, and spent a lot of "what if" time. One of you Gurus would have written my 200 lines -- 20 that do much of anything -- in an hour or so.

The pleasure of Haraka is customizing it, using Node.js, with the comfort of knowing it scales. For me, it is more than I hoped for when looking for solution.

**Comment by baudehlo** [comment]
I'm going to close this because the changes made in 2.8 (config isn't even copied to local installations) make part of this kind of redundant.

We do need better documentation, but that's not worth having a ticket for - every open source project does.
