### ISSUE TITLE
Redirect Logs

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1377]
Hi. 

We are using a Haraka server in production. Somethings our plugins failed, give an unmanaged exception and stop the services.
If we are connected to the server by SSH we can see whats wrong in the console, but if not, when we realize that the service is down we connect to SSH, see the service stopped but can't see what was wrong.

So, how can we redirect the log to a different place than the console? As example, is it possible to save to a file if there are critical errors?

Thanks!

**Comment by smfreegard** [comment]
Use a log plugin like log.syslog to put the logs to syslog.  You should also ensure the you set nodes=cpus in smtp.ini and the service will never stop on plugin crashes as a crashed child will be automatically restarted.   You still need to monitor your logs and fix any of these issues though.
