### ISSUE TITLE
Mail header is splitted into some pieces and add "\n " before being re-concatenated

### ISSUE THREAD

**Issue by nguyendc-systran** [haraka/Haraka#1378]
I have a problem while sending a mail with a long header.
The mail header is splitted into some pieces in `this.header_lines` array (of `transaction.js`) and then re-join in `mailheader.js`. After this step of re-concatenation `"\n "` is added between each element that modify the initial header.

For example: I try to send a mail with following subject: 
`Un longue titre, c'est la dernière vérification. Ça devrait marcher normalement`

The complete header object received:

**Header** {
  **headers**: 
   { received: [ 'from [192.168.70.163] ([192.168.70.163])\n\tby haraka.test (Haraka/1.0.8) with ESMTP id 68E8604A-F6EA-431F-BF43-6F8219215928.1\n\tenvelope-from <sender@systran.fr>;\n\tTue, 08 Mar 2016 09:55:46 +0100\n' ],
     to: [ 'receiver@mailserver.com\n' ],
     from: [ 'sender <sender@systran.fr>\n' ],
     **subject: [ '=?UTF-8?Q?Un_longue_titre=2c_c\'est_la_derni=c3=a8re_v=c3=a9rificati?=\n =?UTF-8?Q?on._=c3=87a_devrait_marcher_normalement?=\n' ]**,
     'message-id': [ '<56DE9392.9060504@systran.fr>\n' ],
     date: [ 'Tue, 8 Mar 2016 09:55:46 +0100\n' ],
     'user-agent': [ 'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101\n Thunderbird/38.2.0\n' ],
     'mime-version': [ '1.0\n' ],
     'content-type': [ 'text/plain; charset=utf-8; format=flowed\n' ],
     'content-transfer-encoding': [ '7bit\n' ] },
  **headers_decoded**: 
   { received: [ 'from [192.168.70.163] ([192.168.70.163])\n by haraka.test (Haraka/1.0.8) with ESMTP id 68E8604A-F6EA-431F-BF43-6F8219215928.1\n envelope-from <sender@systran.fr>;\n Tue, 08 Mar 2016 09:55:46 +0100' ],
     to: [ 'receiver@mailserver.com' ],
     from: [ 'sender <sender@systran.fr>' ],
     **subject: [ 'Un longue titre, c\'est la dernière vérificati\n on. Ça devrait marcher normalement' ]**,
     'message-id': [ '<56DE9392.9060504@systran.fr>' ],
     date: [ 'Tue, 8 Mar 2016 09:55:46 +0100' ],
     'user-agent': [ 'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101\n Thunderbird/38.2.0' ],
     'mime-version': [ '1.0' ],
     'content-type': [ 'text/plain; charset=utf-8; format=flowed' ],
     'content-transfer-encoding': [ '7bit' ] },
  **header_list**: 
   [ 'Received: from [192.168.70.163] ([192.168.70.163])\n\tby haraka.test (Haraka/1.0.8) with ESMTP id 68E8604A-F6EA-431F-BF43-6F8219215928.1\n\tenvelope-from <sender@systran.fr>;\n\tTue, 08 Mar 2016 09:55:46 +0100\n',
     'To: receiver@mailserver.com\n',
     'From: sender <sender@systran.fr>\n',
    '**Subject: =?UTF-8?Q?Un_longue_titre=2c_c\'est_la_derni=c3=a8re_v=c3=a9rificati?=\n =?UTF-8?Q?on._=c3=87a_devrait_marcher_normalement?=\n**',
     'Message-ID: <56DE9392.9060504@systran.fr>\n',
     'Date: Tue, 8 Mar 2016 09:55:46 +0100\n',
     'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101\n Thunderbird/38.2.0\n',
     'MIME-Version: 1.0\n',
     'Content-Type: text/plain; charset=utf-8; format=flowed\n',
     'Content-Transfer-Encoding: 7bit\n' ],
  options: undefined }

So:
`headers.subject = "=?UTF-8?Q?Un_longue_titre=2c_c\'est_la_derni=c3=a8re_v=c3=a9rificati?=\n =?UTF-8?Q?on._=c3=87a_devrait_marcher_normalement?=\n"`

As a result:
`headers_decoded.subject = "Un longue titre, c\'est la dernière vérificati\n on. Ça devrait marcher normalement"`

The word **`"vérification"`** is splitted into **`"vérificati\n on"`**.

It's the same issue with other non utf8 encoding mail but only `"\n"` added between splitted subject elements instead of `"\n "`.

I try a quick fix for this issue by patch `mailheader.js` file from [line 26](https://github.com/haraka/Haraka/blob/master/mailheader.js#L26) as below:

```
        if (line.match(/^[ \t]/)) {
            // continuation
            var currLength = this.header_list.length;
            if (this.header_list[currLength - 1].match(/^(Subject:)/i)) {
                if (this.header_list[currLength - 1].match(/^(Subject: =\?UTF-8\?)/i)) {
                    line = line.replace(/^[ \t]|\n$/g, '');
                }
                else {
                    line = line.replace(/\n$/g, '');
                }
                this.header_list[currLength - 1] = this.header_list[currLength - 1].replace(/\n$/, '');
            }
            this.header_list[currLength - 1] += line;
        }
```

instead of:

```
        if (line.match(/^[ \t]/)) {
            // continuation
            this.header_list[this.header_list.length - 1] += line;
        }
```

**Comment by smfreegard** [comment]
That isn't the correct fix.  E-mail headers are folded by the MUA (not by Haraka) which is allowed by the RFC, they are continued on the next line but are denoted by space or tab characters after the newline.

Your fix will create potentially massive headers without continuations because the header array you are modifying is used by the message_stream when sending the message out.

I think the correct fix is to change the decode function:

`````
--- mailheader.js.orig	2016-03-08 05:53:14.697306575 -0500
+++ mailheader.js	2016-03-08 05:58:12.861085374 -0500
@@ -99,7 +99,7 @@
 
 Header.prototype.decode_header = function decode_header (val) {
     // Fold continuations
-    val = val.replace(/\n[ \t]+/g, "\n ");
+    val = val.replace(/\n[ \t]+/g, "");
 
     // remove end carriage return
     val = val.replace(/\r?\n$/, '');
`````

The alternative would be to leave the continuations in and leave it to the caller of c.t.header.get_decoded() to remove them via a replace(/\n[ \t]+/g, "");

@baudehlo @msimerson  Thoughts?

**Comment by msimerson** [comment]
> I think the correct fix is to change the decode function

+1

I think the natural expectation when calling get_decoded() is to get a UTF string representing what a user would see in their MUA's presentation of that header. The header folding is based on the length of the **encoded** header and doesn't really make sense in get_decoded output.

**Comment by smfreegard** [comment]
My concern was that there might be some people (and I might be one of those) that always uses get_decoded() out of habit and changing the line representation might cause them issues. e.g. a Received header would end up on a single line instead of multiple etc. etc.

I'll change it on my local Haraka and see what shakes out.

**Comment by nguyendc-systran** [comment]
Thank you for your answers. It seems work for me.
Wait for next version :)

**Comment by baudehlo** [comment]
FWIW the change should be:

`val = val.replace(/\n[ \t]+/g, " ");`

Because otherwise you wipe out spaces in header lines.

**Comment by baudehlo** [comment]
Working on a PR for this since the code has changed significantly since this discussion started (with rfc-2231 support).
