### ISSUE TITLE
How to get the envelope

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1393]
We are planing to get an email from haraka, modify it and re send it using nodemailer.

How can we get the envelope of a Haraka session?
I know using the `rcpt` event hook we can get the senders, but in that we dont know if the recepient is a `To` or a `CC` or a `BCC`.

So how can we get the full enveloped to pass it to NodeMailer?

Thanks!

**Comment by baudehlo** [comment]
There's no difference at the SMTP level between those. The only difference is at the mail header level (To and Cc are shown, Bcc is hidden).

**Comment by ricardopolo** [comment]
So, how can you get the BCC from a message? Comparing al rcpt with the headers? Or there is a way with Haraka we can get an array with all To, and array with  CC and array with BBC?

**Comment by ricardopolo** [comment]
@baudehlo Currently we are getting the BBC using something like these

```js
function get_bcc(headers, rcpt_to){
  var bcc = "";
  if(!headers.to || !contains_all_elements(headers.to, rcpt_to)){
    rcpt_to.forEach(function(element){
      if(!bcc){
        bcc = element.address();
      }
      else{
        bcc = bcc + "," + element.address();
      }
    });
  }
  return bcc;
}
````


Any advice to improve this? 
Thanks!

**Comment by baudehlo** [comment]
Yes my advice is you forget about distinguishing them. Nodemailer doesn't care.

**Comment by baudehlo** [comment]
Closing this, it's not really a Haraka issue. It's just a matter of understanding the difference between mail clients using To/CC/BCC and how SMTP works.
