### ISSUE TITLE
Helo command rejected: need fully-qualified hostname\r\n

### ISSUE THREAD

**Issue by robguthrie** [haraka/Haraka#1407]
Hi there Haraka team. I've been trying to use Haraka in production but am having a bit of a hard time.

I'm using Haraka as an outbound SMTP, and finding that when it sends ELHO command it does not send the FQ hostname. Is there a config setting I am missing here?

----

### Haraka version
2.8.0-alpha.8

### Expected behavior
email is queued by remote side

### Observed behavior
smtp_1 | [PROTOCOL] [708FF8AA-CDFC-4FD3-A0AD-493A9A3C860B.1.6] [outbound] S: 504 5.5.2 <c231c1f0bd02>: Helo command rejected: need fully-qualified hostname\r\n

### Steps to reproduce
Sending email using swaks to quite a few hosts belonging to our users.

**Comment by robguthrie** [comment]
I see in outbound.js that mx.bind_helo is used, which is the value of config.get('me'). I think that means I need a `me` file in my `config` directory, then I should expect to see this value used when issuing the EHLO command.

Is that right?

**Comment by smfreegard** [comment]
> I see in outbound.js that mx.bind_helo is used, which is the value of config.get('me'). I think that means I need a me file in my config directory, then I should expect to see this value used when issuing the EHLO command.

config.get('me') if missing uses os.hostname() - so rather than creating `config/me` it would be better to fix the system hostname instead.

**Comment by robguthrie** [comment]
Thanks for your help Steve.
