### ISSUE TITLE
Is it necessary to use a CA signed cert for the TLS plugin?

### ISSUE THREAD

**Issue by robguthrie** [haraka/Haraka#1431]
Sorry, not really an issue, but I wanted to know if there was any real world disadvantage to using a self signed certificate with the tls plugin?

It seems to me like it is not common for other MTA's to care about if your cert is signed or not.

**Comment by baudehlo** [comment]
Correct. Currently it is rare for SMTP servers to care about the signing validity of the certificate. But I feel this will change soon, especially given that certs are now free from letsencrypt.

**Comment by robguthrie** [comment]
Thank you.

**Comment by baudehlo** [comment]
For what it's worth, for 2.9, we will be investigating the possibility of having every Haraka instance have a signed cert using letsencrypt.

**Comment by robguthrie** [comment]
Oh that's very exciting!
