### ISSUE TITLE
Cpu options consume double of RAM

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1442]
When I run Haraka with `nodes=` option in the `smtp.ini`, what hardwared implications does it have?

- I will need the same number of CPUs specified? (Or they will be virtual, or ignored if the number is higher). Whats the behavior?
- I will need twice of RAM if run `nodes=2`?. Each cpu will eat the same ammount of RAM?

Regards and thanks

**Comment by baudehlo** [comment]
Generally you set nodes=cpus and be done with it.

It forks a new process for each "node". The recommendation is to use the
number of CPUs you have or less.

Yes each one will consume approximately the same amount of RAM, along with
some for the overall parent process too.

**Comment by ricardopolo** [comment]
What will happen if you set higger number of CPUS than you have? It will create "virtual processes" killing performance? Or will ignore it?

Thanks!

**Comment by baudehlo** [comment]
It will just create more processes - as many as you ask for. They aren't
"virtual" in any sense. It might make performance worse. There's a balance
to be struck, and usually it's at nodes=cpus. In some rare installations
you might want more - but this is more of a Node.js question - you can find
many articles on this (search for "nodejs cluster optimization").
