### ISSUE TITLE
Matching auth username and mail from

### ISSUE THREAD

**Issue by gramakri** [haraka/Haraka#1444]
It appears that haraka will allow an authenticated user to send out mail as any name@domain.com. AFAICT, there is no plugin that enforces that the AUTH username and the MAIL FROM match.

Can you confirm if this is the case?

If this is a good feature to add to haraka, I will be happy to give it a shot since I need this. I am thinking we can add mail_from hooks to the auth plugins which can enforce this using a config option. If there is a better approach, please let me know.

**Comment by baudehlo** [comment]
Correct that is the current case. It should be an easy plugin to create,
assuming we save the AUTH username somewhere.

**Comment by smfreegard** [comment]
> assuming we save the AUTH username somewhere.
We do: https://github.com/haraka/Haraka/blob/master/plugins/auth/auth_base.js#L99.

**Comment by gramakri** [comment]
@baudehlo @smfreegard do you prefer a separate plugin or can we add this as an option to the auth plugin(s) ?

I am thinking match_username config option. For now, we can do a simple exact match.

**Comment by smfreegard** [comment]
My personal feeling is that it should be a separate plugin.

Personally - this plugin wouldn't work for me, I've either got credentials that are just a UNIX username without a domain or I have several aliases for one login.

I have a slightly different on this here in that I don't allow someone to send a mail from a domain that isn't defined and that's applied irrespective to the use of AUTH or not - it's applied whenever `connection.relaying = true`.

If you did this as a separate plugin, then you could easily expand it to both cases if you wanted to.

**Comment by gramakri** [comment]
@smfreegard Thanks for your response!

Do you guys happen to have a separate repo where we can place some of these custom plugin/samples which don't belong in core? I can add this plugin and a couple other that I already have, if there is interest.

**Comment by baudehlo** [comment]
You can (as of 2.8) just release to npm.

**Comment by gramakri** [comment]
@baudehlo How does that work? Just add module name in plugins?

**Comment by baudehlo** [comment]
Exactly, yes.

There are some differences - like the constants (DENY, etc) aren't stuffed
in - you have to load them from haraka-constants:
https://www.npmjs.com/package/haraka-constants

But it works the same way with the exports.* stuff, aside from that.

**Comment by gramakri** [comment]
I will give it a shot, thanks. For anyone else reading this, see https://github.com/haraka/Haraka/issues/1287 for the design.
