### ISSUE TITLE
Remove Haraka word from Receive headers

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1448]
Currently in the email headers is added the Haraka word and its version.

You see something like
`Received: from na01-by2-obe.outbound.protection.outlook.com
 (mail-by2lp0236.outbound.protection.outlook.com [207.46.163.236]) by
 ServerName (Haraka/2.7.3) with ESMTPS id`

So, any way we can disable the showing of the Haraka version? 
We prefer to not show exactly which server or version are using for security requirements.

Thanks!

**Comment by darkpixel** [comment]
As a quick fix, you could tweak connection.js here: https://github.com/haraka/Haraka/blob/master/connection.js#L1356

**Comment by prasayer** [comment]
How do I go further and remove the client ip and rDNS name?
I can edit that connection.js but am reluctant to do so. Any configuration file is available for this?

**Comment by baudehlo** [comment]
Nope but you could write a plugin that monkey-patches it rather than editing the file.

**Comment by prasayer** [comment]
Thanks Matt. Great work with Haraka. Can you give me some more pointers on
this approach or point me to a tutorial?

**Comment by msimerson** [comment]
The other idea we've suggested, which would be the ideal solution here, is to create a config option (maybe header.received in smtp.ini) that permitted one to define the exact received string, along with a few tokens (maybe %ip, etc..) that get replaced when the header is added.

**Comment by prasayer** [comment]
Agreed. If it is in the cards for near future I can wait for it to be
released. Would you know?

**Comment by msimerson** [comment]
It's waiting for someone to care enough to write it.
