### ISSUE TITLE
Forwarding question

### ISSUE THREAD

**Issue by enmartinson** [haraka/Haraka#1451]
I'm looking to move from a surgemail system to haraka for our email relaying, but am having a bit of confusion about configuring forwarding, hopefully someone can point me in the right direction. We have roughly 850 email addresses across ~400 domains that come in to us, then are forwarded to their corporate accounts through 5 potential relays based on the email address (almost all our email goes through sendgrid). An few examples would be:

info@site1.com -> forwarded to dave@client1.com and susie@client1.com through sendgrid
office@site1.com -> forwarded to alice@client1.com through sendgrid
sales @site2.com -> forwarded to sales@client2.com through gmail
webmaster, abuse + support @all sites -> forwarded to our webmaster, abuse and support email addresses through gmail (but can go through sendgrid)

We only want to accept those addresses specifically setup and drop all the rest.

I see setting up the rcpt_to.routes.ini file for the mx server, but I don't see where I can specify the exact email addresses and their forwards (aliases?). It's quite possible I've been looking at this so long it's right in front of me. Maybe someone has an adjusted rcpt_to plugin that incorporates this?

I also need to be able to manage these with a web front end, so putting them in a database would be best, our internal support has to update from time to time. Any guidance would be appreciated.

**Comment by Dexus** [comment]
Hey, please have a look to aliases.

**Comment by enmartinson** [comment]
This setup is FAR from clear. I can't seem to get aliases to register no matter what I try, and the documentation isn't helping. I don't see any errors in the logs or on the console, not sure how to get this working. 

Here's my plugins config, is there anything in here that would be stopping aliases from starting?

`# This file lists plugins that Haraka will run
#
# Plugin ordering often matters, run 'haraka -o -c /path/to/haraka/config'
# to see the order plugins (and their hooks) will run in.
#
# To see a list of all plugins, run 'haraka -l'
#
# To see the help docs for a particular plugin, run 'haraka -h plugin.name'

#process_title
# Log to syslog (see 'haraka -h log.syslog')
log.syslog
#Add webserver plugin to see live traffic at http://surgemail/watch
watch

aliases

# CONNECT
#toobusy
relay
# control which IPs, rDNS hostnames, HELO hostnames, MAIL FROM addresses, and
# RCPT TO address you accept mail from. See 'haraka -h access'.
access
connect.p0f
connect.geoip
# connect.asn
connect.fcrdns
# block mails from known bad hosts (see config/dnsbl.zones for the DNS zones queried)
dnsbl

# HELO
early_talker
# see config/helo.checks.ini for configuration
helo.checks
# see 'haraka -h tls' for config instructions before enabling!
tls
#
# AUTH plugins require TLS before AUTH is advertised, see
#     https://github.com/haraka/Haraka/wiki/Require-SSL-TLS
auth/flat_file
# auth/auth_proxy
# auth/auth_ldap

# MAIL FROM
# Only accept mail where the MAIL FROM domain is resolvable to an MX record
mail_from.is_resolvable
spf

# RCPT TO
# At least one rcpt_to plugin is REQUIRED for inbound email. The simplest
# plugin is in_host_list, see 'haraka -h rcpt_to.in_host_list' to configure.
rcpt_to.in_host_list
#rcpt_to.qmail_deliverable
#rcpt_to.ldap
#rcpt_to.routes

#relay_localhost
# DATA
bounce
# Check mail headers are valid
data.headers
data.uribl
#attachment
clamd
spamassassin
#dkim_sign
dkim_verify
karma

# QUEUE
# queues: discard  qmail-queue  quarantine  smtp_forward  smtp_proxy
# Queue mail via smtp - see config/smtp_forward.ini for where your mail goes
queue/smtp_forward

# Disconnect client if they spew bad SMTP commands at us
max_unrecognized_commands`

**Comment by enmartinson** [comment]
Damn. Nevermind. Looks like the node install only looks at the files it installed regardless of the configs you specify when starting up. I have configs in /etc/haraka, but the install put everything in /usr/lib/node_modules/Haraka and doesn't care if you specify a different location. I added the aliases link in that plugins file and it at least fired up.

This looks to be a bug in this type of install.

**Comment by baudehlo** [comment]
I literally just release 2.8.4 which should fix this problem. Please let me
know if it helps.

**Comment by enmartinson** [comment]
Yep, that fixed it... was just in process of moving my configs to the other directory - Thanks!
