### ISSUE TITLE
Add SMTP protocol log to Elasticsearch logs

### ISSUE THREAD

**Issue by erickpece** [haraka/Haraka#1455]
It would be useful to include both inbound and outbound SMTP logs in Elasticsearch.  This would ideally be something that can be configured in _config/log.elasticsearch.ini_.

**Comment by celesteking** [comment]
see https://github.com/celesteking/Haraka/blob/master/plugins/log.elasticsearch.js#L48 but I'm not sure if that still works

**Comment by msimerson** [comment]
Moved to haraka/haraka-plugin-elasticsearch#6
