### ISSUE TITLE
RabbitMQ 

### ISSUE THREAD

**Issue by erickpece** [haraka/Haraka#1457]
### Haraka version

2.8.0

### Expected behavior

If message(s) should be relayed, send them to RabbitMQ for queueing.

### Observed behavior

Loading outbound queue fails with the following error:

> [NOTICE] [-] [core] Listening on :::25
> [DEBUG] [-] [server] running init_master hooks
> [INFO] [-] [core] [outbound] Loading outbound queue from /usr/local/haraka/queue
> [CRIT] [-] [core] TypeError: Cannot read property 'close' of undefined
> [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/plugins/queue/rabbitmq_amqplib.js:39:24
> [CRIT] [-] [core]     at /usr/lib/node_modules/amqplib/callback_api.js:16:10
> [CRIT] [-] [core]     at Socket.<anonymous> (/usr/lib/node_modules/amqplib/lib/connect.js:167:18)
> [CRIT] [-] [core]     at Socket.g (events.js:273:16)
> [CRIT] [-] [core]     at emitOne (events.js:90:13)
> [CRIT] [-] [core]     at Socket.emit (events.js:182:7)
> [CRIT] [-] [core]     at emitErrorNT (net.js:1265:8)
> [CRIT] [-] [core]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
> [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:98:9)

### Steps to reproduce

Add queue/rabbitmq_amqplib to plugins before max_unrecognized_commands

Apply the default configuration for rabbitmq_amqplib as seen at https://haraka.github.io/manual/plugins/queue/rabbitmq_amqplib.html

**Comment by gramakri** [comment]
https://github.com/haraka/Haraka/blob/master/plugins/queue/rabbitmq_amqplib.js#L39 must be changed to just be `return`.

Also, https://github.com/haraka/Haraka/blob/master/plugins/queue/rabbitmq_amqplib.js#L14 needs a null `channel`

**Comment by brdude** [comment]
For whatever damn reason the plugin wants rabbitmq_amqplib.ini and rabbitmq.ini to be the same. So:

cp rabbitmq_amqplib.ini rabbitmq.ini

**Comment by erickpece** [comment]
@brdude Thanks - that workaround took care of it for me!

**Comment by baudehlo** [comment]
@gramakri - can you do a PR with those changes please?

**Comment by gramakri** [comment]
@baudehlo I was only pointing out the bug :-) I don't use amqp and have never used it.

That said, I can still do a PR if someone else is willing to test it.
