### ISSUE TITLE
spf plugin ran callback multiple times

### ISSUE THREAD

**Issue by Synchro** [haraka/Haraka#1459]
### Haraka version

2.8.0
### Observed behavior

```
[ERROR] [9D479017-00DE-4899-98D0-E1F8289529B1.83] [core] Error#012 at callback (/usr/lib/node_modules/Haraka/plugins.js:410:34)#012 at null._onTimeout (/usr/lib/node_modules/Haraka/plugins/spf.js:147:16)#012 at Timer.listOnTimeout (timers.js:92:15)
2016-05-13 22:24:41.905
[ERROR] [9D479017-00DE-4899-98D0-E1F8289529B1.83] [core] spf plugin ran callback multiple times - ignoring subsequent calls
2016-05-13 22:24:41.904
[ERROR] [9D479017-00DE-4899-98D0-E1F8289529B1.83] [spf] timeout
```
### Steps to reproduce

We're not sure why this is happening or what it means. It occurs when sending a large number of messages submitted to haraka on localhost from a nodemailer script. We end up with lots of duplicates of this error in the logs. We are using stock spf.ini settings (i.e. none)

We're worked around it by disabling the spf plugin for now. Any idea what's going on?

**Comment by spathon** [comment]
Might be good to mention that I have received the same error for older versions of haraka.

**Comment by johngrasty** [comment]
I am seeing this a lot. The SPF plugin was working fine before I upgraded to the most current. I did skip one or two point releases.

I am happy to do whatever is necessary to debug the problem. I just don't know node. :-D 

Thanks for the great piece of software.

**Comment by msimerson** [comment]
Just noting that this is still an issue with the latest releases:

````
Oct  4 17:28:17 haraka haraka[13156]: [ERROR] [B8771BC0-DDA6-4483-8D52-D979EBDCE47D] [core] spf plugin ran callback multiple times - ignoring subsequent calls
Oct  4 17:28:17 haraka haraka[13156]: [ERROR] [B8771BC0-DDA6-4483-8D52-D979EBDCE47D] [core] spf plugin ran callback multiple times - ignoring subsequent calls
Oct  4 17:28:26 haraka haraka[13156]: [ERROR] [8C895F28-3B23-4A5B-BD54-CC48D063DE0F.1] [core] spf plugin ran callback multiple times - ignoring subsequent calls
````

**Comment by msimerson** [comment]
I just checked the last week of my logs and this seems to have been fixed. Most of the changes to `./spf.js` and './plugins/spf.js` since Oct 16 are of the es6 and lint variety, but perhaps one of them had a beneficial effect. If anyone is still getting this error, please post here or reopen this issue.
