### ISSUE TITLE
Plugins link on manual frontpage links to manual frontpage

### ISSUE THREAD

**Issue by joelbernstein** [haraka/Haraka#1465]
### Haraka version
Github hosted pages

### Expected behavior
Plugins link on https://haraka.github.io/manual.html links to a list of plugins

However, visiting any plugin page (e.g. https://haraka.github.io/manual/plugins/auth/flat_file.html) shows the menu is a Javascript dynamic list. https://haraka.github.io/manual/plugins/ is a 404.

### Observed behavior
Plugins link on https://haraka.github.io/manual.html links back to same page

### Steps to reproduce
Visit https://haraka.github.io/manual.html
Observe that 'plugins' link (second paragraph: "Haraka has very good spam protection (see __plugins__) and works well as a filtering MTA. " does not link to a list of plugins

**Comment by baudehlo** [comment]
Can you file this against haraka/haraka.github.com instead? Thanks.

**Comment by baudehlo** [comment]
FWIW what this is supposed to do is link to the anchor at the bottom of the page. But it should still be filed on https://github.com/haraka/haraka.github.com instead.
