### ISSUE TITLE
Local config ignored in favor of default config

### ISSUE THREAD

**Issue by darkpixel** [haraka/Haraka#1471]
I think #1467 is still occurring.

### Haraka version
2.8.3

### Expected behavior
```haraka -c .``` should load the config in the current directory.  My config/plugins only have the ```queue/lmtp``` plugin loaded and has ```queue/smtp_forward``` commented out.  The ```queue/smtp_forward``` plugin should not be loaded.

### Observed behavior
```haraka -c .``` loads the default config from ```/usr/lib/node_modules/Haraka/config/plugins``` which includes ```queue/smtp_forward``` in addition to ```queue/lmtp```.

Editing ```/usr/lib/node_modules/Haraka/config/plugins``` and removing ```queue/smtp_forward``` causes the plugin to not be loaded.

### Steps to reproduce
```
npm install -g Haraka
Haraka -i /tmp/haraka-test
```
Edit ```/tmp/haraka-test/config/plugins``` and remove ```queue/smtp_forward```.

```haraka -c /tmp/haraka-test -o```

Note that ```queue/smtp_forward``` is listed.

**Comment by brightcode** [comment]
I can confirm the issue. Just did a simple default install and changed config/plugins. However Haraka keeps loading the default plugins.

**Comment by baudehlo** [comment]
Yep, I see the bug. Working on it.

**Comment by baudehlo** [comment]
This is now fixed and released as Haraka 2.8.4. Please test and let us know if you continue to see any problems.
