### ISSUE TITLE
Cant use server.notes in later events

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1476]
Haraka version 2.8.4

I save information in `server.notes` in the `init_master` event.

When i get `server.notes` in the `queue` event notes are empty. I also try `connection.server.notes` and  is empty too. 
Why? Is this the expected behavior? How can I access `server.notes` the in `queue` event?

I think this may be a new bug or a new behavior, it believe the same code was working in older haraka versions.

Thanks

**Comment by baudehlo** [comment]
Sharing data between master and server should never be considered as reliable. Use an external database such as redis (available as a plugin) or anything else.

**Comment by ricardopolo** [comment]
@baudehlo This is my requirement: I need to read a file from the file system that has a  certificate that I need later. How can I read only once from the File System and reuse it later in the plugin?

**Comment by ricardopolo** [comment]
Ok fixed. I was using `init_master` instead `init_child`. it used to work because we dind have cluster active.
