### ISSUE TITLE
Scrambled accents in email body version 2.8.x

### ISSUE THREAD

**Issue by swerter** [haraka/Haraka#1477]
### Haraka version 
2.8.0-2.8.4

### Expected behavior
When sending an outgoing email from outlook 2010 with accents in it (eg àèü), the message body gets scrabled. 

### Observed behavior
Instead of á é í ó ú ñ, the email body shows ï¿½ ï¿½ ï¿½ ï¿½ ï¿½ ï¿½

Message sent is multipart, with the text content part being:

    ------=_NextPart_000_002D_01D1B620.0C9A69F0`
    Content-Type: text/plain;
	charset="Windows-1252"
    Content-Transfer-Encoding: base64

    4SDpIO0g8yD6IPENCg0KClNlbnQgdmlhIE1pZ2FkdS5jb20sIHdvcmxkJ3MgZWFzaWVzdCBlbWFp
    bCBob3N0aW5nCg==
    ------=_NextPart_000_002D_01D1B620.0C9A69F0
    Content-Type: text/html;
	charset="Windows-1252"
    Content-Transfer-Encoding: quoted-printable

### Steps to reproduce
Upgrade from haraka 2.7.3 to haraka 2.8

Please let me know if you need additional informations. Thanks!

**Comment by baudehlo** [comment]
I can't replicate this. Can you detail what plugins you are running?

**Comment by swerter** [comment]
I created a test repo: https://github.com/migadu/haraka_testcase_1477 with a readme how to replicate. It seems the set_banner method scrambles the html content.

**Comment by baudehlo** [comment]
Thanks for the test case - it helped massively.

Fixed in #1483

**Comment by swerter** [comment]
Most welcome! Thank you for Haraka.
