### ISSUE TITLE
How to stop haraka in a Cluster

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1478]
I used to use `process.exit()`, but when using cluster it stops each process and start back after a while.

So how I can I completely stop Haraka programatically?

**Comment by baudehlo** [comment]
Pull in the branch for PR #1470 and issue: `server.sendToMaster('gracefulShutdown');`

**Comment by ricardopolo** [comment]
Let's merge it!

**Comment by baudehlo** [comment]
Have you tested it?

**Comment by ricardopolo** [comment]
I haven't yet, I was waiting for the merge and release for testing :fire:

**Comment by ricardopolo** [comment]
Hi @baudehlo I test it. But I facing an issue: after call it 'I receive messages saying "Shutitng down..." but it does not stop.
<img width="682" alt="screen shot 2016-06-07 at 10 39 41 am" src="https://cloud.githubusercontent.com/assets/1263856/15864309/36c300f0-2c9c-11e6-94fa-130a33b5d3a2.png">


Any advice?

Thanks!

**Comment by baudehlo** [comment]
Upgrade. This was just fixed.

**Comment by ricardopolo** [comment]
@baudehlo tu which version?
I'm facing this behavior with v2.8.6

**Comment by baudehlo** [comment]
Poop. Try latest PR I just did.

**Comment by baudehlo** [comment]
https://github.com/haraka/Haraka/pull/1503

**Comment by ricardopolo** [comment]
With the latest release it works as :)
