### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by jlsjonas** [haraka/Haraka#1487]
## Haraka version
master on github
## Expected behavior
Build succeeding
## Observed behavior
![screenshot](https://i.imgur.com/gbwPDrC.png)
### Travis

[![Build issue](https://camo.githubusercontent.com/a35810fc569814dbd511a1cdded6a90a0da0abad/68747470733a2f2f7472617669732d63692e6f72672f686172616b612f486172616b612e7376673f6272616e63683d6d6173746572)](https://travis-ci.org/haraka/Haraka)

### Appveyor

[![status appveyor](https://camo.githubusercontent.com/42d6f78b4abcceec8b1c53b9d122ebba5c70008c/68747470733a2f2f63692e6170707665796f722e636f6d2f6170692f70726f6a656374732f7374617475732f6732396c3234773771776f616d3437663f7376673d74727565)](https://ci.appveyor.com/project/msimerson/haraka-pa8a5)

**Comment by msimerson** [comment]
Closing, for now at least. Yes, Appveyor builds are failing. But Windows isn't officially supported, and it only passes tests when someone (last time: me) takes the time to make sure all our code uses require('path') instead of hard coded paths. 

PRs are always welcome.
