### ISSUE TITLE
Cherry Pick LOGLEVEL for logging.js

### ISSUE THREAD

**Issue by erickpece** [haraka/Haraka#1488]
The logging functionality in Haraka currently allows for a single log level to be specified, and all levels above the specified one will be included as well.  For an organization that doesn't need to log INFO or NOTICE messages, but wants to still log PROTOCOL (for proof of attempted delivery as an example), this means storing additional data.

A feature to cherry pick individual log levels would be nice - so you could maybe just get:

PROTOCOL
WARN
ERROR
CRIT
ALERT
EMERG

Or, any combination of levels as needed given the specific use case.

**Comment by baudehlo** [comment]
Storage is pretty cheap, and there are many fine tools within the logging infrastructures available to support these needs. For example with runit, svlogd can grep for particular lines.

Without a PR, or at the very least details of a design to hash out, I think this should be closed.

**Comment by msimerson** [comment]
Moved to the [#Feature Requests](https://github.com/haraka/Haraka/wiki) section of the wiki page.
