### ISSUE TITLE
Body encoding/decoding charset

### ISSUE THREAD

**Issue by lebedevmi** [haraka/Haraka#1489]
### Haraka version

Latest (2.8.4).

### Expected behavior

Email with cyrrillic body text or with attachment encoding/decoding to correct charset that was set in body.

### Observed behavior

Email body encodes/decodes probably directly to utf8 - ignoring charset in body.

### Steps to reproduce

I have attached all source emails.

1) "original_yandex" are emails that was sent from yandex to haraka.

2) "haraka_email" are emails that was processed by haraka.

[emails.zip](https://github.com/haraka/Haraka/files/291491/emails.zip)

**Comment by baudehlo** [comment]
This was fixed by #1483
