### ISSUE TITLE
Migrate to maxMind's new API

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#1493]
### Haraka version

All

### Steps to reproduce

Maxmind has a new API for GEO lookups. We should migrate to it whenever we can.

https://github.com/runk/node-maxmind/wiki/Migration-guide

**Comment by msimerson** [comment]
* [x] I have updated [maxmind-geolite-mirror]() to fetch the newer v2 databases. 

### Problems to be solved

* [ ] v2 databases don't have ASN info.

### potential solutions

* have connect.asn load maxmind 0.6 (if available) and use it for getting ASN info (much faster than via DNS providers).
* then connect.geoip can be upgraded to maxmind 1.0+
