### ISSUE TITLE
Receive email via POST

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1509]
Hi. I want to know if Haraka has some it built it or via plugins like this:

We use mailgun/sendgrid to send emails from our websites. Those services are a little bit expensive.

They simply receive a HTTP POST and send a message through SMTP. So... maybe Haraka may allow us do  something like that? Receive a http request, and send and email usingnodemailer?

I know I can implement my own Express website and send using nodemailer or something...

Thanks and regards :)

**Comment by Dexus** [comment]
Hi @ricardopolo,

You can create your own Plugin, that use the HTTP-Server that is buildin.

A Example for sending eMails internal with Haraka you can find here: http://haraka.github.io/manual/Outbound.html

More infos about how to create a plugin you can find here: http://haraka.github.io/manual.html
And let you inspire by reading the other plugins, so you can create a Plugin that fits your needs.

Regards,
Josef

**Comment by baudehlo** [comment]
Nothing built in but there is already a built in HTTP server using express so it would be trivial to implement.
