### ISSUE TITLE
Use Haraka as a proxy

### ISSUE THREAD

**Issue by pconihout** [haraka/Haraka#1515]
Hello,

I would like to monitor emails sent using Business Gmail Account. 
Basically, I was thinking into installing Haraka into AWS and then reroute Gmail to this server. 

But it doesn't seem so simple, i've installed TLS, tried with rcpt_to.in_host_list too, but none of that seems to work. Maybe I'm totally wrong on the way to do it so if you have any advices, I would love to hear from you ;)

> 
> [NOTICE] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] connect ip=209.85.161.199 port=34161 local_ip=:: local_port=25
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running connect_init hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running connect_init_respond
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running lookup_rdns hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running connect hooks
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 220 ip-172-31-60-73 ESMTP Haraka 2.8.6 ready
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] C: EHLO mail-yw0-f199.google.com state=1
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running ehlo hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running capabilities hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running capabilities hook in tls plugin
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] hook=capabilities plugin=tls function=tls_capabilities params="" retval=CONT msg=""
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250-ip-172-31-60-73 Hello mail-yw0-f199.google.com [209.85.161.199], Haraka is at your service.
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250-PIPELINING
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250-8BITMIME
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250-SIZE 0
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250 STARTTLS
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] C: STARTTLS state=1
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running unrecognized_command hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running unrecognized_command hook in tls plugin
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 220 Go ahead.
> [DEBUG] [-] [core] Upgrading to TLS
> [DEBUG] [-] [core] TLS secured.
> [INFO] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [tls] secured: cipher=ECDHE-RSA-AES128-GCM-SHA256 version=TLSv1/SSLv3 verified=true cn="smtp.gmail.com" organization="Google Inc" issuer="Google Inc" expires="Oct 12 00:00:00 2016 GMT" fingerprint=41:D4:85:E1:FC:1B:1D:3A:2D:60:E3:51:AB:E6:4A:A4:52:D8:CF:00
> [INFO] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] hook=unrecognized_command plugin=tls function=tls_unrecognized_command params="STARTTLS" retval=OK msg=""
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] C: EHLO mail-yw0-f199.google.com state=1
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running ehlo hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running capabilities hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] running capabilities hook in tls plugin
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] hook=capabilities plugin=tls function=tls_capabilities params="" retval=CONT msg=""
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250-ip-172-31-60-73 Hello mail-yw0-f199.google.com [209.85.161.199], Haraka is at your service.
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250-PIPELINING
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250-8BITMIME
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] S: 250 SIZE 0
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED] [core] C: MAIL FROM:<pier@gmailbusinessaccount.com> SIZE=2626 state=1
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] running mail hooks
> [NOTICE] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] sender <pier@gmailbusinessaccount.com> code=CONT msg=""
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] S: 250 sender <pier@gmailbusinessaccount.com> OK
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] C: RCPT TO:<john@company.com> state=1
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] running rcpt hooks
> [NOTICE] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] recipient <john@company.com> code=CONT msg="" sender="pier@gmailbusinessaccount.com"
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] S: 550 I cannot deliver mail for <john@company.com>
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] C: DATA state=1
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] S: 503 RCPT required first
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] C: QUIT state=1
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] running quit hooks
> [PROTOCOL] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] S: 221 ip-172-31-60-73 closing connection. Have a jolly good day.
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] running reset_transaction hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] running disconnect hooks
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] running disconnect hook in tls plugin
> [DEBUG] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] hook=disconnect plugin=tls function=hook_disconnect params="" retval=CONT msg=""
> [NOTICE] [C249503F-76B0-4E63-827E-24A8E9C1BAED.1] [core] disconnect ip=209.85.161.199 rdns="mail-yw0-f199.google.com" helo="mail-yw0-f199.google.com" relay=N early=N esmtp=Y tls=Y pipe=N errors=1 txns=1 rcpts=0/0/1 msgs=0/0/0 bytes=0 lr="503 RCPT required first" time=0.197

**Comment by Dexus** [comment]
First: AWS EC2 don't allow PORT 25 Incoming/Outgoing Traffic. So you cant use that Port.

**Comment by smfreegard** [comment]
@Dexus: that's incorrect.  It is rate-limited, but all you have to do is raise a ticket and they will remove it if you state that you're running a mail server.

**Comment by smfreegard** [comment]
@pconihout - what you're trying to do is set-up Haraka as a *relay* for your Google Apps organization, and therefore rcpt_to.in_host_list does not apply as this is for accepting *inbound* traffic to specific domains for onward delivery.

I do exactly the same thing that you are describing, we have a Google Apps domain and we scan inbound/outbound traffic from the Apps domain - however I don't use the standard plugins to do this, I have a complete framework that I've built into a mail security product that we sell.

You appear to already have found that you need to use the Google Apps 'Outbound Gateway' to route the outbound traffic from Google to Haraka, unfortunately Google does not allow you to specify SMTP AUTH credentials to the outbound gateway, so you *have* to do it by IP address ranges as specified by Google:  https://support.google.com/a/answer/60764?rd=1

This is where it gets to be a bit tricky with the in-built Haraka plugins.   To do this you'll need to use the relay plugin - see https://github.com/haraka/Haraka/blob/master/docs/plugins/relay.md for the documentation and basically you'll need to add this to your config/plugins file and then add the Google IP ranges to config/relay_acl_allow, not that you'll need to enable ACL lookups in the \[relay\]  section of the the plugin as per the docs as well.

This is slightly sub-optimal as it means that you'll have to keep up to date with changes to the IP ranges published by Google which is different to how I allow the relaying.  Here - I do it by FCrDNS portion e.g. any host ending in .google.com is allowed to relay, but only using envfrom domains that I specify, however you don't have this option with the stock plugin.

Note also that you'll need to contact AWS and make sure that you're exempt from rate-limiting on your EC2 host *AND* set-up proper rDNS for the EC2 host that reflects your domain name and hostname of the server.   To do this will require an Elastic IP for the EC2 host and once you have set this up you use this form:  https://aws-portal.amazon.com/gp/aws/html-forms-controller/contactus/ec2-email-limit-rdns-request

Hope that helps.

**Comment by pconihout** [comment]
@smfreegard : Thanks a lot for your help, it works perfectly now ! :) :)

**Comment by pconihout** [comment]
@smfreegard : I was just wondering, in terms of queuing a load balancing, what do you use ?

**Comment by smfreegard** [comment]
I use HAProxy if I need to balance traffic across more than one host.

**Comment by pconihout** [comment]
@smfreegard : and no queue ?

**Comment by smfreegard** [comment]
If you balance inbound SMTP, then by definition you spread the load outbound no?

**Comment by pconihout** [comment]
Actually i'm kind of noob in these domains, and I just want to be sure that no emails are lost.

**Comment by baudehlo** [comment]
Emails can't get lost. SMTP is a very stable protocol which always retries
if something fails, even with one server.

**Comment by pconihout** [comment]
@smfreegard : In addition, it should work with Office 365 and private servers. What would happen if I write 0.0.0.0/0 in config/relay_acl_allow ?

Will the emails be marked as spam ?

**Comment by trentmillar** [comment]
So far I have tried running Haraka on Azure and AWS. Both block port 25. I have submitted and have been approved by AWS after submitting this form, https://aws-portal.amazon.com/gp/aws/html-forms-controller/contactus/ec2-email-limit-rdns-request and still no traffic on port 25.  Haraka works great on other ports except 25. 

I have also looked at other cloud vm alternatives and no luck. Google Compute Engine https://cloud.google.com/compute/docs/tutorials/sending-mail/ also blocks 25, and Digital Ocean threads state 25 is blocked on their VMs too.

Unless I am missing something, Haraka is not practical a hosted environment. Has anyone been able to receive inbound traffic on port 25 on any VM?

@smfreegard It sounds like you have a working setup on EC2. If so can you provide more detail on getting Haraka on port 25 running?

**Comment by smfreegard** [comment]
@trentmillar - I'm not using AWS any more.  Provided you've filled-out the necessary form and opened up port 25 on the firewall, it should work just fine.

It sounds like you just haven't modified the firewall settings in AWS to allow it.  Inbound port 25 has always been possible - it's outbound port 25 that they rate-limit (aggressively and for good reason).

**Comment by baudehlo** [comment]
For AWS/EC2 you need to request a static IP, register your reverse DNS, and
add a rule to allow inbound port 25.

The form there is for allowing outbound, not for inbound. For inbound you
just need to add a security group that allows that.

**Comment by trentmillar** [comment]
I have two DNS zones; my domain and then the rDNS to my mail host using the Elastic IP I assigned to my EC2 instance. I'm pretty sure I've set up everything correctly based on Steve's steps and the Haraka documentation.

I've spent a few days setting up & testing with multiple VMs on both Azure & AWS. Everything works when I use any other port than 25, including 587 when I define an auth plugin. 

I always make sure ufw is disabled and my iptable route begins by allowing all traffic, there should be zero friction from my machine. Running `tcpdump` on 25 shows no traffic other than some random packets from a random AWS host sporadically.

FYI, I typically create an Elastic Load Balancer that maps ports. In this case, I created a LB mapping port 25 to the internal port 2525. This made no difference and the Haraka server still sees nothing on 2525. This rules out an issue with iptables or firewall since 2525.

Currently, I have found that the following cloud providers block 25,

- Digital Ocean
- Azure
- Google Engine
- *AWS

AWS, has the application to lift sending limits on the instance. I have requested this and been approved but still nothing. I'll reply to this thread if I can successfully get Haraka running on 25.

**Comment by Chimdiya1** [comment]
> I have two DNS zones; my domain and then the rDNS to my mail host using the Elastic IP I assigned to my EC2 instance. I'm pretty sure I've set up everything correctly based on Steve's steps and the Haraka documentation.
> 
> I've spent a few days setting up & testing with multiple VMs on both Azure & AWS. Everything works when I use any other port than 25, including 587 when I define an auth plugin.
> 
> I always make sure ufw is disabled and my iptable route begins by allowing all traffic, there should be zero friction from my machine. Running `tcpdump` on 25 shows no traffic other than some random packets from a random AWS host sporadically.
> 
> FYI, I typically create an Elastic Load Balancer that maps ports. In this case, I created a LB mapping port 25 to the internal port 2525. This made no difference and the Haraka server still sees nothing on 2525. This rules out an issue with iptables or firewall since 2525.
> 
> Currently, I have found that the following cloud providers block 25,
> 
> * Digital Ocean
> * Azure
> * Google Engine
> * *AWS
> 
> AWS, has the application to lift sending limits on the instance. I have requested this and been approved but still nothing. I'll reply to this thread if I can successfully get Haraka running on 25.

Long time ago, but were you able to get haraka to work on AWS?
