### ISSUE TITLE
Unclear what variables are available , if any , from config files 

### ISSUE THREAD

**Issue by cloverboxfox** [haraka/Haraka#1516]
I am using a standard linux distro . 

I would like to be able to configure certain things mostly paths using ENVIRONMENT variables in my haraka config files . 

This is not really an issue but documentation clarity . 
Thank you for open sourcing it .

**Comment by smfreegard** [comment]
You can't use ENV variables in config files.  You would have to create your config files on start-up or boot using the appropriate ENV variables to do so.

**Comment by cloverboxfox** [comment]
Fair enough thats not to hard . 
Just a bit confudeld .
A little wrapper script to generate the config then run the service . 

Thank you .
