### ISSUE TITLE
SSL Certificate in the Express instaled by default

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1517]
How can we enable HTTPS in the web server built in? Where do we specify or place the certificate key?

In the `http.ini`, I just found the port and the docroot for the web server.

Thanks :)

**Comment by Dexus** [comment]
Currently there is no option to enable https web server nor is it currently implemented.

But we are accept pull request, so if you like to implement it, we are happy to see your PR.

**Comment by baudehlo** [comment]
It's probably better if you put nginx in front anyway for this.

**Comment by msimerson** [comment]
> put nginx in front

I second this, that's how I do it.

However, adding the TLS support is also a reasonable option.

**Comment by sumpton** [comment]
Or haproxy, which we use to terminate. It is light, simple and fast.  It is the linux way to pipe, and in my opinion it makes sense for other projects to maintain and evolve their essential bits that need to keep up with our industry's constant evolution.

**Comment by ricardopolo** [comment]
I think we should add the option for TLS support or completely remove the current web server and force to using nginx.

With HTTP/2 and other current technologies is a web server without certificates is not a useful web server.

**Comment by darkpixel** [comment]
...but what would Nginx talk to?  Nginx is basically a proxy that speaks HTTP and a few other back-end protocols.

Additionally HTTPS is useless for me.  My mail servers have 'private' interfaces that are accessible over a management network.  I don't want to have to constantly hit TAB 5 times, then enter, then tab, then enter again (the keyboard sequence to get past the annoying Chrome 'you have a bad cert' screen).

**Comment by msimerson** [comment]
> a web server without certificates is not a useful web server.

That's an opinion you are entitled to hold. However, that doesn't make it the only valid one. Many of us have different infrastructure needs and prefer to deploy all our HTTP servers/services as HTTP (KISS principle) and handle all the SSL termination "out front" with haproxy / nginx. This is **especially** important in environments where certificate management is less ad hoc (think: FIPS / HIPPA / other legal compliance standards).

**Comment by ricardopolo** [comment]
I was not saying that is not usefull. I am saying that is not usefull for new technologies like HTTP/2.

**Comment by baudehlo** [comment]
Closing this as a non-issue. Put a proxy server in front if you want SSL. That's the team's stance on this. The http server is designed to be minimal not full-featured.
