### ISSUE TITLE
Elasticsearch not working when Cluster

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1518]
If we have the log.elastisearch plugin enable it works when `nodes=0` in `smtp.ini`.

If whe have `nodes=2`, it connects and after a while we see
[ERROR] [-] [log.elasticsearch] cluster is down!

We are using Haraka 2.8.6 and Node 6.2.1

**Comment by Dexus** [comment]
it should more a problem of the elastic search module.

**Comment by baudehlo** [comment]
The code around that says:

```
            // we don't bother error handling hear b/c the ES library does
            // that for us.
            plugin.logerror('cluster is down!');
```
So I'm going to close this as not an issue, just an error message in the logs.
