### ISSUE TITLE
UPGRADE.md is stale - do we need it?

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#1522]
Title says it all.

**Comment by msimerson** [comment]
February isn't *that* old. 

The file is only needed by folks still running ancient versions of Haraka and are considering an upgrade. One could rightly argue that it's insufficient for that purpose, and that it's not well maintained. Maybe it's the sort of thing that belongs in a wiki page instead.

**Comment by baudehlo** [comment]
Yeah I'd say put it on the wiki instead. It misses all the info on the 2.8
upgrade.

**Comment by msimerson** [comment]
Moved [here](https://github.com/haraka/Haraka/wiki/Upgrade).

**Comment by baudehlo** [comment]
Cool, I added the v2.8 upgrade notes to it.
