### ISSUE TITLE
Dont completly stop when using clusters

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1523]
I call `server.sendToMaster('gracefulShutdown')` in `init_http`.
I run Haraka with `Nodes=2` with the latest commit (432174a24d9a8eb13da87712590bb2c2e773d8d1)

It runs this way
<img width="685" alt="screen shot 2016-06-23 at 6 54 37 pm" src="https://cloud.githubusercontent.com/assets/1263856/16323869/04d712ae-3974-11e6-9def-9d27961a75ea.png">

It stucks there. Only finishes when  click Ctrl + C
<img width="617" alt="screen shot 2016-06-23 at 6 54 48 pm" src="https://cloud.githubusercontent.com/assets/1263856/16323883/15866dde-3974-11e6-991f-55c469a06bea.png">

**Comment by baudehlo** [comment]
Can you give a bit more details about how you setup this scenario?

**Comment by darkpixel** [comment]
How long did you wait before hitting CTRL+C.  Isn't there a 30-second timeout or something in case a plugin doesn't shut down properly?

**Comment by baudehlo** [comment]
There is yes, but every core plugin is expected to shutdown nicely.

**Comment by darkpixel** [comment]
True, I was just curious as it might give a clue towards where the issue lies.

**Comment by baudehlo** [comment]
Without any response to this issue, I'm going to have to close this. Reply with more details to re-open.

**Comment by ricardopolo** [comment]
Ok.

I can isolated the issue.
It happens when you 
````js 
 server.sendToMaster('gracefulShutdown');
````

But dont return `next()`

This code fails


````js
exports.register = function() {
  this.register_hook('init_http', 'exit_on_init');
};

exports.exit_on_init = function (next, server) {
  server.sendToMaster('gracefulShutdown');
};
````

This works
````js
exports.register = function() {
  this.register_hook('init_http', 'exit_on_init');
};

exports.exit_on_init = function (next, server) {
  server.sendToMaster('gracefulShutdown');
  return next();
};

`````

**Comment by ricardopolo** [comment]
I'm not sure if this is a expected behaviour or not, but for me is fixed :)
