### ISSUE TITLE
Aliases stoped working

### ISSUE THREAD

**Issue by benoit934** [haraka/Haraka#1525]
### Haraka version
Lastest
### Expected behavior
Rewriting domain
### Observed behavior
Nothing at all but hook runned
[DEBUG] [F9443D21-0172-4240-8E19-B5968276972D.1] [core] running queue hooks
[DEBUG] [F9443D21-0172-4240-8E19-B5968276972D.1] [core] running queue hook in aliases plugin
[DEBUG] [F9443D21-0172-4240-8E19-B5968276972D.1] [core] hook=queue plugin=aliases function=discard params="" retval=CONT msg=""
[DEBUG] [F9443D21-0172-4240-8E19-B5968276972D.1] [core] running queue hook in queue/smtp_forward plugin
[INFO] [F9443D21-0172-4240-8E19-B5968276972D.1] [queue/smtp_forward] forwarding to 178.32.166.231:25

### Steps to reproduce
Setup haraka with aliases plugin and send an email

**Comment by darkpixel** [comment]
It's breaking when you try to rewrite from one domain to another?

**Comment by benoit934** [comment]
Yes any contact to contact@exemple.com I didn't tried to put full adresses because it worked like this before.

The issued appeared on all my servers after updating I gonna try on the same domain with full address

**Comment by darkpixel** [comment]
I'm not able to reproduce it, but I believe have it narrowed down.
Can you post an example line from your aliases config that is failing?

**Comment by benoit934** [comment]
It is not aliases configuration it didn't changed and I've hard coded the redirection, exept the hook log the plugin don't seem to work.

I'll downgrade haraka

**Comment by darkpixel** [comment]
I'm testing with the latest version on NPM and I'm definitely seeing problems with aliasing domains.  At least the way I think the documentation implies domains could be aliases.  I'm curious about your aliases config to see if we are trying to do it the same way.  If so, I have already started writing a test and a fix for the issue.

I just want to make sure I'm hitting your use-case too.

**Comment by darkpixel** [comment]
I don't need the full config--just a line showing how you are aliasing domains.  Feel free to obfuscate the domains with example1.tld and example2.tld if you want.

**Comment by benoit934** [comment]
It was not the aliases files, neither plugins but it was a configuration issue, maybe an invisible char I've reinstalled and just kept aliases, hosts, smtp.ini and forward files and it's working.

Tonight I'll try to do an installation script and check if it's still working.

Thats weird because I've edited only thoses files ...

**Comment by baudehlo** [comment]
@benoit934 please at least provide some minimal config so we can check this out. We would rather try and resolve a bug than leave it hanging. Even if it was a rogue character.

**Comment by benoit934** [comment]
I've run an npm remove so the setup was deleted, I guess it was an issue with my script not your software.

I've also put aliases just after acess but my script was putting it just before smtp_foward I donno if it may cause this issue but it's the only thing I'd changed
