### ISSUE TITLE
Discussion - DKIM Replay Attack

### ISSUE THREAD

**Issue by zllovesuki** [haraka/Haraka#1526]
As per https://wordtothewise.com/2014/05/dkim-injected-headers/ stated, an attack could inject "fake headers" to a legitimate email. Is it practical to follow what the author stated to sign from,to,subject twice?

**Comment by msimerson** [comment]
Short answer: no

Longer answer: that article presumes that you're actually going to reject messages that fail the DKIM  test and in real life not very many sites do that. (See DMARC). 

 A better way going about preventing that is simply to reject messages who have multiple headers or the RFC you specify is only a single one. Haraka has the `headers` plug-in that optionally does that.
