### ISSUE TITLE
Outbound multiple IP rotation

### ISSUE THREAD

**Issue by rsgehlot** [haraka/Haraka#1527]
### Expected behavior

Folks, I'm new to haraka setup, and sincerely need your help to resolve the issue of outbound IP rotation.

Basically i need to bound multiple public IP based on destination domain. There is a outgoing.ini in plugin, and tried configuring the IPs but no luck.

Request you to please help us resolving the issue. If you have sample file which i can refere, please share.

Regards,
Rahul

**Comment by baudehlo** [comment]
You need to write your own plugin for this using the get_mx hook.

**Comment by rsgehlot** [comment]
Thanks -  Could you please help me getting me know the sequence of setting up plugin in haraka?

I will get the plugin developed, but need to know what are the location plugins to be enabled, and referenced.

**Comment by baudehlo** [comment]
http://haraka.github.io/manual/Tutorial.html
