### ISSUE TITLE
dkim_verify fails valid DKIM signatures from GMail

### ISSUE THREAD

**Issue by CmdLnInt** [haraka/Haraka#1530]
### Haraka version
2.7.0 Toaster
### Expected behavior
dkim_verify should pass GMail DKIM signed messages.
### Observed behavior
dkim_verify fails messages from GMail that are DKIM signed. The very same message gets DKIM_VALID from spamd.
### Steps to reproduce
Send mail from any GMail account to Haraka

**Comment by smfreegard** [comment]
> 2.7.0 Toaster

That's old; please use the latest.

**Comment by CmdLnInt** [comment]
Seems like 2.8.7 has the same issue.

**Comment by smfreegard** [comment]
Ok - thanks.  Can you put dkim_verify at the top of your config/plugins file and try again please.

**Comment by CmdLnInt** [comment]
I have tried at the top of the file and I still get the same result. I should add that I see other DKIM signed messages pass and therefore assume GMail is doing something different to the others.

**Comment by baudehlo** [comment]
Can you check if #1566 fixes this, please. Thanks.

**Comment by baudehlo** [comment]
Closing this due to lack of response from the author.
