### ISSUE TITLE
Custom HELO/EHLO message

### ISSUE THREAD

**Issue by xpepermint** [haraka/Haraka#1532]
As I can see from the source, Haraka v2.8.7 currently doesn't have support for EHLO response message customization. I don't want to tell a hacker what SMTP server I'm using so I would like to hide that information by replacing embeded `Haraka` messages (e.g. [Haraka is at your service.](https://github.com/haraka/Haraka/blob/master/connection.js#L787)) with my custom messages. Is there a specific reason that these messages are not configurable? Can we add this option please?

**Comment by baudehlo** [comment]
Patches for this are welcome. I would welcome this being configurable in a flexible manner.

**Comment by msimerson** [comment]
moved to [https://github.com/haraka/Haraka/wiki#feature-requests](https://github.com/haraka/Haraka/wiki#feature-requests)

**Comment by xpepermint** [comment]
ok

**Comment by Bramzor** [comment]
Reopening to create a pull request for this one

**Comment by Dexus** [comment]
Create a PR you don't need to reopen this here...
