### ISSUE TITLE
better `txn.message_stream.get_data` method

### ISSUE THREAD

**Issue by xpepermint** [haraka/Haraka#1537]
Version: 2.8.7

I tried to make the the code of the [dkim_sign](https://github.com/haraka/Haraka/blob/master/plugins/dkim_sign.js#L207) plugin easier so I went and replaced the `txn.message_stream.pipe` part with `txn.message_stream.get_data`. This caused a DKIM validator to return `body altered` message. 

I would propose to replace the `get_data` method with the code of `dkim_sign` plugin so we will be able to always use the `get_data` method and some custom methods. Thoughts?

**Comment by baudehlo** [comment]
No you can't do that. get_data is used in many places not just dkim. It
uses pipe internally anyway though, so i'm not sure why it would be
different.

**Comment by xpepermint** [comment]
Hum... ok... I find the plugin class too complex and I tried to modify it. Well... maybe later :).
