### ISSUE TITLE
SSL error: Wrong Version number

### ISSUE THREAD

**Issue by collinglass** [haraka/Haraka#1539]
### Haraka version
2.8.7

### Expected behavior
I attempt to blast a weekly newsletter of 10,000 emails.

### Observed behavior
My haraka server crashed after 248 emails sent.

Here are the logs:

[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] running ehlo hooks
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] running capabilities hooks
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] running capabilities hook in tls plugin
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] hook=capabilities plugin=tls function=tls_capabilities params="" retval=CONT msg=""
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] running capabilities hook in auth/flat_file plugin
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [auth/flat_file] Auth disabled for insecure public connection
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] hook=capabilities plugin=auth/flat_file function=hook_capabilities params="" retval=CONT msg=""
[PROTOCOL] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] S: 250-saas-smbsoftware.com Hello ns523489.ip-158-69-227.net [158.69.227.22], Haraka is at your service.
[PROTOCOL] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] S: 250-PIPELINING
[PROTOCOL] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] S: 250-8BITMIME
[PROTOCOL] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] S: 250-SIZE 0
[PROTOCOL] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] S: 250 STARTTLS
[PROTOCOL] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] C: STARTTLS state=1
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] running unrecognized_command hooks
[DEBUG] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] running unrecognized_command hook in tls plugin
[PROTOCOL] [1A0D0D21-F659-4ACE-9615-9467BA64E2ED] [core] S: 220 Go ahead.
[DEBUG] [-] [core] Upgrading to TLS
[CRIT] [-] [core] Error: 139650710751040:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
[CRIT] [-] [core]
[CRIT] [-] [core]     at SlabBuffer.use (tls.js:232:18)
[CRIT] [-] [core]     at CleartextStream.read [as _read] (tls.js:452:29)
[CRIT] [-] [core]     at CleartextStream.Readable.read (_stream_readable.js:320:10)
[CRIT] [-] [core]     at EncryptedStream.write [as _write] (tls.js:366:25)
[CRIT] [-] [core]     at doWrite (_stream_writable.js:223:10)
[CRIT] [-] [core]     at writeOrBuffer (_stream_writable.js:213:5)
[CRIT] [-] [core]     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
[CRIT] [-] [core]     at Socket.ondata (stream.js:51:26)
[CRIT] [-] [core]     at Socket.EventEmitter.emit (events.js:95:17)
[CRIT] [-] [core]     at Socket.<anonymous> (_stream_readable.js:746:14)
[CRIT] [-] [core]     at Socket.EventEmitter.emit (events.js:92:17)
[CRIT] [-] [core]     at emitReadable_ (_stream_readable.js:408:10)
[NOTICE] [-] [core] Shutting down

### Steps to reproduce

From a brand new ubuntu install I run the follow:

    sudo apt-get -y update
    sudo apt-get -y upgrade
    sudo apt-get -y install swaks nodejs npm opendkim opendkim-tools
    sudo ln -s /usr/bin/nodejs /usr/bin/node
    sudo npm install -g Haraka

    haraka -i outbound

add config files to config/

    echo "[core]
    methods=PLAIN,LOGIN,CRAM-MD5

    [users]
    yolo@haraka.test=yoloyolo1" > outbound/config/auth_flat_file.ini

    echo "disabled = false
    selector = jul2016._domainkey
    domain = example.com
    headers_to_sign = From, Sender, Reply-To, Subject, Date, Message-ID, To, Cc, MIME-Version" > outbound/config/dkim_sign.ini

    echo "tls
    auth/flat_file
    dkim_sign" > outbound/config/plugins

    echo "listen=[::0]:587
    daemonize=true
    daemon_pid_file=/var/run/outbound.pid" > outbound/config/smtp.ini

Run these commands from HOME ~/

    sudo opendkim-genkey -s mail -d example.com
    sh ~/outbound/config/dkim/dkim_key_gen.sh example.com
    openssl req -x509 -nodes -days 2190 -newkey rsa:2048 -keyout outbound/config/tls_key.pem -out outbound/config/tls_cert.pem
    mv example. outbound/config/dkim/

copy info inside ~/outbound/config/dkim/example.com/dns into DKIM DNS

    haraka -c .

**Comment by Dexus** [comment]
https://ssl-tools.net/mailservers/saas-smbsoftware.com
said no startssl support / invalide response.

ns523489.ip-158-69-227.net rejects connections.

It looks like you don't have enabled ssl/tls correct.
Can you please send also infos about your current node version?

**Comment by msimerson** [comment]
closing, due to lack of a response. Post additional info and reopen if appropriate.
