### ISSUE TITLE
outbound.send_email accept stream

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1549]
Hi.

We use Haraka for processing the email, make some changes, and send it again.

For doing that we use the `connection.transaction.message_stream.pipe`.
When we ended the modifications we send using `outbound.send_email`. However `outbound.send_email` only accepts a string, so we do something like
````js
outbound.send_email(connection.transaction.mail_from, connection.transaction.rcpt_to, message.toString(), function (code, msg) {});
````

As you see, we conver the stream to string, and you know that could be very memory intensive with large attachments.

Would you please allow send a stream?

Thanks!!

**Comment by ricardopolo** [comment]
Any comment @baudehlo?

IMHO this would very very useful. Nodemailer as example accept, a string, but also a STREAM and a path.

**Comment by baudehlo** [comment]
My comment would be: patches welcome :)

**Comment by baudehlo** [comment]
Anyone interested in this, please test the above referenced pull request. I don't have anything that uses outbound.send_email to test it with.

**Comment by ricardopolo** [comment]
@baudehlo great!!!! Thanks for that PR.

I'll test it in my environment tomorrow or on monday
