### ISSUE TITLE
Extremely slow outbound delivery

### ISSUE THREAD

**Issue by taoru** [haraka/Haraka#1552]
### Haraka version
    # haraka --version
    Haraka.js — Version: 2.8.8

### Expected behavior
Outbound delivery of at least 30-60 messages per minute.

### Observed behavior
Outbound delivery of 1-2 message per minute.

### Steps to reproduce
outbound.ini:

    enable_tls=true
    received_header=Example.com outbound
    always_split=true
    concurrency_max=100
    connect_timeout=5
    pool_timeout=100

smtp.ini

    listen=11.22.33.44:587
    public_ip=11.22.33.44
    inactivity_timeout=10
    nodes=56
    spool_dir=/opt/haraka_example_com/spool
    spool_after=0
    force_shutdown_timeout=30

Checking:

    # while true ; echo ( date ); haraka -c /opt/haraka_example_com/ --qstat; haraka -c /opt/haraka_example_com/ --qunstick; sleep 10; end
    Sat Jul 30 08:29:39 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1256 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:29:49 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1256 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:30:00 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1256 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:30:10 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1253 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:30:21 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1253 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:30:31 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1253 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:30:42 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1251 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:30:52 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1251 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:31:02 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1256 }
    250 Command sent for execution. Check Haraka logs for results.
    Sat Jul 30 08:31:13 GMT 2016
    { queue_dir: '/opt/haraka_example_com/queue', queue_count: 1250 }
    250 Command sent for execution. Check Haraka logs for results.

No plugins except dkim_sign.

Thank you!

**Comment by darkpixel** [comment]
nodes=65 seems high.  How many cores do you have on that box?  Also, what plugins do you have enabled?

**Comment by taoru** [comment]
@darkpixel I have 56 cores (actually it's `nodes=cpus` in the config). Anyway, I tried everything from commenting out the `nodes` to making it 2, 4, 8 or 16.

**Comment by taoru** [comment]
Got it. The problem was a misconfiguration on the receiving end (slow handshake, but the connection was established so timeouts weren't firing). I've hard-coded the MX blacklist in the get_mx hook and the sending is back to normal now. Thank you.
