### ISSUE TITLE
Using wrong SMTP for outbound delivery

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1556]
We have a plugin.

In the `queue` event  we query an API to get a outbound SMTP server for each email. The API uses the sender email address to determine which SMTP will use. The result of the API is store in the transaction notes

``` js
          connection.transaction.notes.mx = {
              priority: 0,
              exchange: parsed.OutboundServer.trim(),
              port: parsed.OutboundServerPort.trim()
          };
```

Later, in the `get_mx` event we use the information stored in the notes to select the smtp server. If the information is not present, because the API is down or something, we send using standard procedure (looking the MX DNS entry).

``` js
  exports.set_smtp_server =  function (next, hmail, domain){
    if(hmail.todo.notes.mx){
      return next(OK, hmail.todo.notes.mx);
    }
    else {
      return next();
    }
  };
```

It works. It sends every email using the server from the API, and if we stop the connection to the API it delivers using the MX.

But, we have a problem. We are facing an issue where some emails intended to be to one server, are going through another server. We double checked that the API is returning the right information.

Just in case is relevant, we use node clusters. 

So, we suspect maybe the notes are pass from one transaction to another (very unlikely). Or maybe the outbound pool option is keeping the server from another email.

Any advice?

Thank you!

**Comment by baudehlo** [comment]
It's likely the latter. I never thought about that.

**Comment by ricardopolo** [comment]
@baudehlo any way to disable outbound pool?

**Comment by baudehlo** [comment]
Set it to only allow one connection before closing.

**Comment by ricardopolo** [comment]
@baudehlo how? I dont find a variable that permits that.

**Comment by baudehlo** [comment]
Sadly there is no such variable... I guess you could set the pool timeout to 1 second. But realistically there should be such an option. I would say if `pool_timeout == 0` then connections shouldn't be pooled.

**Comment by baudehlo** [comment]
OK, I've aded support for outbound.ini pool_timeout=0 in the outbound_pool_bugfix branch.

**Comment by ricardopolo** [comment]
Thanks @baudehlo 

We'll be testing with that branch and close the issue when it gets merged.

**Comment by baudehlo** [comment]
Please don't close it. There's clearly a bug there in just relying on the domain.

**Comment by ricardopolo** [comment]
Understood :) @baudehlo

**Comment by ricardopolo** [comment]
The PR looks good @baudehlo, however I am seeing this in the logs
"Releasing a Pool that doesn't exist!"

![screen shot 2016-08-14 at 7 11 36 pm](https://cloud.githubusercontent.com/assets/1263856/17653047/10277c7c-6253-11e6-9fe7-0ce67f67bf78.png)


I add, using this PR instead the master, look like https://github.com/haraka/Haraka/issues/1551 is not happening anymore

**Comment by baudehlo** [comment]
Yeah that's no big deal. I should clean it up though.

**Comment by baudehlo** [comment]
Can you try that branch now? Thanks.

**Comment by ricardopolo** [comment]
@baudehlo looks good, I am not seeing the error anymore

**Comment by ricardopolo** [comment]
This is very sad @baudehlo, but using the master now, and having pool_timeout in zero, we still have emails from one company passing through another company server.

Any advice about what else should we looking for?
Thank you so much!

**Comment by baudehlo** [comment]
Poop.

Can you be more specific about the email addresses in question? Are they at the same domain? You're using a custom `get_mx` hook, right?

**Comment by ricardopolo** [comment]
@baudehlo here are some details:

1. We need to have a different server for each email adress (or group of them). Typically each different sender domain use a different outbount SMTP.
2.  In the queue hook we query the right smtp server from and API, and save the server and port in the notes.
3. In the get_mx we set the server from the notes
````js
  exports.set_smtp_server =  function (next, hmail, domain){
    if(hmail.todo.notes.mx){
      return next(OK, hmail.todo.notes.mx);
    }
    else {
      return next();
    }
  };
````

For some reason, som emails goes through the wrong server. The API responds the correct server. I dont know if there are some kind of reuse of notes, or the outbound connection, or something, that generates that confusion.

**Comment by baudehlo** [comment]
Do you have outbound.always_split set? You want that on.

**Comment by baudehlo** [comment]
Actually I don't even think that (always_split) will help, because if you're storing where to deliver to in transaction.notes it won't matter anyway.

I assume this is set based on mail_from?

Can you at least log some more info in the get_mx hook so you can check the destination is correct? You can access hmail.todo.mail_from and log that vs the returned server.

I can't find anything in the pool code that would cause this frankly, so you could even put the pool timeout back up to a reasonable value.

**Comment by ricardopolo** [comment]
Yes, the SMTP server returned by the API is based on mail_from.

 I configured always_split and make some logging to test it. I will be reporting the results to you

**Comment by ricardopolo** [comment]
I am not being able no identify this issue. We have changed the `always_split` and also put the pool_timeout in 0. The behavior continues.

I have suspects about the DNS resolutions.
In our scenario we query an API based on the FROM address.

For the user A it returns this MX `tulpep-com.mail.protection.outlook.com`
For the user B it returns this MX `tokenmedia-com01c.mail.eo.outlook.com`

And so on. These are different domains from multiple Office 365 customers. 
And in our issue some emails user B appears in the Office 365 logs of customer A.

The tricky part is that if you ping the MX server from A or B, they respond the same IP address. Office 365 shares the same IP for some customers and I think that generates the problem.

Maybe Haraka does not disconnect because they have the same IP address. Any advice about this?

Thank you @baudehlo

**Comment by ricardopolo** [comment]
@baudehle @msimerson and @smfreegard based on your vast knowledge about SMTP, do you have any advice about this?

Something about how fully disconnect Office 365 to dont confuse their servers maybe...

Thank you in advance!

**Comment by baudehlo** [comment]
Yeah I've been on vacation, sorry.

Are you able to be on IRC this weekend to discuss it?

**Comment by smfreegard** [comment]
I forgot about this too.

What perplexes me is this sentence: "Something about how fully disconnect Office 365 to dont confuse their servers maybe...".

There's not confusion as far as I can see.  If two systems have MX records that resolve to the same IP address, that it exactly how the pool should work e.g. it will deliver both messages over the same connection.   The remote end knows the difference because each message will have recipients in their respective domains...

Are you talking about the logs on Office365?  Because if so - then you've found a massive bug with their log reporting if it's leaking data between tenants.

**Comment by ricardopolo** [comment]
Of course I can IRC. Just tell me when and where?

I can share code that simulates that behavior

**Comment by baudehlo** [comment]
I'll be on #haraka on freenode this weekend. I'm baudehlo there.

**Comment by ricardopolo** [comment]
@smfreegard not exactly... because:
1. Company1 has this smtp server: Company1-protection.outlook.com 
2. Company2 has this smtp server: Company2-protection.outlook.com
3. Both DNS names resolves to the same IP.

These domains are the SMTP servers given for Microsoft for each Office 365 tentant.
so *office 365 does not use the IP of the A records to identify the customer.*


Company1 users can write to user1@hotmail.com and Company2 users can write to the same user1@hotmail.com. Both companies send to the same external user. So, *Office 365 could not use the recipient address.*

We have tested also the aliases features in Office 365, and a company can have multiple domains, so we know *Office 365 does not use the sender address*.  

What I think is that Office 365 detects that using the address given in the EHLO process.
If we share the same connection because they have the same IP the EHLO wont work.  Do you think that may be the issue? @baudehlo 

I think the pools should use the DNS name and not the IP Address to share the connections.

**Comment by baudehlo** [comment]
That doesn't make any sense. The EHLO name is our name, not the remote end.

Perhaps outbound.always_split will help?

**Comment by ricardopolo** [comment]
I tried with that setting on and off and still fails....  

I know lots of services that use that kind of configuration.. 

Example:
https://www.wix.com/support/html5/article/tutorial-connecting-your-office-365-services-to-wix

Look in that page for `mail.protection.outlook.com` and see how they send thought the customer server. And I don't think one customers emails goes through the other's server.

Another possibility that comes to my mind is that the pool is not closing fast enought, but I have `pool_timeout` in 0...

Any idea about what could be using Office 365 to identify each customer?  Or what could confuse them?

Thank yo soy much for all your willing to help!!

**Comment by ricardopolo** [comment]
@baudehlo @smfreegard any advice would be awesome!! 😄

**Comment by smfreegard** [comment]
You haven't given us nearly enough information or actually described the problem well enough.   

What you've described so far simply isn't possible, Office365 does not identify tenants by anything other than message that are addressed to the tenant in the RCPT TO: or the SMTP AUTH credentials provided if mail is being relayed out via them.

If you want to get to the bottom of this - you need to provide a *lot* of real-world detail and describe exactly what you are seeing and where.

**Comment by ricardopolo** [comment]
Ohh @smfreegard

**Comment by ricardopolo** [comment]
Ohh  @smfreegard thans for your answer and excuse me for not being clear enought.

I will try to explain in a better way:

What I mean is.. When the administrator of Company 1 goes to its Office 365 Exchange console, you see emails from Company 2 and Company 3, etc in the logs. You see other companies emails going thought his infrastructure.

That is very bad for our product, you don't want info from one customer leaking into another customer logs 🔥

I think, off course, Microsoft shares theirs servers across multiple customers, but don't know what uses it to identify that a specific emails goes through a specific customer.
All MX servers that Microsoft give to each customer has that format (customer-protection.outlook.com) and resolve to a shared server.

However you never see logs from a company into another one. However when sending to multiple customers in a few seconds Haraka logs are mixed!! I though it was something related to pooling but even disabling  it (`pool_timeout=0`) continue having that behavior.


If I am not being clear enough or need any more detail just tell me please.

Regards!!

**Comment by baudehlo** [comment]
Set pool_concurrency_max=0 in the new code and it'll be disabled.

Closing this.

**Comment by ricardopolo** [comment]
Thanks @baudehlo I wait lots for this.

When you will release this new version?

**Comment by baudehlo** [comment]
Soon.
