### ISSUE TITLE
Rspamd report header doesn't work

### ISSUE THREAD

**Issue by fatalbanana** [haraka/Haraka#1563]
### Haraka version

Tested git but should affect released versions as well (probably any featuring rspamd plugin).
### Expected behavior

If headers are added (because `always_add_headers` is set or rspamd recommended `add header`)- `X-Rspamd-Report:` should contain a list of matched symbols and their scores.
### Observed behavior

`X-Rspamd-Report:` is empty.
### Explanation

Code is looking for a `score` property but nothing it sees is actually an object. Possible solutions are:
- Changing format of cleaned data to have symbols grouped in a nested object (is this bad? seems bad)
- Returning unfiltered data in addition to cleaned data used for logs etc (maybe good idea?)
- Tracking which entries are actual symbols in another object (hmmm)
### Aside (EDIT)

During the short period in which this did work, it was pretty ugly- and could likely exceed length limits- it should be wrapped. Adding symbol 'options' could be nice too . :)

**Comment by msimerson** [comment]
Maybe save anyone reading this some cycles by posting some examples of the data. Then we can offer up opinions without digging into the code or a running server to see examples of these scores and symbols. Adding some sample data to the [docs](https://github.com/haraka/Haraka/blob/master/docs/plugins/rspamd.md) would also be welcome.

**Comment by fatalbanana** [comment]
Sample JSON from rspamd below:

```
{
    "default": {
        "is_spam": true,
        "is_skipped": false,
        "score": 20.469504,
        "required_score": 15.0,
        "action": "reject",
        "MIME_GOOD": {
            "name": "MIME_GOOD",
            "score": -0.100000,
            "description": "Known content-type",
            "options": [
                "multipart/alternative"
            ]
        },
        "MIME_HTML_ONLY": {
            "name": "MIME_HTML_ONLY",
            "score": 1.0,
            "description": "Messages that have only HTML part"
        },
        "R_MISSING_CHARSET": {
            "name": "R_MISSING_CHARSET",
            "score": 5.0,
            "description": "Charset is missing in a message"
        },
        "FORGED_SENDER": {
            "name": "FORGED_SENDER",
            "score": 0.300000,
            "description": "Sender is forged (different From: header and smtp MAIL FROM: addresses)"
        },
        "DBL_SPAM": {
            "name": "DBL_SPAM",
            "score": 6.500000,
            "description": "DBL uribl spam",
            "options": [
                "hookup8888.in.dbl.spamhaus.org"
            ]
        },
        "BAYES_SPAM": {
            "name": "BAYES_SPAM",
            "score": 7.769504,
            "description": "Message probably spam, probability: ",
            "options": [
                "99.21%"
            ]
        }
    },
    "message-id": "_redcated_@themysteriesoflife.com",
    "dkim-signature": "v=1; a=rsa-sha256; c=relaxed/relaxed; d=rspamd.tk; s=testdkim; t=1470905106; h=from:reply-to:subject:date:message-id:to:mime-version:content-type; bh=l/RT3h02/UZ2xalaynLe+LF6K3y/ZmcTeFoB9yzcQ6E=; b=Wa2hm1yIwfnW8AyADIU4B3U/t+OKsgYLoIE0HRgCs33it5FXfyBKQbbiRit//WgYZGWKVZfhO8vutWwHi23593Ms7G4wpx3yLyqR/BK8U3OGinDouYgINJG2yOjEwdZe3Tmvt/uemIDd1+zK5PHi5LdwecmkAVtf5kZVDPtnIDI=",
    "rmilter": {
        "add_headers": {
            "X-Spamd-Bar": "++++++++++++++++++++",
            "X-Spam-Level": "********************",
            "X-Spam-Status": "Yes, score=20.47"
        },
        "remove_headers": {
            "X-Spamd-Bar": 1,
            "X-Spam-Level": 1,
            "X-Spam-Status": 1
        }
    }
}
```

Thing returned from parse_response looks like:

```{
  "data": {
    "is_spam": true,
    "is_skipped": false,
    "score": 21.169504,
    "required_score": 15,
    "action": "reject",
    "MIME_GOOD": -0.1,
    "DBL_SPAM": 6.5,
    "BAYES_SPAM": 7.769504,
    "MIME_HTML_ONLY": 1,
    "R_MISSING_CHARSET": 5,
    "FORGED_RECIPIENTS": 1
  },
  "controlData": {
  }
}```

Where only .data part is emitted to logs.

**Comment by msimerson** [comment]
@fatalbanana , has this issue been addressed yet?

**Comment by fatalbanana** [comment]
@msimerson it has not.

**Comment by fatalbanana** [comment]
[This](https://github.com/fatalbanana/Haraka/commit/88b5c9ac908e7bb2c02cd7d23db73aa1df6e86fd) could be one way of dealing with it. I'd like to try make that header a bit nicer to look at still.

**Comment by msimerson** [comment]
Other than calling the data object name `default`, which isn't very descriptive, that looks fine to me.

**Comment by msimerson** [comment]
disclaimers:  a) I'll never enable that header feature and b) I will want to see that data in Elasticsearch.
