### ISSUE TITLE
TypeScript 2.0

### ISSUE THREAD

**Issue by soncodi** [haraka/Haraka#1567]
## TypeScript

I'd like to open the discussion for refactoring the codebase to `TypeScript`. You can see the [roadmap here](https://github.com/Microsoft/TypeScript/wiki/Roadmap). Here are some bullets:

### For
- ES2016+ syntax bump (async/await, lambdas, classes, block scope, templates, etc..)
- Opt-in type safety
- Less magic (checked enums instead of strings)
- Transpile down to ES3/ES5 as needed
- Incremental/layered upgrade
- Tighter sync with documentation (defaults, optional values, etc)

### Against
- Work hours
- Potential bugs via refactoring
- TS learning curve
- Additional build step
- Changes to testing process

I tried to be generous with the 'against' points. But the following:

```js
if (cfg.pool_timeout === undefined) { // can also == 0 now
    cfg.pool_timeout = 300;
}
```
```js
for (var p in server.notes.pool) { // what is notes? nullable?
```

are also a barrier to entry to those unfamiliar with the codebase. Sadly that is the best idiomatic `JS` code can offer.

```sh
[DEBUG] [-] [core] running pre_send_trans_email hooks
[DEBUG] [-] [core] running pre_send_trans_email hook in dkim_sign plugin
[ERROR] [-] [TypeError]
```
Logs like the above are tough to debug without resorting to `console.log`. In many cases, `TS` preempts the situation via self-documenting, non-nullable types, and intellisense.

The moment seems opportune for `TS 2.0`. Thoughts?

**Comment by baudehlo** [comment]
So the only way I see this happening is if you start by porting plugins to npm modules, and write them as TypeScript. In fact that's the smartest way to do it anyway, and would be much easier for people who know TypeScript, rather than trying to get the core Haraka devs to try and pick it up.

Given that it's easily possible for others to start doing this (with the new 2.8 plugin architecture), I see no reason to keep this open.

**Comment by dcharbonnier** [comment]
It's really hard to write haraka plugins without haraka typing.
With some typings, it would become so much easier for contributors. An example I register my plugin, what's the function context, where can I find documentation about this API?
