### ISSUE TITLE
Socket in pool got FIN

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1570]
@baudehlo Removing the line configuration of  `pool_timeout=0`, in the latest version from master, just like the default config is I am getting this error.

"fin" in spanish means end, but I am not sure if that means the same in SMTP context :smile: 

![image](https://cloud.githubusercontent.com/assets/1263856/17824835/e83fa1e6-6629-11e6-9d05-4f79e1d7957a.png)

**Comment by baudehlo** [comment]
That's perfectly normal. It means the remote end had a shorter timeout than the pool.

**Comment by ricardopolo** [comment]
@baudehlo what I think is not normal is that after that we get an exception and haraka is stopped.

**Comment by baudehlo** [comment]
Oh right. Yes I see why.

**Comment by baudehlo** [comment]
Try the outbound_shutdown_error branch which I just pushed.

**Comment by ricardopolo** [comment]
@baudehlo it works!
