### ISSUE TITLE
Crash Haraka SSL3 & auto-launch ?

### ISSUE THREAD

**Issue by pconihout** [haraka/Haraka#1579]
I use Haraka as a proxy to monitor emails and this happened : it only happen once and i don't know why ...

[CRIT] [-] [core] Error: 140222797051776:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:362:
[CRIT] [-] [core] 
[CRIT] [-] [core]     at Error (native)
[CRIT] [-] [core]     at SlabBuffer.use (_tls_legacy.js:42:18)
[CRIT] [-] [core]     at CleartextStream.read [as _read] (_tls_legacy.js:260:29)
[CRIT] [-] [core]     at CleartextStream.Readable.read (_stream_readable.js:336:10)
[CRIT] [-] [core]     at EncryptedStream.write [as _write] (_tls_legacy.js:174:25)
[CRIT] [-] [core]     at doWrite (_stream_writable.js:300:12)
[CRIT] [-] [core]     at writeOrBuffer (_stream_writable.js:286:5)
[CRIT] [-] [core]     at EncryptedStream.Writable.write (_stream_writable.js:214:11)
[CRIT] [-] [core]     at Socket.ondata (_stream_readable.js:542:20)
[CRIT] [-] [core]     at emitOne (events.js:77:13)

Is there a way to automatically re-launch Haraka on crash ?

**Comment by darkpixel** [comment]
You can re-launch if you use a tool like 'forever'  (https://github.com/foreverjs/forever).

I'm not an SSL expert, but I believe this is because SSLv3 is disabled in OpenSSL on quite a few platforms now.

**Comment by smfreegard** [comment]
> You can re-launch if you use a tool like 'forever' (https://github.com/foreverjs/forever).

This is unnecessary for Haraka, just set `nodes=cpus` in config/smtp.ini and it will automatically restart should a crash like this occur.

> [CRIT] [-] [core] Error: 140222797051776:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:362:

Not sure on the cause, but it shouldn't crash Haraka.   Which version of Haraka and Node are you running?

**Comment by darkpixel** [comment]
I've had Haraka crash a few times and take down all the nodes.  Running under something like forever seems to be sensible to try and catch the occasional odd crash.  (i.e. GH-1576 kills Haraka.)

**Comment by baudehlo** [comment]
I'd rather users use something stable and system-wide like runit or systemd
than forever/pm2 - but either would work.

**Comment by msimerson** [comment]
Closing. If this recurs, please update your platforms OpenSSL, make sure node.js is up-to-date (there's been a few "update due to openssl vulnerability" releases lately), and upgrade Haraka. There's been a number of changes and fixes to the TLS code that was just published in 2.8.10.
