### ISSUE TITLE
hook_deferred don't change delay with next(DENYSOFT, '3600'), throw error

### ISSUE THREAD

**Issue by streamtOtO** [haraka/Haraka#1586]
### Haraka version
 2.8.8
### Expected behavior
 Call in  **hook_deferred** `next(DENYSOFT, '3600')`. Must delay email delivery for 3600 seconds.
### Observed behavior
Catch error `[CRIT] [687CEB36-7069-494E-B597-5A69DFFCA095.1.1] [outbound] Plugin bounce failed: TypeError: Cannot read property 'delay' of undefined
    at HMailItem.deferred_respond (/usr/lib/node_modules/Haraka/outbound.js:2072:23)
    at HMailItem.deny_respond (/usr/lib/node_modules/Haraka/plugins.js:558:39)
    at callback (/usr/lib/node_modules/Haraka/plugins.js:459:35)
    at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:463:45)
    at Object.plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:402:13)
    at callback (/usr/lib/node_modules/Haraka/plugins.js:454:21)
    at Plugin.exports.hook_deferred (/opt/prodata-email-validation-2/haraka/plugins/bounce.js:13:5)
    at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:486:28)
    at Object.plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:402:13)
    at HMailItem.temp_fail (/usr/lib/node_modules/Haraka/outbound.js:2063:13)
`
### Steps to reproduce
Call in  **hook_deferred** `next(DENYSOFT, '3600')`

### Maybe here error:
File Haraka/plugins.js, line [558](https://github.com/haraka/Haraka/blob/master/plugins.js#L558):
`object[respond_method](retval, msg)` call function with two parameters `(retval, msg)`, and in the file Haraka/outbound.js, line [2145](https://github.com/haraka/Haraka/blob/master/outbound.js#L2145), expect three parameters `HMailItem.prototype.deferred_respond = function (retval, msg, params)`, where `params` expected is ` object`  `{delay:'delay_in_seconds',err:'some message'}`

**Comment by smfreegard** [comment]
> HMailItem.prototype.deferred_respond = function (retval, msg, params), **where params expected is object** {delay:'delay_in_seconds',err:'some message'}

next(DENYSOFT, { delay: 3600 });

**Comment by streamtOtO** [comment]
> next(DENYSOFT, { delay: 3600 });

**Comment by streamtOtO** [comment]
> next(DENYSOFT, { delay: 3600 });

I try this too, problem is that {delay:3600} is msg variable here `HMailItem.prototype.deferred_respond = function (retval, msg, params)`, and i have error with this line [2151](https://github.com/haraka/Haraka/blob/master/outbound.js#L2151), `TypeError: Cannot read property 'delay' of undefined`, third parameter `params` undefined, later we have line [2159](https://github.com/haraka/Haraka/blob/master/outbound.js#L2159), where would be next error because `params.err` can't get `err` key from `undefined` .

**Comment by streamtOtO** [comment]
If i comment lines that trying to link to third argument in function `params`, all work's fine

**Comment by streamtOtO** [comment]
this function `function get_denyfn (object, hook, params, retval, msg, respond_method) {
    return function (deny_retval, deny_msg) {
        switch (deny_retval) {
            case constants.ok:
                // Override rejection
                object.loginfo('deny(soft?) overriden by deny hook' +
                                (deny_msg ? ': ' + deny_msg : ''));
                // Restore hooks_to_run with saved copy so that
                // any other plugins on this hook can also run.
                if (object.saved_hooks_to_run.length > 0) {
                    object.hooks_to_run = object.saved_hooks_to_run;
                    plugins.run_next_hook(hook, object, params);
                }
                else {
                    object[respond_method](constants.cont, deny_msg);
                }
                break;
            default:
                object.saved_hooks_to_run = [];
                object.hooks_to_run = [];
                object[respond_method](retval, msg);
        }
    };
}`
trace me to `HMailItem.prototype.deferred_respond = function (retval, msg, params)`, and on `switch`, it's return
 `            default:
                object.saved_hooks_to_run = [];
                object.hooks_to_run = [];
                object[respond_method](retval, msg);`
where we pass into our function only two arguments: `retval` and `msg`, but in `HMailItem.prototype.deferred_respond = function (retval, msg, params)`, we are trying declare variable from third parameter that `undefined`

**Comment by streamtOtO** [comment]
> next(DENYSOFT, { delay: 3600 });

and here seconds parameter must be string, you mention this in docs, and code with second parameter fine, [line 2153](https://github.com/haraka/Haraka/blob/master/outbound.js#L2153)
`    if (retval === constants.denysoft) {
        delay = parseInt(msg, 10) * 1000;
    }`

**Comment by streamtOtO** [comment]
If i change [line  558](https://github.com/haraka/Haraka/blob/master/plugins.js#L558) `default: object[respond_method](retval, msg);` to `default: object[respond_method](retval, msg, params);` error don't occur

**Comment by baudehlo** [comment]
Please submit that in a Pull Request.
