### ISSUE TITLE
Relaying to different SMTP server

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#1589]
### Haraka version  2.6.1

Hi 

I Have setup up  one haraka instance for receiving mails and for Outbound Delivery.
It is working great. I can able to connect on smtp and mails are delivering to inbox, almost on all known mail providers.

I want work with large volumes, say 50K per Hour.
1. Is one high configured 32 core, 64GB RAM, high iops server, 10Mbps line will be capable. ??
or
2. (I want to try this)Can we setup multiple haraka instance(small)  and configured as relay smtp server. 
I mean one Haraka instance for receiving mails and route it to all other (3-4) haraka instance equally. 

How can we do this. Where and how to configure? what is the syntax for adding host details.
I did not able to find good details related to syntax, so could not tried.

Can any one help/suggest  on this , I will try and check how if it works and can able process descent volumes.

**Comment by ajay-psd** [comment]
Please suggest, If any other good way/option in Haraka to handle large volumes receiving and processing.

**Comment by baudehlo** [comment]
The first server should be plenty.

But if you want to round-robin between multiple outbounds, just use HAProxy
for that.

**Comment by ajay-psd** [comment]
Thanks for the reply!
HAproxy sounds good for load balancing. I Will try this and see.

If I want to apply domain<mailfrom> based routing and route mails from multiple outbound relay server. Which ever Domain matches should goes from dedicated server else any should select and go from random one.  How can we configure this? 

Thanks!
