### ISSUE TITLE
CDR Logs in haraka

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#1590]
### Haraka version 2.1

Do we have any Haraka Plugin for loging email records  say authenticated username, client IP, subject, to_emailid,from_email_id, other CC/BCC details  and delivery status of email into a mysql database or txt file as a record entry.

Required for MIS purpose.

**Comment by msimerson** [comment]
Take a look at the elasticsearch logging plugin. It basically assembles all the message information into a Json doc and then sends that to elasticsearch. You could just as well save that JSON doc to disk or some other database (depending on your purposes, something like MongoDB or couchdb would likely be perfect.
