### ISSUE TITLE
Mailinglist server not available?

### ISSUE THREAD

**Issue by jahlives** [haraka/Haraka#1593]
I tried to register to the haraka mailinglist (haraka-sub@harakamail.com). My outbound mailserver says that bodger.sergeant.org is not available (connection timeout)  
`Sep 12 09:23:01 mail1 postfix/smtp[26152]: CF5FD63AC9: to=<haraka-sub@harakamail.com>, relay=none, delay=40, delays=9.5/0.06/30/0, dsn=4.4.1, status=deferred (connect to bodger.sergeant.org[91.196.104.90]:25: Connection timed out)`

I tried to connect from several other serves just to be sure that this is not a local problem on my side. But from all it's the same: no connection possible.

**Comment by baudehlo** [comment]
I've mailed the ISP to ask what's going on. Haven't heard back yet.

**Comment by jahlives** [comment]
`Sep 13 15:48:18 mail1 postfix/smtp[3391]: CF5FD63AC9: to=<haraka-sub@harakamail.com>, relay=bodger.sergeant.org[91.196.104.90]:25, delay=109557, delays=109554/0.03/2.1/1.3, dsn=2.0.0, status=sent (250 Mailing list mail sent (166EF5E1-F888-4AD3-90F2-6942A217C583.1)`
so since 15:48 (CEST) the mailinglist server seems to be wokring again :-)
