### ISSUE TITLE
How to insert Return-Path header

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#1597]
Hi 
How can we insert Return-Path header in haraka, By default it is taking as From header.

We need it for bounce management at one place.  Since we are sending mails in behalf of client mail-ids most of IDs are not exists,  so not able to track bounce.

**Comment by baudehlo** [comment]
Check out the Haraka verp plugin on npm. That's how you track bounces not via a header.

**Comment by ajay-psd** [comment]
Thanks, I will check that.

Also Is it possible to modify/Insert Return-Path header in haraka,  Like how Sendgrid and Mailchimp does.

**Comment by baudehlo** [comment]
The Return-Path header is a phantom. It doesn't really exist.

What you want to set is the MAIL FROM value, which is what the plugin I
suggested does.

**Comment by ajay-psd** [comment]
sorry , missed Return-Path: in previous post, below is sendgrid header

Delivered-To: ajay.psd@gmail.com
Received: by 10.31.0.7 with SMTP id 7csp207290vka;
        Tue, 13 Sep 2016 21:34:04 -0700 (PDT)
X-Received: by 10.157.9.39 with SMTP id 36mr410382otp.138.1473827643982;
        Tue, 13 Sep 2016 21:34:03 -0700 (PDT)
**Return-Path: bounces+1334878-91d1-ajay.psd=gmail.com@sendgrid.net**
Received: from o503145155.outbound-mail.sendgrid.net (o503145155.outbound-mail.sendgrid.net. [50.31.45.155])
by mx.google.com with ESMTPS id w22si1164712oif.142.2016.09.13.21.34.03
for ajay.psd@gmail.com
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Tue, 13 Sep 2016 21:34:03 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+1334878-91d1-ajay.psd=gmail.com@sendgrid.net designates 50.31.45.155 as permitted sender) client-ip=50.31.45.155;
Authentication-Results: mx.google.com;
dkim=pass header.i=@sendgrid.me;
spf=pass (google.com: domain of bounces+1334878-91d1-ajay.psd=gmail.com@sendgrid.net designates 50.31.45.155 as permitted sender) smtp.mailfrom=bounces+1334878-91d1-ajay.psd=gmailcom@sendgrid.net

**Comment by smfreegard** [comment]
The Return-Path header is added by the mailbox server receiving the message, not by an intermediate relay and represents the Envelope-From address (e.g. the SMTP MAIL FROM: address) which like @baudehlo said, is what you need to modify (as the verp plugin does)).

See https://tools.ietf.org/html/rfc5321#section-4.4

**Comment by ajay-psd** [comment]
@baudehlo and @smfreegard , Thank you so much for your help and clarifying doubts on smtp subject. Its really helpful.

Also I have used verp plugin, Its seems working great. Thanks!
