### ISSUE TITLE
Send Email With Plain IP Address

### ISSUE THREAD

**Issue by cloverboxfox** [haraka/Haraka#1601]
### Haraka version
2.8.7
### Expected behavior
Sending an email with the from field set to an  IP address should not fail MX lookup . 
### Observed behavior
The email is rejected for failing a MX recored lookup 
### Steps to reproduce
Send an email from something like test@44.444.444

**Comment by baudehlo** [comment]
I don't even think that's valid for an email address. We aren't likely to support it natively - write a get_mx hook if you need that behaviour.

**Comment by smfreegard** [comment]
It isn't valid.  IP addresses have to be in IP-Literal format.  e.g. [1.2.3.4]
