### ISSUE TITLE
Haraka imap feature

### ISSUE THREAD

**Issue by webexplorering** [haraka/Haraka#1605]
Hi guys!

It has been almost 1.5 years since TODO was edited.

@baudehlo developed Boosto (https://github.com/baudehlo/Boosto) which has same architure as Haraka.

Is there any plans  to add imap feature to Haraka soon?

Thanks.

**Comment by ssimpo** [comment]
This really is a *must have* feature (I mean must have in the sense that it should be in Haraka or their should be an imap/pop server in the Haraka ecosystem).

We are currently reviewing our architecture and a move to Haraka would be ideal. This would allow us to further consolidate around JavaScript for Dev work. The only fly in the ointment is that we need to find an equally solid imap solution to fully replace our postfix server.

**Comment by baudehlo** [comment]
That doesn't make sense. Postfix isn't an IMAP server either.

The reason I stopped working on it is because having a flexible IMAP server made no sense - it's just a dumb store. Dovecot does everything you need and more.

**Comment by ssimpo** [comment]
@baudehlo Yes, I know :-)

In my defense it was the middle of the night here in the UK, being woken early by the baby.  I actually read it an hour or so later and thought, "well postfix is not an Imap server, we use Dovecot for that".  This is why I deleted my comment at that time.  I guess not soon enough for you not to be notified and respond.

I suppose a better way of putting it would have been, "We would like to move over to node for Imap, Pop3 and SMTP from our current solution of Postfix/Dovecot".  I am not sure my comment about it being a 'must have' was 100% valid either, I just mean that it would be a great offer to have all using the same technology.

**Comment by msimerson** [comment]
I think it's safe to say we won't ever had IMAP server to Haraka. It's out of scope for the project. If you like Boosto, head over there and post issues and see how much support or interest you can find.
