### ISSUE TITLE
set connection.remote.is_private_ip property

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1631]
This function is used in at least 12 plugins. If it were set automatically in connection.js, it would:

* reduce the number of times is_private_ip() is called
* relieve some plugins from having to load net_utils
* make it easier to repackage plugins as npm modules

**Comment by smfreegard** [comment]
Yeah; this is a good idea.   We still need to keep the function in net_utils though.

**Comment by msimerson** [comment]
> We still need to keep the function in net_utils though.

Right, but only connection.js needs to load net_utils. Plugins that just want to know if the remote is a private IP don't. :-)

**Comment by smfreegard** [comment]
Yeah - I get that.  I just wanted to be clear that you weren't going to remove it from net_utils as there's plenty of times that you might want to call the function on something that isn't the connected IP.

**Comment by msimerson** [comment]
Yes, if I do anything with net_utils it'll be moving it to `haraka-net_utils`, so that npm packaged plugins can load it.  Avoiding that is part of my impetus to set the connection.remote.is_private_ip property. :-)
