### ISSUE TITLE
honorCipherOrder is false by default

### ISSUE THREAD

**Issue by typingArtist** [haraka/Haraka#1666]
As discussed in #1662 the new `honorCipherOrder` option of the tls plugin defaults to `false`. In fact, without configuring this parameter to `true`, server setups are considered insecure today. So the question is whether Haraka’s default setup should set `honorCipherOrder` to `true`, making it the proper secure default, or `false` as it was in the past and as it is with mostly any other TLS server (apache, nginx, etc.).

Note that in general it wouldn’t be a problem for well-configured clients to dictate the cipher preference. However, most clients and client libraries cannot be configured for a manual cipher order, and quite some of the older clients have some weird ordering. For example, [Android 4.4.2](https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2&key=62) orders weak non-PFS ciphers like `TLS_RSA_WITH_3DES_EDE_CBC_SHA` ahead of PFS-ensured state-of-the-art ciphers like `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`. For making use of the better ciphers even on these systems, admins _do_ have to enforce the order and let the server pick the best supported client’s cipher on its own.

Note, however, that modern browsers and clients do have significantly improved on their cipher list and order. The list was drastically shortened, and the order has been changed from speed/power optimized to strict security quality. Such hardened clients don’t actually benefit from `honorCipherOrder=true` because the server cannot actually present any better order, just worse.

So the question is: Should we make `honorCipherOrder` default `true` for a more secure SMTP world? Then perhaps we should also default the `ciphers` string?

Note that a secure connection will be established independent from the actual setting of `honorCipherOrder`. However, if the server admin has put a strict order on the `ciphers` setting based on security, the best cipher can be picked. If we make this setting default to `true` and let admins configure arbitrary ordered `ciphers`, an up-to-date client could be downgraded to a worse encryption than the best supported from both client and server. Take, for example, the web page of ryanair.com which, [according to SSL Lab’s analysis](https://www.ssllabs.com/ssltest/analyze.html?d=www.ryanair.com&latest) from today, was configured to enforce the cipher order with a weak 3DES cipher ahead of better AES256 and AES128 ciphers.

**Comment by msimerson** [comment]
> the question is: Should we make honorCipherOrder default true for a more secure SMTP world? 

My vote: yes.

> also default the ciphers string

I tend to think not here. This is a moving target, and setting this implies that we're going to always keep it up-to-date. If we don't set it, then it's updated for us with each openssl release. Right?

**Comment by typingArtist** [comment]
Well, actually the defaults are chosen for us by the Node programmers *and* the openssl group. From the [docs](https://nodejs.org/api/tls.html#tls_modifying_the_default_tls_cipher_suite):

> Node.js is built with a default suite of enabled and disabled TLS ciphers. Currently, the default cipher suite is:
```
ECDHE-RSA-AES128-GCM-SHA256:
ECDHE-ECDSA-AES128-GCM-SHA256:
ECDHE-RSA-AES256-GCM-SHA384:
ECDHE-ECDSA-AES256-GCM-SHA384:
DHE-RSA-AES128-GCM-SHA256:
ECDHE-RSA-AES128-SHA256:
DHE-RSA-AES128-SHA256:
ECDHE-RSA-AES256-SHA384:
DHE-RSA-AES256-SHA384:
ECDHE-RSA-AES256-SHA256:
DHE-RSA-AES256-SHA256:
HIGH:
!aNULL:
!eNULL:
!EXPORT:
!DES:
!RC4:
!MD5:
!PSK:
!SRP:
!CAMELLIA
```
>

Here, `HIGH` is a quite stupidly collected list of good and seriously bad ciphers, created by the openssl team, which has to be sieved right away to become secure again. `openssl-1.1 ciphers -V HIGH | wc -l` still returns 115 (!) ciphers of which only about 10 can be considered for use in modern setups (5 for RSA, 5 for ECDSA keys), and perhaps 10 more for those systems with required backward compatibility. It’s hard to understand why the openssl team still doesn’t offer a serious default meta list which only contains these good up-to-date ciphers, e.g. the Mozilla Modern lists of modern or intermediate ciphers.

But you are probably right. If we give defaults here, we’re just the third in the chain, and our defaults will become outdated over time. At least the node TLS list filters away the most insecure `HIGH` ciphers, however, the order is wrong, so a responsible admin still has to set a proper cipher list manually.

Perhaps we could also give a sensible default `tls.ini` file?

**Comment by msimerson** [comment]
> Perhaps we could also give a sensible default tls.ini file?

I'd be okay with this **if** there's a mechanism in place to periodically review and update it. Such as, during the [release process](https://github.com/haraka/Haraka/wiki/Release%20Process). Perhaps provide a shell command or script that can be run that automatically updates the tls.ini file.

Another idea: generate a "security review" script that evaluates your "effective settings" (a combination of defaults from tls.ini + any overrides in the local config/tls.ini) and makes suggestions. If it's well thought out and robust, it could be run as part of the install even.

> "YOU SURE LIKE TO LIVE DANGEROUSLY! You really should disable `blahSetting` in $path/config/tls.ini"

**Comment by typingArtist** [comment]
Hi Matt, after a longer review of the Node TLS API I wanted to clarify: `tls.server()` actually *does* have `honorCipherOrder` set default to `true` but `createSecureContext()` defaults to `false`. So for the Node developers, the answer is given: The flag has to be set to `false` manually to revert to the old behavior.

**Comment by msimerson** [comment]
> > Should we make honorCipherOrder default true for a more secure SMTP world?
> My vote: yes.

I still vote yes.

**Comment by Dexus** [comment]
I vote also for yes.

**Comment by typingArtist** [comment]
My vote on yes as well. It’s safer, it’s Node’s default.

**Comment by typingArtist** [comment]
@msimerson, I think we won’t get more votes for (the current) setting to `false` anytime soon, so I’d suggest to go with `true` as a default. Do you want to have two pull requests, one for the Haraka repository, the other for haraka-net-utils?

**Comment by typingArtist** [comment]
btw, if security is a prime concern to us, along `honorCipherOrder=true` shouldn’t we set `rejectUnauthorized=true`, `disable_for_failed_hosts=false`, and –once available– `requireSTARTTLS=true`, `enableOCSP=true` and `checkOCSP=true`, per default? At the moment, an attacker (MITM) can

- filter the offered STARTTLS from the server’s EHLO response (similar to the future `requireSTARTTLS=false`)
- disrupt our STARTTLS session setup so the outbound will re-try without STARTTLS next time (`disable_for_failed_hosts=true`)
- send an invalid certificate, and we’ll happily accept it (`rejectUnauthorized=false`) and won’t check its running revocation status (future `enableOCSP=false` and `checkOCSP=false`).

All three bullets affect both inbound and outbound, and we should offer settings which allow the admin to specify the exact behavior. The options should allow to be set in general and specifically towards hosts and domains. This allows weakening security for known bad hosts as well as strengthening for well-setup peers.

**Comment by smfreegard** [comment]
SMTP is a totally different animal to HTTPS.

Whilst I agree this needs to be configurable the defaults need to be as they are now otherwise you'll find that you can't communicate with a large proportion of the internet as they either use weak encryption or self-signed certificates.

Try your proposed changes on a production mail flow and you'll quickly find this out.

The best thing to do here is document all of the possible settings and the pro's and con's of each.

IMO - the largest issue facing e-mail encryption at the moment is the lack of notifications in the MUAs as to whether TLS was used and at what quality.  e.g. the equivalent of the HTTPS "green bar" in the browser etc.

I suggested recently to someone that the ARC (Authenticated Received Chain) could be used to encode TLS details in comments in the Received header so that an MUA could verify TLS status on each hop so it can tell if the message was encrypted across all hops and of what quality the encryption was etc.

**Comment by msimerson** [comment]
>  shouldn’t we set rejectUnauthorized=true, disable_for_failed_hosts=false, and –once available– requireSTARTTLS=true, enableOCSP=true and checkOCSP=true, per default?

Not at all. There are still many many SMTP servers using self-signed TLS certs and it would be impractical to disallow the receipt and sending of emails to them simply because their cert is self-signed. Maybe in a few years when everyMTA[TM] has built-in support for Let's Encrypt or the equivalent...

**Comment by typingArtist** [comment]
The idea was just to make the default as secure as possible. The process of weakening it for compatibility with the current imperfect internet reality should be a conscious step done not by us but by the admins who use the tool.

Some defaults most probably should differ between client and server, for example `rejectUnauthorized`: a client should always expect a proper certificate by the server these days, but a server should not require the client to offer a valid certificate.

**Comment by msimerson** [comment]
> a client should always expect a proper certificate by the server these days

I'd encourage you to perform a SMTP survey of the TLS certificates of MTAs and validate that your expectations match reality.
