### ISSUE TITLE
new TLS options are not available to SMTPS servers (port 465)

### ISSUE THREAD

**Issue by typingArtist** [haraka/Haraka#1667]
My recent additions to the TLS setup options are only valid for SMTP server setups with STARTTLS. They are completely unavailable for servers running on port 465 as `server.js` does its independent and specialized TLS setup for these sessions.

**Comment by msimerson** [comment]
I honestly would not worry about port 465 at all. It's off by default, it's a long deprecated standard, and it exists only for backwards compatibility with very old (circa 1999) MUAs.

**Comment by typingArtist** [comment]
Thanks for the clarification.

Okay, just found that when browsing the code. Do we want to fix the documentation, at least?

**Comment by msimerson** [comment]
> Do we want to fix the documentation, at least?

Always. :)

**Comment by msimerson** [comment]
Closing. If anything is done regarding this, just do it in a PR and reference this.
