### ISSUE TITLE
smtp_forward incorrect behaviour with multiple rcpts

### ISSUE THREAD

**Issue by LiranLast** [haraka/Haraka#1679]
### system info

Haraka 2.8.9.

### Expected behavior

When relaying an incoming message for two users on the same domain smtp_forward should send it as describe in smtp_forward.ini.

### Observed behavior

When receiving the message smtp_forward.get_config transform the first domain into the forwarded domain (in my case mail.company.com instead of company.com) and when matching with the second user it returns false (smtp_forward.js:48).

This leads to using the default target server (in my case- there's none).

### Fix

changing the line (smtp_forward.js:48) to be:

if (connection.transaction.rcpt_to[i].host !== dom) {

instead of

if (connection.transaction.rcpt_to[i].host !== dst_host) {

Works well for me

**Comment by msimerson** [comment]
Thanks for the report. This has been fixed and will be included in Haraka 2.8.10
