### ISSUE TITLE
Server support for SNI

### ISSUE THREAD

**Issue by typingArtist** [haraka/Haraka#1686]
Subject says it all. Quite some clients do already support SNI these days but only a very small number of SMTP servers support it. E.g. neither sendmail nor postfix support SNI on the server side. Let’s Haraka support it.

**Comment by smfreegard** [comment]
This thread on postfix-users pretty much sums this up: http://postfix.1071664.n5.nabble.com/TLS-SNI-support-td25552.html

**Comment by msimerson** [comment]
> This thread on postfix-users

That thread is from 2012. My first reaction was similar to Steve's. But upon looking into it, I've read that the most common (except notably: Outlook) MUAs have already added SNI support (Android, iOS, Mac OS), as has Dovecot. That's more than enough reason for me to support adding it to Haraka.

**Comment by baudehlo** [comment]
But what does it do? Pick a different cert?

**Comment by msimerson** [comment]
> But what does it do? Pick a different cert?

Yes, exactly. Same as with HTTP and SNI. During the TLS negotiation, the client specifies the hostname they're looking for and if the server supports SNI, it returns the correct TLS certificate.

**Comment by baudehlo** [comment]
How is SNI relevant to Haraka? It's needed for HTTPS because you have
virtual hosts with different configuration. Currently Haraka only has one
configuration per server.

**Comment by msimerson** [comment]
> Currently Haraka only has one configuration per server.

One of the recent feature adds for TLS is the ability to load multiple tls certs and keys.

**Comment by darkpixel** [comment]
I think he wants to be able to have users connect to 'mail.example.tld' and get the 'mail.example.tld' cert in the mail client (like Thunderbird).  But other users are connecting to the same server via 'smtp.example.tld' or 'mail.someotherdomain.tld' and they each have their own certs.

**Comment by typingArtist** [comment]
> One of the recent feature adds for TLS is the ability to load multiple tls certs and keys.

Well, that change can be used only  for a single server, the non-SNI server, for using two kinds of keys (RSA and ECDSA these days). SNI requires more changes, that’s why I actually created this issue.

SNI not only allows a server to have multiple identities from the certificate standpoint, it also allows it to be configured differently depending on the requested hostname. E.g., if addressed as msa.example.com, it could allow AUTH, but if addressed as mx01.example.com, it could refuse AUTH at all. Just as the user database could be specified depending on the actual domain so you don’t need to compose user#his.example.com and user#her.example.com. Of course, other options are selecting different TLS levels and Ciphers per identity.

Haraka has quite some walk ahead for making all of that a reality, but the recent changes to the TLS stack are the entry point to allowing the modern SNI callbacks on the server. Once SNI is working, we can add more and more features which depend on this split identity.

**Comment by celesteking** [comment]
I'd also like to have a knob that would disable SNI when in client mode (smtp_client.js?), mainly for privacy reasons.

**Comment by typingArtist** [comment]
@celesteking, do you regularly disable SNI in your browser? Have you also considered that your MUA and MTA will trigger DNS lookups of your target domain as well as for the MX hosts, which can also be captured and tracked?

That said, yes, there will be an option to disable SNI. However, just like with web servers, SNI might also come to a MTA near you, and it’ll be up to you how many NDNs you let pass until you enable SNI again.

**Comment by typingArtist** [comment]
First configuration option is to allow SNI to be enabled/disabled, separately for server and client functionality. For change to configuration parser, see haraka/haraka-net-utils#6.

**Comment by msimerson** [comment]
I just enabled SNI on dovecot. I'm ready for Haraka to support SNI.

**Comment by typingArtist** [comment]
SNI is already done for ages, I’m again struggling with better testing. We should have different certificates to serve in the tests, and this alone requires a more thorough TLS setup. I’m thinking about another patch for allowing the user – and the tester – to specify a different (set of) root-CAs to trust.

**Comment by baudehlo** [comment]
You can do this easily with Travis. Just copy some files to the OpenSSL root cert dir.

**Comment by msimerson** [comment]
> SNI is already done for ages, I’m again struggling with better testing.

By done you mean, "in a branch somewhere?"  I just tried, for fun, to add a second certificate to my Haraka with this syntax:

```ini
key[]=tls_key.pem
cert[]=tls_cert.pem
; key[]=/data/etc/ssl/private/mail.2nd-domain.com.pem 
; cert[]=/data/etc/ssl/certs/mail.2nd-domain.com.pem 
```

And it didn't work out too well:

````
[CRIT] [-] [core] Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
[CRIT] [-] [core]     at Object.createSecureContext (_tls_common.js:82:19)
[CRIT] [-] [core]     at new Server (_tls_wrap.js:769:25)
[CRIT] [-] [core]     at Object.exports.createServer (_tls_wrap.js:862:10)
[CRIT] [-] [core]     at Object.Server.get_smtp_server (/usr/local/lib/node_modules/Haraka/server.js:336:29)
[CRIT] [-] [core]     at setupListener (/usr/local/lib/node_modules/Haraka/server.js:364:29)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:3025:16
[CRIT] [-] [core]     at eachOfArrayLike (/usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:941:9)
[CRIT] [-] [core]     at eachOf (/usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:991:5)
[CRIT] [-] [core]     at Object.eachLimit (/usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:3089:3)
[CRIT] [-] [core]     at Object.Server.setup_smtp_listeners (/usr/local/lib/node_modules/Haraka/server.js:397:11)
[NOTICE] [-] [core] Shutting down
````

**Comment by msimerson** [comment]
````
haraka[57589]: [ERROR] [-] [core] SNICallback servername: mail.theartfarm.com
haraka[57589]: [ERROR] [-] [core] SNICallback servername: mail.theartfarm.com
haraka[57589]: [ERROR] [-] [core] SNICallback servername: mail.theartfarm.com
````

Well well, there **are** SMTP clients out there sending SNI servername. 😮
