### ISSUE TITLE
SMTP Client (outbound) should allow OCSP Checking

### ISSUE THREAD

**Issue by typingArtist** [haraka/Haraka#1687]
The outbound module currently doesn’t take OCSP into account, neither in its standard form, nor as stapled OCSP responses.

Besides not taking care of OCSP at all, Haraka should support multiple levels of support: requesting and honoring stapled OCSP, or additionally checking OCSP directly at the official servers if we don’t get a stapled response.

**Comment by celesteking** [comment]
I'm against non-stapled ocsp, it exposes hostname you're connecting to.

**Comment by typingArtist** [comment]
First: Non-stapled OCSP checking is still better than being exposed to a compromised key. But in general I agree that OCSP Stapling should really go into a mandatory feature of any TLS service, for this and other reasons.

Remember, a well-developed client will cache the OCSP response –either stapled or fetched by the client– for as long as the stapling is valid, so no further ‘information leakage’ happens for the remaining length of the validity. Furthermore, the only information is that some IP address has fetched the OCSP status for a specific TLS certificate, nothing more. So if the certificate contains multiple host names, the OCSP responder cannot deduce which of the services has been addressed, only the serial number of the certificate counts.

Please also consider that AFAIK there is still no standard for client certificate OCSP stapling. As any client certificate can already contain an OCSP link, you can imagine that now the OCSP responder will be able to track specific *users* towards the service they connect to. This is even more severe, from a privacy standpoint, than non-stapled OCSP checking for a server certificate. However, most users authenticate with a password instead of a certificate, so they are not affected by this missing feature.

Haraka’s client OCSP support will have to allow multiple levels of certificate validation thoroughness. The current state is that the validity of an offered server certificate –except the optional and default-off certificate chain checks– is not checked at all, and that isn’t good. And still many admins offer SMTP+STARTTLS with an invalid certificate, be it outdated or self-signed. Haraka’s certificate checking support will have to allow the admin to specify what to do in such a situation and how picky it shall be about these checks, e.g. whether an OCSP lookup should be performed.

**Comment by celesteking** [comment]
https://www.imperialviolet.org/2012/02/05/crlsets.html on why ocsp/crl checks were removed from chome.

**Comment by msimerson** [comment]
It's been nearly a year. I'm closing this issue as stalled. This is not a feature we have interest in implementing. PRs are welcome.
