### ISSUE TITLE
Beautify NDNs

### ISSUE THREAD

**Issue by typingArtist** [haraka/Haraka#1688]
NDNs currently don’t contain a proper header, at least in the tests I have run (messages bounced because of `rejectUnauthorized`), it’s missing `From`, `To`, and `Subject`.

**Comment by Bramzor** [comment]
Proper header is indeed missing, source of mail:
`
Return-Path: <unknown>
Delivered-To: unknown
To: <>
Delivered-To: <>
`

With setting the file config/outbound.bounce_message to something useful, it already helps a bit to create a nicer looking bounce message. Creating a separate issue for adding a HTML part and the mail as attachment, as it seems the bounce itself is already multipart/report as content type.

**Comment by msimerson** [comment]
@Bramzor HTML additions were merged in #2091.

**Comment by msimerson** [comment]
Is there anything left to do here? The From, To, and Subject headers are being added, unless @typingArtist had a stale or missing `config/bounce_message`.

**Comment by baudehlo** [comment]
The To is wrong. Return Path is right.

**Comment by msimerson** [comment]
Closing as finished in #2091
