### ISSUE TITLE
Shutdown of Outbound process in case of large amount of bad emails

### ISSUE THREAD

**Issue by Fred2MTL** [haraka/Haraka#1699]
### system info

Node | v7.0.0
OS | Linux vps70819.vps.ovh.ca 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior

There is two Haraka processes, one dedicated to Inboud, on dedicated to Outbound. This process send emails to the effective MX receivers, according to demand, then immediately when all is fine, then delayed otherwise (included rejected mechanism). The 'to-be-sent' emails are stored into the queue directory, independently of their respective status.

### Observed behavior

The outbound process produces the following error when more than 40/50 emails couldn't be immediately delivered, driving to the accumulation of corresponding files into the queue directory. The deletion of these files allows the restart of the the outbound process.

[CRIT] [-] [core] RangeError: Maximum call stack size exceeded
[CRIT] [-] [core]     at Date.[Symbol.toPrimitive] (<anonymous>)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/outbound.js:349:34
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:1069:13
[CRIT] [-] [core]     at replenish (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:884:21)
[CRIT] [-] [core]     at iterateeCallback (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:869:21)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:847:20
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:1071:17
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/outbound.js:357:17
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:1069:13
[CRIT] [-] [core]     at replenish (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:884:21)

### Steps to reproduce

1 - Send a large amount of bad email (ie. impossible to be delivered)
2 - Check the accumulation into the queue directory
3 - Check the logs

**Comment by baudehlo** [comment]
Fixed by #1930
