### ISSUE TITLE
missing dkim private key

### ISSUE THREAD

**Issue by devlo** [haraka/Haraka#1705]
### system info

Haraka  2.8.10
Node 6.9.1
OS Debian jessie (3.16.0-4)
Openssl 1.0.1t 3 may 2016
### Expected behavior
Sign DKIM
### Observed behavior
Error: skipped: missing dkim private key
### Steps to reproduce
install haraka, leave only headers_to_sign inside dkim_sign.ini becuase this is multi domain setup. 
generate dkim in standard way using shell script provided by Haraka. Try to send mail.

I have upgraded to version 2.8.10 today. It works fine on version ~2.5.

**Comment by devlo** [comment]
I have found bug responsible for this. This  bug was introduced on 3rd October, do you test your changes?
Because dkim signing doesn't work properly from this commit to everyone. You are using async version of fs.exists instead of fs.existsSync. Fixed in my commit.

**Comment by baudehlo** [comment]
Yes we run tests but tests are imperfect. 

If you wanted them to be better you could have included additional tests in your patch.

**Comment by devlo** [comment]
@baudehlo 

> Yes we run tests but tests are imperfect.

Seeing what kind of trivial bug was laying here for over a month that made DKIM unusable makes me think about quality of the whole project, especially in context of security. 

Sometimes the best test is just to send e-mail message and check the headers, it would catch problems with dkim signing. Or make automatic isolated test for it. Even if you would do that manually once a week, then this problem would be solved 3 weeks ago.

> If you wanted them to be better you could have included additional tests in your patch.

Good that you are grateful that i fixed your bug...
