### ISSUE TITLE
require node.js 4

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1712]
I think it's time for us to drop Node 0.12 support:

For:
- [all the shiny features](http://node.green)
- generic-pool 3 [requires it](https://github.com/coopernurse/node-pool/blob/master/CHANGELOG.md)
- Many (most?) OS distros are bundling Node 4 now
- anyone that upgrades to newest Haraka will likely be updating node.js as well
- node 0.12 [maintenance ends](https://github.com/nodejs/LTS#lts-schedule) on 2016-12-31

Against:
- ?

**Comment by celesteking** [comment]
Having node EOL is enough to force users upgrading.
