### ISSUE TITLE
Remove Attachment from mail

### ISSUE THREAD

**Issue by kostik81** [haraka/Haraka#1722]
Hi,
I use Haraka as SMTP proxy
I want to remove attachments for some mails, Is it possible ?
If yes, please guide me.
(I can add banner to the mail body, but can't find any method to remove attachment)

**Comment by Dexus** [comment]
No it is not possible yet.

Regards

Von meinem iPhone gesendet

**Comment by baudehlo** [comment]
Well it's sort of possible - but you have to construct a new mail and
discard the current one. It's hard to do, that's all.
