### ISSUE TITLE
Create a fully-fledged end-to-end test with live servers and clients

### ISSUE THREAD

**Issue by typingArtist** [haraka/Haraka#1725]
While I like the idea of modular testing, it’s not really representative for the functioning of larger features. For example, a proper test for TLS would require a client capable of requesting STARTTLS and checking the returned certificate, as well as a server that can verify that Haraka as a client can tell good from bad certificates. The current tests for TLS are limited to checking the configuration file format. There are other core parts of the internal functionality which get no test coverage, and I think that it’s time to raise the rather low level of coverage we have right now (below 35%). We already had some bad code from myself on master which didn’t even pass the first connection which wouldn’t have been merged if we had already tests in place that cover actual full client-server interactivity.  

Exporting the internal functions and callbacks for testing is nice and generally a good thing, but it renders quite impractical for complex protocols like STARTTLS.

It should not be a big deal to start listening servers in the travis-ci build slaves, but I have no clue how to setup and utilize them from the current test framework. I am in no way a node.js expert, so help and suggestions are greatly appreciated.

@msimerson already gave some advise in #1682, specifically [here in the second option](https://github.com/haraka/Haraka/pull/1682#issuecomment-255853860), but without a template this   is currently out of reach for me.

**Comment by msimerson** [comment]
We've been meaning to take a crack at adding integration tests, it just hasn't quite happened yet. I'd go about structuring the tests in much the same way I've tested HTTP apps using express and [supertest](https://www.npmjs.com/package/supertest): start up the server, and in the server_is_running callback, run the tests. There is a [smtp-supertest](https://www.npmjs.com/package/smtp-supertest) but it doesn't look too promising. I'd plan to improvise with `assert` and maybe [smtp-connection](https://www.npmjs.com/package/smtp-connection) or [smtp-client](https://www.npmjs.com/package/smtp-client). Pseudocode:

```js
server.startUp(function (err, result) {
    if (err) return err;
    run_test_one(....);
    run_test_two(....);
});
```

I've also considered using node's process manager to fork a process and drive the connection with [swaks](http://www.jetmore.org/john/code/swaks/). One of the most compelling arguments for doing that is that it uses a completely non-node.js based SMTP client.

**Comment by msimerson** [comment]
Okay @typingArtist , I have created a PR that includes an end-to-end test. It spins up a Haraka server instance and then sends an email to it via nodemailer.  You could add additional tests instead using [child_process](https://nodejs.org/api/child_process.html) and driving swaks or for TLS testing, even openssl.

**Comment by typingArtist** [comment]
Thanks @msimerson, that should be the foundation for integration testing. From my investigations, though, it appears that swaks has no support for SNI or OCSP/stapling, and I’m not sure how to enforce server certificate checking. But let’s see. I should have time again in the next weeks for more work.

**Comment by msimerson** [comment]
SWAKS would just be an integration test (like nodemailer). For the TLS validation (SNI, cert validation, etc) I expect you'd need to instead drive openssl:

````
openssl s_client -connect mail.theartfarm.com:587 -starttls smtp
openssl s_client -connect mail.theartfarm.com:587 -starttls smtp -servername snihost.example.com
````

OTOH, nodemailer and its `tls` options block might suffice. You'll notice I had to disable unauthorized certificate rejection in my test to permit a self-signed cert:

````
        var transporter = nodemailer.createTransport({
            host: 'localhost',
            port: 2500,
            tls: {
                // do not fail on invalid certs
                rejectUnauthorized: false
            }
        });
````
