### ISSUE TITLE
dkim private key not found

### ISSUE THREAD

**Issue by toastedmail** [haraka/Haraka#1735]
Haraka | Haraka.js â Version: 2.8.10
 --- | :---
Node | v6.9.1
OS | FreeBSD haraka 10.3-RELEASE-p11 FreeBSD 10.3-RELEASE-p11 #0: Mon Oct 24 18:49:24 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
openssl | OpenSSL 1.0.1s-freebsd  1 Mar 2016

While changes clearly show:

    **Bug Fixes**
    `dkim_sign: per-domain key finding fixed #1707`

Nov 27 19:36:44 haraka haraka[2660]: [ERROR] [0B9201A3-B533-4232-8527-D531193D51DF.1] [dkim_sign] skipped: missing dkim private key

Nov 27 19:36:44 haraka haraka[2660]: [ERROR] [-] [dkim_sign] skipped: missing dkim private key

DKIM key is definitely present:

root@smtpd:/data/haraka/config/dkim/barontel.com # ls
dns             private         public          selector

The private file is root 400 or r--------
Tried changing it to 444 or r--r--r-- did not help.
Haraka cannot find it.

**Comment by msimerson** [comment]
Pay better attention to the Changelog. You aren't running the fixed version.
