### ISSUE TITLE
Haraka not sending mails

### ISSUE THREAD

**Issue by hugh01sm** [haraka/Haraka#1736]
Hi

We are trying to get Haraka to send emails from a Windows box without any sucess.  

We are using VS2015 as the development environment using Node.js tools 1.2.40726.00
The application runs fine except that we have been unable to install iconv.
I attach the plugins.ini file and also a log file. 
While it appears all is well the email never seems to get sent.

[haraka.txt](https://github.com/haraka/Haraka/files/636115/haraka.txt)
[plugins.txt](https://github.com/haraka/Haraka/files/636119/plugins.txt)

We would be most grateful for any help you may be able to provide.

Thanks

**Comment by Dexus** [comment]
How do you try to send emails?

You need to configure haraka to listen on port 25 and 578. Your can't send mails via 25 from clients.

And we missing some support infos. Like OS, node Version and openssl version.

Btw. we do not official support windows as OS.

Von meinem iPhone gesendet

**Comment by smfreegard** [comment]
> [core] disconnect ip=127.0.0.1 rdns="localhost" helo="ESC5" relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=257 lr="451  (91E3F5E4-DDF1-40DA-B5B1-4B2C480F0411.1)" time=0.46

The problem here is this:  **relay=N** unlike other MTAs, Haraka does not implicitly allow localhost to relay, so you need to use a relay plugin to allow it to send mail.

> S: 451  (91E3F5E4-DDF1-40DA-B5B1-4B2C480F0411.1)

You do appear to have found a small bug here too.  The returned message is blank for some reason.  I will investigate this and fix it for the next version.

**Comment by smfreegard** [comment]
> you need to use a relay plugin to allow it to send mail

Actually - I should have said - OR you need to use SMTP AUTH to individually allow relaying from specific services running on localhost, which is more secure than allowing it to relay without authentication.

**Comment by hugh01sm** [comment]
Hi 

Thanks for the quick response.
Just reviewed the plugins.ini and relay was enabled. 
# CONNECT
#toobusy
relay
# control which IPs, rDNS hostnames, HELO hostnames, MAIL FROM addresses, and
# RCPT TO address you accept mail from. See 'haraka -h access'.
access
# connect.p0f
# geoip
# asn
# connect.fcrdns
# block mails from known bad hosts (see config/dnsbl.zones for the DNS zones queried)
dnsbl

Will lock it down with SMTP AUTH when we can actually send a mail.

**Comment by smfreegard** [comment]
The relay plugin might be loaded, but it needs to be configured accordingly as per the docs to allow 127.0.0.1 relay permissions...

**Comment by hugh01sm** [comment]
to do any of the configuration of relay plug we need a relay.ini file.  No such file exists in the current distribution as far as I can see.
Pls provide an example.
Thanks

**Comment by smfreegard** [comment]
How about you read the docs and create the necessary files yourself from the examples already provided there... https://github.com/haraka/Haraka/blob/master/docs/plugins/relay.md

**Comment by msimerson** [comment]
You can also read the docs for the relay plugin with `haraka -h relay`

**Comment by hugh01sm** [comment]
Thanks for your help with this and sorry for the delay in getting back to you.

We have now implemented relay all and we are sending emails njow.  However there still seem to be some configuration issues as gmail rejects the email with the following error:

**[PROTOCOL] [7F232766-3277-45A0-B58D-A7E249745979.1.1] [outbound] S: 501-5.5.4 Empty HELO/EHLO argument not allowed, closing connection.\r\n
[PROTOCOL] [7F232766-3277-45A0-B58D-A7E249745979.1.1] [outbound] S: 501 5.5.4  https://support.google.com/mail/?p=helo q69si10897045ybq.206 - gsmtp\r\n**

We have checked google support and it is saying that we need to send a fully qualified domain name in HELO.  We have not found a way of configuring this.

I attach a complete log.  Hopefully you can point us as what we need to change.

Thanks

[2016-12-14 - gmail.txt](https://github.com/haraka/Haraka/files/653929/2016-12-14.-.gmail.txt)

**Comment by msimerson** [comment]
Create a file named `me` in the config directory. The contents of the file should be a single line with the FQDN / hostname of your server.

**Comment by hugh01sm** [comment]
Thanks very much.
Working with gmail now.

**Comment by hugh01sm** [comment]
Ok
have now moved Haraka to our server and getting the following error.

[PROTOCOL] [0E46A2D4-4184-4A61-B56A-D2020816A381] [core] S: 550 Host names have more than one DNS label

full log 
[2016-12-15.txt](https://github.com/haraka/Haraka/files/654161/2016-12-15.txt)
file attached.
