### ISSUE TITLE
special emails in host_list & etc

### ISSUE THREAD

**Issue by celesteking** [haraka/Haraka#1737]
When special `Address()` is encountered (`<postmaster>`), stuff breaks. See [here](https://github.com/haraka/Haraka/commit/3a3d6893195d93d554fde5d42c18aba649ae0e3d) for discussion.

> IMO, the needful is to go upstream to our address parser and make sure that when host is set, it's always lowered (IE, an RFC 1035 hostname). Then example all of Haraka's code looking at host.toLowerCase() and remove the applicable .toLowerCase() calls.

```js
 $ grep host.toLower `gfind`
./plugins/connect.rdns_access.js:        if (_in_whitelist(connection, plugin, connection.remote.host.toLowerCase())) {
./plugins/connect.rdns_access.js:            return next(DENYDISCONNECT, connection.remote.host.toLowerCase() +
./plugins/connect.rdns_access.js:        if (_in_blacklist(connection, plugin, connection.remote.host.toLowerCase())) {
./plugins/connect.rdns_access.js:            return next(DENYDISCONNECT, connection.remote.host.toLowerCase() +
./plugins/data.uribl.js:    host = host.toLowerCase().split('.').reverse();
./plugins/dkim_sign.js:    try { domain = txn.mail_from.host && txn.mail_from.host.toLowerCase(); }
./plugins/rate_limit.js:        var rdns_array = remote_host.toLowerCase().split('.');
./plugins/rate_limit.js:        var rhs_split = mail.host.toLowerCase().split('.');
./plugins/rcpt_to.host_list_base.js:    var domain = params[0].host.toLowerCase();
./plugins/rcpt_to.in_host_list.js:    var domain = rcpt.host.toLowerCase();
./plugins/rcpt_to.ldap.js:    var domain = rcpt.host.toLowerCase();
./plugins/rcpt_to.qmail_deliverable.js:    var domain = params[0].host.toLowerCase();
./plugins/rcpt_to.qmail_deliverable.js:    var domain = rcpt.host.toLowerCase();
./plugins/rcpt_to.routes.js:    var domain = rcpt.host.toLowerCase();
```

When `lower`ing stuff, need to be careful with strings that have to be preserved, for ex., dkim (?)

**Comment by celesteking** [comment]
Simple testcase: send a test mail with `<postmaster>` envelope, and see what breaks.

**Comment by baudehlo** [comment]
I decided not to support these addresses without @ when I wrote Haraka. What's a good reason to support them (and no, them being in a 30 year old rfc isn't one).

**Comment by celesteking** [comment]
I'm all in! Let's consider `<postmaster>` as bad address then. [This](https://github.com/haraka/node-address-rfc2821/blob/master/index.js#L85) needs to be modified then.

**Comment by msimerson** [comment]
Might it be better for `address-rfc2181` to set the host values to an empty string instead of null? 

I don't think there's any good argument that one is more correct than the other. Both are "falsey" in JS but one does nasty things when we try to treat it as a string (.toLowerCase(), etc..) and the other behaves in more expected ways that don't cause haraka CRIT errors. I think the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) may apply here.

**Comment by baudehlo** [comment]
Sure that probably is a sane thing to do. As long as it copes with that
properly with `.format()` etc.
