### ISSUE TITLE
 Host names have more than one DNS label

### ISSUE THREAD

**Issue by hugh01sm** [haraka/Haraka#1741]
Thanks for the help so far.
Have now moved Haraka to our server and getting the following error.  Full log file is attached.

[PROTOCOL] [0E46A2D4-4184-4A61-B56A-D2020816A381] [core] S: 550 Host names have more than one DNS label
[2016-12-15.txt](https://github.com/haraka/Haraka/files/654460/2016-12-15.txt)

**Comment by smfreegard** [comment]
`````
[PROTOCOL] [0E46A2D4-4184-4A61-B56A-D2020816A381] [core] C: EHLO ESGroup2 state=1
[INFO] [0E46A2D4-4184-4A61-B56A-D2020816A381] [core] hook=ehlo plugin=helo.checks function=valid_hostname params="ESGroup2" retval=DENY msg="Host names have more than one DNS label"
`````

The system that tried to send you the message did not send a valid hostname e.g. ESGroup2 .vs. ESGroup2.domain.com

Either you need to fix that system to send a correct hostname, whitelist it or disable the `helo.checks` plugin.

**Comment by hugh01sm** [comment]
Ok thanks
