### ISSUE TITLE
How to check my server IP is not an Open Relay. I am using Haraka

### ISSUE THREAD

**Issue by bibudha** [haraka/Haraka#1751]
Hello 

I am creating one mail server. I am using Haraka. But I am little confused about the relay thing. How to make relay my mail server so that I can send mail using other domain(DKIM and SPF verified).

I want mail in receiver inbox not in Spam.

**Comment by darkpixel** [comment]
Use 'swaks'.  It's a handy tool for testing SMTP connections.

From a machine that shouldn't be able to relay mail (maybe spin up a Digital Ocean droplet for a few minutes) you can run something like:
```
swaks --from a-fake-address@whatever.tld --to some-other-address@notmyserver.tld --server my-haraka-server.tld
```

See what swaks spits out.

**Comment by bibudha** [comment]
how to install the relay plugin in Haraka

**Comment by baudehlo** [comment]
It currently ships with Haraka.
