### ISSUE TITLE
Best practices for Haraka 

### ISSUE THREAD

**Issue by navinSing** [haraka/Haraka#1753]
Wanted to know if this is already documented somewhere :+1: 

How to save the incoming mails to lets say a mysql database, or custom database instead of file.

Is it via mq/rabbitmq and then writing a client code.
Or we can write some hooks plugins for saving each mail in db rather than file, due to performance.

**Comment by msimerson** [comment]
There really is no "right" answer to this question. Where and how to save emails depends on many factors. Most folks write their own plugin to store emails where they want (RDBMS, doc store, filesystem, etc.

What you'd need to do is determine which storage backend fits your business requirements and then write or adapt an existing queue plugin to store messages there.
