### ISSUE TITLE
Can Haraka mail server be used in Microsoft Outlook 2007 ?

### ISSUE THREAD

**Issue by bibudha** [haraka/Haraka#1761]
Hello

I am using Haraka as a mail server. So if my client wants this service to be configured in Microsoft Outlook 2007 with SMTP configuration then can it be possible ?

Also is there any example available which covers all Haraka plugins properly ? Means need example of Haraka in use of proper sending and receiving mails.

Thank You

**Comment by msimerson** [comment]
> Outlook 2007 with SMTP configuration then can it be possible ?

Yes.

> Also is there any example available which covers all Haraka plugins properly ?

There are install guides on the wiki.

**Comment by ayonsaha2011** [comment]
can i handle Outlook request for retrieve all mails

**Comment by smfreegard** [comment]
> can i handle Outlook request for retrieve all mails

Haraka is an SMTP server, not an IMAP/POP3 server... Haraka will only send and receive messages, it's not a mail store.  You would need to use it with something like Dovecot.

**Comment by ayonsaha2011** [comment]
ok there is any example for this

**Comment by smfreegard** [comment]
> ok there is any example for this

No - not really sure why you would use Haraka over something like Postfix for this type of thing though - there's far more documentation for Postfix/Dovecot, indeed most Linux installations will do most of the heavy lifting for you...
