### ISSUE TITLE
SSL Connection error after PR 1740

### ISSUE THREAD

**Issue by gramakri** [haraka/Haraka#1768]
I am running latest haraka (commit  f6013b9) with node 4.2.2 (I realize haraka requires 4.6.2 atleast but I am logging this issue just in case).

After https://github.com/haraka/Haraka/pull/1740/commits/e407e2f8d08505bc743716d9d13129f0bef78ad8, the server sometimes does not accept TLS connections. I have verified that reverting that change makes things consistently work.

TLS upgrade fails with the error:
```
139672910050968:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
```

The curious part here is that _restarting_ haraka makes the TLS connection go through fine mostly. So, maybe it is some race during setup?

**Comment by gramakri** [comment]
Client debug output:
```
ubuntu@ip-10-0-0-170:~$ openssl s_client -starttls smtp -connect <haraka>:25
CONNECTED(00000003)
140015963801240:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 238 bytes and written 340 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1484696526
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

On the haraka side, I see:
```
[core] client [<ip>] dropped connection
```

**Comment by msimerson** [comment]
`sslv3 alert handshake failure`

That's expected. That PR dropped some of our "hacks to disable SSLv3" code because node.js has already done that for us in supported versions. Until Node.js gets out of the habit of shipping a bundled OpenSSL, you really do need to be running a recent node. Really really.

**Comment by gramakri** [comment]
@msimerson I understand that the code to disable SSLv3 was dropped. I don't understand why haraka starts accepting connections after a restart (with node 4.2.2). Do you have any theories?

I am testing with 6.9.4 right now.

**Comment by gramakri** [comment]
Similar issue when running haraka with 6.9.4. On haraka logs, I see:
```
[core] client [45.55.2.141] connection error: Error: 140158490142528:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1418:
```

**Comment by msimerson** [comment]
Well, that's a much different error: `no shared cipher`.  Are you specifying a set of ciphers in  your Haraka config? 

> Restarting haraka, makes the connection work. 

That makes no sense to me.

What version of openssl are you using as the client?

**Comment by msimerson** [comment]
>  I don't understand why haraka starts accepting connections after a restart (with node 4.2.2). Do you have any theories?

Ohhhhhhh, actually I might. That might be a feature, not a bug. :-)  If a remote fails STARTTLS, we automatically withhold offering that remote STARTTLS on the next connection, so that even when TLS incompatibilities exist, mail still can get through.
