### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thihara** [haraka/Haraka#1772]
This is not an issue, but I'm not sure where exactly to post this question.

I've been looking into how Haraka can be used to receive and send emails, which resulted in the following post http://thihara.github.io/Creating-E-Mail-Service-with-Haraka/

If you guys think this is useful I can put it into the Tutorial section in haraka.github.io. If not please close this issue.

**Comment by smfreegard** [comment]
Thank you very much - this is an excellent post and tutorial!   I'll add it to the Wiki today.

**Comment by smfreegard** [comment]
Added to https://github.com/haraka/Haraka/wiki

**Comment by msimerson** [comment]
Thanks @thihara
