### ISSUE TITLE
What to use in place of Swaks on Windows?

### ISSUE THREAD

**Issue by wzup** [haraka/Haraka#1799]
I'm learning Haraka watching a [video tutorial](https://www.youtube.com/watch?v=6twKXMAsPsw&feature=youtu.be)

The author is using [Swaks ](http://www.jetmore.org/john/code/swaks/) as an SMTP test tool. However there is no `Swaks` on Windows.
What to use in place of `Swaks` on Windows?

**Comment by bmatson** [comment]
https://sourceforge.net/projects/blat/

**Comment by msimerson** [comment]
Swaks will likely also work on windows, but you'll first need to install Strawberry perl.
