### ISSUE TITLE
block js attachments

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1830]
I'm thinking we should also add `.js` to our list of default attachment types that we block.

- [Gmail will block .js file attachments starting February 13, 2017](https://gsuiteupdates.googleblog.com/2017/01/gmail-will-restrict-js-file-attachments.html)
https://t.co/tIy1KPgVHb
- [Gmail: Some file types are blocked](https://support.google.com/mail/answer/6590)

**Comment by baudehlo** [comment]
+1

How about .app.zip too? (that's what you get if you drag an .app to
Mail.app to send)

Probably a few other mac types we'd want to prevent. Perhaps .dmg and .pkg?

**Comment by darkpixel** [comment]
*.* and tell them to use FTP.  It's made for transferring files.  ;)

**Comment by msimerson** [comment]
> .app.zip ....  .dmg and .pkg

I'm wondering whether this is a reasonable **default** when Gatekeeper is doing a pretty good job at preventing that vector on macOS. I just searched my own email and the only legit example I could find was a .app I received from Apple support in 2014, for debugging an issue with a 4k display. Most legit app distributions are via HTTP nowadays. I wonder that the use cases are for sending those file types?
