### ISSUE TITLE
client.socket.remoteAddress undefined!

### ISSUE THREAD

**Issue by shurli** [haraka/Haraka#1835]
### system info
Haraka | Haraka.js — Version: 2.8.12
Node | v6.9.4
OS | Linux mailgateway 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Observed behavior
using smtp_forward plugin to an Exchange server.
everytime on end of smtp_client connection the following logfile entry is created:

[ERROR] [-] [core] client.socket.remoteAddress undefined!

I think everything works fine, is it really an error?
or would logwarn() or lognotice() be more useful in smtp_client.js:151

**Comment by msimerson** [comment]
See #1372 and #239
