### ISSUE TITLE
Enabling OCSP causes crashes

### ISSUE THREAD

**Issue by keithws** [haraka/Haraka#1855]
### system info

Haraka | Haraka.js — Version: 2.8.13
 --- | :--- 
Node | v6.9.4
OS | Linux 4.9.7-x86_64 #2 SMP Thu Feb 2 15:43:55 EST 2017 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux
openssl | OpenSSL 1.0.2k  26 Jan 2017

### Expected behavior

Haraka does not crash after enabling OCSP stapling in tls.ini

### Observed behavior

Haraka crashes with the following:

```
[PROTOCOL] [9D14A877-A0A7-4985-A53C-C751D982134D] [core] S: 220 Go ahead.
[DEBUG] [-] [core] Upgrading to TLS
[DEBUG] [-] [core] OCSP Request, URI: http://ocsp.int-x3.letsencrypt.org/, err=null
[CRIT] [-] [core] TypeError: Cannot read property 'tbsCertificate' of null
[CRIT] [-] [core]     at Object.generate (/usr/lib64/node_modules/Haraka/node_modules/ocsp/lib/ocsp/request.js:22:16)
[CRIT] [-] [core]     at /usr/lib64/node_modules/Haraka/tls_socket.js:180:36
[CRIT] [-] [core]     at Object.getAuthorityInfo (/usr/lib64/node_modules/Haraka/node_modules/ocsp/lib/ocsp/utils.js:168:10)
[CRIT] [-] [core]     at Object.getOCSPURI (/usr/lib64/node_modules/Haraka/node_modules/ocsp/lib/ocsp/api.js:13:14)
[CRIT] [-] [core]     at pseudoTLSServer.<anonymous> (/usr/lib64/node_modules/Haraka/tls_socket.js:174:14)
[CRIT] [-] [core]     at emitThree (events.js:116:13)
[CRIT] [-] [core]     at pseudoTLSServer.emit (events.js:194:7)
[CRIT] [-] [core]     at requestOCSP (_tls_wrap.js:123:17)
[CRIT] [-] [core]     at _tls_wrap.js:167:5
[CRIT] [-] [core]     at loadSNI (_tls_wrap.js:88:12)
[NOTICE] [-] [core] Shutting down
```

### Steps to reproduce

Add `enableOCSPStapling=true` to tls.ini
Get the status of a certificate signed by Let's Encrypt

**Comment by msimerson** [comment]
I just ran across [this issue](https://github.com/nodejs/node/commit/a1802e670d0a19746e49d0bd1dec266bb7ed7a60) while looking at SNI stuff and it made me think this might be node.js version dependent.
