### ISSUE TITLE
HMailItem use of this.domain vs this.todo.domain

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1860]
Within HMailItem, be internally consistent in the location of `domain` (this.domain vs this.todo.domain).

**Comment by msimerson** [comment]
See haraka/haraka-plugin-limit#4

**Comment by msimerson** [comment]
@baudehlo , a PR that addressed this would now be unlikely to collide with your outbound/*.js work, correct?

**Comment by baudehlo** [comment]
I'm all done with that work now.
