### ISSUE TITLE
Rewrite body per recipient

### ISSUE THREAD

**Issue by adamszeptycki** [haraka/Haraka#1867]
Is it possible to rewrite a body per recipient in emails send through haraka?
I have email with three recipients:
to: recipient1@example.com,  recipient2@example.com
cc: recipient3@example.com

Is it possible to edit body so everyone would get a little different email? And all the emails still end up in one "message" in recipients inboxes (they see each others as recipients of the same message)

**Comment by Dexus** [comment]
Can you explain what you wanna to do?
It is not really a possible option, to do what you wanna to try.

**Comment by adamszeptycki** [comment]
I would like to be able to send an email that is tracked (using standard pixel tracking). But when you have multiple recipients it's impossible to say which one of them opened the email UNLESS you change body per recipient. I know it's possible to do this in general I'm not sure if haraka will give me that option.

**Comment by Dexus** [comment]
Its not possible in that way as far as i know. But maybe @smfreegard @baudehlo or @msimerson have an other working idea.

**Comment by adamszeptycki** [comment]
Is there a tutorial how I could use haraka as a simple relay.
I would like to send an email that will go through haraka to smtp.gmail.com?

**Comment by acharkizakaria** [comment]
Take a look to the 'Configuring Haraka For Outbound Email' section what mean (relaying) in the [official documention](https://haraka.github.io/manual/tutorials/SettingUpOutbound.html).

**Comment by smfreegard** [comment]
Closing - this isn't possible.   You have to generate a separate e-mail for each recipient.
