### ISSUE TITLE
cpanel webmail transport unsolicited error

### ISSUE THREAD

**Issue by ayontulip** [haraka/Haraka#1872]
[INFO] [-] [core] [outbound] [outbound::25:162.144.137.50:undefined:2400] dispense() clients=0 available=0
[PROTOCOL] [69DB84AA-AA36-4185-9CD5-F7C4259E381B.1.1] [outbound] S: 220-server.example.in ESMTP Exim 4.88 #1 Wed, 29 Mar 2017 11:47:24 +0000 \r\n
[PROTOCOL] [69DB84AA-AA36-4185-9CD5-F7C4259E381B.1.1] [outbound] S: 220-We do not authorize the use of this system to transport unsolicited, \r\n
[PROTOCOL] [69DB84AA-AA36-4185-9CD5-F7C4259E381B.1.1] [outbound] S: 220 and/or bulk e-mail.\r\n
[PROTOCOL] [69DB84AA-AA36-4185-9CD5-F7C4259E381B.1.1] [outbound] C: EHLO mail.example.com
[ERROR] [69DB84AA-AA36-4185-9CD5-F7C4259E381B.1.1] [outbound] Ongoing connection failed to 162.144.137.50:25 : Error: write after end

**Comment by baudehlo** [comment]
This is a bug in outbound pools. All we can recommend right now is either
try downgrading to 2.8.4 or supply a patch to fix it.

**Comment by ayontulip** [comment]
my haraka version is 2.8.13 . And I am not getting what is "supply a patch"

**Comment by ayontulip** [comment]
new i'm downgrading my haraka version to 2.8.4 and that's work fine but i'm using other plugins with new version function like 'get_plain_passwd()' and i'm using 465 port that's also give error "Missing tls_key.pem for port 465"

So whats the solution ? Can you provide the patch for Outbound Pools

**Comment by Dexus** [comment]
Currently we have not patched this. So we cant provide a patch. We try currently to find, where we have to investigate..

**Comment by baudehlo** [comment]
One alternative that might just work is to copy the outbound.js file from
2.8.4 into a 2.8.13 installation.

**Comment by ayontulip** [comment]
So can will it be fixed in few days ?

**Comment by baudehlo** [comment]
Not likely, no. We've struggled with this bug for months now. It will
likely take weeks for us to figure it out unless someone with more time
available is able to fix it (supply a patch) for us.

**Comment by ayontulip** [comment]
is there any hook for this kind of error
If any hook exists then we can try other mail service like postfix in that
hook

**Comment by ssleptsov** [comment]
Hey, any news on this bug? Because I just got the same issue.
Thanks!

**Comment by KingNoosh** [comment]
I've fixed this, it'll be available in the next version.
