### ISSUE TITLE
karma results missing

### ISSUE THREAD

**Issue by deburau** [haraka/Haraka#1882]
### system info
Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v7.8.0
OS | Linux trillian.f*****t.net 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013
### Expected behavior
No error "karma results missing"
### Observed behavior
Error "karma results missing"
### Steps to reproduce
I'm using uptime robot to check if my Haraka server is up. It connects to port 25 and than closes the connection without sending commands. In this case, the karma plugin logs an error:

> 2017-04-07T11:24:13.640Z [ERROR] [232E8653-0A3E-4833-89BE-E7BA54A07C86] [karma] karma results missing

**Comment by msimerson** [comment]
surfaced by [haraka/haraka-plugin-karma#8]
