### ISSUE TITLE
Authentication required when using TLS

### ISSUE THREAD

**Issue by chasent** [haraka/Haraka#1909]
Currently in connection.js, there exists the following block of code:
```
    // Require authentication on connections to port 587 & 465
    if (!this.relaying && [587,465].indexOf(this.local.port) !== -1) {
        this.errors++;
        return this.respond(550, 'Authentication required');
    }
```

This block is run during the MAIL command (before the plugin hook).
Is this necessary?
I have a plugin that authorises users based on their IP address and MAIL FROM that doesn't work on TLS, but is fine when used in plaintext.

**Comment by Dexus** [comment]
Hi use a plugin that is start very early and set based on your IP verification the `connection.relaying=true`. And you should be able to send without authentication.

**Comment by chasent** [comment]
@Dexus thanks for the response. I would prefer to not set the ```connection.relaying=true``` at all as these emails are to be stored on disk for further processing, not relayed. For the moment I have this block of code removed in my testing environment as it seems somewhat arbitrary that port 25 is allowed.

**Comment by chasent** [comment]
Duplicate of #1873
