### ISSUE TITLE
error in installing haraka

### ISSUE THREAD

**Issue by epsilon-sajain** [haraka/Haraka#1910]
Windows 10 64 bit 
Haraka downloaded from git hub latest .
Node.js installed 
Then ran command npm install -g haraka.
It gives following error:

****C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\Haraka\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node.exe" "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\Haraka\node_modules\iconv
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.4 (node_modules\Haraka\node_modules\haraka-plugin-syslog\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node.exe" "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "Haraka"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sajain\Downloads\Haraka-master\Haraka-master\npm-debug.log
npm ERR! code 1****

**Comment by Dexus** [comment]
make sure you have installed python and set the ENV

**Comment by baudehlo** [comment]
npm install --global windows-build-tools

**Comment by epsilon-sajain** [comment]
hi , i did install python and set it in env variables then i typed the command given above 
npm install --global windows-build-tools
now it gives following error:
C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\Haraka\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
**MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
**s installed elsewhere.  [C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\Haraka\node_m**
odules\iconv\build\binding.sln]**
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node.exe" "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64\node_modules\Haraka\node_modules\iconv
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\sajain\Downloads\node-v6.10.3-win-x64\node-v6.10.3-win-x64
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.4 (node_modules\Haraka\node_modules\haraka-plugin-syslog\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node.exe" "C:\\Users\\sajain\\Downloads\\node-v6.10.3-win-x64\\node-v6.10.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "--g" "haraka"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log
npm ERR! code 1

**Comment by smfreegard** [comment]
Have you installed the .NET Framework 2.0 SDK like it tells you to?

**Comment by superman20** [comment]
For my own experience, the .NET Framework 2.0 SDK was no longer sufficient to compile the code (as the compiler provided with it cannot compile C++ 11 which it complained about).  I was able do a successful build of Haraka on a freshly formatted Windows 7 machine with only Python (must be the 2.X series), Visual Studio 2013 (or its equivalent SDK should work), and obviously node.js.  See [here](https://github.com/haraka/Haraka/issues/1895) for a slight bug (that has been fixed recently) when running the command `haraka -i /path/to/haraka_test`.  I did not use `npm install --global windows-build-tools`.

Also, FYI...the Visual Studio solution files (.sln) that are created when building do work with VS 2013, but they are not formatted properly for VS 2017 (and possible VS 2015).  I haven't looked into that yet.

**Comment by baudehlo** [comment]
Without any more comment, closing.

**Comment by pjebs** [comment]
Had the same issue when I tried to install Haraka on alpine Linux

**Comment by KingNoosh** [comment]
@pjebs  You need to install python.

**Comment by pjebs** [comment]
@KingNoosh For me it happens after attempting to install Haraka on the official `node:alpine`Docker  image .

I attempted to install Python on top of the image before installing Haraka. It didn't work. Do you know how to properly install Python?

**Comment by KingNoosh** [comment]
@pjebs 
```dockerfile
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    openssl \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*
```

**Comment by pjebs** [comment]
Thanks @KingNoosh , but it didn't solve my problem attempting to install Haraka
```
FROM node:alpine

# Install Python
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    openssl \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*

# Install Haraka
RUN npm install -g Haraka

EXPOSE 25 587

#Copy the config files into container and install dependencies
COPY /config /haraka_config
WORKDIR /haraka_config
RUN npm install

#FOR TESTING
RUN echo LOGDEBUG > /haraka_config/config/loglevel

#FOR PRODUCTION
ENTRYPOINT haraka -c /haraka_config

```

**Comment by pjebs** [comment]
It gets stuck at `RUN npm install -g Haraka`.
Infinite loop:
```
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/Haraka/node_modules/modern-syslog/.node-gyp"
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/Haraka/node_modules/modern-syslog/.node-gyp/9.1.0"
```

**Comment by DigaoParceiro** [comment]
I solved my problem 

> TRK0005: Failed to locate: "CL.exe"
with: npm config set msvs_version 2017 (2017 because i've installed Visual Studio 2017)

and I solved the problem:
> Failed at the iconv@2.3.0 install script 'node-gyp rebuild'.
with npm install -g npm (updating npm)

**Comment by wjinbo** [comment]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.18.0-80.el8.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/Haraka/node_modules/iconv
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
