### ISSUE TITLE
Log Plugin Issue

### ISSUE THREAD

**Issue by superman20** [haraka/Haraka#1914]
I'm writing my own log plugin and I have it working to my satisfaction except that it never captures initial startup logs from "Starting up Haraka" to just after all the plugins are loaded.  The first entry I ever receive is "Listening on ...".  It seems that at the end of `plugins.load_plugins` a call to `logger.dump_logs` is made.  This call dumps the buffered startup log output directly to the console ignoring any log hooks.  If I comment out the call to `logger.dump_logs`, then all log output is properly captured by my plugin.  Is this the intended behavior?  I would prefer to have all log info go through my hooks.

**Comment by msimerson** [comment]
It has long annoyed me that some logs are dumped to console when I have the syslog plugin enabled. I concur that if a log plugin is available, then all logs should be logged through it.

**Comment by baudehlo** [comment]
It's a bug. Otherwise there would be no reason to hold them back and dump them. That's why that process is in place at all.

**Comment by superman20** [comment]
It appears to me that the fix for this is to just delete the call to `logger.dump_logs`.  If you agree, I'll create a pull request.  In my testing, deleting this line allows all logs to go to any log hooks establish by plugins or it still gets to the console if no log plugins are present.

**Comment by baudehlo** [comment]
I don't think that is the correct fix.

The logger needs to hold onto log calls until the log plugin is loaded and then dump them through that plugin.

**Comment by superman20** [comment]
It appears to work that way now with the line deleted.  However, I guess it's not technically correct as the buffered logs don't really get output until the next time a log entry is made after the plugins are loaded.
