### ISSUE TITLE
dkim_sign bug on Windows

### ISSUE THREAD

**Issue by superman20** [haraka/Haraka#1918]
At line 188 of current master version, the following code line exists:

`domain = keydir.split('/').pop();`

The `split` function is biased towards unix paths and splits nothing on Windows (which have separators of `\`).  This causes DKIM signing to fail completely on windows.

**Comment by msimerson** [comment]
Yep, it should be using `path.basename()` instead. PRs are welcome.

**Comment by superman20** [comment]
I'll submit one as soon as I figure it out.  I'm a github virgin.
