### ISSUE TITLE
[outbound] Unable to write queue file

### ISSUE THREAD

**Issue by impulsemedia** [haraka/Haraka#1921]
I have been trying to use LMTP to store inbound mails through [WildDuck](https://github.com/wildduck-email/wildduck)

I get the following system error in Haraka when receiving mails from gmail.

![image](https://cloud.githubusercontent.com/assets/1214214/26097133/23800e1c-3a41-11e7-90d0-26946c0a2f4b.png)

**My lmtp.ini (@ /var/www/haraka/config/lmtp.ini)**

host=127.0.0.1
port=2525

**Plugins file-**
(I made only this change)

```
#QUEUE
#queues: discard  qmail-queue  quarantine  smtp_forward  smtp_proxy
# Queue mail via smtp - see config/smtp_forward.ini for where your mail goes
queue/lmtp
```

**Versions**

Haraka | Haraka.js — Version: 2.8.13
 --- | :--- 
Node | v7.10.0
OS | Linux AdityaMain 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

**Installation**

I installed haraka using

npm install -g Haraka
haraka -i /var/www/haraka
haraka -c /var/www/haraka

**Comment by smfreegard** [comment]
Check the permissions of /var/www/haraka and /var/www/haraka/queue - it looks like you've created the directories that do not allow the user that Haraka is running as to write to or access them.

**Comment by impulsemedia** [comment]
Thanks @smfreegard  . I created the queue folder manually. Now it works.
