### ISSUE TITLE
Outbound - PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by acharkizakaria** [haraka/Haraka#1925]
Hi guys, I'm trying to set up the `outbound` plugin with `tls & auth/flat_file`, I have already the tls certificate generated and referenced on the config file `tls.ini` as follow : 

>key=/etc/pki/tls/cert.pem
>cert=/etc/pki/tls/certs/localhost.crt

I'm always getting the same error : 

> Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

Do anyone have an idea about this error ?

More detailed log : 

> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436] [core] S: **235 Authentication successful**
> [INFO] [76A92341-EBC7-4A64-A158-CB5E02B3E436] [core] hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="aGFyYWthX3VzZXIgNDlmOWU3YzZhY2U0MjYyOGU1ZDMzZDdiMmI0Mjk1ODA=" retval=OK msg=""
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436] [core] C: MAIL FROM:<email_test@hotmail.com> state=1
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running mail hooks
> [NOTICE] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] sender <email_test@hotmail.com> code=CONT msg=""
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] S: 250 sender <email_test@hotmail.com> OK
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] C: RCPT TO:<email_test2@hotmail.com> state=1
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running rcpt hooks
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running rcpt_ok hooks
> [NOTICE] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] recipient <email_test2@hotmail.com> code=OK msg="" sender="email_test@hotmail.com"
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] S: 250 recipient <email_test2@hotmail.com> OK
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] C: DATA state=1
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running data hooks
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] S: 354 go ahead, make my day
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running data_post hooks
> [NOTICE] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] message mid="<20170519174243.005550@my_server.host>" size=276 rcpts=1/0/0 delay=0 code=CONT msg=""
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running queue_outbound hooks
> [NOTICE] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] queue code=CONT msg=" (76A92341-EBC7-4A64-A158-CB5E02B3E436.1)"
> [INFO] [-] [core] [outbound] Sending email as a transaction
> [DEBUG] [-] [core] running pre_send_trans_email hooks
> [INFO] [-] [core] [outbound] Processing domain: gmail.com
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running queue_ok hooks
> [NOTICE] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] queue code=OK msg="Message Queued"
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] S: 250 Message Queued
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running reset_transaction hooks
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] C: QUIT state=1
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running quit hooks
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] S: 221 my_server.host closing connection. Have a jolly good day.
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running disconnect hooks
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] running disconnect hook in tls plugin
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] hook=disconnect plugin=tls function=hook_disconnect params="" retval=CONT msg=""
> [NOTICE] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1] [core] disconnect ip=127.0.0.1 rdns="localhost" helo="my_server.host" relay=Y early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=276 lr="" time=0.085
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] running send_email hooks
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] Sending mail: 1495208563916_0_5540_782.my_server.host
> [DEBUG] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] running get_mx hooks
> [INFO] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] Looking up A records for: gmail-smtp-in.l.google.com
> [INFO] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] Attempting to deliver to: 74.125.133.27:25 (0) (0)
> [INFO] [-] [core] [outbound] [outbound::25:74.125.133.27:undefined:50] dispense() clients=1 available=0
> [DEBUG] [-] [core] [outbound] [outbound::25:74.125.133.27:undefined:50] createResource() - creating obj - count=1 min=0 max=10
> [DEBUG] [-] [core] [outbound] host=74.125.133.27 port=25 pool_timeout=50 created
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 220 mx.google.com ESMTP v50si3085217wrc.22 - gsmtp\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] C: EHLO my_server.host
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250-mx.google.com at your service, [37.187.30.55]\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250-SIZE 157286400\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250-8BITMIME\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250-STARTTLS\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250-ENHANCEDSTATUSCODES\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250-PIPELINING\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250-CHUNKING\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 250 SMTPUTF8\r\n
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] C: STARTTLS
> [PROTOCOL] [76A92341-EBC7-4A64-A158-CB5E02B3E436.1.1] [outbound] S: 220 2.0.0 Ready to start TLS\r\n
> **[CRIT] [-] [core] Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
> [CRIT] [-] [core]     at Object.createSecureContext (_tls_common.js:85:17)
> [CRIT] [-] [core]     at _getSecureContext (/usr/lib/node_modules/Haraka/tls_socket.js:226:16)
> [CRIT] [-] [core]     at pluggableStream.socket.upgrade (/usr/lib/node_modules/Haraka/tls_socket.js:315:33)
> [CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/outbound.js:1756:32)
> [CRIT] [-] [core]     at emitOne (events.js:96:13)
> [CRIT] [-] [core]     at pluggableStream.emit (events.js:191:7)
> [CRIT] [-] [core]     at pluggableStream.socket.process_data (/usr/lib/node_modules/Haraka/line_socket.js:24:20)
> [CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/line_socket.js:35:48)
> [CRIT] [-] [core]     at emitOne (events.js:96:13)
> [CRIT] [-] [core]     at pluggableStream.emit (events.js:191:7)**

**Comment by baudehlo** [comment]
There's some suggestions here:
http://stackoverflow.com/questions/20837161/openssl-pem-routinespem-read-biono-start-linepem-lib-c703expecting-truste

**Comment by acharkizakaria** [comment]
Thanks @baudehlo for your response, yes that was an issue of ssl certificate.
