### ISSUE TITLE
cluster shutdown/restart issues

### ISSUE THREAD

**Issue by chazomaticus** [haraka/Haraka#1926]
### Background

We recently upgraded from haraka 2.7.something to 2.8.13.  We use clustering with 20 workers per instance.  After the upgrade, I noticed that haraka would now take ~20 minutes to shut down after it received a SIGTERM, when it used to happen instantaneously.  This was after spending some time fixing our plugins to properly shutdown when requested, which I initially assumed was causing the issue.

### Problem

I traced the problem back to open connections from clients sending us mail (or not, but leaving the connection open anyway).  Haraka doesn't appear to track client connections anywhere explicitly after they're created, but of course open connections prevent the node main loop from exiting, even after everything else in each worker has been properly closed *and* worker.disconnect() has been called.  This is exacerbated by the way workers are shut down [in serial](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L135) and waited on ([up to 1 minute](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L129)) to fully exit.  For deployments of sufficient volume (where you're almost guaranteed at least a few client connections will hold the line without doing anything) using clustering, this means that shutting down haraka now takes as many minutes as there are workers.

### Steps to Reproduce

* Set your smtp.ini with `nodes=2` or more.
* Run haraka, e.g. from master: `node haraka.js`.
* Open a few connections to haraka, e.g. `telnet localhost 25`.
* Leave those connections open and untouched, and send `SIGTERM` to the master process, e.g. `kill ...`.
* Observe that haraka starts to shut down immediately, but stays up, and the connections stay active.
* After one minute, whatever connections that hit the first haraka worker will get closed and haraka will move on to the second worker, etc.
* The whole process only goes down after as many minutes as you had workers with open connections.

I'd expect it to go down in a fixed, even if somewhat long, amount of time.  It's not a huge issue, but I'd expect anyone running the latest version at scale to see the same thing, and it makes scaling slightly more painful.

### Potential Fixes

I'm guessing it's a feature that connections are allowed time to wrap up and close on their own.  I'd love to see the connections being tracked (bonus points for actually keeping tabs on what part of the conversation they're in and waiting until the transaction isn't in a state where dropping the connection might lead to data loss, e.g. after `data_post` but before it's been confirmed from the `smtp_forward` host) and closed after some shorter timeout than the workers themselves get, especially if inactive.

I think there's a quick solution here that gets us part of the way there without changing too much code:  how would people feel about changing the worker shutdown logic to use `async.eachLimit()` instead of [`async.eachSeries()`](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L135), with a limit of `nodes / 2`.  That way there are still always nodes up listening for connections, as is needed if you're doing a graceful restart, but the total time is always capped at a fixed value, instead of growing with the number of nodes.

If that seems like a good idea, I'd be happy to whip up a patch (I'd also take a stab at getting those worker timeouts to be configurable).

All of this was tested on master, node v4.2.6, linux 4.4.0-72-generic x86_64 (ubuntu 16.04).

### Bonus Problem

It doesn't appear that the graceful restart option actually works if you have cluster enabled.  If you use the bin to do `--graceful`, it properly connects to a node and goes through the `INTERNALCMD` rigamarole, even [sending the master process the right message](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L208).  The master process doesn't seem to be listening for that message anywhere though, so it never does the restart.

I'd be happy to include this in my patch, providing someone can give me security guidance on it (i.e. the `INTERNALCMD` mechanism is required to come from localhost *and* have the secret key, and I'm guessing node implements this IPC mechanism as a pipe, but if it's a named pipe or socket of some kind it should get the same treatment I assume).

Also happy to break this out into a separate issue either way.

**Comment by baudehlo** [comment]
There's definitely bugs in this area. I've recently even seen Haraka fail to shut down if it ends up making use of outbound at all. Ultimately the code is designed to shut down regardless of that after 30s. We can probably shorten that.

If that time is getting extended because of cluster then consider that a bug. It should not be 30s x CPUs.

I'm also considering killing the graceful code completely. Or at the very least making it optional and off by default. Shutting down an  SMTP server is pretty much never destructive as long as it syncs files properly to disk. If Haraka isn't doing that it's a much worse bug.

**Comment by msimerson** [comment]
> I'm also considering killing the graceful code completely

+1

**Comment by smfreegard** [comment]
> I'm also considering killing the graceful code completely

+1

I don't think a graceful shutdown is actually that useful in Haraka.  Well written plugins (e.g. all core plugins) will not lose messages provided they are talking to proper SMTP clients, because we'll never send 250 to the client until we've either written the queue file or received 250 from the upstream client in the case.  The only danger is duplicate messages and not losing mail.

The only time this would be of benefit is for clients not compliant with RFC5321 e.g. PHP/Perl scripts that don't queue in case of failure.

**Comment by baudehlo** [comment]
For what it's worth, the internal command stuff is just part of connection.js. It's hard to grep for. Basically when you call `INTERNALCMD foo` it calls the function `foo` in `server.js` in the master process only.

If that's not working, please let us know.

The PR above should also fix your other issues.

**Comment by chazomaticus** [comment]
Thanks for the quick turnaround!  I opened the graceful restart bug as #1933.  Cheers!
