### ISSUE TITLE
graceful restart doesn't work with cluster on

### ISSUE THREAD

**Issue by chazomaticus** [haraka/Haraka#1933]
If cluster is turned on in server, graceful restart (`bin/haraka -c . --graceful` is how I'm invoking it) doesn't work.  The bin script properly connects to a listener in haraka and sends the `INTERNALCMD` just fine.  The server doesn't do anything from there, though.

From the tracing I was doing in #1926, it appeared that the worker handled the `INTERNALCMD` correctly and [properly sent the message along to the master with `process.send()`](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L208).  But, I couldn't find anywhere the master was listening for that message (I could only see `process.on('message', ...)` listening for the cfreader, plugins, and outbound shutdown events).

Here is the extent of the logging output with most plugins off (with my key elided):

```
[NOTICE] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] connect ip=::1 port=36734 local_ip=:: local_port=2525
[DEBUG] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] running connect_init hooks
[DEBUG] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] running connect_init_respond
[DEBUG] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] running lookup_rdns hooks
[DEBUG] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] running connect hooks
[PROTOCOL] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] S: 220 haraka.test ESMTP Haraka 2.8.13 ready
[PROTOCOL] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] C: INTERNALCMD key:562... gracefulRestart state=1
[PROTOCOL] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] S: 250 Command sent for execution. Check Haraka logs for results.
[PROTOCOL] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] C: QUIT state=1
[DEBUG] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] running quit hooks
[PROTOCOL] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] S: 221 haraka.test closing connection. Have a jolly good day.
[DEBUG] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] running disconnect hooks
[NOTICE] [F954621E-D377-4F8D-B4F7-6308F91E96AB] [core] disconnect ip=::1 rdns="ip6-loopback" helo="" relay=N early=N esmtp=N tls=N pipe=N errors=0 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="" time=0.009
```

Tested on master, node v4.2.6, linux 4.4.0-72-generic x86_64 (ubuntu 16.04).

To reproduce, set `nodes=2` or so in smtp.ini, and run haraka from master like `bin/haraka -c .`.  Then run `bin/haraka -c . --graceful` and note that haraka doesn't restart.

**Comment by baudehlo** [comment]
I'm having Haraka launching infinite workers right now, so there's
something much worse going on :)

I'll look into this issue though.

**Comment by baudehlo** [comment]
Check the PR above. I have tested the graceful code now with cluster and it works for me, both using the command line, and telnet:

```
$ telnet localhost 2525
Trying ::1...
Connected to localhost.
Escape character is '^]'.
220 haraka.test ESMTP Haraka 2.8.13 ready
INTERNALCMD gracefulRestart
250 Command sent for execution. Check Haraka logs for results.
```

The logs showed that each worker restarted.

**Comment by baudehlo** [comment]
FWIW the code to receive the message in the master is here: https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L286

**Comment by chazomaticus** [comment]
Was just looking at this when I saw your update.  Your patch didn't change anything for me, but [reading this was enlightening](https://nodejs.org/api/cluster.html#cluster_event_message_1).  This patch fixes it for me:

```diff
diff --git a/server.js b/server.js
index fc14563..33af433 100644
--- a/server.js
+++ b/server.js
@@ -232,7 +232,13 @@ Server.receiveAsMaster = function (command, params) {
     Server[command].apply(Server, params);
 }
 
-function messageHandler (worker, msg) {
+function messageHandler (worker, msg, handle) {
+    if (arguments.length === 2) {
+        handle = msg;
+        msg = worker;
+        worker = undefined;
+    }
+
     // console.log("received cmd: ", msg);
     if (msg && msg.cmd) {
         Server.receiveAsMaster(msg.cmd, msg.params);
```

**Comment by baudehlo** [comment]
You have got to be shitting me - they changed the order of params to add something? Ugh!

Ok I'll do a PR unless you beat me to it.

**Comment by baudehlo** [comment]
PR done.

**Comment by chazomaticus** [comment]
I know, seems like a poorly thought out change on node's part.  Sorry, I'd gotten distracted with other stuff, thanks for finishing this!  :D
