### ISSUE TITLE
Issue with email Delivery for outlook.com

### ISSUE THREAD

**Issue by shanmmukha1589** [haraka/Haraka#1935]
Hello Haraka Team,
 we are using the SMTP configurations as given ..... with some of changes in domain and DKIM Signatures 

so, for sending Email we used Postfix as Email Client it didn't work ....then we started using sendmail and absolutely it worked !!!

but we are having the problem with sendmail too..... Everytime after the message sent we have to restart sendmail  
  bash:$ sudo service sendmail restart 
then we can send the email again

please give the steps to automate the process which doesn't require manual restart 

2) Messages for outlook are delivered to SPAM(Junk)
when we are sending the mails to outlook contacts the messages are delivered to Junk folder 
my email ID: venugopal331@outlook.com

the Orginal Source:
===================MAIL LOG START=====================
Received: from SG2APC01HT151.eop-APC01.prod.protection.outlook.com
 (10.164.137.9) by PN1PR01MB0317.INDPRD01.PROD.OUTLOOK.COM with HTTPS via
 PN1PR01CA0002.INDPRD01.PROD.OUTLOOK.COM; Tue, 23 May 2017 11:38:10 +0000
Received: from SG2APC01FT042.eop-APC01.prod.protection.outlook.com
 (10.152.250.52) by SG2APC01HT151.eop-APC01.prod.protection.outlook.com
 (10.152.251.128) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.1.1075.5; Tue, 23
 May 2017 11:38:09 +0000
Authentication-Results: spf=pass (sender IP is 35.161.49.238)
 smtp.mailfrom=msrkumar.com; outlook.com; dkim=none (message not signed)
 header.d=none;outlook.com; dmarc=bestguesspass action=none
 header.from=msrkumar.com;
Received-SPF: Pass (protection.outlook.com: domain of msrkumar.com designates
 35.161.49.238 as permitted sender) receiver=protection.outlook.com;
 client-ip=35.161.49.238; helo= ip-172-31-21-31.us-west-2.compute.internal;
Received: from SNT004-MC7F5.hotmail.com (10.152.250.59) by
 SG2APC01FT042.mail.protection.outlook.com (10.152.251.18) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.1075.5 via Frontend Transport; Tue, 23 May 2017 11:38:07 +0000
X-IncomingTopHeaderMarker: OriginalChecksum:B229DA8D8F2E74D07E0CF4155285A7DD2CE578B83FE70F81B0BCC2DB4370C8AF;UpperCasedChecksum:329A1878ADC41F2EB86E90E87DE83B6F2761D762084EC0D13108AB41189F9548;SizeAsReceived:846;Count:10
Received: from ip-172-31-21-31.us-west-2.compute.internal ([35.161.49.238]) by SNT004-MC7F5.hotmail.com over TLS secured channel with Microsoft SMTPSVC(7.5.7601.23143);
	 Tue, 23 May 2017 04:37:51 -0700
Received: from ip-172-31-21-31.us-west-2.compute.internal (localhost [127.0.0.1])
	by ip-172-31-21-31.us-west-2.compute.internal (8.14.4/8.14.4/Debian-4.1ubuntu1) with ESMTP id v4NBZIGW032052
	for <venugopal331@outlook.com>; Tue, 23 May 2017 11:35:18 GMT
Message-ID: <201705231135.v4NBZIGW032052@ip-172-31-21-31.us-west-2.compute.internal>
Date: Tue, 23 May 2017 11:35:18 +0000
To: <venugopal331@outlook.com>
From: <dev@msrkumar.com>
Subject: Conformation mail
X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
Return-Path: dev@msrkumar.com
X-OriginalArrivalTime: 23 May 2017 11:37:51.0768 (UTC) FILETIME=[02DE0180:01D2D3B9]
X-IncomingHeaderCount: 10
X-MS-Exchange-Organization-Network-Message-Id: 1d7173b1-a47a-4f24-8314-08d4a1d02fed
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
CMM-sender-ip: 35.161.49.238
CMM-sending-ip: 35.161.49.238
CMM-Authentication-Results: hotmail.com; spf=pass (sender IP is
 35.161.49.238) smtp.mailfrom=dev@msrkumar.com; dkim=none
 header.d=msrkumar.com; x-hmca=pass header.id=dev@msrkumar.com
CMM-X-SID-PRA: dev@msrkumar.com
CMM-X-AUTH-Result: PASS
CMM-X-SID-Result: PASS
CMM-X-Message-Status: n:n
CMM-X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0wO0Q9MjtHRD0yO1NDTD02
CMM-X-Message-Info: 11chDOWqoTk7XtXLqDbQHA+0VDd0aFPstkI91LX9Pm0bmMFWYusMLoW2JNM00xsTvVSfdUClMJfdSIh4048zLTt6eamw8rVe1VVnout1c3oe6l97YKK3W+w3wV2pPvW8Mmy1/FiJQwQdA78LSoU+WMWM6Y5Bm+xC2oz/nRvx8cET99YLr3mnVocMbB+FtCreCqYdiripmS/2m8x7AokpSqkVbA1UIzHRnmrW9TeODsKq7Xjbiidn/D/U9LgSj4XH
X-MS-Exchange-Organization-SCL: 5
X-MS-Exchange-Organization-PCL: 2
X-MS-UserLastLogonTime: Tue, 23 May 2017 11:34:36 +0000
X-Microsoft-Exchange-Diagnostics: 1;SG2APC01FT042;1:IMbFLA5yfLKTh3x5SodwfIPli1UulEK29O5CTvqAsH2Vp1WjyhwAT5fWDJGpuARuW5/K6nHplsuMFLhdwgQIVjv9SBXQNlMA1Q1IVOMZfrDzdZ3+iFQjiWLUq6ZU13C7+6m/vtEfgxeyHNCb2BN4nNuqVTrK9/GZ1M4evh/6KlXUge4NYZOKKe+7DmkaGGNr
X-Forefront-Antispam-Report: EFV:NLI;SFV:SPM;SFS:(28900001);DIR:INB;SFP:;SCL:5;SRVR:SG2APC01HT151;H:SNT004-MC7F5.hotmail.com;FPR:;SPF:None;LANG:en;
Content-Type: text/plain
X-MS-Exchange-Organization-AuthSource: SG2APC01FT042.eop-APC01.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 1d7173b1-a47a-4f24-8314-08d4a1d02fed
X-Microsoft-Antispam: BCL:0;PCL:0;RULEID:(22001)(8291500097)(8291501071);SRVR:SG2APC01HT151;
X-Microsoft-Exchange-Diagnostics: 1;SG2APC01HT151;3:Xx5alyFODx248r3S/WTV98LW1ekAr88ktuTgK0KPwrnTKiJrYQgpdVQnYGCL3ShrbDUG8DtKoh2Zf+xmUUCQmAtgkcopcpA4b0MJMZjuvsQ9WXZEKNs2ab7kLjystRacmYtH0UZkSDa1KMmTEkSTPWDtL+rAHPiwohxJ3cFwLFkOirEZanoEV8zHqeWL5stS14erEfo7F8yNxpvWvZpuamf1KbDAtCE67Ja48rCvZxRHR8e9V0RJUOXIGUkCNkCytsyZzHrMsgiLXd7zgnMdxyHsVpWooOmCrQ3johpw5F3NuV+SKDEx8L31+tX11HEVlzgVUKyJdgZHkF0ms33WUO5eBNeIaR44AO4dt5J3AxlzmnCw3YfducZRs/TDixx2W8HvirQ/omh+nwvyGyHp2A==;25:FuJLraFkzmAlkHI7GbKDT7p0fJXadYwni61aClCQSR4I/FdU/coaZVkNQkn3hA/bnNP8EHBXep8UsLfSH2zRVKgHCWVnhfndhCbodZ0PArh4DZI9zdv4H10A0x1b94Zh3ajqYE+CMFAIKn8hlvKSBk/Vr4oTVdpEu+xWqnHXzgNmFjQcU4EVsJWe7k+pgF/slK8HOFSq2NPUHRRkpAfOTJPk9SgsSpjEQy9NsZ3uzO1/gaP7osdSD7R08ZJQeetWQ3g//OtbXj2xsqnjDbsFQXY4MBKymr3xn/0PZLf8L/Vn6FiLT24QDDlp8N2F7/wdCeejpDO5npZplBQ+xbaS8PRHa+pDkS8WvQPNK16yThWc5vDPZALeTj+MFunOjq8W1xkzkA/zTgits89LGd7jp6IugONRL4v3azire743TwGYFD4SQxIfcKweiY8IMxT83sWASUxYpekeP7fEHvyq9Y8U4zzM7bjCpzI4jDw4PGRF9+c7b52HntG6t/D9Irzo
X-MS-Exchange-Organization-AVStamp-Service: 1.0
X-Microsoft-Exchange-Diagnostics: 1;SG2APC01HT151;31:Mc8uUEINm+0mPs8qIbLwLNEMUUY916/pUfAYY3a3Os12TNVS44YcLIasCnbLnNZeP3E2LEXPpXChlVz6g/Jbm2ZYzlKbwGP81YD0vi3vK+bhkpeyIoKVHuU6WQgYOuSDaWP6HqG2hZo4+sbjZrB71xlNqxGRhwxoFvs18nUNwRBzcLXS63MdrbyaQL0yNUsLk5Zq1QBqR9jXWHZISeJTJujMV4ReefaHv2WAlV9M6a7NN5DwXC3PjyjVLVhFiPEQ9vSKODHrNHuX5uNFi00NjX0VTGYODPfbBSYNfeBwOesM18yt38eUA2AgoXgEY5zb;4:GG7M9FG0VBs5zhQxG83NYJ2V5vArK5V04VuPzz1iRI8tDOekz7F8MuQg/IBultm9ROi6CpDHWjeQMUb339un+UUc/FmcBQCn3YlPLaLSQbvVgwVXLqxNzckzJkCDwWZrq6lWiptAL0YyQ/2zRfJaxH8rrROLKAYUKt4RAdc2+o2kojYZ/oro5tzcH9f/OyxHo0kuThhRPGTcsKKfi/4uriqobS1B2lGYhlyAVuRs4NGL6ejlc1J7I4ZytDmBjkhPh475QG99eJcbKi++zp3xnEbySOmLa4Yan39rKXYemrg=;23:y4kP1LWfTgAvRibwCJr7HbTytCunejFF0CDvRjPbtGAmwfrHZPKbE7cJ6LU6tDsDc5eHonao3nEGk+Sb6ESY8PioLcXG5upzOi3kYwjmwYR1987hyrVlb1Z+wyGPplIBYXeajWdubBWTcKDSP1GPrVIo9wyK6cqS3m7miNuD1mJA9uoZzj8AXkdQECyT9vCkLuehrBE8wTZnDXa5CUAkhw==
X-Exchange-Antispam-Report-CFA-Test: BCL:0;PCL:0;RULEID:(444000031);SRVR:SG2APC01HT151;BCL:0;PCL:0;RULEID:;SRVR:SG2APC01HT151;
X-Microsoft-Exchange-Diagnostics: 1;SG2APC01HT151;6:/KHMMzgNYBxQLmF3mjWwfZeW2LbwurlO/W4V9cFCycAp3lRNm/DAH+9YYEFlWuq6xc3+x5hfV2qBOeC8l9bSpEDZ4zX8ll8XS7t8fgYonj/jdRNdYlBJ/dVILfjh3ahMwjikd6N7kyBE2nfRFThnE5j476e8rsydcqvigl44X3NjV+aDni+eUIsZWtqCpUP3Jt2wyc6ZaxZKIzsiqD3gXP3zucuBV4iHxpadGA8BM0M6iiC7xeGMk+WEcL6yOwa6p//3opD9bWn5o4LL6bK4J+h9kJm6E1N08CAPVZ0vWUAbA+0N3e9HB41YXjYNPxCBJlFs++2r1JkWqswUImVFGLbLnPMkxwnFsN68WQDViz96wDrTRo9O2Q06FXza1Y85Qb5FmSwCfBJX9fgSNNGwbA==;5:WGyw6xmMoOEY3J775vrNE1PFws/MREKL6dzUhhHCWUHuYv0Eh2QPN9PqdhevgdFpXgtxJbw86Dfq96p10UZ6aDfRWWT2k8JalEC3zDm9jekQ4cSx7eojqASkWPbtDBuwXmV4qHid+nHzJxUCmkhY6Q==;24:QniRt0S1b+FP2dkqBRAlnxoKhFdbXtzXglamxjSSPumPx6s/3exFyv492WIUKqPFlDeTMSvRpETheXlvkNeILA==
SpamDiagnosticOutput: 1:22
SpamDiagnosticMetadata: Default
X-Microsoft-Exchange-Diagnostics: 1;SG2APC01HT151;7:7QL4kkAHcHYqQbMASuj/SF7CD8Kh/3Vk/J2m0+V649QPxdoN6rxeL8lC/PVrHgaVj5BZgxbDwjcxcL5KWJ3Yc0l5BCFGfYzNazxrNOoTsIND5KoifMySKJyGqo7yqZGkTTZglB6K8B6ODSkcW2dKR4H9Ku7Z45xKr3C/3alQue3iuumGg5CsFvedlfLrfrrJ3dLjr0LvtqSWZ6GuniiKSqn9LixT6cL/jrc8cRGv57d+5LHvKKU2e1uRSW6J0UrN5DPfbm8wTkL0iG16BN048Kee3hBuwYGWkNSVXU8B5kjbYAnAxyio5mhhiRd861JLH5rmGmpb1fHJ2gXgyNGFkQ==
X-OriginatorOrg: outlook.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 23 May 2017 11:38:07.8258
 (UTC)
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: SG2APC01HT151
X-MS-Exchange-Transport-EndToEndLatency: 00:00:02.5416422
X-Microsoft-Exchange-Diagnostics:
	1;PN1PR01MB0317;27:ZC2VBAS189FP4AM3jdwHnmwo+bezbuL4adBcaIEBlKmK5xqSJrDO3D8o7cK18qGQIqKeGB8Rywr/udL/+4YwL9cBbuhdKmEIeSSjewvyy85/qER4Suu7Q2KunMbBsIsIKxqYdumuyI4tFx4P03pyvA==
X-Microsoft-Antispam-Mailbox-Delivery:
	abwl:0;wl:0;pcwl:0;kl:0;iwl:0;ijl:0;dwl:0;dkl:0;rwl:0;ex:0;auth:1;dest:J;WIMS-SenderIP:35.161.49.238;WIMS-SPF:msrkumar%2ecom;WIMS-DKIM:msrkumar%2ecom;WIMS-822:dev%40msrkumar%2ecom;WIMS-PRA:dev%40msrkumar%2ecom;WIMS-AUTH:PASS;ENG:(5061607094)(102400140)(102420017);RF:JunkEmail;OFR:SpamFilterAuthJ;
MIME-Version: 1.0

Hi Shanmukha,\r
This is a account Conformation code : ASWDS \r
Please activate in our website

==========MAIL LOG END===========

Please Help on this

**Comment by smfreegard** [comment]
This is not a Haraka issue.   Deliverability isn't a software issue either; It's where you're sending the mail from, what with, in what format and the content of the message.  Closing.
