### ISSUE TITLE
Get "Header" object inside delivered hook

### ISSUE THREAD

**Issue by acharkizakaria** [haraka/Haraka#1945]
Hi guys, is there any way to get the header object inside hooks who not accept "connection" object as a parameter ? ("delivered" hook for example).

Else, do I have to pass it in "server" or "transaction" notes ?

Thanks in advance.

**Comment by smfreegard** [comment]
What exactly are you trying to do?   Read or modify a header?

**Comment by acharkizakaria** [comment]
I want just to read it.

**Comment by smfreegard** [comment]
Yeah - you can't do that, the Header object isn't re-created for Outbound.

I suggest storing whatever you need in transaction.notes when the message is received and you'll them be able to access it via hmail.todo.notes in hook_delivered.

**Comment by acharkizakaria** [comment]
OK thanks, I will.
