### ISSUE TITLE
Any Options/Plugin In Haraka to Track mail status Like Open/Clicks

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#1950]
### system info

Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v6.10.3
OS | Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

Hi 
I want to track OPEN/CLICK status on email via tracking pixel.   
How to set up a tracking pixel with Haraka. Is there any plugin available.??
If i need to write a plugin for this, what I need to do and during which Hook it can be done.

Kindly suggest if is there better/easier way to achieve this.

Thanks!

**Comment by ajay-psd** [comment]
Currently i found one solution.

I used  connection.transaction.set_banner(text,html) option under data hook. 
This adds a banner to end of line in type/html mails. Herei have specified img source=url to track mail OPEN event. Its working as expected.

Now i am looking tracking  Click event.
Is there any way to modify email content, i mean i will try to add proxy to all Links of email email content. 

Please suggest!

**Comment by smfreegard** [comment]
See add_body_filter in https://github.com/haraka/Haraka/blob/master/docs/Transaction.md

**Comment by ajay-psd** [comment]
Thanks a bunch! Working as expected.

I have one more query, Please advice... 

If there is multiple recipient in mail, Is it possible to track which email user has open or clicked. May be based on connection ID or any other method?
 
Thanks!

**Comment by smfreegard** [comment]
No - you have to ensure that there is only one message per recipient if you want to track them individually.

**Comment by techknowlogick** [comment]
@ajay-psd would you be able to publish the code you have created to support this functionality?
