### ISSUE TITLE
Redis connections not closing / reused

### ISSUE THREAD

**Issue by frank-bn** [haraka/Haraka#1955]
### system info

Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v6.10.3
OS | Linux dione 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

Ubuntu 16.04
Redis Server 3.2.9
Haraka Plugin Redis: Version 1.0.4 (running with default config)
Haraka Plugin Karma: Version 1.0.6 (running with default config)
redis and karma plugin in config/plugins enabled

### Expected behavior

Karma(?) plugin should need only one connection to redis or/and properly unsubscribe from db.

### Observed behavior

Running the following command after running Haraka for some time:
`redis-cli info clients`
shows:
`connected_clients:1627`
`…`

Running this:
`redis-cli client list`
outputs many clients like this one:
`id=705 addr=127.0.0.1:50664 fd=701 name= age=20864 idle=20836 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=punsubscribe`
The last command (cmd) is always **punsubscribe** and on **db=0**. 

### Steps to reproduce

see my system info

**Comment by msimerson** [comment]
Thanks for the report @frank-bn 

Currently, upon each new connection, the karma plugin creates a new redis client. On **that** redis client, it subscribes to the redis channel of the name `results-$UUID`. The karma plugin instance on that connection only receives messages emitted by Haraka & plugins for that particular connection.

That's different than how the `watch` plugin works. It uses the shared `server.notes.redis` connection and subscribes to `results-*`. In that way the watch plugin receives all results from all plugins on all connections.

The only other way karma results could work would be creating a new server.notes.redis-watch client instance. Then each connection could psubscribe using that shared connection and punsubscribe when they're done. The issue there would be that every open connection would get messages from every other open connection. It would be easy enough to have each connection filter the messages. The question would be, is that extra traffic more or less expensive than establishing a new redis client on each connection?
