### ISSUE TITLE
Authenticate Plugin  for database support

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#1962]
### system info
Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v6.10.3
OS | Linux test-haraka 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

-----------------

Hi

Currently I am running multiple haraka instance on different machine and using auth/flatfile plugin for authentication on all instances. 

I just want to make authenticate from centralized location or from database like MySQL,
Is there any option or plugin available to authenticate from Database or from any central location we can use.

Please Suggest..

Thanks!

**Comment by smfreegard** [comment]
We don't have one in Haraka core, you could look on Github for one or write your own.

**Comment by msimerson** [comment]
Look in the [haraka org](https://github.com/haraka) at plugins that provide auth. There's a redis plugin, postgresql plugin, I know someone published a MySQL plugin, and there's the auth-imap plugin which can front-end Dovecot, which has numerous backends.
