### ISSUE TITLE
Outbound connection timing out to Office 365

### ISSUE THREAD

**Issue by moatak787** [haraka/Haraka#1965]
### system info

Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v6.10.3
OS | Linux 9f65051a73e4 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1t  3 May 2016

### Expected behavior

Email to be delivered to Office 365 account

### Observed behavior

MX records are correctly retrieved however it is timing out when trying to connect to the server.  Office 365 provides a number of different IPs to connect to and it times out to each of these in turn.  However on previous occassions it has connected and sent the email with no issues.

You can see in the logs below that it fails to connect on the first couple attempts and then it is able to after a while.  Some things to note:

 - this sending server is hosted on AWS however we have whitelisted the IP and since it sends eventually it must mean it is ok?
 - the domain it is sending from we own but don't have any MX records setup yet, so a reverse lookup wouldn't point to this server (again since it sends in the end must be this doesn't affect it?)
 - we are using an old version of haraka since I previously read somewhere this was the one to use for outbound since later versions had some issues, does this still hold true?

**LOGS:**
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] running queue_ok hooks
[NOTICE] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] queue code=OK msg="Message Queued"
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] S: 250 Message Queued
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] running reset_transaction hooks
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] client [172.18.0.8] half closed connection
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] running disconnect hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] running disconnect hook in tls plugin
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] hook=disconnect plugin=tls function=hook_disconnect params="" retval=CONT msg=""
[NOTICE] [78B6CE84-8052-48F6-A187-840C7F15B236.1] [core] disconnect ip=172.18.0.8 rdns="ubuntu_mta_process_email_service_1.ubuntu_default" helo="[172.18.0.8]" relay=Y early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=548 lr="" time=0.058
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running send_email hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Sending mail: 1497622030478_0_1_3564.9f65051a73e4
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hook in relay plugin
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] hook=get_mx plugin=relay function=force_routing params="testing.com" retval=CONT msg=""
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Looking up A records for: testing-com.mail.protection.outlook.com
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 213.199.154.138:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=213.199.154.138 port=25 pool_timeout=50 created
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 213.199.154.138:25
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 94.245.120.74:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=94.245.120.74 port=25 pool_timeout=50 created
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 94.245.120.74:25
[DEBUG] [-] [core] Temp fail for: Tried all MXs
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running deferred hooks
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Temp failing 1497622030478_0_1_3564.9f65051a73e4 for 64 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running send_email hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Sending mail: 1497622154486_1_1_3564.9f65051a73e4
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hook in relay plugin
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] hook=get_mx plugin=relay function=force_routing params="testing.com" retval=CONT msg=""
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Looking up A records for: testing-com.mail.protection.outlook.com
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 213.199.154.138:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=213.199.154.138 port=25 pool_timeout=50 created
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection error: Error: connect ETIMEDOUT 213.199.154.138:25
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 94.245.120.74:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=94.245.120.74 port=25 pool_timeout=50 created
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 94.245.120.74:25
[DEBUG] [-] [core] Temp fail for: Tried all MXs
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running deferred hooks
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Temp failing 1497622154486_1_1_3564.9f65051a73e4 for 128 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running send_email hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Sending mail: 1497622315700_2_1_3564.9f65051a73e4
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hook in relay plugin
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] hook=get_mx plugin=relay function=force_routing params="testing.com" retval=CONT msg=""
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Looking up A records for: testing-com.mail.protection.outlook.com
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 213.199.154.106:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.106:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:213.199.154.106:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=213.199.154.106 port=25 pool_timeout=50 created
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 213.199.154.106:25
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 213.199.154.138:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=213.199.154.138 port=25 pool_timeout=50 created
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.106:undefined:50] dispense() clients=0 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 213.199.154.138:25
[DEBUG] [-] [core] Temp fail for: Tried all MXs
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running deferred hooks
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Temp failing 1497622315700_2_1_3564.9f65051a73e4 for 256 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.106:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running send_email hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Sending mail: 1497622632274_3_1_3564.9f65051a73e4
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hook in relay plugin
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] hook=get_mx plugin=relay function=force_routing params="testing.com" retval=CONT msg=""
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Looking up A records for: testing-com.mail.protection.outlook.com
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 213.199.154.138:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=213.199.154.138 port=25 pool_timeout=50 created
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 213.199.154.138:25
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 94.245.120.74:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=94.245.120.74 port=25 pool_timeout=50 created
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 94.245.120.74:25
[DEBUG] [-] [core] Temp fail for: Tried all MXs
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running deferred hooks
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Temp failing 1497622632274_3_1_3564.9f65051a73e4 for 512 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running send_email hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Sending mail: 1497623205366_4_1_3564.9f65051a73e4
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hook in relay plugin
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] hook=get_mx plugin=relay function=force_routing params="testing.com" retval=CONT msg=""
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Looking up A records for: testing-com.mail.protection.outlook.com
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 213.199.154.138:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=213.199.154.138 port=25 pool_timeout=50 created
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 213.199.154.138:25
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 94.245.120.74:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=94.245.120.74 port=25 pool_timeout=50 created
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 94.245.120.74:25
[DEBUG] [-] [core] Temp fail for: Tried all MXs
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running deferred hooks
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Temp failing 1497623205366_4_1_3564.9f65051a73e4 for 1024 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.138:undefined:50] dispense() clients=0 available=0
[INFO] [-] [core] [outbound] [outbound::25:94.245.120.74:undefined:50] dispense() clients=0 available=0
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running send_email hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Sending mail: 1497624289986_5_1_3564.9f65051a73e4
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hooks
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running get_mx hook in relay plugin
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] hook=get_mx plugin=relay function=force_routing params="testing.com" retval=CONT msg=""
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Looking up A records for: testing-com.mail.protection.outlook.com
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] Attempting to deliver to: 213.199.154.106:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.106:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:213.199.154.106:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] host=213.199.154.106 port=25 pool_timeout=50 created
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 220 AM5EUR03FT033.mail.protection.outlook.com Microsoft ESMTP MAIL Service ready at Fri, 16 Jun 2017 14:44:49 +0000\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: EHLO 9f65051a73e4
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-AM5EUR03FT033.mail.protection.outlook.com Hello [35.176.18.2]\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-SIZE 157286400\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-PIPELINING\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-DSN\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-ENHANCEDSTATUSCODES\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-STARTTLS\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-8BITMIME\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-BINARYMIME\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250 CHUNKING\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: STARTTLS
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 220 2.0.0 SMTP server ready\r\n
[DEBUG] [-] [core] client TLS upgrade in progress, awaiting secured.
[DEBUG] [-] [core] client TLS secured.
[INFO] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] secured: cipher=ECDHE-RSA-AES256-SHA384 version=TLSv1/SSLv3 verified=true cn="mail.protection.outlook.com" organization="Microsoft Corporation" issuer="Microsoft Corporation" expires="Apr 30 16:33:37 2018 GMT" fingerprint=6C:D7:E6:0C:21:66:09:E3:AD:5D:FA:E8:7C:A0:DC:54:F3:22:52:AC
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: EHLO 9f65051a73e4
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-AM5EUR03FT033.mail.protection.outlook.com Hello [35.176.18.2]\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-SIZE 157286400\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-PIPELINING\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-DSN\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-ENHANCEDSTATUSCODES\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-AUTH LOGIN\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-8BITMIME\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250-BINARYMIME\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250 CHUNKING\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: MAIL FROM:<alerts-response@test_sender.com>
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250 2.1.0 Sender OK\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: RCPT TO:<tom@testing.com>
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250 2.1.5 Recipient OK\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: DATA
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 354 Start mail input; end with <CRLF>.<CRLF>\r\n
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: .
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] S: 250 2.6.0 <78B6CE84-8052-48F6-A187-840C7F15B236.1@9f65051a73e4> [InternalId=130184753713403, Hostname=DBXPR04MB317.eurprd04.prod.outlook.com] 8273 bytes in 0.296, 27.285 KB/sec Queued mail for delivery\r\n
[NOTICE] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] delivered file=1497624289986_5_1_3564.9f65051a73e4 domain="testing.com" host="testing-com.mail.protection.outlook.com" ip=213.199.154.106 port=25 mode=SMTP tls=Y auth=N response="<78B6CE84-8052-48F6-A187-840C7F15B236.1@9f65051a73e4> [InternalId=130184753713403, Hostname=DBXPR04MB317.eurprd04.prod.outlook.com] 8273 bytes in 0.296, 27.285 KB/sec Queued mail for delivery" delay=2260.851 fails=5 rcpts=1/0/0
[DEBUG] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] running delivered hooks
[DEBUG] [-] [core] [outbound] release_client: 213.199.154.106:25 to undefined
[INFO] [-] [core] [outbound] [outbound::25:213.199.154.106:undefined:50] dispense() clients=0 available=1
[PROTOCOL] [78B6CE84-8052-48F6-A187-840C7F15B236.1.1] [outbound] C: RSET

### Steps to reproduce
Attempt to send an outbound email to a recipient whose account is based on Office 365 (exchange online).

**Comment by smfreegard** [comment]
See https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/
