### ISSUE TITLE
New plugin "accounting-files"

### ISSUE THREAD

**Issue by acharkizakaria** [haraka/Haraka#1967]
Hi guys, first of all I'm glad to be one of the HARAKA contributors and part of this community. After my first contribution ([VMTA plugin](https://github.com/haraka/haraka-plugin-vmta)), I was encouraged by the core contributors @msimerson, @baudehlo (Greetings to them) when my first plugin was merged to be one of the new indepent plugins (NPM package/Github repository) of the next release, what gaves me more enthusiasm to help and trying to enrich this brilliant organization by more and more useful plugins.

I want just to inform you that I have added a new plugin called "accounting-files", this plugin gives the HARAKA users the ability to extract the useful/custom information from the outbound traffic and manage the 'storage/archiving' of the three main types 'Delivered/Deferred/Bounce' (More details in the links below).

GitHub : [haraka-plugin-accounting-files](https://github.com/acharkizakaria/haraka-plugin-accounting-files)
NPM Package : [haraka-plugin-accounting-files](https://www.npmjs.com/package/haraka-plugin-accounting-files)

Glad I could help.

**Comment by baudehlo** [comment]
Would you be interested in starting and maintaining an external plugins page for the main web site?

**Comment by msimerson** [comment]
A complete list of plugins (minus this one) already exists in the 3.0 branch of Haraka.

**Comment by acharkizakaria** [comment]
I'm ready to contribute and glad if I could help.

**Comment by msimerson** [comment]
Please create a PR that adds your plugin to the [Plugins.md](https://github.com/haraka/Haraka/blob/v3/Plugins.md) file. I'll bring that file back into master soon.

**Comment by acharkizakaria** [comment]
Done, should I add the VMTA plugin also to the list ?

**Comment by msimerson** [comment]
Sure, if you think others may find it useful.
