### ISSUE TITLE
Retry option on temp Error (4xx) for outbound delivery

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#1973]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v6.10.3
OS | Linux test-haraka 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

Hi 

I was checking for retry option on temp Error (4xx) for outbound delivery. Not got much information.
Some times we get error "451 4.5.7  try again after some time", and sometimes connection Timed on  MX lookup.
 
Is there any plugin or option can be set for retry on 4xx error for N no. of times with time frequency of Y minute.

Kindly suggest if we can achieve this in Haraka.

Thanks!

**Comment by superman20** [comment]
In the config file outbound.ini, there is a `maxTempFailures` setting that controls how many times Haraka will retry on temp fails (defaulting to 13).  The time is not customizable currently and is automatically determined by the formula:

retry_time (in seconds) = 2^(N+5)
where N = number of failures

So the retry times are 64, 128, 256, 512 seconds...and so on.
