### ISSUE TITLE
"Log" hook

### ISSUE THREAD

**Issue by acharkizakaria** [haraka/Haraka#1974]
Hi guys, Is there any hook for the _log_ ? 

I want to store the HARAKA server log in separated file, for debug purpose, is there any plugin do the trick?

Thanks in advance.

**Comment by msimerson** [comment]
Haraka already logs to a separate file. And there are log plugins that can log to different files, or syslog, or other stores. Can you explain better what you want?

**Comment by superman20** [comment]
Yes, there actually is a "log" hook.  I don't think it is officially documented (at least not [here](https://haraka.github.io/manual/Plugins.html)).  I currently use it to do some custom logging and it works fine.  I register the hook like so:
`plugin.register_hook('log', 'filelog');`
and the prototype of `filelog` is like so:
`exports.filelog = function (next, logger, log_item) `
`log_item` itself is an object that has a member `data` of the actual log entry Haraka wants to make.

**Comment by acharkizakaria** [comment]
Thanks @superman20 your answer is really useful.
