### ISSUE TITLE
'No result' error from dkim_sign, access and data.headers plugins

### ISSUE THREAD

**Issue by wietseva** [haraka/Haraka#1983]
### system info

Haraka | Haraka.js — Version: 2.8.13
 --- | :--- 
Node | v8.1.2
OS | Linux haraka-outbound-deployment-4228847575-1p7b7 4.9.20-std-1 #1 SMP Tue Apr 4 12:56:17 UTC 2017 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1t  3 May 2016

### Expected behavior
Following plugins to handle parse error from address-rfc2822 correctly, and not to exit abruptly
 
- access
- data.headers
- dkim_sign

### Observed behavior
I received `No Result` errors for the above plugins when trying to send an outbound mail. 
I traced the error down to following line in each of the plugins.

access.js
```javascript
exports.data_any = fucntion (next, connection) {
    ...
    var hdr_from = connection.transaction.header.get('From');
    ...
    var hdr_addr = haddr.parse(hdr_from)[0];
    ...
}
```

data.headers.js
```javascript
exports.from_match = fucntion (next, connection) {
    ...
    var hdr_from = connection.transaction.header.get('From');
    ...
    var hdr_addr = (plugin.addrparser.parse(hdr_from))[0];
    ...
}
```

dkim_sign.js
```javascript
exports.get_sender_domain = function (txn) {
    ...
    var from_hdr = txn.header.get('From');
    ...
    var addrs = addrparser.parse(from_hdr);
    ...
}
```

The problem was that the `from header` returns an address with a new line attached to it, which address-rfc2822 fails to parse. 
```
from_hdr = 'Jhon Doe <jhon@example.com>
'
```
#### 1. Trim the 'From' header in each of the plugins
```javascript
var addrs = addrparser.parse(from_hdr.trim());
```
#### 2. Modify the regex that parses the header lines in `mailheader.js`
```javascript
for (let i=0,l=this.header_list.length; i < l; i++) {
    var match = this.header_list[i].match(/^([^\s:]*):\s*([\s\S]*?)(?:\s*)$/);
    ...
}
```
The regex is modified so that trailing white space is excluded from the value of the header.

#### [0]. Surround the parse lines with try catch blocks
Catching the error fixes dkim_sing plugin to correctly return the domain instead of exiting abruptly. 
```javascript 
var addrs
try {
    addrs = addrparser.parse(from_hdr);
} catch (e) {
    plugin.logerror("failed to parse 'From' header")
}
```

**Comment by baudehlo** [comment]
I'll fix that in address-rfc2822.

**Comment by baudehlo** [comment]
$ npm publish
+ address-rfc2822@2.0.1

**Comment by wietseva** [comment]
Thank you for the fast response and quick fix!

**Comment by shurli** [comment]
On Haraka 2.8.16:

Plugin data.headers seems to fail sometimes.
address-rfc2822 plugin throws errors in common use cases.
these errors should be catched in data.headers.js @ line 288

See logline:
2017-10-18T12:49:49.189Z [CRIT] [668C13F7-30CF-4EFF-9A55-C7CD52E88D51.1] [core] Plugin data.headers failed: No results

**Comment by danieltigse** [comment]
In Haraka version 2.8.20 I have this warning:
`[WARN] [CF39BF71-0BBF-4E0F-8389-10FBC773C9DF.1] [data.headers] parsing ""xxx"
 <xxx@xxx.com>" with address-rfc2822 plugin returned error: No results`

is this happens because of the sender? Or is it something that I can handle?

**Comment by msimerson** [comment]
That's a malformed address (pay careful attention to the " marks).
