### ISSUE TITLE
Issue with rcpt_to.access.blacklist

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#1987]
### system info

Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v6.10.3
OS | Linux test-haraka 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

### Expected behavior
Any emailid  removed from rcpt_to.access.blacklist list should not get deny, it should pass for outbound delivery
Any emailid  added to rcpt_to.access.blacklist list should get deny,  This is working

### Observed behavior
Emailid  removed from rcpt_to.access.blacklist list is getting blocked. and not send for outbound delivery. works only if Restart of Haraka
Any emailid  added to rcpt_to.access.blacklist list is  getting blocked,  This is working without haraka restart.

#########

Any changes done in config file, Haraka is reloading the plugin I can see in log which is fine.
[DEBUG] [-] [core] Detected change on rcpt_to.access.blacklist
[DEBUG] [-] [core] Detected change on rcpt_to.access.blacklist
[INFO] [-] [core] Reloading file: /etc/haraka/config/rcpt_to.access.blacklist

I want to implement Realtime Supression List by adding/removing  emailID to config/rcpt_to.access.blacklist file so that email mentioned on List should Blocked and not sent for delivery.

This is working fine if I add emailid to List any time,   But, If i remove any email ID from list, then its not working realtime(its getting blocked) .  If I restart Haraka then only it takes affect and works as expected.  I dont want to restart haraka if  rcpt_to.access.blacklist file gets modified.

Can any one Please Suggest where can i check and how to  fix this.

**Comment by msimerson** [comment]
See #1990

**Comment by msimerson** [comment]
@ajay-psd , please report back after you've tested to confirm that change resolves your issue.
