### ISSUE TITLE
VMTA selection not applied when x-vmta passed to send_email()

### ISSUE THREAD

**Issue by sstevan** [haraka/Haraka#1996]
### VMTA issue with send_email (splitting #1993)

I've enabled VMTA plugin and I can see that configuration is properly loaded:
```
[INFO] [-] [vmta] VMTA configs are fully loaded from 'vmta.ini'.
[INFO] [-] [vmta] { main: {},
  default_01: { ip: '111.111.111.111', host: 'mta01.sample.com' },
  default_02: { ip: '222.222.222.222', host: 'mta02.sample.com' },
  default_03: { ip: '111.111.222.222', host: 'mta03.sample.com' },
```

When I post raw message content with `x-vmta: default_02` to HTTP API ( check #1993)
I don't get proper VMTA selected and `x-vmta` header is not removed. What should I do
to get raw message properly processed?

---

#### Haraka

Stack | Version
------|---------
Haraka | Haraka.js — Version: 2.8.13
Node | v8.0.0
OS | Ubuntu 16.04
openssl | OpenSSL 1.0.2g  1 Mar 2016

**Comment by sstevan** [comment]
Should I move this to plugin repo?
https://github.com/haraka/haraka-plugin-vmta

**Comment by acharkizakaria** [comment]
Please add the full example here with the _raw message content_ that contains the `x-vmta` parameter.

**Comment by baudehlo** [comment]
Yes please move the issue there.

**Comment by acharkizakaria** [comment]
This one was moved and fixed in https://github.com/haraka/haraka-plugin-vmta/issues/4 , could be closed now.

**Comment by sstevan** [comment]
Thank you @acharkizakaria and @baudehlo for the quick resolution. I'd like to know if donations are shared among contributors or should be made individually?

**Comment by baudehlo** [comment]
They are currently not shared. I'd like to find a way to change that (PayPal is obviously not the best way).
