### ISSUE TITLE
Elasticsearch Plugin: failed to parse [count.msg]

### ISSUE THREAD

**Issue by frank-bn** [haraka/Haraka#1998]
### system info

Haraka | Haraka.js — Version: 2.8.13
 --- | :---
Node | v6.10.3
OS | Linux dione 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

**Elasticsearch 5.4.3**

### Expected behavior

Elasticsearch plugin http://haraka.github.io/manual/plugins/log.elasticsearch.html should work when running with default config as documented.

### Observed behavior

Elasticsearch is running fine but Haraka throws constant following errors:
`[log.elasticsearch] [mapper_parsing_exception] failed to parse [count.msg]`

I didn’t get the plugin working.
Is the ES template in the documentation not up-to-date? Sorry, it is my first contact with ES so no idea what the real problem is and how to debug.

### Steps to reproduce

Setup Haraka
Setup Elasticsearch (5.4.3)
Create a ES map template as documented
Enable log.elasticsearch in plugins

**Comment by msimerson** [comment]
> Is the ES template in the documentation not up-to-date?

It's likely one of two issues: The template mapping may be out of date, or the type of count.msg has changed from ES 2 to ES 5. Since I'm not seeing that on my ES 2 cluster, I'm guessing it's an issue between ES 2 and 5. When I get around to updating my ES cluster to v5, this should bubble up and I'll fix it then. Unless someone else dips in first and gets to the bottom of it.

**Comment by msimerson** [comment]
I haven't updated to ES 5 yet but I did get a chance to look again at the error and the map template and I think I have a solution. There's a collision where a field named `msg` exists in two places. It's an array of strings in one and integer in the other. My guess is that ES 5 is more strict, or it applies the template a little differently. Try changing this section of the map template to make it more specific:

```json
                { "msg_results" : {
                        "match" : "msg",
                        "mapping" : {
                            "type" : "string", "index" : "not_analyzed"
                        }
                    }
                },
```

to this:

```json
                { "msg_results" : {
                        "match" : "plugin.*.msg",
                        "mapping" : {
                            "type" : "string", "index" : "not_analyzed"
                        }
                    }
                },
```

And let me know if that works for you.
