### ISSUE TITLE
Haraka doesn't start.

### ISSUE THREAD

**Issue by tmechlinski** [haraka/Haraka#2005]
### system info
FreeBSD 10.3-RELEASE-p18
Haraka | Haraka.js — Version: 2.8.13
Node | v8.1.4
OpenSSL 1.0.1s-freebsd  1 Mar 2016

### Expected behavior
Schould start.

### Observed behavior
[NOTICE] [-] [core] Daemonizing...
[CRIT] [-] [core] TypeError: "cwd" must be a string
[CRIT] [-] [core]     at normalizeSpawnArguments (child_process.js:400:11)
[CRIT] [-] [core]     at Object.exports.spawn (child_process.js:485:38)
[CRIT] [-] [core]     at Function.module.exports.daemon (/usr/local/lib/node_modules/Haraka/node_modules/daemon/index.js:50:31)
[CRIT] [-] [core]     at module.exports (/usr/local/lib/node_modules/Haraka/node_modules/daemon/index.js:25:20)
[CRIT] [-] [core]     at Object.Server.daemonize (/usr/local/lib/node_modules/Haraka/server.js:70:5)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/server.js:486:16
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound.js:165:16
[CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:135:15)

### Steps to reproduce
Restart after update Node.

**Comment by msimerson** [comment]
Looks like there's at least two issues with node v8. For now, downgrade to the node6 package for now.

**Comment by tmechlinski** [comment]
Yes I did it but it's vulenrable  :)

**Comment by msimerson** [comment]
So is node v8 (in ports, as of a day or two ago). ;-)  If you're worried about the vulnerability, then you need to wait a few days (for a prebuilt package to be available) or build from the ports tree.

**Comment by msimerson** [comment]
In case my explanation isn't clear, all active branches of node have been patched. The patch is likely already available in the ports tree (after updating with portsnap) but may not yet be available as a pre-built package.

**Comment by tmechlinski** [comment]
All clear :)

**Comment by msimerson** [comment]
FWIW, I noticed on a PR yesterday that Travis installed node 8.2.1 and the test suite passed, so maybe our version 8 issue with node.js is resolved upstream.

**Comment by msimerson** [comment]
Fixed in node 8.2. See node/node#13938
