### ISSUE TITLE
How to start processing outbound emails from queue folder?

### ISSUE THREAD

**Issue by sstevan** [haraka/Haraka#2007]
Is it possible to start processing messages from `queue` folder after Haraka crash (caused by #1954)?

**Comment by baudehlo** [comment]
It's automatic.

**Comment by sstevan** [comment]
I guess I should see something in output log once I run it with `haraka -c /etc/haraka/`?
Right now it starts (loads each plugin successfully) and the last thing I get is from Spamhaus.
```
[DEBUG] [-] [dnsbl] looking up: 1.0.0.127.zen.spamhaus.org.
[DEBUG] [-] [dnsbl] looking up: 2.0.0.127.zen.spamhaus.org.
```

**Comment by superman20** [comment]
There was a bug related to this in #1940 (...fixed in current Master).  However, it only seemed to be a bug for single process configurations.  Are you single process?

**Comment by sstevan** [comment]
@superman20 Thanks! That did the trick - I've installed Haraka using `npm` - I'll build it from `master` now.
