### ISSUE TITLE
Feature request- Add attachments to outbound.send_email

### ISSUE THREAD

**Issue by cleartext** [haraka/Haraka#201]
Would be great to be able to add attachments to email sent with outbound.send_email.

**Comment by harmansingh2908** [comment]
how to use  mailComposer with haraka for outbounds emails with attachments

**Comment by msimerson** [comment]
> how to use mailComposer with haraka for outbounds emails with attachments

1. generate email message
2. insert in Haraka outbound queue

**Comment by baudehlo** [comment]
Using outbound.send_email()
