### ISSUE TITLE
Communication with Microsoft Outlook

### ISSUE THREAD

**Issue by bibudha** [haraka/Haraka#2029]
Hello

I am using HARAKA for sending and receiving mail using custom domain address. I stored email in Database (MySQL).  So how can I give mail to Microsoft Outlook or any other mail clients.

**Comment by smfreegard** [comment]
Haraka is an SMTP server which is used to inject and transport e-mail.  To allow a client (MUA) to access a mailbox you would need to implement either a POP3 or IMAP server to allow the mails stored in your database to be accessed.   It's not a Haraka function.

**Comment by bibudha** [comment]
Oh i see...thank you...can you suggest which library is best for this type of work ?

**Comment by smfreegard** [comment]
No - it's not something I have any experience with, you're better off Googling it for yourself and looking on npm for Node modules.   There are a few, but POP3 is quite old now and not used so much and IMAP is preferred, but it's a very complicated protocol and your database schema is going to need to be very good to be able to work with it efficiently.   Unless you know a lot about e-mail, I wouldn't recommend trying to create a mailbox server using a database and IMAP server, you'd be better off looking at what already exists and using those e.g. Dovecot, DBMail, Cyrus IMAP etc.
