### ISSUE TITLE
Rspamd headers - too many

### ISSUE THREAD

**Issue by Grucqq** [haraka/Haraka#2044]
### system info

Haraka | Haraka.js — Version: 2.8.14
 --- | :---
Node | v7.10.0
OS | Linux mx15..pl 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

Rspamd daemon version 1.6.3

### Observed behavior
Haraka as relay with smtd_forward (tried with smtp_proxy, smtp_brdge). After enabling rspamd in plugins every email in haraka logs got too many headers (possible mail loop)

**Comment by smfreegard** [comment]
Logs required.  echo LOGDEBUG > config/loglevel and paste an example SMTP session of this happening.

**Comment by Grucqq** [comment]
[log.txt](https://github.com/haraka/Haraka/files/1246009/log.txt)

**Comment by smfreegard** [comment]
I don't think this has anything to do with the rspamd plugin at all.

You've created a mail loop plain and simple.  Inbound mail for your domain is being delivered back to Haraka in a loop.
