### ISSUE TITLE
How to use syslog 

### ISSUE THREAD

**Issue by bibudha** [haraka/Haraka#2046]
Hey I want to debug the haraka incoming mail. How can I debug using your syslog plugin ?

**Comment by KingNoosh** [comment]
Set the log level in config/loglevel to LOG{LEVEL}, so if you want to log `DEBUG` level stuff, set it to LOGDEBUG.
To get to the syslog log file, by default it goes to your syslog's MAIL log file, this is normally in /var/log/mail.log for me, it might differ for you.
