### ISSUE TITLE
can we configure remove all reply content from incoming mail body

### ISSUE THREAD

**Issue by chiragob** [haraka/Haraka#2055]
hi
can we configure remove all reply content from incoming mail body in haraka. 

is any their any way to filter only original message in all mails like 
https://github.com/mailgun/talon

i try with add_body_filter but there is some asynchronous issue came 

```js
exports.hook_data =  async function (next, connection) {
   let plugin = this;
   connection.transaction.parse_body = true;
   
   connection.transaction.add_body_filter(/text\/(html)/, function (ct, enc, buff) {
       let newBuff = null
       let buf = buff.toString('utf-8')

      var url = 'https://localhost:5000/filterHtml/REST-API/'+buf;
      let newBuff1 = null
      rpRequest.get({ uri: url }).then(function(result) {
	    newBuff1 = result
      })
      
     return new Buffer(newBuff1)
   })
   next()
}
```
please help us

**Comment by msimerson** [comment]
You're returning newBuff1 before the async function has returned. At the very least, you need to move your return into the callback from `rpRequest.get`
