### ISSUE TITLE
ES6: replace most uses of var with let or const.

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2065]
Rather than polluting hundreds of PRs over many months to get this done, this should be done in its own PR. Soon.

* [x] add to eslintrc.json
* [ ] add to [haraka-eslint](https://github.com/haraka/haraka-eslint) so it trickles down
    * [ ] in warning mode only. It can't get switched to error until updates have been made everywhere

**Comment by KingNoosh** [comment]
To enforce these rules, we should probably also update .eslint.json to throw an error if someone uses var over let or const.

https://eslint.org/docs/rules/prefer-const
https://eslint.org/docs/rules/no-var

**Comment by baudehlo** [comment]
What's the advantage of doing this wholesale rather than just doing it on
new code or code you edit? There's no performance advantage to let as far
as I've read.

**Comment by msimerson** [comment]
The problem with doing it on code you edit is death by a thousand paper cuts. It makes every future PR larger than necessary and thus harder to review.

Example: #2063 

Due to the `s/var/const/g` change, you can barely tell that I removed several instances of modules that were being loaded twice. Using const prevents those errors from ever getting committed.
