### ISSUE TITLE
outbound: tidy-up __tmp__ files synchronously at master start-up.

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#2068]
From IRC:

EyePulp: Over time I get a fair buildup of aging \_\_tmp\_\_ files in some of my outbound queues.  I've stripped the \_\_tmp\_\_ before and restarted the haraka instance, and it will process the files successfully for the most part.  running 2.8.13 and wondering if others run into this or if I'm causing it.

EyePulp: nice - found a failure right near the UUID in the log -- one of my plugins (whitelist of approved destination address lookup).

_smf_: \_\_tmp\_\_ files shouldn't result in a lost message.

EyePulp:  hot dog - showed up again, and went through unmolested on a different server.  Dang - I should quit now, today can't get more productive than this.

**Comment by analogic** [comment]
Wasn't it already fixed with #2395? Nevertheless I've pushed PR #2593 which does exactly `clean_dot_files` when loading queue

**Comment by analogic** [comment]
Fixed with #2593 see https://github.com/analogic/Haraka/blob/5464aa17d2839428917317215c7cc6444512036f/outbound/queue.js#L79
