### ISSUE TITLE
Add support for MTA-STS (Strict Transport Security)

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#2070]
Related to #779 (DANE support)

MTA-STS is a 'lite' version of DANE where the domain cannot or does not want to use DNSSEC. 
Some large providers are already publishing records (albeit in 'report' mode):

`````
[root@mail1-ewh Haraka]# grep check_mta_sts /var/log/maillog | grep v=STS | grep -Po 'domain=\S+'  | sort | uniq -c | sort -rn
     34 domain="gmail.com"
      4 domain="yahoo.com"
      4 domain="comcast.net"
      3 domain="mail.com"
      2 domain="web.de"
      1 domain="gmx.com"
`````

Currently an RFC draft: https://tools.ietf.org/html/draft-ietf-uta-mta-sts-08

**Comment by msimerson** [comment]
Migrated to [wiki](https://github.com/haraka/Haraka/wiki)
