### ISSUE TITLE
es6: use destructuring assignment

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2075]
replace instances of code like this:

```js
var res = /some/fancy/regex/.exec(something);
if (res[1]) .....
if (res[2]) ....
```

with:

```js
const [ , well, named, variables]  = /some/fancy/regex/.exec(something);
...
if (well || named) ...
```

**Comment by romainwn** [comment]
Hi, I would liketo work on this ! starting the PR's from October 1st :)

**Comment by KingNoosh** [comment]
@romainwn No problem, please could you do a PR per file you update? This is to make it easier for us to review them.

Thanks!

**Comment by shabbir1993** [comment]
Hello, Can I work on this ???

**Comment by romainwn** [comment]
@shabbir1993 sure !
