### ISSUE TITLE
beta releases

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2078]
We got out of publishing beta releases of Haraka when NPM broke the old way with special release numbers. The current way to do releases that users don't get them automatically when they type `npm i Haraka` is with [tags](https://docs.npmjs.com/cli/publish):

`npm publish --tag=beta`

Because npm installs only `--tag=latest` by default, we can bump the version in package.json, release beta version(s), and when we're ready, `npm publish --tag=latest`. Example:

`npm publish --tag=beta1`   // only visible as Haraka@beta1
`npm publish --tag=beta2`
`npm publish --tag=beta3`
`npm publish`  // implicit --tag=latest

I don't see a ton of value in beta releases because its so dreadfully easy to `npm install haraka/Haraka#[branch | commit id]`. Thoughts?

**Comment by baudehlo** [comment]
Seems like more work for us with little gain.
