### ISSUE TITLE
Investigate the use of the codependency for v3.0 to reduce installation size

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#2080]
Currently - a completely stock installation of Haraka means a node_modules folder of around 88M:

smf@i7desktop:~/test/Haraka$ du -h -s node_modules/
88M	node_modules/

This is mostly because we're having to pull in all the plugins that have been converted to npm modules to maintain compatibility and because all the devDependencies are pulled in when you run `npm install` with no arguments.

Running `npm install --no-optional --no-shrinkwrap --only=production` yields a node_modules folder of around 19Mb which is a reduction of ~78%.

This could be further reduced by removing other plugins such as haraka-plugin-access and haraka-plugin-limit which are currently listed as requirements.

lodash (4.9Mb) which is required by `async` and iconv (9Mb) are the largest remaining modules.

For 3.0 we could look at using the [codependency](https://www.npmjs.com/package/codependency) module to gracefully handle this and all of the plugins available can be listed in optionalPeerDependencies instead and the user prompted to install any missing requirements at start-up.

**Comment by msimerson** [comment]
I'm +1 on moving the remaining plugins from deps to optional immediately. I've been doing that by default for all the newer plugins I've converted to modules.

**Comment by baudehlo** [comment]
Is install size a problem? What's the downside?

**Comment by smfreegard** [comment]
> Is install size a problem? What's the downside?

No - not particularly although 88Mb is rather high though.  I'd just like the install to be as small as possible for v3, so only core should be downloaded without any additional plugins or dependencies.  Currently all the plugins-as-modules are downloaded regardless as to whether they're wanted or not.

**Comment by msimerson** [comment]
88MB is the high water mark and a bit of a red herring. A more typical production install is less than half that:
````
$ npm install --production Haraka && du -d1 -h .
<snip>
 37M	./node_modules
 37M	.
````

As you rightfully pointed out, for those who care about 37M being pudgy, there's always `--no-optional`:

````
npm install --production --no-optional Haraka && du -d1 -h .
24M	./node_modules
24M	.
````

In my mind, that doesn't rise to the "we should do something about that" level.

**Comment by baudehlo** [comment]
Yeah our app at $dayjob is 190M and I'm not worried about it.

**Comment by msimerson** [comment]
Discussion seems to be concluded.
