### ISSUE TITLE
Replace exponential backoff for outbound pool exhaustion

### ISSUE THREAD

**Issue by adelphes** [haraka/Haraka#2084]
When the outbound connection pool is exhausted, additional outbound messages are held and delayed using the same exponential backoff rate (min 64 seconds, doubling each time) as a connection error.

When sending a batch of emails, this frequently leads to the pool going from completely used to completely available after a few seconds and then left idle, waiting for the timeout to expire before batch-sending again (causing the pool to be immediately exhausted again, longer backoffs, etc). This can potentially cause a very long delay (minutes) before messages are finally sent, even though the connection pool is mostly idle during this time.

Although a quick solution is to arbitrarily increase the maximum pool size, it would be much better for released pool connections to be made immediately available to any waiting outbound requests (the exponential backoff should really only apply to connection retries where we have actively attempted a connection to a server and don't want to be retrying for some time).

**Comment by msimerson** [comment]
baudehlo mentioned on #haraka, [simple-redis-safe-work-queue](https://www.npmjs.com/package/simple-redis-safe-work-queue), as a potential solution. (Also mentioned: async.queue and QEWD.)

**Comment by msimerson** [comment]
and [bee-queue](https://github.com/bee-queue/bee-queue)

**Comment by msimerson** [comment]
Referenced and added to [Outbound Improvements](https://github.com/haraka/Haraka/wiki/Outbound-Improvements)
