### ISSUE TITLE
Cannot create plugin with subdirectory within command line

### ISSUE THREAD

**Issue by KingNoosh** [haraka/Haraka#2087]
### system info

Haraka | Haraka.js — Version: 2.8.14
 --- | :--- 
Node | v6.10.0
OS | Darwin Anoshs-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
openssl | OpenSSL 0.9.8zh 14 Jan 2016

### Expected behavior

`haraka -c . -p foo/bar` to produce:

 - `./plugins/foo/bar.js`
 - `./docs/plugins/foo/bar.md`

```
Plugin foo/bar created
Now edit javascript in:    /Users/anoshmalik/Workspace/HarakaTest/plugins/foo/bar.js
Add the plugin to config:  /Users/anoshmalik/Workspace/HarakaTest/config/plugins
And edit documentation in: /Users/anoshmalik/Workspace/HarakaTest/docs/plugins/foo/bar.md
```

### Observed behavior

`haraka -c . -p foo/bar` to doesn't produce:

 - `./plugins/foo/bar.js`
 - `./docs/plugins/foo/bar.md`

```
warning: Unable to create file: Error: ENOENT: no such file or directory, open '/Users/anoshmalik/Workspace/HarakaTest/plugins/foo/bar.js'
warning: Unable to create file: Error: ENOENT: no such file or directory, open '/Users/anoshmalik/Workspace/HarakaTest/docs/plugins/foo/bar.md'
Plugin foo/bar created
Now edit javascript in:    /Users/anoshmalik/Workspace/HarakaTest/plugins/foo/bar.js
Add the plugin to config:  /Users/anoshmalik/Workspace/HarakaTest/config/plugins
And edit documentation in: /Users/anoshmalik/Workspace/HarakaTest/docs/plugins/foo/bar.md
```

### Steps to reproduce

Run `haraka -c . -p foo/bar`.

**Comment by msimerson** [comment]
You do know we're encouraging everyone to use NPM packaged plugins, right?

**Comment by smfreegard** [comment]
> You do know we're encouraging everyone to use NPM packaged plugins, right?

Not everyone needs to deploy their plugins as npm packaged modules though.

If you want to create a local plugin then `haraka -c /etc/haraka -p my_cool_plugin` is a good way for a newbie to get boilerplated files to start writing one, so it should work.
