### ISSUE TITLE
Use the available multipart content-type to add HTML code to bounces

### ISSUE THREAD

**Issue by Bramzor** [haraka/Haraka#2090]
### system info

Haraka | Haraka.js — Version: 2.8.14
 --- | :--- 
Node | v8.4.0
OS | Linux devs01.spamfree.io 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior

Noticed that although the bounces have the type: "Content-Type: multipart/report; report-type=delivery-status;", it is currently not possible to add an HTML part in the bounce like Gmail does for example. Making it more easy to view the bounce and possibly even add the mail itself to the bounced message as attachment?

### Observed behavior

Ugly bounce that misses headers which has been logged +1 year ago in issue #1688 
Also the content of the bounced mail could be added to the bounce itself?

### Steps to reproduce

Trigger a bounce.
For example by creating an email forward (using aliases) to an email address that does not exist.

**Comment by smfreegard** [comment]
> Also the content of the bounced mail could be added to the bounce itself?

This isn't a great idea IMO - this would create a security issue in the form of a reflection attack.

e.g. find a Haraka system using https://censys.io/ipv4?q=Haraka that does not reject invalid recipients at RCPT TO time.  Intentionally send it a message to an invalid user and spoof the MAIL FROM as the target address you want to send a payload to.   Then either send spam or malware as the message body.

The Haraka system will then generate a bounce message with the complete message in the bounce to the target system....

**Comment by Bramzor** [comment]
A lot of vendors do send the mail with the bounce as an attachment or as content but I get your point. Can leave that point out of the issue than. For the HTML mail itself, I already have it working on my code here so I will see if I can create a pull request for it.

**Comment by smfreegard** [comment]
> A lot of vendors do send the mail with the bounce as an attachment

Indeed - it's a disaster that's waiting to happen, so I'd rather we avoid it now than with regrets later.

> For the HTML mail itself, I already have it working on my code here so I will see if I can create a pull request for it.

That would be great!  Thank you.

**Comment by Bramzor** [comment]
Pull request is created but I'm unable to test the code myself. If I try to git clone my own fork and npm install packages.json, I don't get all the plugin packages like I do get when doing npm install Haraka for some reason. Code was tested on my own version and working. Just need someone to test it.
