### ISSUE TITLE
Add hook_fork so plugins can fork their own workers.

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#2099]
This is to fix an annoyance I have on my spam trap.   I start up a bunch of HTTP proxies in `hook_init_master` which starts the listeners etc.

The problem with this is that if one of them crashes, then it completely brings down Haraka as the master process dies.   It's also sub-optimal from a performance standpoint as the master is then dealing with some really busy sockets.

I can't put the HTTP listeners in `hook_init_child` because the sockets are so busy it affects SMTP handling as the event-loop becomes saturated.

So I'd like to look into a way of creating a `hook_fork` which when run under cluster would fork `nodes=` children, assign their `process.title` to the plugin name and then manage respawning them.

**Comment by msimerson** [comment]
moved to ideas section of [wiki](https://github.com/haraka/Haraka/wiki)
