### ISSUE TITLE
Receiving duplicate emails. 

### ISSUE THREAD

**Issue by konalm** [haraka/Haraka#2114]
Hello. 

I am currently using Haraka to receive emails to my smtp server however I am continuously receiving duplicate messages multiple times and eventually the email sender will receive the following message from gmail;

Delivery incomplete
--
There was a temporary problem delivering your message to johndoe@gmail.com. Gmail will retry for 21 more hours. You'll be notified if the delivery fails permanently.

I currently believe this is because I am not using the smtp forward plugin to forward these email as I do not wish to forward the emails being received and the mail server is led to believe that sending the message has failed. I am looking for a solution where i could possible inform the mail server that the sent message is okay to avoid it continuously resending the same email. Is this possible ? and If yes could somebody point me in the correct direction. 

Thank you.

**Comment by smfreegard** [comment]
There could be all sorts of reasons for this.  You'll need to supply some logs showing the delivery attempts for one of these messages.

It's unlikely to be to do with anything related to smtp_forward.

The only time you can get duplicates is if the sending host doesn't receive the end of message dot, but Haraka thinks it has sent it.  It's usually caused by network issues (e.g. Path MTU failures, Cisco protocol inspection) or timeouts.   It's therefore impossible to tell without logs to determine what is happening.

**Comment by konalm** [comment]
[NOTICE] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] sender <connorlloydmoore@gmail.com> code=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running rcpt hooks
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running rcpt hook in access plugin
[DEBUG] [-] [access] empty file: rcpt_to.access.whitelist_regex
[DEBUG] [-] [access] empty file: rcpt_to.access.blacklist_regex
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=rcpt plugin=access function=rcpt_to_access params="<connor@codegood.co.readstalk.com>" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running rcpt hook in access plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=rcpt plugin=access function=any params="<connor@codegood.co.readstalk.com>" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running rcpt hook in rcpt_to.in_host_list plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [rcpt_to.in_host_list] Checking if version 2 <connor@codegood.co.readstalk.com> host is in host_list
[DEBUG] [-] [rcpt_to.in_host_list] checking codegood.co.readstalk.com in config/host_list
[DEBUG] [-] [rcpt_to.in_host_list] checking codegood.co.readstalk.com against config/host_list_regex
[INFO] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=rcpt plugin=rcpt_to.in_host_list function=hook_rcpt params="<connor@codegood.co.readstalk.com>" retval=OK msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running rcpt_ok hooks
[NOTICE] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] recipient <connor@codegood.co.readstalk.com> code=OK msg="" sender="connorlloydmoore@gmail.com"
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data hooks
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data hook in mail_handler plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data plugin=mail_handler function=hook_data params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data hook in debug plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data plugin=debug function=hook_data params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hooks
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in access plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=access function=data_any params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in mail_handler plugin
[INFO] [-] [mail_handler] <--------- NEXT ------->
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=mail_handler function=hook_data_post params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in debug plugin
[INFO] [-] [debug] MAIL HANDLER PLUGIN DETECTED $$$$$$$$$$
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] logdebug MAIL HANDLER PLUGIN DETECTED $$$$$$$$$
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=debug function=hook_data_post params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=duplicate_singular params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=missing_required params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [data.headers] message date: Thu, 14 Sep 2017 15:11:20 +0100
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=invalid_date params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=invalid_return_path params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=user_agent params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=direct_to_mx params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=from_match params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=delivered_to params="" retval=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running data_post hook in data.headers plugin
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] hook=data_post plugin=data.headers function=mailing_list params="" retval=CONT msg=""
[NOTICE] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] message mid="<CAOVmGBhQmmJqnAJTcBTG88TinzRK8WB9DxWX-6fvkWj+V6+Qvg@mail.gmail.com>" size=2423 rcpts=1/0/0 delay=0.58 code=CONT msg=""
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running queue hooks
[NOTICE] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] queue code=CONT msg=" (D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1)"
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running reset_transaction hooks
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running quit hooks
[DEBUG] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] running disconnect hooks
[NOTICE] [D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1] [core] disconnect ip=209.85.161.171 rdns="mail-yw0-f171.google.com" helo="mail-yw0-f171.google.com" relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=2423 lr="451  (D9D84641-AC54-4DE1-A784-B4DD01BAD67C.1)" time=1.219

**Comment by konalm** [comment]
[NOTICE] [-] [core] Listening on :::25
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
[NOTICE] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A] [core] connect ip=209.85.161.171 port=49125 local_ip=:: local_port=25
[INFO] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A] [helo.checks] helo_host: mail-yw0-f171.google.com, ips: 209.85.161.171, pass:match_re, bare_ip, dynamic, big_co(not), literal_mismatch, valid_hostname, rdns_match, forward_dns, host_mismatch
[NOTICE] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1] [core] sender <connorlloydmoore@gmail.com> code=CONT msg=""
[INFO] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1] [core] hook=rcpt plugin=rcpt_to.in_host_list function=hook_rcpt params="<connor@codegood.co.readstalk.com>" retval=OK msg=""
[NOTICE] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1] [core] recipient <connor@codegood.co.readstalk.com> code=OK msg="" sender="connorlloydmoore@gmail.com"
[INFO] [-] [mail_handler] <--------- NEXT with return ------->
[INFO] [-] [mail_handler] <!-- DONE --!>
[INFO] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1] [core] hook=data_post plugin=mail_handler function=hook_data_post params="" retval=OK msg=""
[NOTICE] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1] [core] message mid="<CAOVmGBgp+_q0kBL6U0CLLSoQHu7fjB0txngyrbuhPSS3q4s=3A@mail.gmail.com>" size=2398 rcpts=1/0/0 delay=1.478 code=OK msg=""
[NOTICE] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1] [core] queue code=CONT msg=" (9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1)"
[NOTICE] [9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1] [core] disconnect ip=209.85.161.171 rdns="mail-yw0-f171.google.com" helo="mail-yw0-f171.google.com" relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=2398 lr="451  (9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1)" time=2.176

**Comment by smfreegard** [comment]
I think you'll need to up your debug level - try `echo LOGDEBUG > config/loglevel` and try again so I can see better output.

I can see from the above, that something is deferring the message, but isn't outputting a reason:

451 (9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1)

Have you modified Haraka in any way and what is `mail_handler` doing (as that isn't one of our plugins)?

**Comment by konalm** [comment]
Appears to be empty:

[root@pipe /]# echo LOGDEBUG > /etc/haraka/config/loglevel
[root@pipe /]#

**Comment by msimerson** [comment]
> 451 (9E5BFD8E-6B61-4314-8629-0BD2B33B502A.1)

I've seen that. It happens when no queue plugin returns OK.

**Comment by konalm** [comment]
Is it possible to work without a queue plugins ? As i do not wish to forward the email

**Comment by smfreegard** [comment]
> Is it possible to work without a queue plugins ? As i do not wish to forward the email

No - and that isn't what hook_queue does.

I think I can now guess what is happening here.   You're (incorrectly) sending the mail to it's destination in the mail_handler plugin that you have created.

Don't do that - change `exports.hook_data_post = ...` in your plugin to `exports.hook_queue = ...` and make sure that once your plugin successfully handles the message that you `return next(OK, 'Message accepted with id <some identifier>');`

`hook_queue` doesn't queue the mail, it's just a hook in the SMTP transaction where you handle the message and tell the remove system that you've handled the message so that it can delete the message from it's queue.

You appear to be handling the message in hook_data_post - which is wrong, data_post is designed solely to process the message (e.g. virus scanning or spam scanning etc.).

**Comment by konalm** [comment]
You Sir are a life saver ! Thank you very much.

**Comment by smfreegard** [comment]
No problem - glad you got it all working.
