### ISSUE TITLE
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection error: Error: bind EADDRNOTAVAIL

### ISSUE THREAD

**Issue by rccess** [haraka/Haraka#2123]
### system info

Hello Everyone , 

I am using Haraka V 2.8.15 with Node V 8.5.0 on centos 6.5 

i am getting following error on outbound sending , i have tried it already with other version of node but issue is still same 

Here is the logs
*************************************************************
[NOTICE] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1] [core] message mid=<1506168056902260.59c64cf850088@lucahfost.com> size=633 rcpts=1/0/0 delay=1.528 code=CONT msg=""
[INFO] [-] [core] [smtp_client_pool] [2555:localhost:300] dispense() clients=1 available=0
[INFO] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1] [queue/smtp_forward] forwarding to localhost:2555
[ERROR] [-] [core] backend failure: localhost:2555 - FC8D01A6-A845-436B-A9FF-2AE2BC4BD934: [localhost:2555] SMTP connection errored Error: getaddrinfo ENOTFOUND localhost localhost:2555
[NOTICE] [-] [db] {"event":"processed","timestamp":"2017-09-23T12:00:59.281Z","email":"<lucas.f@angelic.com>","host":"angelic.com","uuid":"66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1","message_id":"<66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1@center.xxxxxppp.net; auth=pass (cram-md5)>"}
[NOTICE] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1] [core] queue code=CONT msg=" (66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1)"
[INFO] [-] [core] [outbound] Sending email as a transaction
[INFO] [-] [core] [outbound] Processing domain: angelic.com
[NOTICE] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1] [core] queue code=OK msg="Message Queued"
[INFO] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1.1] [outbound]  hook=get_mx plugin=dedicate_ip function=hook_get_mx params=angelic.com retval=OK msg="[object Object],[object Object]"
[INFO] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1.1] [outbound] Looking up A records for: mx01.mail.com
[INFO] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1.1] [outbound] Attempting to deliver to: 74.208.5.22:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:74.208.5.22:149.56.183.12:50] dispense() clients=1 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection error: Error: bind EADDRNOTAVAIL 149.56.183.12
[INFO] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1.1] [outbound] Looking up A records for: mx00.mail.com
[INFO] [-] [core] [outbound] [outbound::25:74.208.5.22:149.56.183.12:50] dispense() clients=0 available=0
[NOTICE] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1] [core] disconnect ip=181.215.104.248 rdns=NXDOMAIN helo=domain.com relay=Y early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=633 lr="" time=2.941
[INFO] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1.1] [outbound] Attempting to deliver to: 74.208.5.20:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:74.208.5.20:149.56.183.13:50] dispense() clients=1 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection error: Error: bind EADDRNOTAVAIL 149.56.183.13
[NOTICE] [-] [db] {"event":"deferred","timestamp":"2017-09-23T12:00:59.334Z","email":"<lucas.f@domain.com>","host":"angelic.com","uuid":"66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1.1","delay":64,"err":"Tried all MXs"}
[INFO] [66E08CD4-47AB-4950-9FC2-BE44A4F2C7DD.1.1] [outbound] Temp failing 1506168059284_1506168059284_0_16176_BhUfr1_1_center.domain.net for 64 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::25:74.208.5.20:149.56.183.13:50] dispense() clients=0 available=0

******************************************************************************
Note : it binding with other ips which i don't have in my server (149.56.183.12, 149.56.183.13,149.56.183.14, 149.56.183.15)

Please help for the same

Thanks

**Comment by smfreegard** [comment]
> Note : it binding with other ips which i don't have in my server

No it isn't.  You can't bind to an address that you don't have configured on an interface - this simply isn't possible and that is why it is failing.

You must add any addresses that you wish to send mail from to a valid interface otherwise the kernel will return EADDRNOTAVAIL   The only other time you can get this error is if you are generating a lot of traffic and are running out of ephemeral ports - see http://www.toptip.ca/2010/02/linux-eaddrnotavail-address-not.html
