### ISSUE TITLE
Error getting on Running Haraka  in  Daemonizing , TypeError: "cwd" must be a string

### ISSUE THREAD

**Issue by rccess** [haraka/Haraka#2125]
I am using Haraka V2.8 with node 8.5.0 

and running in  Daemonizing mode but getting error 

the logs are following
**************************************************
[CRIT] [-] [core] TypeError: "cwd" must be a string
[CRIT] [-] [core]     at normalizeSpawnArguments (child_process.js:400:11)
[CRIT] [-] [core]     at Object.exports.spawn (child_process.js:487:38)
[CRIT] [-] [core]     at Function.module.exports.daemon (/usr/local/lib/node_modules/Haraka/node_modules/daemon/index.js:50:31)
[CRIT] [-] [core]     at module.exports (/usr/local/lib/node_modules/Haraka/node_modules/daemon/index.js:25:20)
[CRIT] [-] [core]     at Object.Server.daemonize (/usr/local/lib/node_modules/Haraka/server.js:74:5)
[CRIT] [-] [core]     at Object.Server.createServer (/usr/local/lib/node_modules/Haraka/server.js:296:16)
[CRIT] [-] [core]     at Object.<anonymous> (/usr/local/lib/node_modules/Haraka/haraka.js:76:8)
[CRIT] [-] [core]     at Module._compile (module.js:624:30)
[CRIT] [-] [core]     at Object.Module._extensions..js (module.js:635:10)
[CRIT] [-] [core]     at Module.load (module.js:545:32)

***********************************************************************
Note : i already go through the same issue posted by another one 
https://github.com/haraka/Haraka/issues/2005
but Not worked for me, i don't want to downgrade node version

Please advise

Thanks

**Comment by msimerson** [comment]
This is related to #2036

**Comment by msimerson** [comment]
Please try the patch in #2126

**Comment by msimerson** [comment]
@rccess , did you get a chance to try my patch?

**Comment by rccess** [comment]
i am new at github #2126 getting complex to me due more engagement in the comment , please clear again here , thanks in advance
