### ISSUE TITLE
New loglevel "emerg" is invalid

### ISSUE THREAD

**Issue by tknecht** [haraka/Haraka#2127]
### system info

```
Docker Base Image: node:alpine
Haraka | Haraka.js — Version: 2.8.15
 --- | :---
Node | v8.5.0
OS | Linux haraka-alpine-1 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 Linux
openssl | OpenSSL 1.0.2k  26 Jan 2017
```

### Expected behavior

If "emerg" is a loglevel it should not fail when used.

### Observed behavior

When setting loglevel to "emerg" in log.ini the following happens in Haraka:

```
loglevel: EMERG
[DEBUG] [-] [core] Returning boolean false for main.timestamps=false
invalid loglevel: emerg defaulting to LOGWARN
log format: DEFAULT
```

### Steps to reproduce

log.ini

```
[main]

; level=data, protocol, debug, info, notice, warn, error, crit, alert, emerg
level=emerg

; prepend timestamps to log entries? This setting does NOT affect logs emitted
; by logging plugins (like syslog).
timestamps=false

;  format=default, logfmt
format=default
```

**Comment by KingNoosh** [comment]
You're lucky I just faced this issue the moment you posted it, I'm putting in a PR now

**Comment by tknecht** [comment]
he he good timing. ;)

Not a big issues, but should be fixed at least for cosmetics :) Thanks.

**Comment by KingNoosh** [comment]
I fixed it in https://github.com/haraka/Haraka/pull/2128, I'm going to finish off the PR when I get home though. ;)
