### ISSUE TITLE
ES6: Replace string concatenations with template literals

### ISSUE THREAD

**Issue by KingNoosh** [haraka/Haraka#2129]
We currently use string concatenations all over the codebase, easily found whenever we try to log something.

It is currently known that template literals are more efficient than string concatenation.

To make the codebase just that bit neater, we'd like to receive pull requests PER file of transforming string concatenations to template literals.

If you have any questions, drop them in the comments. 🎃

**Comment by kajes** [comment]
I'll start working on this.

**Comment by KingNoosh** [comment]
Thanks @kajes, if you're doing this in the hopes for Hacktoberfest, remember that only pull requests from the 1st of October will be counted by GitHub.

And remember that we want ONE easily reviewable pull-request per file. :)

**Comment by kajes** [comment]
Well, given the amount of concatenations on my first look, I don't expect to make a pull request before the 1st of october anyway ;). Already gone through som of the files though. I'll keep a fork with my commits until I've gone through everything at least once.

**Comment by SamuelGrave** [comment]
can I help on that issue too?

**Comment by KingNoosh** [comment]
@kajes make sure it's one file per PR ;)
@SamuelGrave go ahead, fork, branch, pick a file, change it, commit it, push it, create a pr we'll will review

**Comment by baudehlo** [comment]
Why one file per pr?

**Comment by KingNoosh** [comment]
It's more to make the PRs easier to review. That last const/let PR was
pretty painful to go through.

**Comment by jattoabdul** [comment]
i would also like to join on this too. Will go through the codebase and start on OCT 1st. Hopefully it will make me happy and fulfilled as my birthday is OCT 3rd.

**Comment by KingNoosh** [comment]
Go ahead, just put in a PR and we'll review it!
No need to keep asking for permission. 😃

**Comment by PSSGCSim** [comment]
Calling dibs on haraka/haraka-config if possible :smile_cat:

**Comment by shabbir1993** [comment]
I will work on it...

**Comment by martypowell** [comment]
@KingNoosh what else if left, I can contribute.

**Comment by mtrivera** [comment]
@KingNoosh I'm currently working on dkim.js

**Comment by pvsousalima** [comment]
@KingNoosh  I am working on logger.js

**Comment by pvsousalima** [comment]
I got plugins/clamd.js !

**Comment by Hari70a** [comment]
@pvsousalima 
Can I change this file and give a PR on this

**Comment by Hari70a** [comment]
@pvsousalima 
I have change this file and made a PR.Can u please review it #2234
