### ISSUE TITLE
ES6: Replace current classes with ES6 classes

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#2133]
Currently all our classes in Haraka use the old style function declaration then adding `Name.prototype.method = function (...) { ... }` methods to them.

The plan would be to use ES6 `class` declarations instead.

This is a hacktoberfest ticket, so please don't submit PRs until after Oct 1st.

All PRs should be one file per PR to make it easier for us to review (it also gets you to 4 PRs faster, so double bonus!).

**Comment by MuraraAllan** [comment]
i will be working on it. Starting with connection.js. After 1 OCT i will make the PR (respecting 1 file per PR).  As soon as i finish a file i ask for another.
There are bunch of functions to convert guys, don't be intimidate. I'm at IRC if you are willing to help in the conversion and need some support.

**Comment by MuraraAllan** [comment]
For functions like setupClient i suggest turn into fat arrow scope too, what do you think about it?

**Comment by mdew192837** [comment]
What's your IRC nick @MuraraAllan ?

**Comment by MuraraAllan** [comment]
muraraallan

**Comment by pvsousalima** [comment]
I can help with this!

**Comment by MuraraAllan** [comment]
Working over spf.js

**Comment by rw251** [comment]
ES6 classes allow use of getters and setters. If a class property appears to be a 'getter' should it be set as such? E.g. the 'length' property in outbound/timer_queue.

This does mean that other files would need updating as getting the length of the timerqueue would change from `timerqueue.length()` to `timerqueue.length`.

**Comment by baudehlo** [comment]
We can do that another time.

**Comment by Hari70a** [comment]
@msimerson  and @baudehlo 
Is this issue still persists.Also could u please tell me if some files is still pending.If so, Iam eager to do.Can u help me on this

**Comment by andela-ieyo** [comment]
How do I get involved in this. Would love to contribute to this project.

**Comment by KingNoosh** [comment]
Pick a file that needs updating, update it. If you can't find any, I'll try
to help locate one for you.

More specifically, fork this repository, clone it, branch, make changes,
make pull request, get reviewed, get merged.

Happy Hacktoberfest!
🎃🎃🎃
