### ISSUE TITLE
Question : limit outbound mails per minute

### ISSUE THREAD

**Issue by MatthieuHPP** [haraka/Haraka#2172]
Hi,

I am using Haraka since 2 months now and It is a pleasure to use this great tool.

I would like to limit the rate of emails that can be sent each minute by the server. I have not found any plugin doing this... I think I am missing something, is their a plugin doing this ?

Many thanks for your help

Matthieu

**Comment by msimerson** [comment]
[haraka-plugin-limit](https://github.com/haraka/haraka-plugin-limit) has the only option for limiting. If the outbound limit there isn't sufficient, create an issue in that repo.
