### ISSUE TITLE
Base64 decoding appears to truncate data in some cases.

### ISSUE THREAD

**Issue by atheken** [haraka/Haraka#2180]
This issue was noted in "attachment" parsing, but applies equally to "body text" processing.

Haraka appears to parse base64 content line-by-line, and assembling the buffer of each line and then emitting the full data:

https://github.com/haraka/Haraka/blob/b310442c30eb2ebaa81c37838a72a083f7b7861a/mailbody.js#L381

When line lengths are not evenly divisible by `8/6`, this technique, when combined with node's `new Buffer(line, 'base64')` constructor can lead to data truncation.

Why `8/6`? Typically, `base64` data is broken with 76 chars of base 64 data, and a `\r\n` per line in a MIME part. This is in accordance with the recommendation in RFC 2822. Each character of a base64 encoded string carries 6 bits of data. When nodejs decodes this as a buffer, incomplete bytes are dropped.

However, RFC 2822 does not _require_ that base64 lines always be 76 chars, lines are sometimes encoded with fewer chars per line. So, for example, a message folds base64 lines every 75 chars, we'll end up with nodejs "trimming" 2 bits per line.

The way to correct for this is to capture all of the base64 lines before doing a single node buffer decode. This would also be beneficial, because if there are other filters, Haraka currently "reassembles" the base64 from the constituent line buffers.

Please let me know if you agree with this analysis, and if you'd be open to a patch to resolve it.

**Comment by baudehlo** [comment]
That would defeat the purpose of being able to stream extremely large
attachments, which I need.

**Comment by atheken** [comment]
Are you aware of a requirement in the RFCs that base64 lines be exactly 76 chars? In that case, I'd be happy to close this issue. I guess I'm not sure if you're agreeing that this is an actual problem or not, just that my proposed solution isn't acceptable.

The other way to do it would be to keep the "remainder" when lines would get truncated and to stream that extra byte when the rest of the data becomes available. This would resolve the truncation issue, and preserve streaming, while adding a slight amount of complexity.

**Comment by baudehlo** [comment]
I'm agreeing it's a potential problem, just we can't buffer the whole thing
in memory.

**Comment by msimerson** [comment]
> The other way to do it would be to keep the "remainder" when lines would get truncated and to stream that extra byte when the rest of the data becomes available. This would resolve the truncation issue, and preserve streaming, while adding a slight amount of complexity.

This is how it's normally done in streaming environments. That seems a prudent approach here.

**Comment by atheken** [comment]
Here's a marginally hackish way to deal with this that is not intrusive:

```
Body.prototype.decode_base64 = function (line) {
    //number of bytes encoded in this line
    var toProcess = this.decode_remainder + line.trim();
    var emitLength = toProcess.length;
    var remainderLength = 0;
    // Not elegant at all...
    while (emitLength * (6 / 8) != Math.floor(emitLength * (6 / 8))) {
        remainderLength++;
        emitLength--;
    }
    
    if (emitLength > 0) {
        var emitNow = toProcess.substring(0, emitLength);
        this.decode_remainder = toProcess.substring(emitLength);
        return new Buffer(emitNow, 'base64');
    } else {
        // this is the end of the base64 data, we don't really have enough bits
        // to fill up the bytes, but that's because we're on the last line, and ==
        // might have been elided
        return new Buffer(toProcess, 'base64');
    }    
};
```

I would be happy to add some tests and package this up as a PR if you all are interested.

FWIW, I think that certain text encodings in QP might exhibit similar boundary problem, as unicode normalization might cause a character to be "fixed" when each line is processed separately. I haven't really researched that issue, or how something like Iconv would affect it.

**Comment by atheken** [comment]
Actually, that snippet probably has several bugs, but if you are interested in the changes I'll work on it more, and package it up as a PR.

**Comment by baudehlo** [comment]
Yes we are interested.

**Comment by msimerson** [comment]
Please do! And if you include a test that fails when presently, and works with your modifications, you get bonus stickers on your PR.

**Comment by atheken** [comment]
As it turns out, the parameter "line" was assumed to be a single line, but when the root part is a text part, the base64 data can include `[\r\n]*` - this will cause this fix to break and/or drop data. I'll submit a patch to resolve this, shortly.
