### ISSUE TITLE
Haraka throws exception when local hostname includes underscores

### ISSUE THREAD

**Issue by andris9** [haraka/Haraka#2225]
Haraka generates queue filenames based on [hostname](https://github.com/haraka/Haraka/blob/38d62f545d73653ede0abc950ae24757c928b8ea/outbound/qfile.js#L3) and joins separate parts with underscores. If the local hostname is configured to include underscore as well (eg "example_host" – not sure if it is even valid but it happens) then this underscore also gets included in the filename which results in a failed [filename check](https://github.com/haraka/Haraka/blob/38d62f545d73653ede0abc950ae24757c928b8ea/outbound/qfile.js#L53-L56) which in turn is causes an [exception to be thrown](https://github.com/haraka/Haraka/blob/38d62f545d73653ede0abc950ae24757c928b8ea/outbound/hmail.js#L52). Easy fix would be to replace underscore with a codepoint as is done with "/" and ":" but maybe something more thorough should be considered? Like replacing all non-alphanumeric chars with codepoints?

**Comment by smfreegard** [comment]
Hostnames containing underscores are illegal in DNS anyway IIRC.

**Comment by andris9** [comment]
I had this issue when trying to run Haraka in a fresh Linode server. It turns out Linode servers (or at least some of these) have the local hostname set to "example_hostname" by default.

**Comment by baudehlo** [comment]
Illegal in DNS but we should escape them anyway.
