### ISSUE TITLE
"[core] [NOTICE] - recipient rcpt.format() code=DENY ..."

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2228]
https://github.com/haraka/Haraka/blob/0c95e42015dd262cb0bee0a5d9d6699fa6fe1b42/connection.js#L1037

There is something wrong with this line in master. I am no expert in Javascript nor understand why template literars are not working as supposed to.

**Comment by msimerson** [comment]
Help us help you. Create a new ticket, and this time, instead of deleting all the extra information we ask for in new issues, include it.

**Comment by analogic** [comment]
Sorry. I've found issue, it does only when rcpt_to list is empty (by my own faulty filtering) and thus rcpt is undef/null, but its strange behaviour of js to evaluate literars like that...

**Comment by msimerson** [comment]
> its strange behaviour of js to evaluate literars like that

I wondered if it peculiar to your version of node.js. 🤷‍♂️

**Comment by baudehlo** [comment]
The rcpt_ok_respond hook assumes there is at least one rcpt_to in
transaction.rcpt_to, because you just OK'd it.

We could probably put some belt and braces around that, but it's not a HUGE
deal.
