### ISSUE TITLE
haraka and external api communication stuck

### ISSUE THREAD

**Issue by rc111** [haraka/Haraka#2267]
### system info:
Haraka | Haraka.js — Version: 2.8.16
 --- | :--- 
Node | v8.7.0
OS | Linux vps149890.vps.ovh.ca 2.6.32-696.13.2.el6.x86_64 #1 SMP Thu Oct 5 21:22:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

### Expected behavior

Returning boolean false for main.timestamps=false
loaded TLD files: 1=1544 2=6156 3=2246
loaded 8357 Public Suffixes
Returning boolean false for main.disabled=false
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.16
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: dkim_sign
[INFO] [-] [core] Loading plugin: spf
[INFO] [-] [core] Loading plugin: queue/smtp_forward

[NOTICE] [-] [core] Listening on 152.42.231.201:587
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
[NOTICE] [9A39E99A-6FB4-4C20-B409-F3430BDCF025] [core] connect ip=131.225.14.268 port=42382 local_ip=152.42.231.201 local_port=25
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025] [spf] identity=helo ip=131.225.14.268 domain=fbsdf@vf.com" mfrom=<postmaster@fbsdf@vf.com> result=None
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025] [spf] scope: helo, result: None, domain: fbsdf@vf.com
[NOTICE] [-] [auth/flat_file] running query: SELECT password FROM tbl_smtp where smtpusername=? user=hts64311
[NOTICE] [-] [auth/flat_file] DB results: [{"password":"1af2a4eeefw39"}]
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [spf] identity=mfrom ip=131.225.14.268 domain="rasdys.co" mfrom=<sales@rasdys.co> result=SoftFail
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [spf] scope: mfrom, result: SoftFail, domain: rasys.co
[NOTICE] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [core] sender <sales@rasdys.co> code=CONT msg=""
[NOTICE] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [core] recipient <rc1ss1@rmail.com> code=OK msg="" sender=sales@rasdys.co
[WARN] [-] [via] undefined
[WARN] [-] [via] sales@rasdys.co
[WARN] [-] [via] sales@rasdys.co
[NOTICE] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [core] message mid=<1509014314336006.59f1dbb2a05cbd@rasys.co> size=604 rcpts=1/0/0 delay=0.441 code=CONT msg=""
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [dkim_sign] signed for radsys.co
[INFO] [-] [core] [smtp_client_pool] [2555:localhost:300] dispense() clients=1 available=0
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [queue/smtp_forward] forwarding to localhost:2555
[ERROR] [-] [core] backend failure: localhost:2555 - B9C44535-DAAF-4F2E-94D9-84618F335527: [localhost:2555] SMTP connection errored Error: connect ECONNREFUSED 127.0.0.1:2555
[NOTICE] [-] [db] {"event":"processed","timestamp":"2017-10-26T10:38:35.623Z","email":"<rc124@rmail.com>","host":"rmail.com","uuid":"9A39E99A-6FB4-4C20-B409-F3430BDCF025.1","message_id":"<9A39E99A-6FB4-4C20-B409-F3430BDCF025.1@vps149890.vps.ovh.ca; auth=pass (plain); spf=softfail smtp.mailfrom=rasdys.co>"}
[NOTICE] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [core] queue code=CONT msg=" (9A39E99A-6FB4-4C20-B409-F3430BDCF025.1)"
[INFO] [-] [core] [outbound] Sending email as a transaction
[INFO] [-] [core] [outbound] Processing domain: rmail.com
[NOTICE] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1] [core] queue code=OK msg="Message Queued"
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1.1] [outbound] Looking up A records for: rmail-smtp-in.l.google.com
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1.1] [outbound] Attempting to deliver to: 133.134.224.237:587 (0) (0)
[INFO] [-] [core] [outbound] [outbound::587:133.134.224.237:undefined:50] dispense() clients=1 available=0
[INFO] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1.1] [outbound] secured verified=true cipher=ECDHE-RSA-AES128-GCM-SHA256 version=TLSv1/SSLv3 cn=mx.google.com organization="Google Inc" issuer="Google Inc" expires="Dec 29 00:00:00 2017 GMT" fingerprint=2D:F3:A7:EF:57:67:83:16:89:B9:E8:4C:B7:0C:10:73:C9:22:80:77
[NOTICE] [9A39E99A-6FB4-4C20-B409-F3430BDCF025.1.1] [outbound]  delivered file=1509014315628_1509014315628_0_17338_wqiszD_1_vps149890.vps.ovh.ca domain=rmail.com host=rmail-smtp-in.l.google.com ip=133.134.224.237 port=587 mode=SMTP tls=Y auth=N response="OK 1509014316 z60si3000999qtc.470 - gsmtp" delay=0.565 fails=0 rcpts=1/0/0
[NOTICE] [-] [db] {"event":"delivered","timestamp":"2017-10-26T10:38:36.192Z","email":"<rc1s4@gmail.com>","host":"gmail.com","uuid":"9A39E99A-6FB4-4C20-B409-F3430BDCF025.1.1","mx_ip":"133.134.224.237","response":"OK 1509014316 z60si3000999qtc.470 - gsmtp","delay":0.565}
[INFO] [-] [core] [outbound] [outbound::587:133.134.224.237:undefined:50] dispense() clients=0 available=1

Firstly i mentioned that here ip's and domain names are modified here for security reasons . 

### Observed behavior
This process is only worked for the one application. as
                                                                    Haraka Output:

Returning boolean false for main.timestamps=false
loaded TLD files: 1=1544 2=6156 3=2246
loaded 8357 Public Suffixes
Returning boolean false for main.disabled=false
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.16
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: dkim_sign
[INFO] [-] [core] Loading plugin: spf
[INFO] [-] [core] Loading plugin: queue/smtp_forward

[NOTICE] [-] [core] Listening on 152.42.231.201:587
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
[NOTICE] [EA07C337-73CB-4B5E-A3DA-BA02DFE2D121] [core] connect ip=131.225.14.268 port=43702 local_ip=152.42.231.201 local_port=587
[INFO] [EA07C337-73CB-4B5E-A3DA-BA02DFE2D121] [spf] identity=helo ip=131.225.14.268  domain="hstds2.oyper.me" mfrom=<postmaster@hstds2.oyper.me> result=None
[INFO] [EA07C337-73CB-4B5E-A3DA-BA02DFE2D121] [spf] scope: helo, result: None, domain: host2.opper.me
[INFO] [EA07C337-73CB-4B5E-A3DA-BA02DFE2D121.1] [spf] identity=mfrom ip=131.225.14.268 domain="rasdys.co" mfrom=<sales@rasdys.co> result=SoftFail
[INFO] [EA07C337-73CB-4B5E-A3DA-BA02DFE2D121.1] [spf] scope: mfrom, result: SoftFail, domain: rasdys.co
[NOTICE] [EA07C337-73CB-4B5E-A3DA-BA02DFE2D121.1] [core] sender <sales@rasdys.co> code=CONT msg=""
[NOTICE] [EA07C337-73CB-4B5E-A3DA-BA02DFE2D121.1] [core] recipient <hhfhf3191@gmail.com> code=OK msg="" sender=sales@radsys.co

                                                            Response of Process:
A test email has not been successfully sent to the email address hhfhf3191@rmail.com: 550 I cannot deliver mail for <hhfhf3191@rmail.com>

### Steps to reproduce
Sending Email again and check the logs.

**Comment by smfreegard** [comment]
This makes absolutely no sense whatsoever.    The first part you show a message being injected via SMTP AUTH; which works correctly for the most part, then the 2nd doesn't use SMTP AUTH and fails - which is entirely expected.

I think you need to go and read the documentation again.   If you want to accept inbound mail, then you need to do that on port 25, and you'll need to use the rcpt_to.in_host_list plugin and configure it along with queue/smtp_forward accordingly.

**Comment by rc111** [comment]
I'm not using queue/smtp_forward plugin and enable the  rcpt_to.in_host_list plugin but my user and password is contain from the database and it is an plain format.
also try on both port  25 and 587 but it is not working .
user and passwd store in mysql database.

**Comment by smfreegard** [comment]
Then why are you loading the `queue/smtp_forward` plugin at all then?

If this is for outbound only - then you either need to make every client send SMTP AUTH or you need to use the `relay` plugin and enable relaying by IP address.

**Comment by rc111** [comment]
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.16
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: dkim_sign
[INFO] [-] [core] Loading plugin: spf
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[NOTICE] [-] [core] Listening on 142.44.211.201:25
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
[NOTICE] [C3FD1A65-4563-4927-AA20-B36CF19A8821] [core] connect ip=181.214.205.44 port=43302 local_ip=142.44.211.201 local_port=25
[INFO] [C3FD1A65-4563-4927-AA20-B36CF19A8821] [spf] identity=helo ip=181.214.205.44 domain="host2.opper.me" mfrom=<postmaster@host2.opper.me> result=None
[INFO] [C3FD1A65-4563-4927-AA20-B36CF19A8821] [spf] scope: helo, result: None, domain: host2.opper.me
[INFO] [C3FD1A65-4563-4927-AA20-B36CF19A8821.1] [spf] identity=mfrom ip=181.214.205.44 domain="rasys.co" mfrom=<sales@rasys.co> result=SoftFail
[INFO] [C3FD1A65-4563-4927-AA20-B36CF19A8821.1] [spf] scope: mfrom, result: SoftFail, domain: rasys.co
[NOTICE] [C3FD1A65-4563-4927-AA20-B36CF19A8821.1] [core] sender <sales@rasys.co> code=CONT msg=""
[NOTICE] [C3FD1A65-4563-4927-AA20-B36CF19A8821.1] [core] recipient <hemstechnosys1@gmail.com> code=OK msg="" sender=sales@rasys.co

**Comment by smfreegard** [comment]
Repeating yourself isn't going to change the fact you're doing it wrong.

There was no SMTP AUTH sent on this connection *which is required for port 587*, so it was rejected.   Simple as that.

**Comment by rc111** [comment]
This an updated log

**Comment by smfreegard** [comment]
It might be updated - but I don't see any difference.  It's still wrong.

**Comment by rc111** [comment]
start the relay plugin but it is not working .

**Comment by Dexus** [comment]
@rc111 the problem is that you configured you haraka wrong and/or your client don't auth against haraka. if you are not able to listen to @smfreegard notice, dont write any longer here please. There is nothing wrong, and if there is something wrong, you should provide your config and give more details to reproduce the problem.

Thanks.

**Comment by anosh-plutoflume** [comment]
I'm going to repeat what I said on IRC, some of the plugins such as dkim_sign you've modified.

We need as many details as possible to even help. If can tell us what you've changed, that will help.

This is more likely a user error since most of us who run Haraka in production are not facing the same issue are you are.

**Comment by KingNoosh** [comment]
I'm going to repeat what I said on IRC, some of the plugins such as dkim_sign you've modified.

We need as many details as possible to even help. If can tell us what you've changed, that will help.

This is more likely a user error since most of us who run Haraka in production are not facing the same issue are you are.

**Comment by rccess** [comment]
i am also working with tylor team ,

let me explain you in details 

we modified dkim_sign.js just for passing with multiple domains and as we defined everything with modified path only and dkim , spf, dmarc passed successfully and working smoothly 

and tested with the web application 
and since i am sending with interspire or outlook we are getting stuck 
even there is no firewall on server to block to accept request 

as the issue i can guess is different mailing clients send different auth type thats why it is working with only one email client application (web based)
we have tested on both port 25 and 587 , both port working on the one client application (web based)
since we installed haraka old version few days ago , was worked perfectly with all application with same configuration

and now we are on latest version of haraka 

you all are very supporting , your hints always worked for me

Your advise highly appreciated 

Thanks

**Comment by KingNoosh** [comment]
Have you tried removing plugins one by one? Try removing auth/flat_file and sending a message.

**Comment by rccess** [comment]
anosh , i already tired to remove plugins one by one , actually i already removed this auth/flat_file because my smtp details coming from mysql database and mysql connection i defined in another .ini file .

**Comment by rccess** [comment]
let me try to remove the plugins again and send output logs , so will much helper to identify the issue

**Comment by rc111** [comment]
I successfully done my work , actually i'm using the single PLAIN method in ini file, but the solution of it is
method=PLAIN,LOGIN,CRAM-MD5.
Thank you for helping me on my issue.
