### ISSUE TITLE
Warning message, pool connection between Nodemailer and Haraka

### ISSUE THREAD

**Issue by MatthieuHPP** [haraka/Haraka#2272]
Hello,

I am using pool: true on Nodemailer to limit the rate of emails sent with Haraka ((latest version / node 6.11 / Debian 8)), via Nodemailer.

I did not configure anything, related to pool, on Haraka. default configuration seems good for my usage. Once emails are sent via pool connection between Nodemailer and Haraka, I do obtain the following log warnings on Haraka :

```
[WARN] [-] [core] [outbound] Socket [outbound::25:188.xxx.xx.79:undefined:50] in pool got FIN
[WARN] [xxxxx-0A9F-xxxxx-9953-ECD236FA8B3B.1] [core] client [149.xxxxxxx] connection timed out
```

Functionally, emails are sent as expected. I did not notice anything weird.

Am I doing something wrong ?

Many thanks

**Comment by msimerson** [comment]
Looks okay from here.
