### ISSUE TITLE
Authorization doesn't work.

### ISSUE THREAD

**Issue by MrSorcus** [haraka/Haraka#2301]
### system info

Haraka | Haraka.js — Version: 2.8.16
 --- | :--- 
Node | v6.11.3
OS | Linux server.inwebse.org 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Logs (loglevel: DEBUG)
https://gist.github.com/MrSorcus/bea6c7e2ede7fdb0afe4cb38b92e496d - haraka log.
https://gist.github.com/MrSorcus/cdcb05836873bb635bc32ec181583fd9 - client log.

### Mail client
```JavaScript
[root@server]~# cat test_mail.js 
// https://github.com/nodemailer/nodemailer

let nodemailer = require('nodemailer')

let transporter = nodemailer.createTransport('smtp://username:pass@inwebse.com:25')

let mailOptions = {
    host: 'inwebse.com',
    port: 587,
    from: 'username@inwebse.com', // sender address
    to: 'undefined@inwebse.com', // list of receivers
    subject: 'Hello',
    text: 'Hello world',
    debug: true,
    auth: {
        user: 'sorcus',
        pass: 'pass'
    }
}

// send mail with defined transport object
transporter.sendMail (mailOptions, (error, info) => {
    if (error) {
        return console.log(error)
    }
    console.log('Message sent: ' + info.response)
})
```

plugins: https://gist.github.com/MrSorcus/a12eb4d726c9813eb97f71b273421a40
tls.ini: https://gist.github.com/MrSorcus/bf2a756f9cbd87254e525cf9574c0279
auth_flat_file.ini: https://gist.github.com/MrSorcus/a51e1a98a9bf766a92ec9b8ead1f9dba

Pass and login is right, but i get error.

**Comment by smfreegard** [comment]
Try loading the `auth_flat_file` plugin after `tls` in `config/plugins` and see if it starts working after that.

**Comment by MrSorcus** [comment]
But i have it. [plugins](https://gist.github.com/MrSorcus/a12eb4d726c9813eb97f71b273421a40#file-plugins-ini-L32-L36)

**Comment by MrSorcus** [comment]
Swaks log - https://gist.github.com/MrSorcus/4c756ea805838940236181667796ebf5

**Comment by smfreegard** [comment]
`username@inwebse.com = {CRAM-MD5}XXXXXX`

You aren't actually putting {CRAM-MD5} in there literally are you?  It should be username = password IIRC.

**Comment by MrSorcus** [comment]
> You aren't actually putting {CRAM-MD5} in there literally are you? It should be username = password IIRC.

Pass shoud be inserted as plaintext, right? Looks as insecure.

**Comment by smfreegard** [comment]
> Pass shoud be inserted as plaintext, right? Looks as insecure.

Correct - as per the documentation for this pluign: https://github.com/haraka/Haraka/blob/master/docs/plugins/auth/flat_file.md

Patches welcome if you want to improve it.

**Comment by MrSorcus** [comment]
Switching to [imap haraka plugin](https://github.com/haraka/haraka-plugin-auth-imap). Now all works for me. Thank  for help.
