### ISSUE TITLE
Outbound getting stuck ! 

### ISSUE THREAD

**Issue by rccess** [haraka/Haraka#2302]
### system info
centos 6.4
Haraka version 2.8.16

I am facing issue with error

Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback
**************************************************************************
and haraka get down

another concern 

i have used ip rotation  with mx hooks
sometime it passed and sometime it failed with timeout 

Please advise

thanks

**Comment by smfreegard** [comment]
You shouldn't raise issues on plugins that are custom.   Issues are for bugs in the supplied code only.

**Comment by rccess** [comment]
the logs are here 

sult=None
[INFO] [2C37F075-5BA7-4BC7-B506-25C35CD53E64] [spf] scope: helo, result: None, domain: localhost.localdomain
[INFO] [2C37F075-5BA7-4BC7-B506-25C35CD53E64] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [2C37F075-5BA7-4BC7-B506-25C35CD53E64] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNjk5 retval=OK msg=""
[ERROR] [-] [outbound] Ongoing connection failed to 192.185.129.43:25 : Error: write after end
[NOTICE] [-] [db] {"event":"deferred","timestamp":"2017-11-22T09:33:14.324Z","email":"<himani@vigorpddfgdfharma.com>","host":"vigorpharma.com","uuid":"2F662992-BE98-47F2-9144-B6724AB7F747.1.1","delay":1024,"err":"Tried all MXs"}
[INFO] [-] [outbound] Temp failing 1511341710118_1511342994728_4_14781_59L2Wx_334_vps121528.vps.ovh.ca for 1024 seconds: Tried all MXs
[CRIT] [-] [outbound] Socket write failed unexpectedly: Error: write after end
[CRIT] [28E6CAEA-641D-46FE-9B87-A537C6BCC51A] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback

**Comment by rccess** [comment]
new logs

[INFO] [C2239795-FE3F-47AF-93E9-7505DA774C71] [spf] scope: helo, result: None, domain: 27.4.161.21
[INFO] [C2239795-FE3F-47AF-93E9-7505DA774C71] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [C2239795-FE3F-47AF-93E9-7505DA774C71] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNjk0 retval=OK msg=""
[CRIT] [13B18F17-0D1E-47A8-94A0-2C818DBBEC09] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback
[INFO] [13B18F17-0D1E-47A8-94A0-2C818DBBEC09] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="YTU3MDA4YjU=" retval=DENYSOFT msg="plugin timeout"
[INFO] [13B18F17-0D1E-47A8-94A0-2C818DBBEC09] [core] client [27.4.161.21] half closed connection
[NOTICE] [C9C064B1-6FA6-4F3C-8D17-B2ACEBB3A305] [core] connect ip=27.4.161.21 port=57047 local_ip=149.56.142.134 local_port=587
[NOTICE] [750A22F7-EBF0-4A3D-B85F-51AF9B7A0215] [core] connect ip=27.4.161.21 port=57048 local_ip=149.56.142.134 local_port=587
[INFO] [C9C064B1-6FA6-4F3C-8D17-B2ACEBB3A305] [spf] identity=helo ip=27.4.161.21 domain="27.4.161.21" mfrom=<postmaster@27.4.161.21> result=None
[INFO] [C9C064B1-6FA6-4F3C-8D17-B2ACEBB3A305] [spf] scope: helo, result: None, domain: 27.4.161.21
[INFO] [750A22F7-EBF0-4A3D-B85F-51AF9B7A0215] [spf] identity=helo ip=27.4.161.21 domain="27.4.161.21" mfrom=<postmaster@27.4.161.21> result=None
[INFO] [750A22F7-EBF0-4A3D-B85F-51AF9B7A0215] [spf] scope: helo, result: None, domain: 27.4.161.21
[NOTICE] [5BBD6BF2-C631-49B1-B295-479791609404] [core] connect ip=27.4.161.21 port=57049 local_ip=149.56.142.134 local_port=587
[INFO] [C9C064B1-6FA6-4F3C-8D17-B2ACEBB3A305] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [750A22F7-EBF0-4A3D-B85F-51AF9B7A0215] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [5BBD6BF2-C631-49B1-B295-479791609404] [spf] identity=helo ip=27.4.161.21 domain="27.4.161.21" mfrom=<postmaster@27.4.161.21> result=None
[INFO] [5BBD6BF2-C631-49B1-B295-479791609404] [spf] scope: helo, result: None, domain: 27.4.161.21
[INFO] [C9C064B1-6FA6-4F3C-8D17-B2ACEBB3A305] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNjk0 retval=OK msg=""
[INFO] [750A22F7-EBF0-4A3D-B85F-51AF9B7A0215] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNjk0 retval=OK msg=""
[INFO] [5BBD6BF2-C631-49B1-B295-479791609404] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [5BBD6BF2-C631-49B1-B295-479791609404] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNjk0 retval=OK msg=""
[NOTICE] [CA0FF68F-6933-4EA0-9FAB-9321DFC2656D] [core] connect ip=27.4.161.21 port=57050 local_ip=149.56.142.134 local_port=587
[INFO] [CA0FF68F-6933-4EA0-9FAB-9321DFC2656D] [spf] identity=helo ip=27.4.161.21 domain="27.4.161.21" mfrom=<postmaster@27.4.161.21> result=None
[INFO] [CA0FF68F-6933-4EA0-9FAB-9321DFC2656D] [spf] scope: helo, result: None, domain: 27.4.161.21
[INFO] [CA0FF68F-6933-4EA0-9FAB-9321DFC2656D] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [CA0FF68F-6933-4EA0-9FAB-9321DFC2656D] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNjk0 retval=OK msg=""
[CRIT] [70CCB2F1-A15D-4BCA-9E2A-A4C96DA7429D] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback
[INFO] [70CCB2F1-A15D-4BCA-9E2A-A4C96DA7429D] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="U3RhbmRhcmRAMQ==" retval=DENYSOFT msg="plugin timeout"
[INFO] [70CCB2F1-A15D-4BCA-9E2A-A4C96DA7429D] [core] client [78.47.118.201] half closed connection

**Comment by rccess** [comment]
updated logs

[DEBUG] [6375FD3C-59F6-4177-ACBF-D98790069831] [core] running rset hooks
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running ehlo hooks
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running ehlo hook in spf plugin
[DEBUG] [-] [spf] ip=103.5.133.103 domain=user63085bed9c mail_from=postmaster@user63085bed9c
[DEBUG] [-] [spf] error looking up TXT record: queryTxt ENOTFOUND user63085bed9c
[INFO] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [spf] identity=helo ip=103.5.133.103 domain="user63085bed9c" mfrom=<postmaster@user63085bed9c> result=None
[INFO] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [spf] scope: helo, result: None, domain: user63085bed9c
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core]  hook=ehlo plugin=spf function=hook_ehlo params=user63085bed9c retval=CONT msg=""
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running capabilities hooks
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running capabilities hook in auth/flat_file plugin
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core]  hook=capabilities plugin=auth/flat_file function=hook_capabilities params="" retval=CONT msg=""
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running unrecognized_command hooks
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running unrecognized_command hook in auth/flat_file plugin
[INFO] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running unrecognized_command hooks
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running unrecognized_command hook in auth/flat_file plugin
[INFO] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNjQ4 retval=OK msg=""
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running unrecognized_command hooks
[DEBUG] [78D18F06-726C-479A-BA9F-EEA4B0DCC563] [core] running unrecognized_command hook in auth/flat_file plugin
[CRIT] [DF9A40C0-E67C-4626-8C16-60F91D0D165D] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback
[INFO] [DF9A40C0-E67C-4626-8C16-60F91D0D165D] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="U3RhbmRhcmRAMQ==" retval=DENYSOFT msg="plugin timeout"
[DEBUG] [DF9A40C0-E67C-4626-8C16-60F91D0D165D] [core] running deny hooks
[INFO] [DF9A40C0-E67C-4626-8C16-60F91D0D165D] [core] client [78.47.118.201] half closed connection
[DEBUG] [DF9A40C0-E67C-4626-8C16-60F91D0D165D] [core] client has disconnected
[DEBUG] [DF9A40C0-E67C-4626-8C16-60F91D0D165D] [core] aborting disconnect hook
[DEBUG] [-] [outbound] running send_email hooks
[DEBUG] [-] [outbound] Sending mail: 1511344142238_1511344214937_1_15329_qmqqtb_17_vps121528.vps.ovh.ca
[DEBUG] [-] [outbound] running get_mx hooks
[DEBUG] [-] [outbound] running get_mx hook in multi_ip plugin
[INFO] [-] [outbound]  hook=get_mx plugin=multi_ip function=hook_get_mx params=otenet.gr retval=OK msg="[object Object],[object Object],[object Object],[object Object]"
[DEBUG] [-] [outbound] Got an MX from Plugin: otenet.gr => 0 [object Object],[object Object],[object Object],[object Object]
[INFO] [-] [outbound] Looking up A records for: mx.otenet.gr
[INFO] [-] [outbound] Attempting to deliver to: 62.103.147.198:25 (0) (79)
[INFO] [-] [core] [outbound] [outbound::25:62.103.147.198:144.217.193.56:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:62.103.147.198:144.217.193.56:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] created host=62.103.147.198 port=25 pool_timeout=50
[DEBUG] [-] [core] client TLS upgrade in progress, awaiting secured.

**Comment by rccess** [comment]
here is the new logs

[NOTICE] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] connect ip=50.87.144.192 port=52535 local_ip=149.56.142.134 local_port=587
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running connect_init hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running connect_init_respond
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running lookup_rdns hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running connect hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running connect hook in max_unrecognized_commands plugin
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core]  hook=connect plugin=max_unrecognized_commands function=hook_connect params="" retval=CONT msg=""
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running ehlo hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running ehlo hook in spf plugin
[DEBUG] [-] [spf] ip=50.87.144.192 domain=localhost.localdomain mail_from=postmaster@localhost.localdomain
[DEBUG] [-] [spf] error looking up TXT record: queryTxt ENOTFOUND localhost.localdomain
[INFO] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [spf] identity=helo ip=50.87.144.192 domain="localhost.localdomain" mfrom=<postmaster@localhost.localdomain> result=None
[INFO] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [spf] scope: helo, result: None, domain: localhost.localdomain
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core]  hook=ehlo plugin=spf function=hook_ehlo params=localhost.localdomain retval=CONT msg=""
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running capabilities hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running capabilities hook in auth/flat_file plugin
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core]  hook=capabilities plugin=auth/flat_file function=hook_capabilities params="" retval=CONT msg=""
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running unrecognized_command hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running unrecognized_command hook in auth/flat_file plugin
[INFO] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running unrecognized_command hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running unrecognized_command hook in auth/flat_file plugin
[INFO] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=aHRzNzAy retval=OK msg=""
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running unrecognized_command hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running unrecognized_command hook in auth/flat_file plugin
[CRIT] [A4DE3C2A-DC4F-4FD2-A6DA-66AE05FCCAC3] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback
[INFO] [A4DE3C2A-DC4F-4FD2-A6DA-66AE05FCCAC3] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="Yzg1OWRmM2I=" retval=DENYSOFT msg="plugin timeout"
[DEBUG] [A4DE3C2A-DC4F-4FD2-A6DA-66AE05FCCAC3] [core] running deny hooks
[DEBUG] [A4DE3C2A-DC4F-4FD2-A6DA-66AE05FCCAC3] [core] running rset hooks
[CRIT] [D617516F-2D26-4C8D-AB47-81C078E6BE27] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback
[INFO] [D617516F-2D26-4C8D-AB47-81C078E6BE27] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="MWYxNDVmYmY=" retval=DENYSOFT msg="plugin timeout"
[DEBUG] [D617516F-2D26-4C8D-AB47-81C078E6BE27] [core] running deny hooks
[INFO] [A4DE3C2A-DC4F-4FD2-A6DA-66AE05FCCAC3] [core] client [108.167.189.69] half closed connection
[DEBUG] [A4DE3C2A-DC4F-4FD2-A6DA-66AE05FCCAC3] [core] client has disconnected
[DEBUG] [A4DE3C2A-DC4F-4FD2-A6DA-66AE05FCCAC3] [core] aborting disconnect hook
[DEBUG] [D617516F-2D26-4C8D-AB47-81C078E6BE27] [core] running rset hooks
[INFO] [D617516F-2D26-4C8D-AB47-81C078E6BE27] [core] client [198.57.247.194] half closed connection
[DEBUG] [D617516F-2D26-4C8D-AB47-81C078E6BE27] [core] client has disconnected
[DEBUG] [D617516F-2D26-4C8D-AB47-81C078E6BE27] [core] aborting disconnect hook
[CRIT] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] Plugin auth/flat_file timed out on hook unrecognized_command - make sure it calls the callback
[INFO] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="MDZlYjBhMWU=" retval=DENYSOFT msg="plugin timeout"
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running deny hooks
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] running rset hooks
[INFO] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] client [50.87.144.192] half closed connection
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] client has disconnected
[DEBUG] [2C7C93D1-B97F-4A3F-AB56-6B2B710BD34C] [core] aborting disconnect hook
