### ISSUE TITLE
Error: iconv conversion from cp-850 to UTF-8 failed

### ISSUE THREAD

**Issue by frank-bn** [haraka/Haraka#2306]
### system info

Haraka | Haraka.js — Version: 2.8.16
 --- | :---
Node | v6.12.0
OS | Linux dione 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016
iconv | 2.23

### Expected behavior

No Problem with CP-850 Mails.

### Observed behavior

`[ERROR] [-] [core] iconv conversion from cp-850 to UTF-8 failed: Conversion from cp-850 to UTF-8//TRANSLIT//IGNORE is not supported.`

### Steps to reproduce

Receive mails with CP-850 encoding.

### Solution?

Maybe the iconv option CP-850 is wrong and should be CP850?

**Comment by smfreegard** [comment]
This shouldn't prevent a message from being received.  It's merely that the engine can't convert the message into UTF-8 internally, so some things won't work.

It looks like whoever is sending the message has incorrectly specified the encoding in the MIME headers (as it should be cp850 by the looks of it).

**Comment by frank-bn** [comment]
Thanks for your fast feedback.

If this error is not limiting the functionality of Haraka you can close this issue.
It wouldn't be fine if unwanted mails with intentionally mailformed headers could pass the filters.

**Comment by smfreegard** [comment]
They do pass the filters, this is just a warning, so what we should probably do is change the severity.
