### ISSUE TITLE
Problem with karma and redis

### ISSUE THREAD

**Issue by frank-bn** [haraka/Haraka#2308]
### system info

Haraka | Haraka.js — Version: 2.8.16
 --- | :---
Node | v6.12.0
OS | Linux dione 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016
redis Server | 3.0.6
haraka-karma | 1.0.11
haraka-redis | 1.0.7

### Expected behavior

Karma plugin should be running without redis errors

### Observed behavior

**1) Test without(!) adding and enabling redis in config/plugins**
Plugins like greylist and limit connect to redis and seem to work.
On Haraka startup karma shows:
`[karma] connected to redis://127.0.0.1:6379 v3.0.6`
But on receiving the first incoming mail the log displays:
`[karma] karma requires the redis plugin`

**2) Test with adding and enabling redis in config/plugins**
Haraka startup without any problems. Redis connections seem to work.
After receiving mails for several hours executing:
`redis-cli info clients`
shows:
`connected_clients:4064`
Nearly all connections are on redis db=0.
Because of the default redis maxclients setting on my server the next incoming mail causes:
```
[CRIT] [-] [core] ReplyError: Ready check failed: ERR max number of clients reached
[CRIT] [-] [core]     at parseError (/usr/lib/node_modules/Haraka/node_modules/redis-parser/lib/parser.js:193:12)
[CRIT] [-] [core]     at parseType (/usr/lib/node_modules/Haraka/node_modules/redis-parser/lib/parser.js:303:14)
[NOTICE] [-] [core] Shutting down
```
Checking the number of clients with cli:
`redis-cli info clients`
`ERR max number of clients reached`

This problem seems similar or is maybe the same I had when trying Haraka the first time. See my issue #1955
Is there something wrong with my configuration?

### Steps to reproduce

see my system info

**Comment by msimerson** [comment]
I'll update my system soon and see if I can't reproduce. Today, I can't:

* redis-cli info clients: 21
* redis server: 3.2.10
* node: 6.11.5
* Haraka: 2.8.16

**Comment by msimerson** [comment]
Hi @frank-bn , I've created a small PR against `haraka-plugin-redis` that I think will resolve issue #2 for you.

**Comment by msimerson** [comment]
Update: on a server that exhibited behavior 2 above, I applied this patch and after running half a day:
````
root@mail:~ # redis-cli info clients
# Clients
connected_clients:14
````
