### ISSUE TITLE
Memory leak from smtp_client

### ISSUE THREAD

**Issue by dumbird** [haraka/Haraka#2312]
I'm working on a plugin that's modified based on smtp_forward, and haraka crashed under stress test. I believe it's caused by the smtp_client.release() method didn't remove listeners for event connection-error, resulting in existing transactions cannot be gc'ed. Lots of errors like this logged:
(node:7329) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection-error listeners added. Use emitter.setMaxListeners() to increase limit

After adding smtp_client.removeAllListeners('connection-error') after calling smtp_client.release() I no longer see memory leak.

**Comment by msimerson** [comment]
Thanks for the report @dumbird . Sure enough, we add the listener and then fail to remove it. I'll created a PR to fix it.
