### ISSUE TITLE
TypeError: net_utils.tls_ini_section_with_defaults is not a function

### ISSUE THREAD

**Issue by keithws** [haraka/Haraka#2340]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.16
 --- | :---
Node | v6.11.5
OS | Linux 4.9.76-gentoo-r1 #1 SMP Wed Jan 24 20:14:01 PST 2018 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux
openssl | OpenSSL 1.0.2n  7 Dec 2017
### Expected behavior

Not crash.

### Observed behavior

Crashes when processing outbound queue. Specifically, when attempting to deliver to Google.

Here is the related log entries:

```
[INFO] [-] [core] [outbound] Loading the queue...
[INFO] [FBB01AC2-3A59-4166-A3B3-D4D0AC3240B0.1.1] [outbound] Looking up A records for: aspmx.l.google.com
[INFO] [FBB01AC2-3A59-4166-A3B3-D4D0AC3240B0.1.1] [outbound] Attempting to deliver to: 64.233.168.27:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:64.233.168.27:undefined:50] dispense() clients=1 available=0
[CRIT] [-] [core] TypeError: net_utils.tls_ini_section_with_defaults is not a function
[CRIT] [-] [core]     at Object.exports.get_tls_options (/usr/lib64/node_modules/Haraka/outbound/tls.js:10:35)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib64/node_modules/Haraka/outbound/hmail.js:774:51)
[CRIT] [-] [core]     at emitOne (events.js:96:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:188:7)
[CRIT] [-] [core]     at pluggableStream.socket.process_data (/usr/lib64/node_modules/Haraka/line_socket.js:24:20)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib64/node_modules/Haraka/line_socket.js:35:48)
[CRIT] [-] [core]     at emitOne (events.js:96:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:188:7)
[CRIT] [-] [core]     at Socket.<anonymous> (/usr/lib64/node_modules/Haraka/tls_socket.js:57:14)
[CRIT] [-] [core]     at emitOne (events.js:96:13)
[NOTICE] [-] [core] Shutting down
```

### Steps to reproduce

Send a message to a gmail account.

**Comment by msimerson** [comment]
When did you install this? If you `rm -rf node_modules && npm install` it should fix the issue.

**Comment by KingNoosh** [comment]
@keithws is this still ongoing?

**Comment by baudehlo** [comment]
No, msimerson fixed the net_utils library and deleted the broken one from
npm.

**Comment by msimerson** [comment]
> deleted the broken one

Slight correction: deprecated broken and published anew. NPM has changed and we can no longer unpublish old versions.

**Comment by msimerson** [comment]
closing, until we get a response from @keithws confirming this is still an issue. (it should be fixed in repo and npm).

**Comment by keithws** [comment]
Sorry, I got the flu.

I installed Haraka a while ago, at least March 2017, maybe earlier. I did a `rm -rf node_modules && npm install` in the each Haraka config folder for smtp and submission, but that didn't help. I then tried the Haraka install in my global node modules folder and I started getting odd permission errors. I ended up completely reinstalling node/npm/Haraka to fix the permission errors and now it does not crash, but I still get the following errors. One of these for each MX:

```
[INFO] [FBB01AC2-3A59-4166-A3B3-D4D0AC3240B0.1.1] [outbound] Looking up A records for: aspmx2.googlemail.com
[INFO] [FBB01AC2-3A59-4166-A3B3-D4D0AC3240B0.1.1] [outbound] Attempting to deliver to: 173.194.219.27:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:173.194.219.27:undefined:50] dispense() clients=1 available=0
[INFO] [-] [core] [outbound] acquired socket 64F5EFFE-9A7E-4918-BA12-EC3C6577EE7F for outbound::25:173.194.219.27:undefined:50
[ERROR] [FBB01AC2-3A59-4166-A3B3-D4D0AC3240B0.1.1] [outbound] Remote end 173.194.219.27:25 closed connection while we were processing mail. Trying next MX.
```

And then one of these at the end:

```
[INFO] [FBB01AC2-3A59-4166-A3B3-D4D0AC3240B0.1.1] [outbound] Temp failing 1518636639277_1518809672616_3_5481_vRkixM_2_hostname for 512 seconds: Tried all MXs
```

Is this the expected behavior?

**Comment by baudehlo** [comment]
Yes.
