### ISSUE TITLE
Plugin watch works, but no valuable information displayed.

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2357]
Haraka 2.8.17,  node v8.9.4

![image](https://user-images.githubusercontent.com/5416196/36956428-37f4859c-2093-11e8-8010-ba4686f86b17.png)

and only inbound emails events can be displayed on this page.

**Comment by msimerson** [comment]
Correct, only inbound messages are displayed. It would be good to add outbound but I haven't done it yet. 

Watch gets all the connection details via redis pub/sub. Haraka and plugins save data to `haraka-results` (make sure redis_publis=true in config/results.ini) which publishes the data to redis. The watch plugin subscribes to that feed and uses that data to update the HTML page.

Troubleshooting steps would be:
* watch redis and verify that data is being published
* use your browsers inspection tool and make sure there are no errors

**Comment by zinwalin** [comment]
@msimerson after installed haraka-results with npm install, how to enable haraka-results?   when added results into config/plugins,  haraka can't find plugin results.

**Comment by msimerson** [comment]
Moved to haraka/haraka-plugin-watch#33
