### ISSUE TITLE
Shutting down  automatically

### ISSUE THREAD

**Issue by Manishjodhani** [haraka/Haraka#2358]
I'm using haraka latest version and it shut-down automatically..when i check the log...I don't find any error.

**here is the log** 

[CRIT] [-] [core]     at HMailItem.hmail.next_cb (/usr/lib/node_modules/Haraka/outbound/queue.js:40:9)
[CRIT] [-] [core]     at HMailItem.discard (/usr/lib/node_modules/Haraka/outbound/hmail.js:1241:18)
[CRIT] [-] [core]     at outbound.send_email.origin (/usr/lib/node_modules/Haraka/outbound/hmail.js:1203:22)
[CRIT] [-] [core]     at async.forEachSeries (/usr/lib/node_modules/Haraka/outbound/index.js:287:17)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:421:16
[CRIT] [-] [core]     at replenish (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:941:25)
[CRIT] [-] [core]     at iterateeCallback (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:931:17)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:906:16
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/outbound/index.js:312:17
[NOTICE] [-] [core] Shutting down

**Comment by Dexus** [comment]
That is really anything you got from the logs?

**Comment by Manishjodhani** [comment]
Yes....i use this cmd.
**tail -f /var/log/haraka.log**

**Comment by smfreegard** [comment]
That error message is truncated - you're missing the really important line or two above this one.  `tail -n50 -f /var/log/maillog` might be more appropriate.

**Comment by Manishjodhani** [comment]
have look in screen shot..

![](https://user-images.githubusercontent.com/8230690/36971500-95494e70-209e-11e8-97ce-9f059d325ef5.png)

**Comment by Manishjodhani** [comment]
have a look in this screen-shot.
![screenshot_8](https://user-images.githubusercontent.com/28861157/36975482-39269204-20a0-11e8-86d9-c228e3328d1d.png)

**Comment by msimerson** [comment]
What version of Haraka is this?

**Comment by Manishjodhani** [comment]
Its 2.8

**Comment by msimerson** [comment]
Please try 2.8.17 or newer. There's an outbound crashing bug that was already fixed. Reopen this Issue if it still occurs after upgrade.
