### ISSUE TITLE
will Haraka support outbound email with attachment? 

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2363]
Or any idea to customize it ?

**Comment by baudehlo** [comment]
Haraka supports whatever attachments you want. The question is a bit vague though. Can you be more specific?

**Comment by zinwalin** [comment]
@baudehlo when you send email with outbound.send_email(xxx), how to add attachments?

**Comment by baudehlo** [comment]
Use some node library to construct the email.
