### ISSUE TITLE
how to reply inbound email with conversation details

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2365]
For some reason, I need to reply inbound email with recipient like no_reply@mydomain.com, and using outbound.send_email to reply , it works but losing previous conversation details, so Gmail create a new thread in the inbox.   Is it possible to reply back with conversation details when getting inbound emails?

**Comment by baudehlo** [comment]
There's no magic to it. It's just the format of the email itself and the
headers.

It needs things like a References header, a "Re: " in front of the original
subject, etc.

This might help: https://cr.yp.to/immhf/thread.html
