### ISSUE TITLE
is there any way to get report of email sent? 

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2368]
Like how many emails been sent ?  how many been rejected or bounce back?  etc.,

Plugin watch only support real-time monitor, it doesn't meet this requirement.

**Comment by baudehlo** [comment]
You could probably adapt Haraka-plugin-graph for this. Or use elastic search plugins. There’s a million ways you could do it. Hell you could grep | wc daily to do it.

**Comment by celesteking** [comment]
Let's, possibly, close this issue? And other stale ones, preferably.
