### ISSUE TITLE
queue streaming issue shutting down haraka

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2371]
[DEBUG] [-] [server]  hook=init_wss plugin=watch function=hook_init_wss params="" retval=CONT msg=""
[INFO] [-] [core] init_wss_respond
[NOTICE] [-] [core] worker 354 listening on :::8080
[CRIT] [-] [core] TypeError: addr.replace is not a function
[CRIT] [-] [core]     at Address.parse (/usr/lib/node_modules/Haraka/node_modules/address-rfc2821/index.js:90:17)
[CRIT] [-] [core]     at new Address (/usr/lib/node_modules/Haraka/node_modules/address-rfc2821/index.js:24:14)
[CRIT] [-] [core]     at todo.rcpt_to.todo.rcpt_to.map.a (/usr/lib/node_modules/Haraka/outbound/hmail.js:123:64)
[CRIT] [-] [core]     at Array.map (<anonymous>)
[CRIT] [-] [core]     at _stream_bytes_from (/usr/lib/node_modules/Haraka/outbound/hmail.js:123:55)
[CRIT] [-] [core]     at ReadStream.stream.on (/usr/lib/node_modules/Haraka/outbound/hmail.js:149:13)
[CRIT] [-] [core]     at emitNone (events.js:111:20)
[CRIT] [-] [core]     at ReadStream.emit (events.js:208:7)
[CRIT] [-] [core]     at endReadableNT (_stream_readable.js:1064:12)
[CRIT] [-] [core]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[NOTICE] [-] [core] Shutting down
[NOTICE] [-] [core] worker 354 exited with error code: 1
[NOTICE] [-] [core] worker started worker=355 pid=5908
loaded TLD files: 1=1544 2=8347 3=2424
loaded 8447 Public Suffixes

-----------------
in queue folder, there's one unreadable file "1521577525774_1521577525774_0_6720_fYLpkn_1_ip-10-0-0-111" which make Haraka shut down, after remove all files in queue folder, Haraka able to restart. 

**Haraka Version: 2.8.18**

**Comment by javascriptlove** [comment]
I'm actually hitting same issue which is hard to trace since I now have a queue of 1000s of emails and one of them gives `addr.replace is not a function` and everything crashes
