### ISSUE TITLE
password in auth_flat_file.ini not secure

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2379]
is it possible to encrypt password in that file?

**Comment by msimerson** [comment]
PR welcome. I'd encourage an implementation that:

1. Uses an algorithm that's designed for hashing passwords like scrypt, PBKDF2 or bcrypt.
2. Uses the same semantics as passwords stored in /etc/[shadow|master.passwd]
3. sniffs the userlist when the plugin is loaded, and if encrypted passwords are present in the file (can be detected based on password prefix), removes CRAM-MD5 from the auth types (CRAM-MD5 requires the plain text password to be stored)
4. is backwards compatible: detects if the password is plain or crypto and then performs the correct comparison.

**Comment by AuspeXeu** [comment]
Created a plugin for this https://www.npmjs.com/package/haraka-plugin-auth-enc-file

**Comment by msimerson** [comment]
Awesome @AuspeXeu . Next steps: create a PR in this repo that:

- adds your plugin to the [registry](https://github.com/haraka/Haraka/blob/master/Plugins.md)
- updates the [auth/auth_flat](https://github.com/haraka/Haraka/blob/master/docs/plugins/auth/flat_file.md) plugin docs to announce that your plugin exists as a recommended alternative.
- contains the words "fixes #2379" in the PR.

**Comment by AuspeXeu** [comment]
Will do :) - glad to see that contributions are so welcomed. Really great project you got going here!
