### ISSUE TITLE
Adding `From` in header with non-ASCII characters result in invalid mail address

### ISSUE THREAD

**Issue by jiegec** [haraka/Haraka#2381]
Related code:
https://github.com/haraka/Haraka/blob/8c7ce575512ea5d64ae8a64c0ddf89091e44e796/mailheader.js#L140-L144

Suppose I add a header `From: SOME_CJK_HERE <i@example.com>` , then it gets encoded as:
`From: =?UTF-8?q?=AB=CD=EF=FE=DC=BA <i@example.com>?=`, which is a bad address. I found this problem, when `dkim_sign` fail to find the domain of the sender.

I think the solution would be:
1. add_header_raw() or something
2. only encode those characters, but not those ASCII ones.

Additionally, I would like to choose the Base64 encoding, because some clients do not support QPEncode.

**Comment by baudehlo** [comment]
What's bad about it?

**Comment by jiegec** [comment]
When `dkim_sign` tries to find the domain of the sender address, it fails to do so.

**Comment by baudehlo** [comment]
dkim_sign needs to use get_decoded() on the From header, not get().

https://github.com/haraka/Haraka/blob/master/plugins/dkim_sign.js#L303

Try that and let me know if it works.

**Comment by jiegec** [comment]
Yes, it is working now.

**Comment by jiegec** [comment]
I finally encoded the address in my code in production. Some mail clients fail to read `=?UTF-8?q?=AB=CD=EF=FE=DC=BA <i@example.com>?=`. I manually encoded it as `=?UTF-8?q?=AB=CD=EF=FE=DC=BA?= <i@example.com>`.

**Comment by baudehlo** [comment]
Eww, why are they so broken? I guess we could do similar, but it seems so
inefficient.

**Comment by baudehlo** [comment]
Re-opening until the issue is fixed here.

**Comment by jiegec** [comment]
I think the address `=?UTF-8?q?=AB=CD=EF=FE=DC=BA <i@example.com>?=` does not conform to RFC 2822.

**Comment by celesteking** [comment]
Patches are welcome. 
No patches? Issue closed!

**Comment by jiegec** [comment]
I think it is fixed in #2568.
