### ISSUE TITLE
closed connection while we were processing mail

### ISSUE THREAD

**Issue by Manishjodhani** [haraka/Haraka#2384]
### system info
Haraka | Haraka.js — Version: 2.8.18
Node | v9.11.1
OS | Centos 6.9
### Expected behavior
[root@v ~]# haraka -c /etc/haraka/
loaded TLD files: 1=1544 2=8347 3=2424
loaded 8447 Public Suffixes
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.18
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[NOTICE] [-] [core] worker started worker=1 pid=29023
[NOTICE] [-] [core] worker started worker=2 pid=29028
loaded TLD files: 1=1544 2=8347 3=2424
loaded TLD files: 1=1544 2=8347 3=2424
loaded 8447 Public Suffixes
loaded 8447 Public Suffixes
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.18
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[INFO] [-] [core] [outbound] Loading queue for pid: 28761
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
[NOTICE] [-] [core] Listening on IP:587
[NOTICE] [-] [core] worker 1 listening on IP:587
[INFO] [-] [core] [outbound] Grabbing queue files for pid: 28761
[INFO] [-] [core] [outbound] Done fixing up old PID queue files
[INFO] [-] [core] [outbound] 0 files in my delivery queue
[INFO] [-] [core] [outbound] 1 files in my load queue
[INFO] [-] [core] [outbound] 0 files in my temp fail queue
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.18
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[INFO] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Looking up A records for: gmail-smtp-in.l.google.com
[INFO] [-] [core] [outbound] Loading queue for pid: 28766
[INFO] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Attempting to deliver to: IP:25 (0) (0)
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
[INFO] [-] [core] [outbound] [outbound::IP:undefined:50] dispense() clients=1 available=0
[NOTICE] [-] [core] Listening on IP:587
[NOTICE] [-] [core] worker 2 listening on IP:587
[INFO] [-] [core] [outbound] Grabbing queue files for pid: 28766
[INFO] [-] [core] [outbound] Done fixing up old PID queue files
[INFO] [-] [core] [outbound] 0 files in my delivery queue
[INFO] [-] [core] [outbound] 1 files in my load queue
[INFO] [-] [core] [outbound] 0 files in my temp fail queue
[INFO] [83F4DB40-9EEF-47D3-93BF-1BE9757494E5.1.1] [outbound] Looking up A records for: gmail-smtp-in.l.google.com
[INFO] [83F4DB40-9EEF-47D3-93BF-1BE9757494E5.1.1] [outbound] Attempting to deliver to: IP:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::IP:undefined:50] dispense() clients=1 available=0
[INFO] [-] [core] [outbound] acquired socket BBEA00FF-7399-4104-9509-D5D11373F64B for outbound::25:74.125.204.27:undefined:50
[INFO] [-] [core] [outbound] acquired socket 776F7312-4C42-4B04-A97D-A6F99C87B0DE for outbound::25:74.125.204.27:undefined:50
[ERROR] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Remote end 74.125.204.27:25 closed connection while we were processing mail. Trying next MX.
[INFO] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Looking up A records for: alt1.gmail-smtp-in.l.google.com
[INFO] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Attempting to deliver to: 173.194.200.26:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:173.194.200.26:undefined:50] dispense() clients=1 available=0
[ERROR] [83F4DB40-9EEF-47D3-93BF-1BE9757494E5.1.1] [outbound] Remote end 74.125.204.27:25 closed connection while we were processing mail. Trying next MX.
[INFO] [83F4DB40-9EEF-47D3-93BF-1BE9757494E5.1.1] [outbound] Looking up A records for: alt1.gmail-smtp-in.l.google.com
[INFO] [83F4DB40-9EEF-47D3-93BF-1BE9757494E5.1.1] [outbound] Attempting to deliver to: 173.194.200.26:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:173.194.200.26:undefined:50] dispense() clients=1 available=0
[INFO] [-] [core] [outbound] acquired socket 8BD4884E-22DF-4A1A-9050-7A2F489FA14A for outbound::25:173.194.200.26:undefined:50
[INFO] [-] [core] [outbound] acquired socket 1B964C40-1616-4F1D-B34E-4FC83D57BF79 for outbound::25:173.194.200.26:undefined:50
[ERROR] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Remote end 173.194.200.26:25 closed connection while we were processing mail. Trying next MX.
[INFO] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Looking up A records for: alt2.gmail-smtp-in.l.google.com
[INFO] [B43C511A-B7AC-496D-8790-EE0DE99FF6F5.1.1] [outbound] Attempting to deliver to: 209.85.200.27:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:209.85.200.27:undefined:50] dispense() clients=1 available=0
[ERROR] [83F4DB40-9EEF-47D3-93BF-1BE9757494E5.1.1] [outbound] Remote end 173.194.200.26:25 closed connection while we were processing mail. Trying next MX.

**Comment by smfreegard** [comment]
You need to set `config/me` to your fully-qualified hostname.

**Comment by Manishjodhani** [comment]
I have created file me in config and restart the haraka but same problem again

**Comment by smfreegard** [comment]
You did the equivalent of `hostname -f > config/me` right?

If so -

`echo LOGPROTOCOL > config/loglevel`

Then try again - and then paste your output.

**Comment by Manishjodhani** [comment]
[ERROR] [-] [core] tls key tls_key.pem could not be loaded.
[ERROR] [-] [core] Config {
  root_path: '/etc/haraka/config',
  module_config: [Function],
  overrides_path: '/etc/haraka/config' }
[ERROR] [-] [core] tls cert tls_cert.pem could not be loaded.
[root@vps177316 Haraka]# [CRIT] [-] [core] TypeError [ERR_INVALID_ARG_TYPE]: The "cert" argument must be one of type string, Buffer, TypedArray, or DataView
[CRIT] [-] [core]     at validateKeyCert (_tls_common.js:59:11)
[CRIT] [-] [core]     at Object.createSecureContext (_tls_common.js:114:9)
[CRIT] [-] [core]     at new exports.connect (_tls_wrap.js:1116:48)
[CRIT] [-] [core]     at pluggableStream.socket.upgrade (/usr/lib/node_modules/Haraka/tls_socket.js:672:27)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/outbound/hmail.js:750:36)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:180:13)
[CRIT] [-] [core]     at pluggableStream.on_socket_data (/usr/lib/node_modules/Haraka/line_socket.js:25:20)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:180:13)
[CRIT] [-] [core]     at Socket.<anonymous> (/usr/lib/node_modules/Haraka/tls_socket.js:59:18)
[CRIT] [-] [core]     at Socket.emit (events.js:180:13)
Now this error showing

**Comment by smfreegard** [comment]
So your tls_cert.pem file is broken then.

**Comment by Manishjodhani** [comment]
can you tell me how to loaded tls??

**Comment by smfreegard** [comment]
It's in the documentation: https://github.com/haraka/Haraka/blob/master/docs/plugins/tls.md

**Comment by Manishjodhani** [comment]
Hi,
Now i'm this getting this error "550 Authentication required"

**Comment by smfreegard** [comment]
I fail to see how going from a dropped connection at Gmail to a TLS error to an Authentication required error are in any way related to the original log output you gave me.

Please read the documentation and understand a bit how SMTP actually works before raising issues here as it wastes our time if you don't.

Authentication required means that you need to send SMTP AUTH from your client which requires an auth/* plugin to be loaded and configured.  I expect you're getting this because you're trying to send mail over port 587 which is the submission port which requires authentication before you are allowed to relay messages.

Alternatively you can configure the `relay` plugin, configure an ACL and use port 25 to inject the messages.
