### ISSUE TITLE
Do a logwarn() when smtp.ini nodes= is unset

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#2388]
Most people miss this setting, and it's important for keeping the server up (and for scalability). We should issue a logwarn() on startup if it's unset.

Not that anyone reads the logs though...

**Comment by msimerson** [comment]
> Not that anyone reads the logs

Well said. Which means, just adding a log message isn't a very good fix.

In #2573 I have also set the default value to nodes=1. That solves the "keeping the server up" half of the issue. I've also added a logwarn with a link to the wiki page on performance tuning Haraka. That's the other half of the issue and it directs people to a good resource.
