### ISSUE TITLE
Using with another MTA?

### ISSUE THREAD

**Issue by rightaway** [haraka/Haraka#2405]
Sorry if the question doesn't belong here, I'm new to sending mail and would like to learn Haraka. The wikipedia page says

> Haraka is frequently used as a filtering MTA in front of other MTAs that lack the performance and/or filtering capabilities of Haraka. Craigslist uses Haraka[8] to handle inbound and then forward validated connections to Postfix

And the README says

> Haraka makes no attempt to be a mail store (like Exchange or Postfix/Exim/Qmail), a LDA, nor an IMAP server (like Dovecot or Courier). Haraka is typically used with such systems.

What would be the benefit of putting Haraka in front of something like Postfix instead of sending the mail directly with Haraka?

What functionality would Postfix offer that Haraka doesn't?

In the quote above, what is meant by `mail store`? I tried googling it but I couldn't find anything. I thought Postfix etc are for sending mail not storing it, so I'm just confused at the `mail store` terminology.

**Comment by msimerson** [comment]
> What would be the benefit of putting Haraka in front of something like Postfix instead of sending the mail directly with Haraka? What functionality would Postfix offer that Haraka doesn't?

We appreciate your interest in Haraka, but it's not the right MTA for you. Haraka is primarily for SMTP hackers who have plenty of experience with other MTAs and greater flexibility and customization than they offer. IOW, if you have to ask, it's not for you.
