### ISSUE TITLE
Invalid DKIM signature with empty email

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2410]
### system info
Haraka | Haraka.js — Version: 2.8.18
 --- | :--- 
Node | v8.11.1
OS | Linux e3bb5005bb6e 4.10.0-041000-generic #201702191831 SMP Sun Feb 19 23:33:19 UTC 2017 x86_64 GNU/Linux
openssl | OpenSSL 1.1.0f  25 May 2017

### Steps to reproduce
Send email with empty body AND empty subject to something like mail-tester.com

**Comment by AuspeXeu** [comment]
What do you mean by invalid signature? It seems like there is no signature generated in that case.

**Comment by analogic** [comment]
Nope, tested right now. Invalid signature is generated. I guess thats something like "null" js stuff

**Comment by AuspeXeu** [comment]
How do you test this? My gmail does not complain.

**Comment by analogic** [comment]
> Steps to reproduce
Send email with empty body AND empty subject to something like mail-tester.com
