### ISSUE TITLE
Confused with queue and rcpt hook

### ISSUE THREAD

**Issue by bibudha** [haraka/Haraka#2430]
Hello

I am using haraka for handling both incoming and outgoing mails. But sometimes such situation happens like multiple recipient of my mail server receive mail at time. Suppose one mail is for two user of our server.
At that time i have used rcpt hook to check the user and then in queue hook it process the mail. But in that case rcpt hook runs twice where as queue hook runs for just one. Why so ?

**Comment by celesteking** [comment]
You might want to ask this generic question [on SO](https://stackoverflow.com/questions/tagged/haraka). It's more related to SMTP proto in general than to haraka in particular.

**Comment by bibudha** [comment]
but data hook is running if I mailed from any gmail with custom domain. But its not running if I mailed from normal gmail account. Is there any difference in transaction object ?

**Comment by bibudha** [comment]
Actually the rcpt_to object got new email object pushed. But in other case it remains unique. Like this
 rcpt_to: \n
   [ Address {\n
       original: '<admin@preranasharma.com>',\n
       user: 'admin',\n
       host: 'preranasharma.com' },\n
     Address {\n
       original: '<ritu@preranasharma.com>',\n
       user: 'ritu',\n
       host: 'preranasharma.com' } ],\n


--------------------------------------------
  rcpt_to: \n
   [ Address {\n
       original: '<admin@preranasharma.com>',\n
       user: 'admin',\n
       host: 'preranasharma.com' } ],\n

  rcpt_to: \n
   [ Address {\n
       original: '<ritu@preranasharma.com>',\n
       user: 'ritu',\n
       host: 'preranasharma.com' } ],\n

ALso in above case UUID remains so haraka processes only once but in other case it has different UUID  which is correct. What configuration do I have to change to receive the mail differently for multiple users ?

**Comment by msimerson** [comment]
> But in that case rcpt hook runs twice where as queue hook runs for just one. Why so ?

Because that's how it works (as designed).

> What configuration do I have to change to receive the mail differently for multiple users ?

That depends on how you queue the messages. Have a look at smtp_forward's `one_message_per_rcpt=true` setting.
