### ISSUE TITLE
Transaction UUID remains same if mail received from Gmail to multiple users in haraka

### ISSUE THREAD

**Issue by bibudha** [haraka/Haraka#2433]
Hello 

I have a mail server setup with haraka. When someone mails from gmail to multiple users in haraka the transaction UUID remains same for both the users. So haraka treats both the mail as same mail. But sometimes when someone mails from custom domain gmail the UUID changes for the both the user and haraka treats wisely for the both the users.

Any configuration changes I have to make for this so haraka treat the mail differently from Gmail

**Comment by smfreegard** [comment]
No - that's how e-mail works.

One message to multiple recipients is a sent as a single transaction and unit and is the most efficient way to do this.

Forcing GMail to split recipients into separate deliveries will be 1) Slow and 2) Use N x bandwidth.

Maybe if you actually explain what you're trying to do, then it might be more obvious.   The transaction UUID will never be unique to the recipient for a multiple recipient message.

**Comment by bibudha** [comment]
Got it. I have handled now.
