### ISSUE TITLE
Unable to extract attachments using attachment_stream

### ISSUE THREAD

**Issue by apmcodes** [haraka/Haraka#2437]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.18
 --- | :--- 
Node | v8.10.0
OS | Linux devtop 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.0g  2 Nov 2017

Situation: Need to parse the outbound emails and store the parts including attachments in mongodb. parse_body enabled in hook_data. Able to extract the attachment in attachment_hooks but email/ attachment size more than databytes also get stored before the email being rejected. So need this in hook_queue_outboud. Refering to https://gist.github.com/smfreegard/4191321

Issue: Able to pipe the entire message using message_stream in hook_queue_outbound, Trying to extract the attachments before queuing, but attachment_stream on the attachment object doesn't seem to work (updated with #2424 ). Not sure what going wrong, have been trying this since 2 days. Please guide.

Gist https://gist.github.com/apmcodes/68a0c13e1ac7237181b423247c4dc919

Please refer to the below Haraka output.

**Comment by apmcodes** [comment]
SERVER SIDE

Haraka hangs on the line transaction.body.children[1].attachment_stream.pipe(s); 
and times out after
[INFO] [-] [queue/stream] New inbound email detected, inserting into mongodb

Haraka Output
sudo node haraka.js
[sudo] password for xxx: 
WARNING: Not running installed Haraka - command line arguments ignored
loaded TLD files: 1=1544 2=8347 3=2424
loaded 8447 Public Suffixes
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.18
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] loading tls.ini
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: data/parse
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: queue/stream
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[NOTICE] [-] [max_unrecognized_commands] the plugin max_unrecognized_commands has been replaced by 'limit'. Please update config/plugins
[NOTICE] [-] [core] Listening on 127.0.0.1:25
[NOTICE] [-] [core] Listening on 127.0.0.1:587
[INFO] [-] [core] [outbound] Loading outbound queue from /work/git/tranx/gateway/master/Haraka/queue
[NOTICE] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1] [core] connect ip=127.0.0.1 port=42374 local_ip=127.0.0.1 local_port=25
[INFO] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1] [helo.checks] multi: true, skip:proto_mismatch(private), host_mismatch(private)
[ERROR] [-] [tls] no valid TLS config
[INFO] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params=AUTH retval=OK msg=""
[INFO] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="c210cDE=" retval=OK msg=""
[INFO] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1] [core]  hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="c210cDE=" retval=OK msg=""
[NOTICE] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core] sender <xxx@xxx> code=CONT msg=""
[INFO] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core]  hook=rcpt plugin=rcpt_to.in_host_list function=hook_rcpt params=<xxx@gmail.com> retval=OK msg=""
[NOTICE] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core] recipient <xxx@gmail.com> code=OK msg="" sender=xxx@xxx
[INFO] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core] HOOK DATA
[NOTICE] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core] message mid=<20180529122829.057406@devtop> size=945 rcpts=1/0/0 delay=0.007 code=CONT msg=""
[INFO] [-] [queue/stream] New inbound email detected, inserting into mongodb
[CRIT] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core] Plugin queue/stream timed out on hook queue_outbound - make sure it calls the callback
[INFO] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core]  hook=queue_outbound plugin=queue/stream function=hook_queue_outbound params="" retval=DENYSOFT msg="plugin timeout"
[NOTICE] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core] queue code=DENYSOFT msg="plugin timeout (C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1)"
[NOTICE] [C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1] [core] disconnect ip=127.0.0.1 rdns=Unknown helo=devtop relay=Y early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=945 lr="450 plugin timeout (C81EEE2F-96F0-4005-8E3B-EBB7A21843C1.1)" time=30.045



CLIENT SIDE

swaks -server 127.0.0.1 -p 25 -to xxx@gmail.com -from xxx@xxx     --auth    --auth-user=smtp1    --auth-password=smtp1 --attach /var/tmp/test --timeout 120
=== Trying 127.0.0.1:25...
=== Connected to 127.0.0.1.
<-  220 devtop ESMTP Haraka/2.8.18 ready
 -> EHLO devtop
<-  250-devtop Hello Unknown [127.0.0.1], Haraka is at your service.
<-  250-PIPELINING
<-  250-8BITMIME
<-  250-SMTPUTF8
<-  250-SIZE 26214400
<-  250 AUTH LOGIN
 -> AUTH LOGIN
<-  334 VXNlcm5hbWU6
 -> c210cDE=
<-  334 UGFzc3dvcmQ6
 -> c210cDE=
<-  235 Authentication successful
 -> MAIL FROM:<xxx@xxx>
<-  250 sender <xxx@xxx> OK
 -> RCPT TO:<xxx@gmail.com>
<-  250 recipient <xxx@gmail.com> OK
 -> DATA
<-  354 go ahead, make my day
 -> Date: Tue, 29 May 2018 12:28:29 +0530
 -> To: xxx@gmail.com
 -> From: xxx@xxx
 -> Subject: test Tue, 29 May 2018 12:28:29 +0530
 -> Message-Id: <20180529122829.057406@devtop>
 -> X-Mailer: swaks v20170101.0 jetmore.org/john/code/swaks/
 -> MIME-Version: 1.0
 -> Content-Type: multipart/mixed; boundary="----=_MIME_BOUNDARY_000_57406"
 -> 
 -> ------=_MIME_BOUNDARY_000_57406
 -> Content-Type: text/plain
 -> 
 -> This is a test mailing
 -> ------=_MIME_BOUNDARY_000_57406
 -> Content-Type: application/octet-stream; name="test"
 -> Content-Description: test
 -> Content-Disposition: attachment; filename="test"
 -> Content-Transfer-Encoding: BASE64
 -> 
 -> J3VzZSBzdHJpY3QnOwoKbW9kdWxlLmV4cG9ydHMgPSB7CiAgICBwbXRhOiB7CiAgICAgICAgbmFt
 -> ZTogJ2RldkJvdCcsCiAgICB9LAogICAgZGVmYXV0TGFiZWxzOiB7cG10YTogJ2RldkJvdCd9LAog
 -> ICAgdGltZW91dDogNTAwMCwKICAgIHNlcnZlcjogewogICAgICAgIGhvc3Q6ICdsb2NhbGhvc3Qn
 -> LAogICAgICAgIHBvcnQ6ICczMDAwJywKICAgIH0KfQo=
 -> 
 -> ------=_MIME_BOUNDARY_000_57406--
 -> 
 -> 
 -> .

**Comment by smfreegard** [comment]
You can't do this:

`````
    // testing - manually extract the first attachment
    transaction.body.children[1].attachment_stream.pipe(s);
`````

As the attachment streams are completely finished by hook_data().   We don't buffer the attachments streams like the message stream is currently.

See the `attachment` plugin as a guide as to how to use the attachment streams.   You would have to save each attachments separately and you would need to implement the same `wait_for_attachment_hooks()` in hook_data.

All you can do in hook_queue_outbound would be to store the entire message including the attachments via:

    transaction.message_stream.pipe(s);

**Comment by apmcodes** [comment]
Okay, will go though it. Thank you very much for the guidance.
