### ISSUE TITLE
How to prevent login users from counterfeit senders

### ISSUE THREAD

**Issue by renothing** [haraka/Haraka#2443]
I did a test like following:
use **user-a@xx.com** and its password login to haraka send an email with "From: **user-b@xx.com**" to an address, it succeed.
when I check the Email Original Message, I can't find anything if it's fake sender, everything looks ok, it's the same as really **user-b@xx.com**

how to keep users login and From consistency to avoid fishing?

**Comment by analogic** [comment]
Simply by creating plugin which parses From header from transaction:

1. get header with connection.transaction.header.get('From')
2. parse it with https://github.com/haraka/node-address-rfc2822
3. compare it with authenticated user
