### ISSUE TITLE
Bounce messages

### ISSUE THREAD

**Issue by thenitai** [haraka/Haraka#2444]
Hi all,

Is there a way to not bounce bounced messages? I've looked all over but do not see any setting. Also, is there a setting to limit a bounce message to a recipient, e.g., only send 3 bounce messages?

Thank you.

**Comment by analogic** [comment]
Just create plugin which register to `bounce` hook and counts bounces to recipient with expiration via redis. (or just returns OK to disable it completely) see https://haraka.github.io/manual/Outbound.html#the-deferred-hook

**Comment by thenitai** [comment]
Sorry, have to come back to this one. 

All bounce messages from Haraka have never any "deferred_rcpt" or "bounced_rcpt", hence I cannot really track the bounced to an address. 

This is what is being returned in the "error" object:

```
"mx" : {
  "exchange" : "aspmx.l.google.com", 
  "priority" : NumberInt(10), 
  "family" : "A", 
  "bind_helo" : "mysmtp.net"
}, 
"deferred_rcpt" : null, 
"bounced_rcpt" : null
```

I hope I'm just missing something completely obvious here :)
