### ISSUE TITLE
Connection errors when set up HAProxy

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2445]
Haraka v2.8.18

I set up one HAProxy(10.0.0.100) server and two haraka(10.0.0.11, 10.0.0.12) instances.

in HAProxy.cfg:
```
listen email_proxy
    bind *:25,*:587
        mode tcp
        option tcplog
        option smtpchk
        balance roundrobin
	server Haraka01 10.0.0.11 check-send-proxy check inter 10s send-proxy
	server Haraka02 10.0.0.12 check-send-proxy check inter 10s send-proxy
```

in HAProxy log: 
Server email_proxy/Haraka01 is UP
Server email_proxy/Haraka02 is UP

in Haraka01 log:
[core] client [10.0.0.100] connection error: Error: write EPIPE
.....
[core] client [10.0.0.100] connection error: Error: read ECONNRESET

in Haraka02 log:
[core] client [10.0.0.100] connection error: Error: write EPIPE
.....
[core] client [10.0.0.100] connection error: Error: read ECONNRESET

BTW: which machine is for creating tls certificates?  If I generate certificates on HAProxy, can i copy to haraka instances which refered in tls.ini ?

**Comment by smfreegard** [comment]
Is 10.0.0.100 in haproxy_hosts?

**Comment by zinwalin** [comment]
@smfreegard Yes, 10.0.0.100 was added in haproxy_hosts file.

**Comment by celesteking** [comment]
Haraka works fine with haproxy enabled, so something must be amiss in your configuration. You will have to tcpdump to see what's going on on the wire.

I'd recommend trying the following instead of `option smtpchk`:

        option  log-health-checks
        option tcp-check
        tcp-check expect rstring 2\d+[\s\-]+
        tcp-check send QUIT\r\n
        tcp-check expect rstring 2\d+[\s\-]+

**Comment by msimerson** [comment]
Can this issue be closed?
