### ISSUE TITLE
Plugin data.headers failed: TypeError: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2449]
Another [CRIT] log I've found at my system

### system info

Haraka | Haraka.js — Version: 2.8.18
 --- | :--- 
Node | v8.11.2
OS | Linux ... 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 GNU/Linux
openssl | OpenSSL 1.1.0f  25 May 2017

### Observed behavior

It is typicaly seen with cron messages
- MAIL FROM:<system@localhost>
- email header "From: root (Cron Daemon)"

I am unable to wrap around my head how it is able to get to line https://github.com/haraka/Haraka/blob/770aa4edeaa96353a1048115aa24e5a5360c9a22/plugins/data.headers.js#L301

It should already return at previous lines if it fails to parse header

**Comment by celesteking** [comment]
yeah, that's impossible. mind providing full stack trace?

**Comment by analogic** [comment]
I don't have one - the only stacktraces I get are when haraka shutdowns completely due error. This is not the case and the only message I have is at subj so maybe I am searching at wrong place but address property is accessed only at line 301...

**Comment by msimerson** [comment]
hey @analogic , if you get a chance, please test #2458. I think that'll fix the issue.

**Comment by msimerson** [comment]
The reason the “bug“ happens is because the address fails to parse.  When `address-rfc2822.parse` fails to parse the “root (cron)” address it throws an exception which is caught by the try.  When the exception is caught, execution within the try block immediately ends and the code in the catch block is executed.

**Comment by celesteking** [comment]
I'm with @analogic . the catch block returns, so nothing is gonna be executed afterwards.
Unless we're looking at different file.

**Comment by msimerson** [comment]
You guys are partly right. `address-rfc2822.parse()` does throw and then the catch block executes. However, the catch block doesn't return. 😮 The catch expects `address-rfc2822` to be a good little JS module and throw an error object which it dutifully prints by accessing the .message property. However, `address-rfc2822` instead throws a string and there things go awry.

**Comment by msimerson** [comment]
I'm glad you guys pursued this. I didn't know exactly why #2458 fixed it, I just knew from the log messages that **somehow** after `address-rfc2822.parse()` threw, the code below the try/catch was getting executed.

**Comment by baudehlo** [comment]
That probably changed when I changed the internals of it. Mea culpa.
