### ISSUE TITLE
Parsing of message/rfc822 is not implemented

### ISSUE THREAD

**Issue by Thealoner** [haraka/Haraka#2462]
### system info

Haraka | Haraka.js — Version: 2.8.18
 --- | :---
Node | v7.10.1
OS | Linux 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior
We send an email with an attached message (`Content-Type: message/rfc822`) to Haraka (see example below).
We expect that Haraka will parse the attached message. We would like to get the attached message headers, body, and attachments from Haraka.

### Observed behavior
Attached message is being ignored.

### Steps to reproduce
Send this email to Haraka to reproduce the issue:

```
MIME-Version: 1.0
Received: by 10.170.174.11 with HTTP; Wed, 12 Feb 2014 00:11:54 -0800 (PST)
Date: Mon, 02 Jul 2018 10:11:54 +0200
Delivered-To: to@example.com
Subject: Re: test
From: from@example.com
To: to@example.com
Content-Type: multipart/mixed; boundary=001a113a5f342eb47b04f2312025

--001a113a5f342eb47b04f2312025
Content-Type: multipart/alternative; boundary=001a113a5f342eb47704f2312023

--001a113a5f342eb47704f2312023
Content-Type: text/plain; charset=KOI8-R
Content-Transfer-Encoding: quoted-printable

test

--001a113a5f342eb47704f2312023--
--001a113a5f342eb47b04f2312025
Content-Type: message/rfc822;


Delivered-To: to2@example.com
Date: Tue, 11 Mar 2014 19:54:46 +0400
From: from2@sample.com
To: to2@example.com
Subject: Test rfc822
Mime-Version: 1.0
Content-Type: text/plain;

Example content

--001a113a5f342eb47b04f2312025--
```

**Comment by baudehlo** [comment]
Not a bug. We don’t parse attachments.

**Comment by Thealoner** [comment]
@baudehlo Thank you for your reply. Could you please take a look at the message? It is not about parsing attachments. The message has another message included and that message is getting lost. Is there a way to preserve it?

**Comment by baudehlo** [comment]
The message “included” is an attachment.
