### ISSUE TITLE
TLS not loading again at 2.8.20

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2463]
I guess I have some kind of config combination which prevents TLS working due #2459

I am getting "no TLS valid config" and no STARTTLS capability, but when I insert tls_socket.load_tls_ini() somewhere at tls.js it works as intended. I have not found place where it should actualy load at inbound, am I missing something?

**Comment by analogic** [comment]
It seems that #2429 at master partly fixed this BUT it will load tls socket settings with tls.get_plugin_ready() only when outbound is enabled AND haraka is not at cluster mode with https://github.com/haraka/Haraka/blame/master/outbound/queue.js#L72

**Comment by msimerson** [comment]
Oooooooohhhhhhh, we're no longer calling `tls_socket.load_tls_ini();` in plugins.tls. Try adding just that in `plugins/tls.register()` and that should solve the problem.

**Comment by baudehlo** [comment]
Time for 2.8.21 ;)

**Comment by analogic** [comment]
Yep that works!
