### ISSUE TITLE
How to use html and change header from name

### ISSUE THREAD

**Issue by seanfmark** [haraka/Haraka#2466]
Hi!
I'm newbie on node.js using Haraka, Today i've success Install Haraka on my Centos 7 Server.
Now i want to ask how i can using html as Subject Body Email ? And How to change the Header from name ? like Picture on below

Header Name
<img src="https://cdn.pbrd.co/images/Ht1moCG.png"/>

Html Body Text
<img src="https://cdn.pbrd.co/images/Ht1nc57.png"/>

Thank you!

**Comment by baudehlo** [comment]
I don’t even think that’s what this question was about: I think it was basically about how to make a HTML email. There’s some good info in the nodemailer documentation about that. But it’s unrelated to Haraka.

Closing.

**Comment by jchook** [comment]
Ah, I saw the title:

> How to use html and **change header from name**

and this section of the OP:

> And How to change the Header from name ?

Which I assumed meant he/she wanted to alter existing MIME headers/body.
