### ISSUE TITLE
Add a headers hook

### ISSUE THREAD

**Issue by mikehardenize** [haraka/Haraka#2475]
### system info

Haraka | Haraka.js — Version: 2.8.20
 --- | :--- 
Node | v10.1.0
OS | Darwin mikes-macbook.grepular.com 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
openssl | OpenSSL 1.0.2o  27 Mar 2018

### Question

I wish to do "things" to the attachments of an incoming email, but only if the email Subject header matches a certain pattern. I've managed to do this by setting `transaction.parse_body = 1`, and then checking `transaction.header.get('Subject')` inside of my attachment_hook's.

This seems wasteful though. If the email subject doesn't match, I don't want to do anything else to the body, so there seems little point in mime parsing it and calling attachment hooks.

I feel like we're missing a "headers" hook, which is called after the first blank line is sent during the DATA phase. Obviously, we can't block the client from sending the body at that point, but it at least gives us time to check the headers and decide if we want to turn on "parse_body" and add attachment hooks. Perhaps even dropping the connection whilst the client is still in the middle of sending it's body if we want to be rude.

**Comment by msimerson** [comment]
This is interesting, but sounds a lot like a premature optimization based on squishy feelings. I'd suggest doing some benchmarks with and without parse_body enabled, so you can hang some meat onto your concerns over waste. If there's some meat there, then reopen this issue citing your data.

On a related note, you may wish to pay attention to `transaction.header.get_decoded('Subject')` instead of `get('Subject')`.

**Comment by baudehlo** [comment]
I actually don't mind the idea of this (though there's the thought that it
adds overhead for everyone - additional hooks are more overhead). I think
parsing the email is probably not as lightweight as we'd like it to be.

**Comment by msimerson** [comment]
> I actually don't mind the idea of this

I don't mind either, but I'd like data to back it up. My suspicion is that since the vast majority of messages are very small, the overall effect of parsing them all is also not very consequential.
