### ISSUE TITLE
Dynamically disable any plugin per connection

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2487]
There are couple plugins which use 
 - conn.is_private
 - conn.relaying
 - its own ip whitelist
as indicator to skip itself.  Year ago I've commited "conn.notes.disable_karma" to disable karma plugin. My case is that right now I need to dynamicaly disable early_talker plugin and I would rather use some better way than add another note condition. I am wondering if there is any more generic way to disable plugin per connection? 

If not my idea is to create something like conn.skip_plugins = [] and add skipping condition to plugins.run_next_hook OR later introduce some kind of framework which will handle is_private/relaying/whitelist aside from plugins code (not sure if it is good idea)

**Comment by smfreegard** [comment]
I do something similar here.   I delay *all* pre-DATA rejections until hook_rcpt by using hook_deny and storing each rejection.

That way I can apply per-recipient whitelisting and to skip certain plugin rejections, which seems to be exactly what you are trying to achieve.

**Comment by analogic** [comment]
Awesome idea! But I don't have problem with plugin results but in case of early_talker with communication delays itself. I would like to have custom IP whitelist which at connection_init disables everything what can negatively impact delivery time (spf, asn, uribl, p0f, dnsbl, fcrdns...)

**Comment by smfreegard** [comment]
Wow - you must be doing a lot of traffic for that to matter...

**Comment by smfreegard** [comment]
FWIW - this should be easy to do.   Just add a whitelist that runs first on all of the hooks (except rcpt) that returns next(OK).   It will prevent any other plugins from running on that hook.   If you want to always run a specific plugin, make sure it runs before this plugin.    That is basically what I do here.

**Comment by analogic** [comment]
> It will prevent any other plugins from running on that hook.

Sadly there are still plugins on hook which are meant to be run. I am afraid that there is no solution to do that with current state. I will try to create PR and will see what happens :)

**Comment by Thoro** [comment]
@analogic Not sure if this covers what you need: https://github.com/creamfinance/haraka-plugin-plugin_manager

It allows to define "queues" where a check can be run on the connection object before the hooks are passed to the plugins. The check inside the yaml is a bit wonky, but I didn't want to introduce a complex js file require structure.

I also had issues with the plugin system and rewrote it yesterday, I tested all the plugins in the example config, your milage may vary.

**Comment by mike3784** [comment]
would it be possible to use external smtp and Haraka outbound depending on From email?
if i send mail from "x" i want to use sendgrid smtp relay for example(smtp forward plugin)
and if i send it from "y" Haraka outbound?

**Comment by Thoro** [comment]
haven't thought about it, but generally yes, should be possible, even though the queues would be awkward

**Comment by msimerson** [comment]
Main issue resolved in #2551 

> would it be possible to use external smtp and Haraka outbound depending on

Yes. Have a look in the code for `queue.wants`. You can set that note before queue time to specify which queue plugin (smtp_forward, outbound, discard, etc.) you want to handle that transaction.
