### ISSUE TITLE
haraka-plugin-recipient-routes split domain recipient routing

### ISSUE THREAD

**Issue by kazoobs** [haraka/Haraka#2489]
Hello, am a newbie and trying to use haraka-plugin-recipient-routes for recipient routing kind of like split domain routing eg john@example.com > mail1.example.com and peter@example.com > mail2.example.com but does not see to work below is my  rcpt_to.routes.ini  config, am not using redis

[routes]
john@example.com=mail1.example.com:25
peter@example.com=john@example.com:25
example.com=mail1.example.com:25

### system info

Haraka | Haraka.js â Version: 2.8.20
 --- | :--- 
Node | v10.8.0
OS | Linux .localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by Dexus** [comment]
Nice config 😂 john@example.com:25 is in the wrong syntax...

Von meinem iPhone gesendet

**Comment by kazoobs** [comment]
Sorry That was a typo error,  should be peter@example.com=mail2.example.com:25

**Comment by msimerson** [comment]
"does not seem to work" is not very descriptive. Please provide your exact config file, active recipient plugins, and the log messages showing what did happen.

**Comment by kazoobs** [comment]
I have enabled haraka-plugin-recipient-routes and  rcpt_to.in_host_list, 
/rcpt_to.routes.ini config as below
[redis]
host=127.0.0.1
port=6379
db=0

[routes]
john@example.com=mail1.example.com:25
peter@example.com=mail2.example.com:25
example.com=mail3.example.com:25

below is the log giving a temp defferal 451 error.

[NOTICE] [960EC9AF-B30E-488D-A473-00380A0AF285] [core] connect ip=192.168.0.42 port=47962 local_ip=192.168.0.56 local_port=25
[INFO] [960EC9AF-B30E-488D-A473-00380A0AF285] [helo.checks] helo_host: mailstore.access.com, ips: 192.168.0.45, pass:match_re, bare_ip, dynamic, big_co(not), literal_mismatch, valid_hostname, rdns_match(org_dom), forward_dns(domain), host_mismatch
[NOTICE] [960EC9AF-B30E-488D-A473-00380A0AF285.1] [core] sender <test@access.com> code=CONT msg=""
[INFO] [960EC9AF-B30E-488D-A473-00380A0AF285.1] [core]  hook=rcpt plugin=haraka-plugin-recipient-routes function=rcpt params=<john@example> retval=OK msg=""
[NOTICE] [960EC9AF-B30E-488D-A473-00380A0AF285.1] [core] recipient <john@example.com> code=OK msg="" sender=test@access.com
[NOTICE] [960EC9AF-B30E-488D-A473-00380A0AF285.1] [core] message mid=<CF8AD1D9-2B4F-4C6C-AE91-B1EB50332F23@access.com> size=712 rcpts=1/0/0 delay=0.01 code=CONT msg=""
[NOTICE] [960EC9AF-B30E-488D-A473-00380A0AF285.1] [core] queue code=CONT msg=" (960EC9AF-B30E-488D-A473-00380A0AF285.1)"
[NOTICE] [960EC9AF-B30E-488D-A473-00380A0AF285.1] [core] disconnect ip=192.168.0.42 rdns=outbound.access.com helo=mailstore.access.com relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=712 lr="451  (960EC9AF-B30E-488D-A473-00380A0AF285.1)" time=0.159

**Comment by kazoobs** [comment]
Hello, Any assistance will be appreciated.

**Comment by kazoobs** [comment]
Think I found where was making a mistake.. Thanks all
