### ISSUE TITLE
Can't get smtp submission with starttls to work

### ISSUE THREAD

**Issue by pvagner** [haraka/Haraka#2490]
### system info

Haraka | Haraka.js — Version: 2.8.20
 --- | :--- 
Node | v10.8.0
OS | Linux host.name.not.provided 3.16.6-042stab127.46 #1 SMP Wed Mar 28 01:57:40 CEST 2018 x86_64 GNU/Linux
openssl | OpenSSL 1.1.0h  27 Mar 2018

### Expected behavior
I am trying to configure smtp submission on port 587 with start tls.

### Observed behavior
After upgrading Haraka 2.8.18 to 2.8.19 and 2.8.20 starttls is no longer advertised.
So 2.8.18 has been working fine for me and more up to date releases are not.
At the time of loading plugins no errors related to certificate loading are printed even with log level raised to debug.

### Steps to reproduce
Configure the following parameters
config/smtp.ini
```
listen=[::0]:587,127.0.0.1:25,[::1]:25
user=smtpd
group=smtpd
daemonize=true
daemon_log_file=/var/log/haraka-outbound.log
daemon_pid_file=/run/haraka-outbound.pid
spool_dir=/var/spool/haraka/outbound
spool_after=65536
me=host.name.not.provided
```

config/tls.ini
```
key=mail.name.not.provided_privkey.pem
cert=mail.name.not.provided_fullchain.pem
dhparam=ssl-dhparams.pem
requestCert=false
[outbound]
key=host.name.not.provided_privkey.pem
cert=host.name.not.provided_fullchain.pem
dhparam=ssl-dhparams.pem
```
This instance of haraka is used for outbound email only. Thus it accepts mails on local addresses on port 25 and also port 587 via starttls.
The starttls portion of the config is not working.
All mails including local mails are delivered via smtp using mx hosts configured in the DNS system.
That includes delivery of local mails which are sent via smtp to another instance of haraka running on the same machine listening on publicly visible interfaces port 25. That other instance then relays through to dovecot via lmtp.
I have other bits and pieces in the config e.g. rspamd plugin and ldap plugin for resolving aliases and veryfying senders if they are allowed to post.
 All the certs and keys are accessible to root and are not accessible to smtpd user which haraka drops its privileges to.
Once again nothing has changed in my config and upgrade of haraka from 2.8.18 to a more recent version has introduced this starttls related issue.

Debug log:
```
[NOTICE] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] connect ip=212.55.230.33 port=40654 local_ip=:: local_port=587
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running connect_init hooks
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running connect_init_respond
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running lookup_rdns hooks
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running connect hooks
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running ehlo hooks
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running capabilities hooks
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running capabilities hook in tls plugin
[ERROR] [-] [tls] no valid TLS config
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core]  hook=capabilities plugin=tls function=advertise_starttls params="" retval=CONT msg=""
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running capabilities hook in ldap plugin
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core]  hook=capabilities plugin=ldap function=hook_capabilities params="" retval=CONT msg=""
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running quit hooks
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] client has disconnected
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running disconnect hooks
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] client has disconnected
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] running disconnect hook in tls plugin
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] client has disconnected
[DEBUG] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core]  hook=disconnect plugin=tls function=hook_disconnect params="" retval=CONT msg=""
[NOTICE] [C23D6B78-5BB5-49A3-AE9F-4A55A6ACE332] [core] disconnect ip=212.55.230.33 rdns=ipe-gw.mi.slovanet.sk helo=[10.250.146.62] relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="" time=0.201
```

**Comment by baudehlo** [comment]
Yikes - just experienced this too. Will try and fix it today.

**Comment by baudehlo** [comment]
So mine was just missing `tls` in config/plugins - do you have it there?

**Comment by pvagner** [comment]
tls is specified in the config/plugins and it also appears to be loaded from the [full log](https://privatebin.net/?5a0044565492c7a1#VoH9QT6RLGUVHtflBX3iyZ8QbXQU21IB4aN76Urog+k=). Is there something else I should check please?

**Comment by baudehlo** [comment]
Can you try the current master branch? We just fixed some bugs around
outbound tls.

**Comment by pvagner** [comment]
okay, that appears to work.
However I'm unable to install haraka from git system wide so I have to run it directly from the git checkout until this is released.

**Comment by baudehlo** [comment]
There's a release in progress. Should be out soon.

**Comment by msimerson** [comment]
2.8.21 released, which resolves this.
