### ISSUE TITLE
[outbound] Oops, TLS config not loaded yet!

### ISSUE THREAD

**Issue by pfrejowski** [haraka/Haraka#2494]
### system info

Fresh Mail-Toaster 6 install, Freebsd 11.2, newest version of Haraka 2.8.22, Lets encrypt certificates.

### Expected behavior

TLS secured outbound messages

### Observed behavior
Haraka is not encrypting outbound messages and sends mails in clear text, in logs I have such error message:
[outbound] Oops, TLS config not loaded yet!
despite configuration is ok, now I rolled back to 2.8.19 version and tls outbound encryption is working fine. (with the same, prepared by Mail-Toaster, default configuration).

**Comment by msimerson** [comment]
I can confirm, I ran out of time to debug. Will look at it next week.

**Comment by msimerson** [comment]
In looking at it again today, I'm not seeing that error on a fresh install. And I can't remember where I did see it last week. 😞 Today my outbound messages are getting TLS encrypted and everything is working as expected.

**Comment by msimerson** [comment]
If you're still seeing this error, please provide enough information to replicate your setup (and do include the system info blocks) and your TLS related config.

**Comment by pfrejowski** [comment]
ok, I hope I'll be able to do this tomorrow.

**Comment by pfrejowski** [comment]
I have no tls.ini file, so I'm using default config (but I also tried and created it and problem remained) , Let's Encrypt certs, in tls_cert.pem, tls_key.pem, dhparams.pem. 
My mistake in first mail, my not working version was 2.8.22 not 21 
When I just installed 2.8.19 with the same config problem disappeared. 

Haraka | Haraka.js — Version: 2.8.22
 --- | :---
Node | v8.11.3
OS | FreeBSD haraka 11.2-RELEASE-p1 FreeBSD 11.2-RELEASE-p1 #0: Sun Aug  5 12:04:13 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
openssl | OpenSSL 1.0.2o-freebsd  27 Mar 2018

**Comment by bughit** [comment]
@msimerson 

Here's what I am seeing debugging 2.8.21 startup (clustered):

- Server.init_master_respond is called once on startup
- it (and only it) calls outbound.scan_queue_pids
- the callback of which never sends outbound.load_pid_queue to the workers because pids is empty
   ```
    outbound.scan_queue_pids(function (err, pids) {
        if (err) {
            Server.logcrit("Scanning queue failed. Shutting down.");
            return logger.dump_and_exit(1);
        }
        Server.daemonize();
        // Fork workers
        const workers = (c.nodes === 'cpus') ? os.cpus().length : c.nodes;
        const new_workers = [];
        for (let i=0; i<workers; i++) {
            new_workers.push(cluster.fork({ CLUSTER_MASTER_PID: process.pid }));
        }
        for (let j=0; j<pids.length; j++) {
            new_workers[j % new_workers.length]
                .send({event: 'outbound.load_pid_queue', data: pids[j]});
        }
   ```
- the only other sending of outbound.load_pid_queue is when a worker dies
- load_pid_queue is the only caller load_que in a worker
- which is the only caller of obtls.init
- which is the only caller of load_config

So the config is never loaded in workers. Please reopen.

**Comment by baudehlo** [comment]
Check the pull request I just opened. It should resolve the issue.
