### ISSUE TITLE
Rewrite body per recipient #1867

### ISSUE THREAD

**Issue by Manishjodhani** [haraka/Haraka#2495]
Any update on this issue.
Because we are also facing same issue.
Please take a look in this issue #1867

**Comment by baudehlo** [comment]
Take a look at what the haraka mailing list software does to achieve this.
It generates a brand new email per recipient.

https://github.com/baudehlo/haraka-mailinglist/blob/master/haraka/ml.js#L253-L283

**Comment by Manishjodhani** [comment]
we checked it.
Haraka is send mail as each mail as one recipient but the result is not coming as single mails.
Means we checked in haraka logs there were only results of one mail id's not of other cc mails id's

**Comment by msimerson** [comment]
You're asking Haraka for a mailing list feature. Haraka is an MTA, not mailing list software. You can modify your Haraka locally with such changes but I don't expect this to ever be a feature of Haraka.
