### ISSUE TITLE
Support tagged addresses in LMTP delivery

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#2496]
### system info

Anything that supports LMTP. Tested with `procmail -z`

### Expected behavior

Mail to `foo-tag@example.com` should be delivered to account `foo`.

### Observed behavior

Mail gets rejected with 'no such user'

### Steps to reproduce

Config/plugins:

```
dnsbl
tls
#data.nomsgid
#data.noreceived
data.signatures
data.uribl
early_talker
#graph
helo.checks
mail_from.is_resolvable
mail_from.nobounces
mail_from.blocklist
max_unrecognized_commands
rcpt_to.max_count
rcpt_to.in_host_list
rdns.regexp
queue/lmtp
```

Otherwise it's mostly defaults.

**Comment by baudehlo** [comment]
It’s not that LMTP doesn’t support it, it’s that we are relying on the LMTP server to support it vs dealing with tagged addresses in Haraka and translating them to non-tagged addresses (optionally, of course).

I wrote a plug-in for now but I wonder if it should be a core feature.

**Comment by analogic** [comment]
If it should be vote then I am voting for NO as core feature - AFAIK tagging is not standardized in any way and seems more like custom feature. I've also written plugin too with extending LMTP but I am using "+" as tag delimiter as google does (https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html)

**Comment by msimerson** [comment]
I agree that it does not belong in core.  I’ve been planning to implement this feature as an extension of the aliases plug-in.  And then write a web UI to manage the aliases. Then the back and no longer needs to know anything about the alias extensions, what delimiters they use, etc.

**Comment by msimerson** [comment]
Taken up over at [haraka-plugin-rcpt_to-strip-tagging](https://github.com/haraka/haraka-plugin-rcpt_to-strip-tagging)
