### ISSUE TITLE
Hook for bounces

### ISSUE THREAD

**Issue by Bramzor** [haraka/Haraka#2497]
Is there a way to have a hook on bounces and disable those as I want to disable bounces that are generated by my specific outbound.send_email trigger. Reason for this is that I want to forward mails but hide the address and if it bounces at the end step, the sender will receive the end receiver his email address and not the protected address.

Alternative is that I try to modify the text inside the bounces of this specific outbound.send_email trigger but that seems more difficult.

**Comment by Bramzor** [comment]
I just found the following:

> The bounce hook
Parameters: next, hmail, error
If the mail completely bounces then the bounce hook is called. This is not called if the mail is issued a temporary failure (a 4xx error code). The hook parameter is the error message received from the remote end as an Error object. The object may also have the following properties:
mx - the MX object that caused the bounce
deferred_rcpt - the deferred recipients that eventually bounced
bounced_rcpt - the bounced recipients
If you do not wish to have a bounce message sent to the originating sender of the email then you can return OK from this hook to stop it from sending a bounce message.

The only thing I would extra is a way to identify if the bounce was triggered because of the failed outbound.send_mail and not because of something else. Alternative is to run 2 Haraka instances, one for sending (with the outbound.send_mail) and one for receiving mail?

**Comment by Bramzor** [comment]
I assume I can use notes for that:

> outbound.send_email(from, to, contents, outnext, { notes: transaction.notes });

Just need to figure out how I can change the bounce message in the bounce hook then if that transaction note is found...

**Comment by baudehlo** [comment]
The value should be in hmail.notes. Re-open if you have problems.
