### ISSUE TITLE
No 250-STARTTLS

### ISSUE THREAD

**Issue by Bramzor** [haraka/Haraka#2500]
### system info

I have upgraded Haraka and noticed that TLS was not working anymore in the newer version.
250-STARTTLS was missing during connection.

My configuration:

> config/plugins:tls
config/tls.ini:key=tls/privkey.pem
config/tls.ini:cert=tls/fullchain.pem

Haraka | Haraka.js — Version: 2.8.20
 --- | :--- 
Node | v8.4.0
OS | Linux devs01.spamfree.io 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior

No missing 250-STARTTLS

### Observed behavior

Missing and reported by MX Toolbox

**Comment by Dexus** [comment]
did you read https://github.com/haraka/Haraka/blob/c9d98aae317dd1c568b5e8ee00d8a5540cbe0691/docs/plugins/tls.md ?

Also we miss some logs so we can check against...

**Comment by Bramzor** [comment]
Yes I did. It was working on older version.

Logs:
`220 KNIP ESMTP Haraka ready [674 ms]
EHLO EC2AMAZ-14J9QQI.mxtoolbox.com
250-somedomain.example.com Hello keeper-us-east-1c.mxtoolbox.com [18.205.72.90]
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250 SIZE 0 [739 ms]`

Missing: 250-STARTTLS

**Comment by Bramzor** [comment]
See an error on the server on incoming connection:

> [ERROR] [-] [tls] no valid TLS config

My tls.ini file:

> key=privkey.pem
cert=fullchain.pem

I even tried moving the files and things like:

> key[]=privkey.pem
cert[]=fullchain.pem

Checked the certificates and they are valid and are mentioning the correct domainname.

So I'm a bit lost... Worked fine before. Might be related to #2455 but removing the .ini file did not resolve the error...

**Comment by msimerson** [comment]
I see the problem. You're on 2.8.20 which doesn't have #2465 yet. Upgrade to 2.8.21 or manually apply that PR.
