### ISSUE TITLE
problem with haraka startup.

### ISSUE THREAD

**Issue by vicoooo26** [haraka/Haraka#2506]
### system info
Haraka: v2.8.21
OS:Win 10
### Expected behavior
I want to send an E-Mail by sender@mymail.com to get@myemail.com,but it doesn't seem to work.

### Observed behavior
D:\>perl swaks.pl -h "mymail.com" -t get@mymail.com -f sender@mymail.com -s localhost -p 25
=== Trying localhost:25...
=== Connected to localhost.
<-  220 vico.chu ESMTP Haraka/2.8.21 ready
 -> EHLO mymail.com
<-  250-vico.chu Hello Unknown [127.0.0.1], Haraka is at your service.
<-  250-PIPELINING
<-  250-8BITMIME
<-  250-SMTPUTF8
<-  250-SIZE 0
<-  250 STARTTLS
 -> MAIL FROM:<sender@mymail.com>
<-  250 sender <sender@mymail.com> OK
 -> RCPT TO:<get@mymail.com>
<-  250 recipient <get@mymail.com> OK
 -> DATA
<-  354 go ahead, make my day
 -> Date: Fri, 14 Sep 2018 10:50:35 +0800
 -> To: get@mymail.com
 -> From: sender@mymail.com
 -> Subject: test Fri, 14 Sep 2018 10:50:35 +0800
 -> Message-Id: <20180914105035.006528@DESKTOP-46T2ORH>
 -> X-Mailer: swaks v20170101.0 jetmore.org/john/code/swaks/
 ->
 -> This is a test mailing
 ->
 -> .
<** 451  (87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1)
 -> QUIT
<-  221 vico.chu closing connection. Have a jolly good day.
=== Connection closed with remote host.

### Here is the logs.
loaded TLD files: 1=1542 2=8370 3=2426
loaded 8611 Public Suffixes
loglevel: PROTOCOL
log format: DEFAULT
Starting up Haraka version 2.8.21
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: access
[DEBUG] [-] [core] no timeout in access.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin access timeout is: 30s
[INFO] [-] [access] skipping helo.checks.regexps
[DEBUG] [-] [core] registered hook connect to access.rdns_access priority 0
[DEBUG] [-] [core] registered hook mail to access.mail_from_access priority 0
[DEBUG] [-] [core] registered hook rcpt to access.rcpt_to_access priority 0
[DEBUG] [-] [core] registered hook connect to access.any priority 0
[DEBUG] [-] [core] registered hook helo to access.any priority 0
[DEBUG] [-] [core] registered hook ehlo to access.any priority 0
[DEBUG] [-] [core] registered hook mail to access.any priority 0
[DEBUG] [-] [core] registered hook rcpt to access.any priority 0
[DEBUG] [-] [core] registered hook data_post to access.data_any priority 0
[INFO] [-] [core] Loading plugin: helo.checks
[DEBUG] [-] [core] no timeout in helo.checks.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin helo.checks timeout is: 30s
[DEBUG] [-] [core] registered hook helo to helo.checks.proto_mismatch_smtp priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.proto_mismatch_esmtp priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.init priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.init priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.match_re priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.match_re priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.bare_ip priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.bare_ip priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.dynamic priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.dynamic priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.big_company priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.big_company priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.literal_mismatch priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.literal_mismatch priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.valid_hostname priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.valid_hostname priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.rdns_match priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.rdns_match priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.forward_dns priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.forward_dns priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.host_mismatch priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.host_mismatch priority 0
[DEBUG] [-] [core] registered hook helo to helo.checks.emit_log priority 0
[DEBUG] [-] [core] registered hook ehlo to helo.checks.emit_log priority 0
[INFO] [-] [core] Loading plugin: tls
[DEBUG] [-] [core] no timeout in tls.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin tls timeout is: 30s
[INFO] [-] [core] loading tls.ini
[DEBUG] [-] [core] loading dhparams from dhparams.pem
[DEBUG] [-] [core] registered hook capabilities to tls.advertise_starttls priority 0
[DEBUG] [-] [core] registered hook unrecognized_command to tls.upgrade_connection priority 0
[DEBUG] [-] [core] registered hook disconnect to tls.hook_disconnect priority 0
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[DEBUG] [-] [core] no timeout in mail_from.is_resolvable.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin mail_from.is_resolvable timeout is: 30s
[DEBUG] [-] [core] registered hook mail to mail_from.is_resolvable.hook_mail priority 0
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[DEBUG] [-] [core] no timeout in rcpt_to.in_host_list.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin rcpt_to.in_host_list timeout is: 30s
[DEBUG] [-] [core] no timeout in rcpt_to.host_list_base.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin rcpt_to.host_list_base timeout is: 30s
[DEBUG] [-] [core] registered hook rcpt to rcpt_to.in_host_list.hook_rcpt priority 0
[DEBUG] [-] [core] registered hook mail to rcpt_to.in_host_list.hook_mail priority 0
[INFO] [-] [core] getting SocketOpts for SMTPS server
[NOTICE] [-] [core] Listening on :::25
[NOTICE] [-] [core] Listening on :::587
[INFO] [-] [core] Creating TLS server on ::0:465
[DEBUG] [-] [core] addOCSP: not available
[NOTICE] [-] [core] Listening on :::465
[DEBUG] [-] [server] running init_master hooks
[INFO] [-] [core] loading tls.ini
[INFO] [-] [core] [outbound] Loading outbound queue from D:\haraka\queue
[INFO] [-] [core] express loaded at Server.http.express
[INFO] [-] [core] express app is at Server.http.app
[NOTICE] [-] [core] Listening on :::80
[DEBUG] [-] [server] running init_http hooks
[INFO] [-] [core] init_http_respond
[INFO] [-] [core] Server.http.wss loaded
[DEBUG] [-] [server] running init_wss hooks
[INFO] [-] [core] init_wss_respond
[INFO] [-] [core] using html docroot: D:\haraka\html
[DEBUG] [-] [core] addOCSP: not available
[NOTICE] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] connect ip=127.0.0.1 port=60114 local_ip=:: local_port=25
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running connect_init hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running connect_init_respond
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running lookup_rdns hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running connect hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running connect hook in access plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [access] checking 127.0.0.1 against connect.rdns_access.whitelist
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [access] checking 127.0.0.1 against connect.rdns_access.whitelist_regex
[DEBUG] [-] [access] empty file: connect.rdns_access.whitelist_regex
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [access] checking unknown against connect.rdns_access.whitelist
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [access] checking unknown against connect.rdns_access.whitelist_regex
[DEBUG] [-] [access] empty file: connect.rdns_access.whitelist_regex
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [access] checking 127.0.0.1 against connect.rdns_access.blacklist_regex
[DEBUG] [-] [access] empty file: connect.rdns_access.blacklist_regex
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [access] checking unknown against connect.rdns_access.blacklist_regex
[DEBUG] [-] [access] empty file: connect.rdns_access.blacklist_regex
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=connect plugin=access function=rdns_access params="" retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running connect hook in access plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [access] domain detect failed on hook: connect
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=connect plugin=access function=any params="" retval=CONT msg=""
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] S: 220 vico.chu ESMTP Haraka/2.8.21 ready
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] C: EHLO mymail.com state=1
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in access plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=access function=any params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=proto_mismatch_esmtp params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=init params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=match_re params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=bare_ip params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=dynamic params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=big_company params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=literal_mismatch params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=valid_hostname params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=rdns_match params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=forward_dns params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=host_mismatch params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running ehlo hook in helo.checks plugin
[INFO] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [helo.checks] multi: true, skip:proto_mismatch(private), host_mismatch(private)
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=ehlo plugin=helo.checks function=emit_log params=mymail.com retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running capabilities hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] running capabilities hook in tls plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core]  hook=capabilities plugin=tls function=advertise_starttls params="" retval=CONT msg=""
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] S: 250-vico.chu Hello Unknown [127.0.0.1], Haraka is at your service.
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] S: 250-PIPELINING
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] S: 250-8BITMIME
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] S: 250-SMTPUTF8
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] S: 250-SIZE 0
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] S: 250 STARTTLS
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624] [core] C: MAIL FROM:<sender@mymail.com> state=1
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running mail hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running mail hook in access plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [access] checking sender@mymail.com against mail_from.access.whitelist
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [access] checking sender@mymail.com against mail_from.access.whitelist_regex
[DEBUG] [-] [access] empty file: mail_from.access.whitelist_regex
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [access] checking sender@mymail.com against mail_from.access.blacklist_regex
[DEBUG] [-] [access] empty file: mail_from.access.blacklist_regex
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=mail plugin=access function=mail_from_access params=<sender@mymail.com> retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running mail hook in access plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=mail plugin=access function=any params=<sender@mymail.com> retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running mail hook in mail_from.is_resolvable plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [mail_from.is_resolvable] mymail.com: MX 0 mail.mymail.net => 69.13.196.34
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [mail_from.is_resolvable] mymail.com: 69.13.196.34
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=mail plugin=mail_from.is_resolvable function=hook_mail params=<sender@mymail.com> retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running mail hook in rcpt_to.in_host_list plugin
[DEBUG] [-] [rcpt_to.in_host_list] checking mymail.com in config/host_list
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=mail plugin=rcpt_to.in_host_list function=hook_mail params=<sender@mymail.com> retval=CONT msg=""
[NOTICE] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] sender <sender@mymail.com> code=CONT msg=""
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] S: 250 sender <sender@mymail.com> OK
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] C: RCPT TO:<get@mymail.com> state=1
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running rcpt hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running rcpt hook in access plugin
[DEBUG] [-] [access] empty file: rcpt_to.access.whitelist_regex
[DEBUG] [-] [access] empty file: rcpt_to.access.blacklist_regex
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=rcpt plugin=access function=rcpt_to_access params=<get@mymail.com> retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running rcpt hook in access plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=rcpt plugin=access function=any params=<get@mymail.com> retval=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running rcpt hook in rcpt_to.in_host_list plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [rcpt_to.in_host_list] Checking if <get@mymail.com> host is in host_list
[DEBUG] [-] [rcpt_to.in_host_list] checking mymail.com in config/host_list
[INFO] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=rcpt plugin=rcpt_to.in_host_list function=hook_rcpt params=<get@mymail.com> retval=OK msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running rcpt_ok hooks
[NOTICE] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] recipient <get@mymail.com> code=OK msg="" sender=sender@mymail.com
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] S: 250 recipient <get@mymail.com> OK
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] C: DATA state=1
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running data hooks
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] S: 354 go ahead, make my day
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running data_post hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running data_post hook in access plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=data_post plugin=access function=data_any params="" retval=CONT msg=""
[NOTICE] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] message mid=<20180914105035.006528@DESKTOP-46T2ORH> size=273 rcpts=1/0/0 delay=0.012 code=CONT msg=""
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running queue hooks
[NOTICE] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] queue code=CONT msg=" (87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1)"
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] S: 451  (87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1)
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running reset_transaction hooks
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] C: QUIT state=1
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running quit hooks
[PROTOCOL] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] S: 221 vico.chu closing connection. Have a jolly good day.
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] client has disconnected
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running disconnect hooks
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] client has disconnected
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] running disconnect hook in tls plugin
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] client has disconnected
[DEBUG] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core]  hook=disconnect plugin=tls function=hook_disconnect params="" retval=CONT msg=""
[NOTICE] [87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1] [core] disconnect ip=127.0.0.1 rdns=Unknown helo=mymail.com relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=273 lr="451  (87333DD0-F4C5-4EAB-9ECC-70B2B6006624.1)" time=3.931

### and my config/plugins
access
helo.checks
tls
mail_from.is_resolvable
rcpt_to.in_host_list

### config/host_list
mymail.com
qq.com
163.com
gmail.com
outlook.com

**Comment by baudehlo** [comment]
You don't have any queue plugins defined, so Haraka doesn't know how to
queue that mail.
