### ISSUE TITLE
Plugin use mail_body from haraka in plugin?

### ISSUE THREAD

**Issue by Dexus** [haraka/Haraka#2508]
What is the best way to import haraka files in a plugin?

I don't like to maintain code twice, so I would like to access haraka files in a plugin, especially mail_body.js and mail_header.js.

I working on the milter support. But maybe it should be a core feature, that is not a external plugin.

What do you think?

cc/ @smfreegard @baudehlo @msimerson

**Comment by msimerson** [comment]
I'm pretty sure that's exactly the use case we have [haraka_require](https://github.com/haraka/Haraka/blob/master/plugins.js#L33-L35) for.

**Comment by Dexus** [comment]
Damn, yes I missed that.
