### ISSUE TITLE
outbound mail delivery slow

### ISSUE THREAD

**Issue by vicoooo26** [haraka/Haraka#2510]
Hello, I am a novice programmer and I own an AWS EC2 where haraka is running on. After making sure every DNS record was configured properly, I use this haraka server to send some test mail from my domain to somewhere else.
It works fine when I only send one mail per time. But if I send bulk mails such as 500 mails one time, then problem comes.  It will take quite a long time to receive these mails. So what I should do to improve this mail delay.

outbound.ini as follow: 
disable=false
concurrency_max=256
pool_concurrency_max=32

Also, I add "nodes=cpus" to smtp.ini

Any help will be appreciated, and sorry for making a noise.

**Comment by smfreegard** [comment]
From https://aws.amazon.com/ec2/faqs/

Q: Are there any limitations in sending email from Amazon EC2 instances?

Yes. In order to maintain the quality of Amazon EC2 addresses for sending email, we enforce default limits on the amount of email that can be sent from EC2 accounts. If you wish to send larger amounts of email from EC2, you can apply to have these limits removed from your account by filling out this form.

**Comment by vicoooo26** [comment]
Thanks for your quick turnaround.
I still feel confused, but it is may not caused by Haraka.
I can use 25 port to send a java mail where I use 587 port it does not work as expected. The error logs says "Couldn't connect to host, port: mail.mydomain.com , 587; timeout -1"
So I try to ping and telnet port 25/587, both of them failed with the "timeout " error. 
Is it possible that EC2 has closed this 587 port? 
Many thanks steve.

**Comment by smfreegard** [comment]
I haven't used Haraka on EC2 for ages - so I don't know the answer to that.   But as their FAQ states - SMTP is rate-limited, so that will include 25/tcp and 587/tcp (and probably 465/tcp).

**Comment by vicoooo26** [comment]
Thanks, now everything works fine. 
I hava one more question. Imagine a situation that my mail server goes down unfortunatly, what we can do to reduce the mail loss and improve my server's robustness. Is there any feasible practice?

**Comment by baudehlo** [comment]
There should be no loss on outbound mail. It’s designed to recover from all failures.
