### ISSUE TITLE
Dynamically rewrite mail_from in plugin

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/Haraka#2511]
I have been poking around with `hook_mail` and tried to overwrite the mail_from like this.

```
exports.hook_mail = function (next, connection, params) {
  connection.transaction.mail_from = new Address('<new@domain.com>');
  next()
}
```

However the emails I receive are still sent by the old address.

**Comment by rogereiddir** [comment]
Hello @AuspeXeu have you find some solution to this? can you please share some code thanks
