### ISSUE TITLE
Why doesn't Haraka copy all the config files to user defined directory?

### ISSUE THREAD

**Issue by kalesh13** [haraka/Haraka#2513]
It could have been better if all the cofig files are copied to the directory when we install Haraka using
`haraka -i [dir]`

As of now it copies only few config files and to add or update, either we have to copy files manually from the source folder or create a new file referering the docs. If the purpose of the above command was to copy configs then why limit it to just the necessary files? A standalone command just to copy the required config files might also work.

Thank you.

**Comment by msimerson** [comment]
Search the repo here for conversations on that. A couple reasons off the top of my head:

1. there were a LOT of config files, making discovery difficult
2. it's unsafe to upgrade config files on Haraka upgrades, making it impossible for us to determine what was legacy default -vs- config you wanted.

**Comment by baudehlo** [comment]
It's also well documented:
https://github.com/haraka/haraka-config#default-config-and-overrides
