### ISSUE TITLE
[outbound] Oops, TLS config not loaded yet!

### ISSUE THREAD

**Issue by rradu92** [haraka/Haraka#2519]
### system info

Haraka | Haraka.js — Version: 2.8.21
 --- | :--- 
Node | v6.14.3
OS | Linux smtp1.raclus.net 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior
TLS Suppor enabled

### Observed behavior
Haraka is throwing errr "[outbound] Oops, TLS config not loaded yet!" when enable nodes=cpus in smtp.ini

### Steps to reproduce
Enable nodes=cpus in smtp.ini
If I disable nodes=cpus all works fine

### My smtp.ini config file (no comments)
listen=0.0.0.0:587
user=mail
group=mail
nodes=cpus

### My tls.ini config file
key=certs/key.pem
cert=certs/cert.pem
dhparam=certs/dhparams.pem
ciphers=ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4

key, cert and dhparam files are in certs directory

**Comment by AuspeXeu** [comment]
`Oops, TLS config not loaded yet!`

Having the same problem.
