### ISSUE TITLE
Temp fail

### ISSUE THREAD

**Issue by manjeshpv** [haraka/Haraka#2520]
### system info

Haraka | Haraka.js — Version: 2.8.18
 --- | :--- 
Node | v8.9.3
OS | Linux subdomain.domain.com 4.17.17-x86_64-linode116 #1 SMP PREEMPT Mon Aug 20 16:07:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior

Mail has to be delivered

### Observed behavior

for gmail temp failing
[outbound] Remote end X.X.X.X:25 closed connection while we were processing mail. Trying next MX.

for mail-tester.com : bounce happening

### Steps to reproduce

Oct 17 13:10:59 haraka[23821]: [ERROR] [7B6260E0-240F-4AAD-9E52-1188B0D14DC5.1.1] [outbound] Remote end 173.194.219.27:25 closed connection while we were processing mail. Trying next MX.
Oct 17 13:10:59  haraka[23821]: [INFO] [7B6260E0-240F-4AAD-9E52-1188B0D14DC5.1.1] [outbound] **Temp failing** 1539758017236_1539762057544_6_23821_XrUdrN_11_subdomain.domain.com for 4096 seconds: Tried all MXs

Everything was working fine from long time, suddenly stopped working.

I'm confused, is this issue with misconfiguration or blacklist

**Comment by baudehlo** [comment]
This looks like the correct behaviour. What are you expecting?

**Comment by msimerson** [comment]
No response, behavior looks correct to me too.
