### ISSUE TITLE
Path for tls credentials

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/Haraka#2521]
It seems like the paths given for `cert` and `key` option of the tls plugin are always relative to the config folder. This is not very good if you want to separate the configuration files from the credentials. I think absolute paths should be supported.

**Comment by msimerson** [comment]
moved to [wiki](https://github.com/haraka/Haraka/wiki)

**Comment by msimerson** [comment]
Update. See haraka/haraka-config#46

**Comment by msimerson** [comment]
Completed.
