### ISSUE TITLE
Low performance when accepting large mails?

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2528]
I've hit this problem by sending larger email (like 20mb attachments) with roundcube which timeouted. 

Debug with empty email with 16MB attachment:

```
2018-11-02 09:49:34  ⭠ DATA
2018-11-02 09:49:34  [core] [DEBUG] - running data hooks
2018-11-02 09:49:34  ⭢ 354 go ahead, make my day
... 18 seconds of upload and node at 100% CPU ...
2018-11-02 09:49:52  [core] [DEBUG] - running data_post hooks
```
There are no plugins which can limit "upload" rate enabled and there should not be any parsing happening afaik. So it gives me that email is uploaded at rate < 1MB/s from localhost to localhost with enough ram and i7 cpu. Is there anything what I should look for to tweak or I have simply unreal expectations?

**Comment by baudehlo** [comment]
Do you have spooling turned on or off? Try disabling it.

**Comment by analogic** [comment]
spooling to SSD should be negligible I guess

```
$ head -c 16MB < /dev/urandom > 16MBfile
$ time swaks -t root@localhost --server localhost --attach 16MBfile
real	0m18.922s
user	0m0.417s
sys	0m0.474s

### spooling_after = -1

$ time swaks -t root@localhost --server localhost --attach 16MBfile
real	0m17.056s
user	0m0.424s
sys	0m0.509s
```

**Comment by baudehlo** [comment]
I mean I guess it could just be overhead inside Haraka then. Only way we
can find out is if you profile it. There's some simple profiling built into
Node: https://nodejs.org/en/docs/guides/simple-profiling/ (note the doc
focusses on web requests, so you'll have to adjust it a bit).

**Comment by analogic** [comment]
with pr
```
real	0m5.749s
user	0m0.430s
sys	0m0.571s
```
