### ISSUE TITLE
npm install fails.

### ISSUE THREAD

**Issue by trusktr** [haraka/Haraka#253]
I enounter an error installing Haraka. This is the output after doing `npm install -g Haraka`:
http://pastie.org/5353972

I also tried using the git version but no luck:

```
# git clone <Haraka-repo>
# node haraka.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/srv/mail/Haraka/server.js:12:19)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

After that I tried `npm intstall` but of course that gives the same node-syslog error, but then Haraka seems to start.

If I do `node ./node-modules/Haraka/haraka.js -i ./haraka_test` it just hangs with the message `Starting up Haraka version 1.4.0` and never goes anywhere. I don't have qmail installed though and I haven't edited any config files. Is that why it hangs? I wish the documentation was more clear.

**Comment by unplugged216** [comment]
> Just looked at your log output - the 'npm install -g Haraka' is failing because you don't appear to have any development tools installed:
> 
> stack Error: not found: make
> 
> You'll need 'make', 'gcc' and 'gcc-c++' installed for npm to be able to build the modules required by Haraka.

Could this be added to the documentation? There is not even a remote inference to those who may be newer or may simply not have ever used nom in this capacity. Something like:

`sudo apt install make gcc gcc++`

**Comment by msimerson** [comment]
> Could this be added to the documentation?

No, it's outside of Haraka's scope. Some NPM dependencies have their own dependencies, and we aren't going to delve into those weeds as they're deep and at the bottom is time-sucking muck.

> sudo apt install build-essential

That would fail to work for as many people as it helped.
