### ISSUE TITLE
LMTP pool blocks under stress

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2556]
I have noticed strange behaviour on one installation where nagios generated hunderds of emails at one time which are sent through haraka to local LMTP server. When that happend haraka after ~70 emails stopped delivering to LMTP with

```
[outbound] [INFO] - Attempting to deliver to: 127.0.0.1:24 using LMTP (0) (3)
[outbound] [INFO] - Temp failing 1544181767545_1544181767545_0_651_dgzLB6_41_mail.example.com for 64 seconds: Tried all MXs
```
It seems ok - LMTP was exhausted at the time - but it contiued even after load was essentialy zero
```
[outbound] [INFO] - Temp failing 1544181767545_1544181831613_1_651_dgzLB6_46_mail.example.com for 128 seconds: Tried all MXs
...
[outbound] [INFO] - Temp failing 1544181767545_1544181960330_2_651_dgzLB6_2901_mail.example.com for 256 seconds: Tried all MXs
...
[outbound] [INFO] - Temp failing 1544181767545_1544182216353_3_651_dgzLB6_1116_mail.example.com for 512 seconds: Tried all MXs
```
Important is that Dovecots LMTP was working ok, another instance of haraka had no problem with delivery.

Second thing is that pool seems to be blocked forever I guess - we have noticed issue after 8 hours.

It can be fairly easily reproduced with something like
```
#!/bin/bash

for IT in {0..999}
do
    swaks --to rec1@example.com,rec2@example.com --server localhost > /dev/null &
    swaks --to rec1@example.com,rec2@example.com --server localhost > /dev/null &
    swaks --to rec1@example.com,rec2@example.com --server localhost > /dev/null &
    swaks --to rec1@example.com,rec2@example.com --server localhost > /dev/null &
    swaks --to rec1@example.com,rec2@example.com --server localhost > /dev/null
done
```

**Comment by analogic** [comment]
It seems it is not issue of pools. `concurrency_max=0` makes thing actualy worse, it took 15 emails to block.

**Comment by analogic** [comment]
It could be dovecot not accepting another connection and haraka is stuck in this state forever

**Comment by analogic** [comment]
Another thing I've just noticed is that 10 emails after the 15 initial ones are in this state (and no other delivery message or another attempt):
```[outbound] [INFO] - Attempting to deliver to: 127.0.0.1:24 using LMTP (0) (0)```

Others are temp failed and regularly tried to deliver.

**Comment by analogic** [comment]
Switching LMTP to unix socket have no effect either

**Comment by baudehlo** [comment]
Maybe we don't close the socket and so as you say, Dovecot rightly blocks
it?

Maybe check via lsof or netstat?

**Comment by analogic** [comment]
> Maybe we don't close the socket and so as you say, Dovecot rightly blocks it? Maybe check via lsof or netstat?

netstat or lsof don't show any hanging connections. It must be node itself or socket management inside hmail.js

**Comment by baudehlo** [comment]
Yeah the code doesn't seem to have 100% stabilized just yet. I'm hoping
someone else can put some eyes on it.

**Comment by analogic** [comment]
It seems that the first emails hanging are waiting on pool.acquire at
https://github.com/haraka/Haraka/blob/366e695dbc46a81577315f6f26a7d60ef36daf53/outbound/client_pool.js#L103 so something connections are not properly releasing pool

pool_concurrency_max=0 solve this (previously I've mistakenly set concurrency_max=0)

**Comment by baudehlo** [comment]
Yeah but I'd like to resolve the underlying issue with the pools :)

**Comment by baudehlo** [comment]
+1 - I'll expect a PR any second :)

I think the true/false issue is due to lack of pool.release() here:
https://github.com/haraka/Haraka/blob/62de615edceaad7ab509faf9fbf89890e57565a1/outbound/client_pool.js#L136-L138

**Comment by analogic** [comment]
I see. Is it ok that client is not released from pool in case of error?

The true origin of this issue is probably my latest PR which send QUIT instead of RSET (which is invalid and leads to other issues). It should just continue releasing client and not sending RSET untill there is 3xx or 4xx and then send QUIT. I'll create fix later
