### ISSUE TITLE
Mails always go to spam for Gmail although the score is 10 on mail-tester

### ISSUE THREAD

**Issue by vshall20** [haraka/Haraka#2558]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

echo "Haraka | $(haraka -v)"; echo " --- | :--- "; echo "Node | $(node -v)"; echo "OS | $(uname -a)"; 
Haraka | Haraka.js — Version: 2.8.23
 --- | :--- 
Node | v8.10.0
OS | Linux mailtestserver 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

echo "openssl | $(openssl version)"
openssl | OpenSSL 1.1.0g  2 Nov 2017

I have configured Haraka on DigitalOcean instance and I am trying to send mail to other domains, for domains other than Gmail, it is landing in Inbox, but for Gmail it is landing in Spam.

I tested on mail-tester, and the score is 10. (link to report)[https://www.mail-tester.com/test-cxl8q]
![image](https://user-images.githubusercontent.com/3425121/49686069-29dc7980-fb15-11e8-99d6-95a1000e81db.png)

Domain is: **mailtestserver.ml**
The MX record, SPF, DKIM, DMARC everything is proper on mxtoolbox.

I have also add an SSL certificate, created from sslforfree.com 

### Expected behavior
The mails should land in Inbox for all providers.

### Observed behavior
The mail is landing in Spam for Gmail.

**Comment by msimerson** [comment]
Sorry, this is not a gmail support forum.

**Comment by vshall20** [comment]
@msimerson  I am sorry if I created some confusion, but I want to know if what I am doing is correct or is there any setting that I need to do so that mails land in Inbox for everyone.
Any kind of help is appreciated :)

**Comment by msimerson** [comment]
No confusion, it’s just there’s many reasons why your email might land in Gmail’s spam box and that’s outside the scope of Haraka.

**Comment by msimerson** [comment]
Your mail test results suggest that you have taken the right steps so set up your server.  my first guess as to the reason is that your IP address was previously used for nefarious purposes. The “digital marketing” crowd often set up their IP addresses several months in advance before actually using them for email marketing.

**Comment by vshall20** [comment]
Thanks for the information @msimerson , but I am not going to use it for email marketing, it is more of a personal email server which I would use instead of going for a service like gmail, yahoo etc.
For all other services, my mails land in the Inbox but for Gmail it is always spam, so I was wondering if I missed any step here..
