### ISSUE TITLE
Failed at the iconv@2.3.1 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by yendluric** [haraka/Haraka#2565]
### system info

OS - Windows 10 Home
Node - 10.14.1
Haraka - 2.8.23

### Expected behavior
trying to install Haraka
### Observed behavior
npm ERR! iconv@2.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.1 install script 'node-gyp rebuild'.
### Steps to reproduce
npm install -g Haraka
![error one](https://user-images.githubusercontent.com/45775335/49912054-cfb22000-fe56-11e8-9281-ec68d4bc16e3.jpg)
![error two](https://user-images.githubusercontent.com/45775335/49912055-cfb22000-fe56-11e8-9d00-76ee80e6209a.jpg)

**Comment by semenmiroshnichenko** [comment]
You need to install latest version of python2 (python3 is not supported by node-gyp).

**Comment by msimerson** [comment]
None of @haraka/core use Windows so it's not officially supported. We take care to avoid breaking Windows, but if you're going to deploy on Windows,  you're expected to know it better than we do.
