### ISSUE TITLE
hotmail.com ECONNRESET

### ISSUE THREAD

**Issue by rradu92** [haraka/Haraka#2567]
### system info

Haraka | Haraka.js — Version: 2.8.23
 --- | :--- 
Node | v6.14.3
OS | Linux smtp1.raclus.net 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior
Dont show this warn message

### Observed behavior
When send to hotmail.com I get this error:
```
2018-12-19T10:58:03.002Z [WARN] [-] [core] [outbound] Socket got an error while shutting down: Error: read ECONNRESET
```
### Steps to reproduce
Send some email to hotmail.com (TLS enabled)

**Comment by baudehlo** [comment]
Does the mail get delivered or not?

That line is just a warning.

**Comment by rradu92** [comment]
Hello,

Yep, the mail is successfuly delivered, just this warning.

**Comment by baudehlo** [comment]
OK, then I'm closing the ticket. We could probably tone it down a bit, but without a PR to do so, it's just a warning.
