### ISSUE TITLE
DOCKER : build error : failed to make module : modern-syslog

### ISSUE THREAD

**Issue by dreynaud-w3line** [haraka/Haraka#2570]
An error occured while building the docker image.

```
git clone https://github.com/haraka/Haraka.git
cd Haraka
docker build .
```

Please, see attached file for the log details.

[Haraka-error.txt](https://github.com/haraka/Haraka/files/2703600/Haraka-error.txt)

**Comment by msimerson** [comment]
Docker isn't officially supported. See #2550 and #2552 

PRs are welcome.
