### ISSUE TITLE
Latest version on npmjs.org is 2.8.23?!

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/Haraka#2586]
The latest version that can be installed via npm is `2.8.23` https://www.npmjs.com/package/Haraka However, the releases on github provide `2.8.22` as the latest release!?

**Comment by KingNoosh** [comment]
@msimerson Do you have any insight into this?

**Comment by baudehlo** [comment]
We probably didn't do the release properly. I think we just had to bump the
version due to NPM doing some weird things. This, I think, is the only
change:
https://github.com/haraka/Haraka/commit/dbc888e57c4de7dcb794304ad6da1c04cbb6bb2b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by msimerson** [comment]
Yeah, I didn't the full release process for 2.8.23. The problem will go away after our next release.
