### ISSUE TITLE
Some emails get invalid DKIM body hash

### ISSUE THREAD

**Issue by analogic** [haraka/Haraka#2594]
When examining DMARC reports I've found that small percentage of emails fails with DKIM. Later I've found that the problem is that "body hash did not verify" and also it seems that it happens almost only when email is "generated" and attachment included.

Steps to reproduce:
1. enable dkim_sign plugin & generate keys
2. install and enable rspamd
3. turn DMARC reporting on with sending through haraka
4. send some emails (from DMARC enabled domains) back and forth
...wait aprox 1 day...
5. rspamd will send out DMARC reports with invalid DKIM body hash

I am sure that there is more simple method but this is the only way I've identified yet. (I will post examples later if I don't get this bug on my own)

**Comment by analogic** [comment]
I think I've found where this is comming from.

Source email:
```
smthing\n
\n
------=_NextPart_000_024E_01CC9B0A.AFE54C00\n
Content-Type: application/gzip\n
Content-Transfer-Encoding: base64\n
Content-Disposition: attachment;\n
\tfilename="....gz"\n
\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n
------=_NextPart_000_024E_01CC9B0A.AFE54C00--\r\n
```

Received email:
```
smthing\n
\n
------=_NextPart_000_024E_01CC9B0A.AFE54C00\n
Content-Type: application/gzip\n
Content-Transfer-Encoding: base64\n
Content-Disposition: attachment;\n
\tfilename="....gz"\n
\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n
------=_NextPart_000_024E_01CC9B0A.AFE54C00--\r\n
```

So some code between dkim_sign and outbound send is removing CRLF in MIME and damaging DKIM. It seems very similar to https://github.com/haraka/Haraka/issues/2182. When email is queued to file I can clearly see it has proper CRLF, so no cripling happening on receiving part. I was not able to find any code touching line endings at outbound, do you have any advice what should I search for @msimerson ?

**Comment by baudehlo** [comment]
It comes from transaction.js, add_data() function (L93 and L100).

Maybe we should consider removing the \r stripping from there.

**Comment by analogic** [comment]
Example mail which always fails [crlf-bug.txt](https://github.com/haraka/Haraka/files/2788980/crlf-bug.txt)

Edit `From`, `To` and run with `swaks --server <haraka> --from <from> --to <to> -ndf --data crlf-bug.txt`

**Comment by analogic** [comment]
@msimerson not working. I have tried remove replace regexp from L100 and nothing changed. I'll try to utilize debuger tomorrow

**Comment by baudehlo** [comment]
Note: Different Matt.

There's also L136 (from a grep, so I'm not sure what it does), and there's
a ton of stuff looking for \r in dkim.js

**Comment by analogic** [comment]
@baudehlo ouch, sorry, I have constant problem distinguish you two since touching qpsmtd :)

I don't think problem is in transaction.js or dkim.js. AFAIK they don't touch email after queued. I found valid dkim body hash in queued file BUT after it is delivered with outbound \r\n from mime disapears...

**Comment by analogic** [comment]
Kind of RFC question: Is receiving DATA with simple LF line breaks problem itself? 

Haraka send buffer directly from fs as is and it seems even google is fixing LFs to CRLFs. I know that headers&commands have to be ended with CRLFs but is it required for body lines? Might simple replacing lf->crlf hit some corner case?

**Comment by msimerson** [comment]
> Kind of RFC question: Is receiving DATA with simple LF line breaks problem itself?

That's called bare linefeeds, and yes it violates the RFCs. I think.

What @baudehlo suggested and I think you should test is this patch:

```diff
diff --git a/transaction.js b/transaction.js
index 13a80ba8..88ac523f 100644
--- a/transaction.js
+++ b/transaction.js
@@ -90,14 +90,14 @@ class Transaction {
             // Build up headers
             if (this.header_lines.length < MAX_HEADER_LINES) {
                 if (line[0] === 0x2E) line = line.slice(1); // Strip leading '.'
-                this.header_lines.push(line.toString(this.encoding).replace(/\r\n$/, '\n'));
+                this.header_lines.push(line.toString(this.encoding));
             }
         }
         else if (this.header_pos && this.parse_body) {
             let new_line = line;
             if (new_line[0] === 0x2E) new_line = new_line.slice(1); // Strip leading "."
 
-            new_line = this.body.parse_more(new_line.toString(this.encoding).replace(/\r\n$/, '\n'));
+            new_line = this.body.parse_more(new_line.toString(this.encoding));
 
             if (!new_line.length) return; // buffering for banners
         }
@@ -132,8 +132,7 @@ class Transaction {
             let data = this.body.parse_end();
             if (data.length) {
                 data = data.toString(this.encoding)
-                    .replace(/^\./gm, '..')
-                    .replace(/\r?\n/gm, '\r\n');
+                    .replace(/^\./gm, '..');
                 const line = Buffer.from(data, this.encoding);
 
                 this.body.force_end();
```

**Comment by msimerson** [comment]
Regarding bare linefeeds, see: [http://haraka.github.io/barelf.html](http://haraka.github.io/barelf.html)

**Comment by baudehlo** [comment]
Yeah but we only check on the final dot. So you have to send your data
ending in ".\r\n" - if you send ".\n" it will throw that error. It's the
only place we enforce it.

**Comment by analogic** [comment]
1. I've fixed rspamd's DMARC reports and sent them PR. So large number of emails with invalid DKIM should be gone now (for me)
2. Other sources of barelf or invalid DKIM are unknown (maybe 0.1%...) - I need to investigate it on production so I will rather not try this patch. Ill create plugin that checks barelf at outbound hook.
3. As I've tested Qmail rejects this type of email, Gmail is accepting it but converts LF & damage DKIM so I'll let design decision up to you. Adding check/transform during smtp communication should be simple to add or we can just leave it and you can close this...

**Comment by analogic** [comment]
Closing. I have not found any other source of barelf emails in the wild
