### ISSUE TITLE
regression: dkim_sign Single Domain Configuration is no longer used when per domain config is missing

### ISSUE THREAD

**Issue by bughit** [haraka/Haraka#2600]
Before [this](/haraka/Haraka/pull/2499/files#diff-c8825222b471dc1fc021bdc07cec178aR179) change, single domain config was used if per domain keydir was [not present](/haraka/Haraka/pull/2499/files#diff-c8825222b471dc1fc021bdc07cec178aL182)

```js
        if (!keydir) {
            domain = plugin.cfg.main.domain;
            private_key = plugin.private_key;
            selector = plugin.cfg.main.selector;
        }
```

now single domain config is only used when sender domain is missing, and the absence of per domain keydir is ignored.

This is a breaking change, where a minor version upgrade with a commit to "improved log messages" disables dkim signing

**Comment by msimerson** [comment]
That's definitely a bug. It's on my list to review and fix.
