### ISSUE TITLE
Support PROXY protocol v2

### ISSUE THREAD

**Issue by fcoelho** [haraka/Haraka#2601]
Haraka currently [supports the PROXY protocol](https://github.com/haraka/Haraka/blob/a68a435e56cfac60049d259919e526bd5bdb649f/docs/HAProxy.md) for incoming connections, but unfortunately [it's only able to process version 1](https://github.com/haraka/Haraka/blob/a68a435e56cfac60049d259919e526bd5bdb649f/connection.js#L438), which is text-based.

[Version 2 uses a binary format](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) and is not compatible with the previous version.

Version 2 is used, for example, by [AWS network load balancers](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol), and without this it's not possible to retrieve the actual client address when Haraka is being run behind one of those LBs.

**Comment by msimerson** [comment]
Migrated to [wiki TODO](https://github.com/haraka/Haraka/wiki/TODO)
