### ISSUE TITLE
Example of a limit.ini

### ISSUE THREAD

**Issue by thenitai** [haraka/Haraka#2613]
As max_unrecognized_commands is now deprecated and we should use limit I was just wondering if anyone got an example of a limit.ini file?

From what I read at https://haraka.github.io/manual/plugins/limit.html it should be something like:

[recipients]
max=10 (does that mean 10 messages to this email or what?)

[unrecognized_commands]
max=10 (I think that is the same value as max_unrecognized_commands used to be?)

Thanks for any pointers.

**Comment by msimerson** [comment]
Hi @thenitai , have a look at the [default limit.ini file](https://github.com/haraka/haraka-plugin-limit/blob/master/config/limit.ini) in the plugin repo.

**Comment by thenitai** [comment]
Duh... I was looking in this repo for the file. That explains. Thank you

**Comment by msimerson** [comment]
I just checked and I actually did update the limit docs to reference the limit.ini file. However, the old  limit.md is still published in the manual you referenced above. It's horribly out of date.
