### ISSUE TITLE
eslint: arrow parens rule

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2622]
### Quoting @baudehlo in #2615 

> I'm not a fan of cutting out the brackets in arrow function definitions "just because you can". It makes a single argument version look too different. I suggest a rule: Only omit the single-parameter brackets when there's no curly brackets in the body definition (and thus implicit return). Thoughts?

### I replied:

I'm not a fan of using ambiguous terms like "brackets" unless you mean square brackets. The context in this thread is immediately below a change that did omit the parens but did not omit the curly braces, so I was scratching my head to figure out which brackets you were talking about. Here's some clarifying terminology (forgive me, I grew up in a print shop):

    [ ] are brackets    or square brackets
    { } are braces      or curly  brackets
    ( ) are parens      or round  brackets
    < > are guillemets  or angle  brackets

I'm not _just_ nit picking, I brought that up to _partly_ agree with @baudehlo 's point. It's qualitatively better when what we're reading is easy to read and understand.

What I'm not convinced of is that adding additional punctuation adds clarity. Yes, it is different **looking** than es4 and es5 code, but it also behaves a little bit differently, sometimes. In principle, I believe that code that behaves different should **look** different, which favors a rule like what @baudehlo suggests.

However, I've been writing a fair bit of es6 in other projects and I've been dropping the parens on single argument arrow functions. Not _just_ because I can, but because I prefer a style with less punctuation. I find it easier to read, as do the vast majority of programmers (perl vs python, etc.). Even if I didn't prefer it, I'd still argue against adding a rule like that. After getting used to the SAAF style, it hurts my head less to read other JS where it is very common.

### Your turn

Reply below if you wish to weigh in.

**Comment by msimerson** [comment]
If we did want to add a rule like this, I think it would be: `arrow-body-style: [ error, as-needed]`, and adding that would require additional code changes besides what's in PR #2615

**Comment by baudehlo** [comment]
Putting my reply here:

What I mean is:

Don't do this: `some_func(params, err => { multi-line code block })` and in the same breath also have this: `some_func(params, (err, results) => { multi-line })` - we should have one style which I suggest would be: `some_func(params, (err) => { multi-line })` regardless of the number of parameters, because JS doesn't let you omit the parens if there are multiple parameters. So it's about consistency, because you can't omit the parens in the second case anyway.

I'm fine omitting in the one-liner case, where the return is implicit, for example: `array_of_objects.map(i => i.some_key)`

(Note: I'm not laying down the law here or anything - I just want to have a discussion about it)

**Comment by msimerson** [comment]
Okay, so we're talking about the [arrow parens rule](https://eslint.org/docs/rules/arrow-parens). 

Your first paragraph could be implemented with: `arrow-parens: [error, always]`

> I'm fine omitting in the one-liner case, where the return is implicit

I think this does that: `arrow-parens: [error, "as-needed", { "requireForBlockBody": true }]`

Note that the AirBnB style guide agrees with you and is why eslint has the rule. They purport that it adds clarity and consistency.

As I previously mentioned, I've been omitting the params in code for other projects. While I agree always using parens adds consistency, I'm not convinced it adds clarity.

**Comment by baudehlo** [comment]
Thanks. I'll probably add the rule to our $work codebase and see how it pans out.
