### ISSUE TITLE
crash on get_mx hooks

### ISSUE THREAD

**Issue by javierron** [haraka/Haraka#2626]
### system info

Haraka | Haraka.js — Version: 2.8.20
 --- | :--- 
Node | v10.15.0
OS | Linux 4.4.0-1061-aws 70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Description

Process crashes after it tries to get_mx with the follwing domain: 'torbox3uiot6wchz.onion'

Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [NOTICE] [-] [core] Listening on :::25
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [-] [server] running init_master hooks
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [INFO] [-] [core] [outbound] Loading the queue...
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [-] [core] [outbound] File needs processing later: 4268257ms
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [-] [core] [outbound] File needs processing now
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [-] [dnsbl] looking up: 2.0.0.127.zen.spamhaus.org.
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [-] [outbound] todo header length: 1081
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [F48D091A-4AFF-49FC-8881-ED79CB5C6E6D.1.1] [outbound] running send_email hooks
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [F48D091A-4AFF-49FC-8881-ED79CB5C6E6D.1.1] [outbound] Sending mail: 1554222463968_1554222463968_0_22266_WoQM13_2049_ip-xxx.xxx.xxx.xxx
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [DEBUG] [F48D091A-4AFF-49FC-8881-ED79CB5C6E6D.1.1] [outbound] running get_mx hooks
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: *** Error in `node': free(): invalid pointer: 0x00007fffcbec139e ***
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: ======= Backtrace: =========
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f0efe8b27e5]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f0efe8bb37a]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f0efe8bf53c]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: node(ares_query+0x66)[0x16a37e6]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: node[0x8af36a]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: node[0x8b31d3]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: node[0xb5f33f]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: node(_ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE+0xb9)[0xb5fea9]
Apr 02 16:57:25 ip-172-31-26-208 haraka[7479]: [0x9984dc5be1d]

**Comment by baudehlo** [comment]
That looks like an internal Node issue. I suggest upgrading Node.js itself,
and also upgrade to the latest Haraka and see if the problem goes away.

**Comment by danieltigse** [comment]
I have the same issue with the last version of Node (10.15.3) and last version of Haraka (2.8.24)

**Comment by hamzakilic** [comment]
I have opened an issue at nodejs 
https://github.com/nodejs/node/issues/27530
I think there is a bug at version 10.15.3.

**Comment by msimerson** [comment]
Yep, it’s an upstream bug, fixed upstream. Should get backported to node 10, eventually.
