### ISSUE TITLE
Remove TLSSocket peer certificate verification info from sslheader

### ISSUE THREAD

**Issue by andris9** [haraka/Haraka#2634]
The `Received` header has a TLS section in it ([defined here](https://github.com/haraka/Haraka/blob/6913ae3479682cee60a848031dc898dfa7708f5f/connection.js#L1446-L1461)) that lists `cipher`, `version` and `verify` properties. I'd suggest making the following changes:

* Remove `version` property. It is a legacy field in Node TLS object and [always has the same value](https://nodejs.org/api/tls.html#tls_tlssocket_getcipher) (TLSv1/SSLv3). Some people freak out on seeing SSL in mail headers
* Remove `verify` property or alternatively only keep it if there is a valid `peerCertificate`. Currently all messages get `verify=FAIL` in the `Received` header since no clients that connect to a MX server have a valid client certificate.

Current:

```
Received: from...
  (version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES128-GCM-SHA256 verify=FAIL)
```

Suggested:

```
Received: from...
  (cipher=ECDHE-RSA-AES128-GCM-SHA256)
```

**Comment by msimerson** [comment]
> since no clients that connect to a MX server have a valid client certificate

Some clients do have valid certs. That ‘fail’ does mislead plenty of people (there are issues here created about it). Maybe remove that property unless it’s true?
