### ISSUE TITLE
SNI support not working

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/Haraka#2636]
### system info
Haraka | Haraka.js — Version: 2.8.24
 --- | :--- 
Node | v10.15.3
OS | Linux 3.10.0-042stab136.1 #1 SMP Wed Feb 27 09:04:24 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior
Haraka should support SNI

### Observed behavior
Haraka disregards the servername and presents the default SSL certificate

### Steps to reproduce
1. Configure tls.ini like so
```
cert = main.com.crt
key = main.com.key
```
2. Provide separate cert bundles in the `config/tls` folder like so
```
cat subdomain1.key subdomain1.crt ca.crt > config/tls/subdomain1.pem
cat subdomain2.key subdomain2.crt ca.crt > config/tls/subdomain2.pem
```
3. Test SNI using openssl
```
openssl s_client -servername subdomain1 -connect subdomain1:587 -starttls smtp
```
4. Get presented with main.com's certificate

**Comment by msimerson** [comment]
Can't help you, because you didn't included the requested information in the issue template.

**Comment by AuspeXeu** [comment]
Wonder why you open source a project if contributions are not welcome.

**Comment by msimerson** [comment]
Contributions are welcome. Posting issues without the information we asked for in the issue template makes it hard/impossible to help you. You can fix that.

**Comment by AuspeXeu** [comment]
Added the system info which is what I assume you were referring to?

**Comment by analogic** [comment]
It seems that Postfix doesn't do SNI either. Do you have any special reason for needing SNI? I am using lets encrypt's cert alternative names (SAN) for dealing with multiple domains (100 domains limit per cert).

**Comment by msimerson** [comment]
Haraka **does** support SNI, I added it a year or two ago. If SNI is not working, it's likely due to the version of node.js, because openssl is embedded in node.js. That's why the version of node matters.

**Comment by msimerson** [comment]
I am unable to duplicate this issue in node 8 or 10.

The only issues I see that *may* be related is that your installed version of openssl is quite old (current is 1.0.2r). My guess is that perhaps that version of openssl doesn't work with node SNI integration. If that's the case, it's likely that SNI won't work for you with any version of Haraka and it won't matter whether you're using node 8, 10, or 12.

Try updating openssl on your distro, rebuilding Node, and see if that helps.

# node 8

Haraka | Haraka.js — Version: 2.8.24
--- | :--- 
Node | v8.16.0
OS | FreeBSD haraka 11.2-RELEASE-p9 FreeBSD 11.2-RELEASE-p9 #0: Tue Feb  5 15:30:36 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
openssl | OpenSSL 1.0.2o-freebsd  27 Mar 2018

```sh
$ openssl s_client -connect jails.tnpi.net:587 -starttls smtp -servername mail.simerson.net 2>&1 | grep ^subject
subject=/CN=mail.simerson.net
quit
$ openssl s_client -connect jails.tnpi.net:587 -starttls smtp -servername mail.theartfarm.com 2>&1 | grep ^subject
subject=/CN=mail.theartfarm.com
quit
```

# node 10

Haraka | Haraka.js — Version: 2.8.24
--- | :---
Node | v10.15.3
OS | FreeBSD haraka 11.2-RELEASE-p9 FreeBSD 11.2-RELEASE-p9 #0: Tue Feb  5 15:30:36 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
openssl | OpenSSL 1.0.2o-freebsd  27 Mar 2018

```sh
$ openssl s_client -connect jails.tnpi.net:587 -starttls smtp -servername mail.simerson.net 2>&1 | grep ^subject
subject=/CN=mail.simerson.net
quit
$ openssl s_client -connect jails.tnpi.net:587 -starttls smtp -servername mail.theartfarm.com 2>&1 | grep ^subject
subject=/CN=mail.theartfarm.com
quit
```

**Comment by msimerson** [comment]
Closing, because this isn't a Haraka issue, it's a node.js with openssl issue, and there's nothing that Haraka can do about it.
