### ISSUE TITLE
Restrict mail from for specific IP address

### ISSUE THREAD

**Issue by bunyevacz** [haraka/Haraka#2637]
Lately we got immerse spam using the same technique, namely both the `from` and `to` match to the user email.
So I got emails which looks like I sent it to myself.

Each user gets about 20-30 spam/day like this, littering the junk folder, with other spams. Makes hard to catch miscategorized hams.

Our incoming email setup is haraka -> rspamd -> mail server (wildduck).
Rspamd correctly categorize it as spam, since both spf and dkim fails on these messages.
(we have dmarc, spf set up, and sign all outgoing emails with dkim)

But I would like to reject these kind of spams at the connection level.  
So I would like to enforce emails with sender `@mydomain.com` to specific IP addresses:
- LAN ip address (emails between collegues)
- primary MX IP address
- secondary MX IP address
- two sendgrid.com dedicated IP addresses
(- servers within 1e100.net, ie. google "send as" feature to work. Currently sends from their server, and they only sign it with `X-Google-DKIM-Signature: ...  d=1e100.net; s=20161025;` )

The right point of attack in our setup is haraka imho. But I'm stuck. I have read all plugins doc, but could not find my specific usecase.

I know spf is meant for this usecase, and we do have DNS txt record for spf. But I would like to enforce it for ourself only in haraka. Since many ham senders don't bother to correctly set up dkim and spf. So I need whitelist in rspamd. But for ourself I can reject it without putting them in the junk folder. Since its 100% sure forged email. Hence haraka:)

Any idea?

### system info
Haraka | Haraka.js — Version: 2.8.17
 --- | :--- 
Node | v8.11.2
OS | Linux mail.mydomain.com  Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

**Comment by msimerson** [comment]
Set SPF `context=myself` so that relaying messages from your legit users pass SPF evaluation and then let SPF block messages that fail SPF.

**Comment by msimerson** [comment]
You block failing SPF by adding this to spf.ini:

```ini
[relay]
context=myself 

[deny]
mfrom_fail=true
```
