### ISSUE TITLE
How the process_title plugin work

### ISSUE THREAD

**Issue by Abdeljalil0Cyclo** [haraka/Haraka#2640]
Hello , Where can i see the same ouput shown in the docs for the process_title plugin in Haraka , which hook to use to work with the results

Haraka (master) cn=11148 cc=1082 cps=21/25.24/79 rcpts=144950/1.84 rps=518/328.18/586 msgs=78815/7.07 mps=302/178.44/329 out=0/0/0 respawn=0 
 \_ Haraka (worker) cn=1646 cc=140 cps=5/3.73/17 rcpts=20310/1.86 rps=75/46.04/102 msgs=10938/6.65 mps=42/24.8/56 out=0/0/0 
 \_ Haraka (worker) cn=1563 cc=168 cps=3/3.54/18 rcpts=19844/1.87 rps=78/45/96

hope someone could help me , appreciate it guys

**Comment by smfreegard** [comment]
You'll see the output from the process title using the UNIX `ps` command:

`````
# ps axf
  PID TTY      STAT   TIME COMMAND
    2 ?        S      0:00 [kthreadd]
<snip>
 6709 ?        Ssl   20:25 Haraka (master) cn=54956 cc=0 cps=0/0.12/14 msgs=48088 mps=0/0.1/21 out=0/0/29 respawn=0 
 6726 ?        S      0:25  \_ vmstat -n 5
 6727 ?        S      0:12  \_ free -bs 5
 6732 ?        Sl    35:14  \_ Haraka (worker) cn=13740 cc=0 cps=0/0.03/4 msgs=12289 mps=0/0.03/10 out=0/0/8 
 6737 ?        Sl    33:41  \_ Haraka (worker) cn=13738 cc=0 cps=0/0.03/4 msgs=11442 mps=0/0.02/10 out=0/0/7 
 6738 ?        Sl    33:46  \_ Haraka (worker) cn=13740 cc=0 cps=0/0.03/3 msgs=12324 mps=0/0.03/10 out=0/0/11 
 6747 ?        Sl    33:48  \_ Haraka (worker) cn=13738 cc=0 cps=0/0.03/4 msgs=12033 mps=0/0.03/12 out=0/0/3 
`````

**Comment by Abdeljalil0Cyclo** [comment]
I tried the command in CentOs 6.10 this is what it showed  , some ouput is missing

> ps axf |grep Haraka
> 13327 pts/0    S+     0:00  |       \_ grep Haraka
> 12948 ?        Ssl    0:03 Haraka (master) cn=46 cc=0 cps=0/0.02/1 rcpts=46/1 rps=0/0.02/1 msg
> 13157 ?        Sl     0:03  \_ Haraka (worker) cn=23 cc=0 cps=0/0.01/1 rcpts=23/1 rps=0/0.01/1 msg
> 13165 ?        Sl     0:02  \_ Haraka (worker) cn=22 cc=0 cps=0/0.01/1 rcpts=22/1 rps=0/0.01/1 msg

**Comment by baudehlo** [comment]
You have to add fake nonsense to the command line used to start Haraka, so
that the memory is allocated for it to be used by process_title.

So basically `haraka -c /path/to/haraka
???????????????????????????????????????????????????????????????????????????????`
where there are enough question marks to fill the room used by the
process_title plugin.
