### ISSUE TITLE
transaction.remove_header removes too much

### ISSUE THREAD

**Issue by d--j** [haraka/Haraka#2641]
The following test plugin should remove the header `X-Test` but do not affect any other headers.

```js
exports.register = function () {
    const plugin = this;
    plugin.inherits('queue/quarantine')
    plugin.load_quarantine_ini();
    plugin.register_hook('queue',          'quarantine');
    plugin.register_hook('queue_outbound', 'quarantine');
}

exports.hook_rcpt = function (next, connection) {
    const plugin = this
    connection.notes.quarantine = true
    next(OK)
}

exports.hook_data_post = function (next, connection) {
    const plugin = this
    connection.transaction.remove_header('X-Test')
    next()
}

```

But when I call
```shell
swaks -s $HARAKA_HOST -p $HARAKA_PORT -t test@example.com --add-header "X-Test: remove-me" --add-header "X-Test-1: do-not-remove-me"
```

The `X-Test-1` header gets spuriously removed, too.

Looks like `_remove_more` in `mailheader.js` is the culprit:
https://github.com/haraka/Haraka/blob/4aea44d56834a1a4be78c56b646a6c266aa7d7b5/mailheader.js#L127-L135
(only comparing the header key where it should compare key + ':')

**Comment by msimerson** [comment]
That was kind of an odd one. I added a test and was surprised to see that `header.get('X-Test-1')` still retrieved the header. But then I realized that _remove_more was only removing it from `header_list`. I have created a PR that fixes this.
