### ISSUE TITLE
haraka: command not found

### ISSUE THREAD

**Issue by prashant2288** [haraka/Haraka#2646]
### system info

haraka: command not found
Haraka | 
 --- | :--- 
Node | v8.16.0
OS | Linux sarv-desktop 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.1b  26 Feb 2019)

###Issue:

I have installed haraka on my system with the following command:

sudo npm install -g Haraka --unsafe-perm

I used --unsafe-perm because without this i wasn't able to install it because it was showing that root doesn't have permission to to create folder etc... So i tried it and it worked for me, i also tried haraka command at that time and that was also working for me but when i restart my system and tried haraka command then its showing haraka: command not found. I also reinstalled the haraka but the issue remain same. Please help it's not working...

Thanks

**Comment by msimerson** [comment]
This might be related to #2686 

If you're still having issues, we can reopen this.
