### ISSUE TITLE
Make TLS configurable per domain for incoming/outgoing

### ISSUE THREAD

**Issue by eldok2** [haraka/Haraka#2658]
I have a postfix configuration set up to enforce TLS on specific incoming and outgoing connections to a list of domains, and fail if plaintext is used. If the domain is not there, use the most secure connection possible.

I found a way to disable TLS for a specific domain from Haraka, within the TLS config. (The [no_tls_hosts] option) but no way to force it as a requirement for a domain.

Is there a way to force TLS and block plain-text sessions for some domains, incoming and outgoing?

**Comment by msimerson** [comment]
Generally no. For incoming messages, TLS is usually negotiated before the mail domain(s) are known. For outbound, keeping track of mail hosts TLS failed for lets us deliver mail to hosts with broken TLS, and then automatically upgrade in the future when they begin working.

If you want to extend Haraka to support configurable TLS per domain, we'll certainly review the PR. If it includes tests, has clean code that's easy for humans to understand, and a decent docs, it has a good chance of landing. If it improves the TLS code/docs/config and is backwards compatible, it has a very good chance of merging.
