### ISSUE TITLE
Please publish docs to github site

### ISSUE THREAD

**Issue by tcrowe** [haraka/Haraka#2661]
### system info

(system info not relevant to this one)

### Expected behavior

This page:
https://haraka.github.io/manual/CoreConfig.html

Matches:
https://github.com/haraka/Haraka/blob/master/docs/CoreConfig.md

### Observed behavior

It doesn't match. My guess is that it's possibly out of date.
https://haraka.github.io/manual/CoreConfig.html

### Steps to reproduce

If you click both links above you can see they don't match.

---

Thank you, Harakians! 🤓

**Comment by baudehlo** [comment]
Done. Can someone please check them?
