### ISSUE TITLE
Outbound mail, TLS disabled by default

### ISSUE THREAD

**Issue by Bramzor** [haraka/Haraka#2665]
According to the documentation, for outbound mail, TLS is by default disabled.
It does not mention why this is the case, but sounds to me it should be enabled by default as best practices?

According to the outbound.ini file:
`; uncomment to disable tls for outbound mail
; enable_tls=false`

So either documentation (manual) on the website has a typo or the outbound.ini file.

**Comment by msimerson** [comment]
> According to the documentation, for outbound mail, TLS is by default disabled.

Citation please.

> According to the outbound.ini file:
> ; uncomment to disable tls for outbound mail
> ; enable_tls=false

That's correct. TLS is enabled by default. Uncomment that line to disable TLS.
