### ISSUE TITLE
TLS with Let's encrypt

### ISSUE THREAD

**Issue by giancarllorojas** [haraka/Haraka#2678]
Has anyone successfully configured TLS using Let's Encrypt certificates? I'm struggling trying to make it work.

I activated the TLS plugin and copied the certificate as follow:
cp /etc/letsencrypt/live/MYDOMAIN/privkey.pem /home/jenkins/haraka/config/tls_key.pem
cp /etc/letsencrypt/live/MYDOMAIN/cert.pem    /home/jenkins/haraka/config/tls_cert.pem 

### system info
Node v8.10.0 using the lastest Haraka from git

### Expected behavior
TLS to work

### Observed behavior
TLS is working, but the certificate is not.

### Steps to reproduce
- Clone Haraka from github
- Generate a Let's Encrypt certificate
- Activate the TLS plugin
- Copy the certificate as follow:
cp /etc/letsencrypt/live/MYDOMAIN/privkey.pem /home/jenkins/haraka/config/tls_key.pem
cp /etc/letsencrypt/live/MYDOMAIN/cert.pem    /home/jenkins/haraka/config/tls_cert.pem

**Comment by baudehlo** [comment]
I have mine working fine with the following configuration:

matt@ms1vm01:~$ cat /home/smtpd/haraka-inbound/config/tls.ini

key=/etc/letsencrypt/live/mail.sergeant.org/privkey.pem

cert=/etc/letsencrypt/live/mail.sergeant.org/fullchain.pem

**Comment by msimerson** [comment]
LE certs work great with Haraka. Make sure you have the full certificate chain installed for the cert.
