### ISSUE TITLE
Outbound delivery stalls indefinitely when receiver SMTP accepts connection, but is silent

### ISSUE THREAD

**Issue by fredrikdev** [haraka/Haraka#2683]
### System info

Haraka.js — Version: 2.8.24
Node v10.16.0
Microsoft Windows [Version 10.0.14393]

### Expected behavior

Problem first: When the outbound delivery process in Haraka connects to a receiver SMTP server, that accepts connection, but doesn't send `220 Welcome`, delivery silently fails or seem to stall indefinitely. 

Wanted behaviour would probably be that that `/line_socket.js` emits a `close` event after some timeout. This would make the method `try_deliver_host_on_socket` continue and not stall.

### Observed behavior

Here's an excerpt from the log:

```
2019-08-13T15:25:05.931Z [INFO] [94427591-A78D-4563-B1BD-A278967AD0AA.7077.1] [outbound] Looking up A records for: mail.udo-kilian.de
2019-08-13T15:25:05.931Z [INFO] [94427591-A78D-4563-B1BD-A278967AD0AA.7077.1] [outbound] Attempting to deliver to: 88.198.35.234:25 (0) (0)
2019-08-13T15:25:05.931Z [INFO] [-] [core] [outbound] [outbound::25:88.198.35.234:undefined:60] dispense() clients=1 available=0
2019-08-13T15:25:05.931Z [DEBUG] [1E8CEFB8-C950-486D-84B6-308E269F65A0] [core] [outbound] created
2019-08-13T15:25:05.931Z [DEBUG] [-] [core] [outbound] [outbound::25:88.198.35.234:undefined:60] createResource() - creating obj - count=1 min=0 max=10
2019-08-13T15:25:05.947Z [INFO] [-] [core] [outbound] acquired socket 1E8CEFB8-C950-486D-84B6-308E269F65A0 for outbound::25:88.198.35.234:undefined:60
```

And nothing more about this session. Never... My guess is that `/line_socket.js` never emits a "line" event (since a line is never received 😄) and that there's a need for a read-timeout feature in this class. 

### Steps to reproduce

Send a a mail to a recipient that has a MX-server that accepts the connection, but never says `220 Welcome`. I guess you try the MX above, although I'm not the owner. 

Another way would be to hack the method `found_mx` (in hmail.js) so that it always returns a given host which accepts the connection but doesn't talk back. (And setup your own listener...)

**Comment by baudehlo** [comment]
By "never" how long did you wait? The initial timeout is supposed to be 5
minutes: https://tools.ietf.org/html/rfc5321#section-4.5.3.2

**Comment by fredrikdev** [comment]
I did wait (in some case up to 24 hours), but the process seem to stall/hang. - If it did timeout, shouldn't that generate another row in the log (idk..)? Also, the mail isn't retried until i restart the server -- so I guess it really waits indefinitely. ⏳ 

Guess you can't trust the implementations of receiving SMTP servers, so I do think Haraka need to have it's own timeout for these cases.

**Comment by baudehlo** [comment]
As a follow up, the code does set an idle timeout of 30 seconds by default.
I guess it's entirely possible it's not working...

**Comment by analogic** [comment]
AFAIK stalled tcp connection should be killed by OS eventually. Linux has 2 hours by default but anyway it is far away from RFC

**Comment by baudehlo** [comment]
So does Socket.setTimeout just not work then?

**Comment by fredrikdev** [comment]
Could it be that `./tls_socket.js `has the following piece of code? (So that timeout might be infinite)

`this._timeout = 0;`

... I'll try to do some more testing today (and perhaps even debugging) to see if I can get some more leads for you. Thanks!

**Comment by fredrikdev** [comment]
I think this might be a good patch for the issue. The following patch to `./hmail.js` will handle the `timeout`-event emitted from the socket by simply emitting an `error`-event.

```
...
    try_deliver_host_on_socket (mx, host, port, socket) {
        const self            = this;
        let processing_mail = true;

        socket.removeAllListeners('error');
        socket.removeAllListeners('close');
        socket.removeAllListeners('end');

        // NEW: handle socket timeout
        socket.once('timeout', function() {
            socket.emit('error', './hmail.js/try_deliver_host_on_socket(): received socket timeout, emitting error event');
        });

        socket.once('error', function (err) {
            if (processing_mail) {
...
```

I've tried it and it seems to work gracefully and nice. 2-3 tests is good enought to put into production 😄 Right?

**Comment by baudehlo** [comment]
Unfortunately that's the wrong place because those sockets can be used for
more than one email, but it's nice to know that "fixes" things for you - it
gives me more to explore.

**Comment by fredrikdev** [comment]
Great! Thanks for looking in to this 👍

**Comment by apmcodes** [comment]
Exact same issue happened today with a specific domain (arh.org) that do not responsd with 220 on connection and the session hangs after _acquired socket_

Neither pool_timeout (after 50 sec) nor socket.setTimeout (after 30 sec) gets triggered.  

Adding the below timeout handler does gets triggered and then I can try the next MX. Thanks @fredrikdev. 


> I think this might be a good patch for the issue. The following patch to `./outbound/hmail.js` will handle the `timeout`-event emitted from the socket by simply emitting an `error`-event.
> 
> ```
> ...
>     try_deliver_host_on_socket (mx, host, port, socket) {
>         const self            = this;
>         let processing_mail = true;
> 
>         socket.removeAllListeners('error');
>         socket.removeAllListeners('close');
>         socket.removeAllListeners('end');
> 
>         // NEW: handle socket timeout
>         socket.once('timeout', function() {
>             socket.emit('error', './outbound/hmail.js/try_deliver_host_on_socket(): received socket timeout, emitting error event');
>         });
> 
>         socket.once('error', function (err) {
>             if (processing_mail) {
> ...
> ```
> 
> I've tried it and it seems to work gracefully and nice. 2-3 tests is good enough to put into production  Right?

**Comment by baudehlo** [comment]
I decided the patch was mostly right. See the PR.
