### ISSUE TITLE
Stuck at Attempting to deliver. Needs generic_pool update?

### ISSUE THREAD

**Issue by apmcodes** [haraka/Haraka#2694]
Stuck at Attempting to deliver and doesn't timeout after connect_timeout (30 sec)

```
info: Looking up A records for: aspmx.l.google.com
info: Attempting to deliver to: 108.177.127.26:25 ... 
```
Seems google is not accepting the connection. And not sure why generic_pool do not timeout/ return error. 
As per generic_pool v2.5 code, acquire() returns after acquiring client. Not sure if this is related. 
```
 * Request a new client. The callback will be called,
 * when a new client will be availabe, passing the client to it.
```
But, in generic_pool v3.x theres a acquireTimeoutMillis, will that trigge a timeout in such scenario?

`acquireTimeoutMillis: max milliseconds an acquire call will wait for a resource before timing out. (default no limit), if supplied should non-zero positive integer.`

Will upgrading generic_pool to v3 will help?

**Comment by msimerson** [comment]
We **do** need to update generic pool. There's some important changes in v3, as well as API (it's promise based now) changes we need to make.

**Comment by apmcodes** [comment]
Okay. Thanks.

Just to confirm, this issue of getting stuck at Attempting to deliver is due to generic-pool?

**Comment by apmcodes** [comment]
Have upgraded generic-pool to v.3.7.1. Will check if the above issue reappears.

**Comment by celesteking** [comment]
There's no bug in socket timeout handling code in client_pool.js code. Prove me wrong by providing full log and a reproducible test-case.
