### ISSUE TITLE
Multiline Headers are unfolded incorrectly

### ISSUE THREAD

**Issue by shurli** [haraka/Haraka#2702]
### system info

Haraka 2.8.23

### Expected behavior
Correct Folding of multiline headers

### Observed behavior
mailheader.js line 25:

>for (const line of lines) {
>  if (/^[ \t]/.test(line)) {
>    // continuation
>    this.header_list[this.header_list.length - 1] += line;
>  }

if headerlines starts with tab or whitespace they are add to preveous headerline.
But tab and whitespace is preserved.

mailheader.js line 55:
>decode_header (val) {
>  // Fold continuations
>  val = val.replace(/\r?\n/g, '');

linefeeds are removed, but whitespace is preserved

This leads to extra unwanted whitespace in long subjects
or even to unparsable addresses see  [node-address-rfc2822#41](https://github.com/Haraka/node-address-rfc2822/issues/41)

**Comment by shurli** [comment]
ok, maybe this praxis is ok with standard headers (see rfc822  3.1.1) 
but there is at least a problem with encoded headers

**Comment by shurli** [comment]
rfc 2047 6.2:

> When displaying a particular header field that contains multiple
>    'encoded-word's, any 'linear-white-space' that separates a pair of
>    adjacent 'encoded-word's is ignored.  (This is to allow the use of
>    multiple 'encoded-word's to represent long strings of unencoded text,
>    without having to separate 'encoded-word's where spaces occur in the
>    unencoded text.)

**Comment by shurli** [comment]
Possible solution
Inserted before line 89:

val = val.replace(/(\?=)\s*(=\?)/g,"$1$2");

**Comment by KingNoosh** [comment]
How confident are you with the above working @shurli?

**Comment by shurli** [comment]
I'm still testing in our production environment.
But for now it works for me.

Of course there is a minimal risk that the characters x?= =?y
where x and y is a non whitespace character occur even though theres not an encoded word.
In this case the whitespace whould be lost.
But i am not clever enough to make a more complete regex that fetches all whitespaces

**Comment by shurli** [comment]
`val = val.replace(/(=\?.+?\?=)\s+(?==\?.+?\?=)/g,"$1");`

This is the better regex which matches the encoded word on opening and closing delimiter.
I just learned the concept of regex positive lookahaid
