### ISSUE TITLE
[Outbound] Ongoing connection times out at connect_timeout instead of pool_timeout

### ISSUE THREAD

**Issue by apmcodes** [haraka/Haraka#2717]
If recipient smtp server takes time to respond on cmd (such as RCPT TO), socket timeout triggered at connect_timeout time instead of pool_timeout. 

In _create_socket fn we are setting socket timeout to connect_timeout (say 30s) but on connect we are not setting socket timeout again to pool_timeout (say 300s). Though we are setting idleTimeoutMillis.

We might need to reset socket timeout to pool_timeout on connect as below

```
    socket.once('connect', () => {
        socket.removeAllListeners('error'); // these get added after callback
        socket.removeAllListeners('timeout');
        socket.setTimeout(cfg.pool_timeout * 1000);  // ??? NEED THIS
        callback(null, socket);
    });
```

**Comment by celesteking** [comment]
`connect_timeout` is used to set every _incoming data_ timeout during outbound session. `pool_timeout` sets the time we keep the _pool resource_ AKA _outbound connection_ "hot".

I actually understand why you would want to have several knobs for different command timeouts -- some MTAs like to back off for spam-fighting purposes, but that behavior is not right I think as the proper thing would be just sending a 4xx tempfail code instead. 

And yeah, RFC is not followed on outbound timeouts, sadly. I'd suggest just raising the connect_timeout setting.  PRs are welcome.
