### ISSUE TITLE
Per origin log level

### ISSUE THREAD

**Issue by Stono** [haraka/Haraka#2727]
Hello, 
I'm wondering if it is possible to configure the log level per `origin`.

Basically, I want to set `core` to warn, but everything else on info, to suppress connection and disconnection messages.

Thanks

**Comment by baudehlo** [comment]
It's not possible by config. You might be able to hack it a bit via a
plugin (via logger.set_loglevel()), but the best you could do is adjust the
log level for a single process for the time period that origin's
transaction is open.

**Comment by msimerson** [comment]
> I'm wondering if it is possible to configure the log level per origin.

We cannot. You aren't the first person to want more customizable log levels. I'd love to have a definable log levels for an origin, or a plugin.
