### ISSUE TITLE
Should rabbitmq_amqplib try to reconnect to RabbitMQ if it fails?

### ISSUE THREAD

**Issue by vcorr** [haraka/Haraka#2733]
It looks like rabbitmq_amqplib does not try connect if RabbitMQ is not accepting connections when the plugin starts. Is this expected behaviour and why?
With the (older?) rabbitmq plugin the behaviour is different, and it will try reconnecting.

I tested this by running both Haraka and RabbitMQ with Docker compose and as RabbitMQ takes a while to start up, it will not be ready when the plugin first tries to reach it. With the "non amqplib" plugin that is not a problem as the connection is made and works once Rabbit is ready

**Comment by msimerson** [comment]
I think it should. After some backoff delay.

**Comment by msimerson** [comment]
stale.
