### ISSUE TITLE
How to pause the Q ?

### ISSUE THREAD

**Issue by dcaizued** [haraka/Haraka#2735]
Hi i don't know where to ask this question , can anyone help me please thank you in advance
How to pause the Queue and relase it after some time in haraka like we find in Port 25 powermta? 
or is there a way to pause using a plugin , or some hook in haraka

**Comment by celesteking** [comment]
By writing your own plugin that hooks on `send_email` hook and by responding with `next(DELAY, delay_seconds)` to defer sending the email. E.g., creating a lock file and delaying in case it's present and returning a `next()` in case it's not.

**Comment by baudehlo** [comment]
You can also set config/outbound.disabled

**Comment by celesteking** [comment]
OR that. Let's close this issue.

**Comment by KingNoosh** [comment]
No response from OP in a while, closing ticket

**Comment by dcaizued** [comment]
sorry for the  delay i though no body would answer thanks all , @celesteking  i get it now also @baudehlo  that was on the docummentation i don't know how i missed it  ,
another quetion is it possible to pause acoording to an event using for exemple http request or a socket ,  when the user click on pause button it pauses ,and   queuing emails but start sending when the user click resume ??

i apreciate your help guys

**Comment by baudehlo** [comment]
Yes, config files are reloaded immediately when changed, so just have that
http request change outbound.disabled and it should stop automatically.
