### ISSUE TITLE
Redis connection failures after initial setup

### ISSUE THREAD

**Issue by nmummau** [haraka/Haraka#2746]
### system info
OS: Ubuntu 18.04.3 LTS
Node: 10.17.0
npm: 6.13.0

### Expected behavior
Server runs without Redis connection failures

### Observed behavior
After following instructions [here](https://github.com/haraka/Haraka#running-haraka), my server runs but I get errors 

### Steps to reproduce
1. Follow README instructions at [Running Haraka](https://github.com/haraka/Haraka#running-haraka)
2. Server starts but never-ending Redis connection errors occur.

```
loaded TLD files: 1=1528 2=8564 3=2448
loaded 8787 Public Suffixes
loglevel: INFO
log format: DEFAULT
[WARN] [-] [core] smtp.ini.nodes unset, using 1, see https://github.com/haraka/Haraka/wiki/Performance-Tuning
Starting up Haraka version 2.8.25
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[NOTICE] [-] [queue/smtp_forward] outbound enabled, will default to disabled in Haraka v3 (see #1472)
[INFO] [-] [core] Loading plugin: limit
[NOTICE] [-] [core] Listening on :::25
[NOTICE] [-] [core] worker 1 listening on ::0:25
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[INFO] [-] [limit] Disconnected from redis://127.0.0.1:6379/4
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379```

**Comment by msimerson** [comment]
The [limit plugin](https://github.com/haraka/haraka-plugin-limit) requires redis. Either install redis or disable the limit plugin. The plugin has instructions.

**Comment by nmummau** [comment]
@msimerson Why is the limit plugin enabled? The basic setup instructions led me to where I am. It seems misleading that the basic instructions started me off with plugin errors like this.

As far as I see, limit is disabled in my `plugins` file:
```
#limit
```

So how do I go about disabling it?

**Comment by nmummau** [comment]
These redis errors only happen when I run with sudo: `sudo haraka -c /path/to/haraka_test`.

If I don't run with sudo, I get errors about EACCES
```
[ERROR] [-] [core] Failed to setup listeners: bind EACCES ::0:25
```

Either way, I feel like this issue was closed prematurely.

**Comment by baudehlo** [comment]
Don’t worry about the EACCESS errors - that’s saying that you can’t use port 25 unless you’re root (ie sudo).

We close issues when we don’t think there’s a Haraka bug. There likely isn’t here, but if there’s an error in the docs we will re-open.

Can you show us the entire contents of haraka_test/config/plugins ?

**Comment by nmummau** [comment]
@baudehlo Sure thing. The contents of my `config/plugins` is exactly what you get as a result of following the [Installing Haraka](https://github.com/haraka/Haraka#running-haraka) part of the README.

```
# This file lists plugins that Haraka will run
#
# Plugin ordering often matters, run 'haraka -o -c /path/to/haraka/config'
# to see the order plugins (and their hooks) will run in.
#
# To see a list of all plugins, run 'haraka -l'
#
# To see the help docs for a particular plugin, run 'haraka -h plugin.name'

#status
#process_title
# Log to syslog (see 'haraka -h syslog')
# syslog

# CONNECT
#toobusy
#karma
#relay
# control which IPs, rDNS hostnames, HELO hostnames, MAIL FROM addresses, and
# RCPT TO address you accept mail from. See 'haraka -h access'.
# access
# p0f
# geoip
# asn
# fcrdns
# block mails from known bad hosts (see config/dnsbl.zones for the DNS zones queried)
dnsbl

# HELO
#early_talker
# see config/helo.checks.ini for configuration
helo.checks
# see 'haraka -h tls' for config instructions before enabling!
# tls
#
# AUTH plugins require TLS before AUTH is advertised, see
#     https://github.com/haraka/Haraka/wiki/Require-SSL-TLS
# auth/flat_file
# auth/auth_proxy
# auth/auth_ldap

# MAIL FROM
# Only accept mail where the MAIL FROM domain is resolvable to an MX record
mail_from.is_resolvable
#spf

# RCPT TO
# At least one rcpt_to plugin is REQUIRED for inbound email. The simplest
# plugin is in_host_list, see 'haraka -h rcpt_to.in_host_list' to configure.
rcpt_to.in_host_list
#qmail-deliverable
#rcpt_to.ldap
#rcpt_to.routes

# DATA
#bounce
# Check mail headers are valid
data.headers
#data.uribl
#attachment
#clamd
#spamassassin
#dkim_sign
#limit

# QUEUE
# queues: discard  qmail-queue  quarantine  smtp_forward  smtp_proxy
# Queue mail via smtp - see config/smtp_forward.ini for where your mail goes
queue/smtp_forward

# Disconnect client if they spew bad SMTP commands at us
max_unrecognized_commands

#watch
```

**Comment by nmummau** [comment]
@baudehlo I should emphasize that I only get the Redis errors when running `sudo` but I get the EACCES error when running _without_ `sudo`. I'm just trying to get the server to run without errors as a first step in my Haraka setup.

**Comment by msimerson** [comment]
There's a mismatch between your config(s) and expectations. What you showed in your initial posts included this:

````
[INFO] [-] [core] Loading plugin: limit
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
````

Which means that the limit plugin **is** being loaded. Unless something new and novel happened in the Haraka code, that can only happen when it is enabled/uncommented in `config/plugins`. It seems more likely to me that there's some confusion about exactly where the plugins file is. 

When you pass the argument `-c /path/to/haraka/config` to haraka, the config path for haraka is thus `/path/to/haraka/config/config`, and your plugins file is thus `/path/to/haraka/config/config/plugins`.

Perhaps the bug here is that -c isn't really your config directory but the parent of the config directory.

**Comment by nmummau** [comment]
The file structure looks is what I got when first running `npm -i /home/nmummau/Code/haraka_test`
It looks like this:
```
/home/nmummau/Code/haraka_test
/home/nmummau/Code/haraka_test/config
/home/nmummau/Code/haraka_test/docs
/home/nmummau/Code/haraka_test/plugins
/home/nmummau/Code/haraka_test/queue
```

My `plugins` file exists in `/home/nmummau/Code/haraka_test/config` and limit is still commented out in `config/plugins`. 

When running `sudo haraka -c /home/nmummau/Code/haraka_test` I still get redis errors.
When running `haraka -c /home/nmummau/Code/haraka_test` I do not get redis errors.

Let me know if you're interested in anything else from me.

**Comment by vialoh** [comment]
I'm having the same issue, and I believe it is due to the `limit` plugin being loaded in place of the `max_unrecognized_commands` plugin. See each `NOTICE` below from the logs when running Haraka:

```
Starting up Haraka version 2.8.25
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[NOTICE] [-] [queue/smtp_forward] outbound enabled, will default to disabled in Haraka v3 (see #1472)
[NOTICE] [-] [core] the plugin max_unrecognized_commands has been replaced by 'limit'. Please update config/plugins
[INFO] [-] [core] Loading plugin: limit
[NOTICE] [-] [core] Listening on :::25
[NOTICE] [-] [core] worker 1 listening on ::0:25
[ERROR] [-] [limit] Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[INFO] [-] [limit] Disconnected from redis://127.0.0.1:6379/4
```

I just installed haraka, and the only commands I've run so far are `haraka -i /path/to/haraka` and `haraka -c /path/to/haraka`.

Should I go ahead and try v3?

@nmummau Are you still using haraka or did you switch to something else? If something else, I'm curious as to what you've chosen.

**Comment by msimerson** [comment]
You are correct @vialoh. To resolve you can either disable the max_unrecognized_commands plugin or provide a redis for the plugins to use.
