### ISSUE TITLE
Sending Email Without host_list

### ISSUE THREAD

**Issue by raihan519** [haraka/Haraka#2750]
Hi Guys, can someone help me with this issue?

## The Purpose
I want to use Haraka for SMTP Relay who is sending email to the recipient domain

## The Problem
I have a case. Let's say i want to send email to domain.com with Haraka.
By default, if i want my email sent successfully to domain.com, i must add line contains "domain.com" in config/host_list.

This is too complicated for me, beacuse i have to add the recipient domain to the config/host_list everytime when i am going to send email to a new domain

## The Question
**Is it possible to send email to domain.com, without add line contains domain.com in config/host_list?**

If it's possible, can someone inform how to do that?

**Comment by baudehlo** [comment]
You have to authenticate in some manner. That can be via IP address, via
SMTP AUTH (see the auth plugins), or some other means.

If we didn't enforce some form of authentication then anyone could use your
mail server as what's known as an "Open Relay".

**Comment by raihan519** [comment]
Hi Baudehlo,

Thank you for the information.
Now, i can relay Haraka to other relay server.
I think you can make it not becoming open relay by adding specific trusted network on relay_acl_network. So, only server with network specified in relay_acl_network can send email with Haraka

Best Regards,
Raihan
