### ISSUE TITLE
haraka.log timestamps

### ISSUE THREAD

**Issue by raihan519** [haraka/Haraka#2751]
Hi Guys, can someone help me with this issue?

## The Problem
I have a case. Timestamps on my haraka.log is not match with the server timezone.
My server timezone is using Asia/Jakarta, but it seems timestamps in haraka.log still using the UTC. Down below is the example of my haraka.log

```
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugins
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugin: syslog
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugin: dnsbl
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugin: helo.checks
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugin: mail_from.is_resolvable
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugin: data.headers
2020-01-17T03:09:14.257Z [INFO] [-] [core] Loading plugin: queue/smtp_forward
```

### log.ini
And this is the content of my log.ini file
```
[main]

; level=data, protocol, debug, info, notice, warn, error, crit, alert, emerg
level=info

; prepend timestamps to log entries? This setting does NOT affect logs emitted
; by logging plugins (like syslog).
timestamps=true

;  format=default, logfmt
format=default
```

## The Question
**Has someone in here know workaround of this issue? How to correct the timestamps in haraka.log?**

**Comment by msimerson** [comment]
The logged timezones are the TZ of the server. AFAIK, Haraka just logs the time using what a `Date` object returns. If you're getting something else, consider [setting the TZ environment variable as recommended here](https://stackoverflow.com/questions/8083410/how-can-i-set-the-default-timezone-in-node-js).

Another option is using the syslog plugin. Surely that is spitting out dates in your systems timezone.

**Comment by raihan519** [comment]
Hi msimerson,

Thank you so much for the information.
I already got my log timestamp correctly.
I solved this using rsyslog on ubuntu, not using daemonizing

### How???
* First step, add & activate haraka.service in systemd. The command kinda looks like this.
```
# cp /opt/Haraka/contrib/haraka.service /etc/systemd/system/
# sed "s~ExecStart=/usr/bin/haraka -c /path/to/your/config~ExecStart=/usr/bin/haraka -c /usr/local/haraka~g" -i  /etc/systemd/system/haraka.service
# systemctl daemon-reload
```
* Second step, try start haraka with systemd command.
```
# systemctl start haraka
# systemctl status haraka
haraka.service - Haraka MTA
Loaded: loaded (/etc/systemd/system/haraka.service; disabled; vendor preset: enabled)
Active: active (running) since Fri 2020-01-17 15:28:59 WIB; 5s ago
Main PID: 2393 (node)
Tasks: 18 (limit: 2318)
CGroup: /system.slice/haraka.service
├─2393 node /usr/bin/haraka -c /usr/local/haraka/
└─2404 /usr/bin/node /usr/lib/node_modules/Haraka/haraka.js -c /usr/local/haraka/
```
* Third step, redirecting haraka output to specific log file. Im using some kind of command from this reference (https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file).
  * Add 2 more line below the **[Service]** in **/etc/systemd/system/haraka.service** file.
```
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=haraka
```
   * Create new file **/etc/rsyslog.d/haraka.conf** and add the text below.
```
if $programname == 'haraka' then /var/log/haraka.log
& stop
```
   * Create and give permission to the log file.
```
# touch /var/log/haraka.log
# chown syslog:adm /var/log/haraka.log
```
* Fourth step, restart rsyslog and haraka service.
```
# systemctl daemon-reload
# systemctl restart rsyslog
# systemctl restart haraka
```

Then, you can monitor everything happen to your haraka from **/var/log/haraka.log**

**Comment by msimerson** [comment]
Using systemd to pipe stdout to syslog works fine. 

For reference, you can also log directly from haraka to [syslog](https://github.com/haraka/haraka-plugin-syslog)
