### ISSUE TITLE
 [core] tls cert could not be loaded.

### ISSUE THREAD

**Issue by dogpatchmedia** [haraka/Haraka#2752]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.25
 --- | :--- 
Node | v8.10.0
OS | Linux mail 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1  11 Sep 2018

### Expected behavior

TLS certificates to load

### Observed behavior

[ERROR] [-] [core] tls key /home/haraka/config/tls/privkey.pem could not be loaded.
[ERROR] [-] [core] tls cert /home/haraka/config/tls/fullchain.pem could not be loaded.

### Steps to reproduce

install haraka 2.8.25 and try and get TLS to work and see what happens.

**Comment by msimerson** [comment]
Did you modify the settings in config/tls.ini to match those non-default locations?

**Comment by msimerson** [comment]
Does it match the location of your TLS certificates? A mismatch between your config and the location of the file is the most likely explanation.

**Comment by dogpatchmedia** [comment]
Yeah all the paths are correct. I have updated all the config files and tripple checked them all and I still get that error.

**Comment by msimerson** [comment]
I still think your TLS paths aren't correct. show us the contents of these commands, when run in your config directory.

```sh
cat tls.ini
ls *.pem
ls tls/*.pem
```

**Comment by dogpatchmedia** [comment]
hunh, ok, my bad. spelling error that i didnt notice in the config file. i swear you look at these files long enough it all starts to look the same. good looking out. i appreciate the help.
