### ISSUE TITLE
config in $HOME is only partially read when dropping privileges

### ISSUE THREAD

**Issue by 3hhh** [haraka/Haraka#2756]
### system info

Haraka | Haraka.js  Version: 2.8.25
 --- | :--- 
Node | v8.10.0
OS | Linux 4.15.0-76-generic Ubuntu x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1  11 Sep 2018

### Steps to reproduce

1. `npm install -g haraka`
2. Install the configuration to a home directory, e.g. `/root/`, make sure it is world readable.
3. Configure more than one thread & privilege dropping to a user such as `haraka:haraka`.
4. Start `haraka` (I used systemd).
5. Change the configuration, e.g. `echo testing > /root/hconfig/config/smtpgreeting`

### Expected behavior
The changed config has an effect _or_ some error is logged. E.g. `telnet localhost 25` shows a different greeting.

### Observed behavior
The changed config has no effect. Nothing is logged.

### Notes
Interestingly, haraka notices the new config in its log (`...reloaded file xyz.`), but it has no effect. I did test this with various config files. More interestingly, some config files are read, e.g. `smtp.ini` and `log.ini`, others are not.

All works fine with the config in e.g. `/etc/`.

It's probably because the master thread runs as `root` and can read the config it requires, but the child threads run as `haraka` and `$HOME` usually has `o-r` permissions.
Anyway: Haraka detects the config file according to its own log, but cannot read it? This should at least be logged.

**Comment by msimerson** [comment]
This foot gun is warned about [in the docs](https://github.com/haraka/haraka-config?tab=readme-ov-file#reloadingcaching). The solution is: don't do that. If you drop privs, assure that Haraka processes still have the permissions they need.
