### ISSUE TITLE
Outbound needs to use a sane default for config.me in the HELO/EHLO

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#2757]
No more description required. Connection.js uses: `config.get('me') || os.hostname()`.

**Comment by msimerson** [comment]
I can't immediately think of any reason why outbound can't use the same.

**Comment by msimerson** [comment]
I just peeked inside haraka-net-utils and see that it exports get_primary_host_name.

```js
exports.get_primary_host_name = function () {
  return exports.config.get('me') || os.hostname();
}
```
