### ISSUE TITLE
Haraka crashes when MX A address is valid and AAAA is not valid

### ISSUE THREAD

**Issue by lnedry** [haraka/Haraka#2763]
### system info

Haraka | Haraka.js — Version: 2.8.23
 --- | :--- 
Node | v6.17.1
OS | Linux mx.bluestreak.net 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior

I expect Haraka to not crash.

### Observed behavior

Haraka crashes: if an MX host has an invalid AAAA address, even though it has a valid A address, an exception is thrown.

Feb 14 08:59:52 mx haraka[18095]: [INFO] [0816B6BC-2EE6-457B-8731-731B342E7332.1] [mail_from.is_resolvable] e.smilereminder.com: MX 5 mail.communitect.com => 192.41.13.251,::192.41.13.251
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core] Error: ipaddr: the address has neither IPv6 nor IPv4 format
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at Object.ipaddr.parse (/usr/lib/node_modules/Haraka/node_modules/ipaddr.js/lib/ipaddr.js:595:13)
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at Object.exports.ipv6_bogus (/usr/lib/node_modules/Haraka/node_modules/haraka-net-utils/index.js:347:26)
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/plugins/mail_from.is_resolvable.js:119:39
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/haraka-net-utils/index.js:328:7
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:3888:9
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:473:16
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at iteratorCallback (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:1064:13)
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:969:16
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:3885:13
Feb 14 08:59:52 mx haraka[18095]: [CRIT] [-] [core]     at dns.resolve6 (/usr/lib/node_modules/Haraka/node_modules/haraka-net-utils/index.js:320:11)

### Steps to reproduce

Haraka is running on server with IPv4 only.
Haraka will crash when it receives an email from an MX host that has a valid A address and an invalid AAAA address.
$ host mail.communitect.com
mail.communitect.com has address 192.41.13.251
mail.communitect.com has IPv6 address ::192.41.13.251

**Comment by baudehlo** [comment]
Can you also provide the stack trace from the crash, please?

**Comment by lnedry** [comment]
I edited the Observed Behavior, probably right after you received your email about this issue.
