### ISSUE TITLE
Iconv installed but Haraka thinks it's not

### ISSUE THREAD

**Issue by thenitai** [haraka/Haraka#2765]
Ubuntu LTS 18.04.4
Haraka 2.8.25
Node 12.16.1

Haraka reports on startup that "No iconv available - install with 'npm install iconv'"

However, iconv is locally installed and also globally (just to make sure). The node shell also recognizes iconv. Even the code from Haraka in the shell works:

```
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> Iconv = require('iconv').Iconv
[Function: Iconv]
> try { Iconv = require('iconv').Iconv }
... catch (err) {
...     logger.logdebug("No iconv available - install with 'npm install iconv'");
... }
[Function: Iconv]
```

**Comment by baudehlo** [comment]
How do you start Haraka? Are you sure it's installed for the same version?
(e.g. are you using nvm or something?). Also please include the actual
Haraka log lines.

**Comment by thenitai** [comment]
Sorry for the delay... I was able to get it all installed by uninstalling everything. Then using "npm -g config set user root" and installing Haraka again.
