### ISSUE TITLE
Make stamping of Original-Authentication-Results headers optional

### ISSUE THREAD

**Issue by sathishvenkataraman** [haraka/Haraka#2766]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.23
 --- | :---
Node | v10.17.0
OS | CYGWIN_NT-10.0 5570-7VTRPF2 2.11.2(0.329/5/3) 2018-11-08 14:34 x86_64 Cygwin
openssl | OpenSSL 1.0.2p  14 Aug 2018

### Expected behavior
The headers Original-Authentication-Results needs to be optional controlled under a property
as there are requirements to receive emails untampered as much as possible
### Observed behavior
The following headers are added.
Original-Authentication-Results: xxxx.yyyy.com;
	spf=fail smtp.mailfrom=aaaa@yyyy.com;
	dmarc=reject header.from=yyyy.com
### Steps to reproduce
Receive any email in Haraka and you can see these headers added.

**Comment by msimerson** [comment]
I vote no. When I last read the RFC about A-R, this is the prescribed behavior. 

We don’t generate the OAR header from thin air, the original-authentication-results header is the result of having an authentication-results header when the email arrives.

**Comment by sathishvenkataraman** [comment]
@msimerson Thanks for looking into this.  What you described is a valid behavior, however I have a requirement where the EML should be received and stored as-is, hence requesting to make "not stamping" optional controlled by a property.

**Comment by msimerson** [comment]
Closing. You are welcome to develop such a feature and submit it as a plugin. You might even borrow liberally from the [elasticsearch](https://github.com/haraka/haraka-plugin-elasticsearch/) plugin that stores much of a transaction metadata in an ES document. You could also save the message body there too. 

Or just write a plugin that queues the message to disk before data_post when the head updates are made. This is something you'll need to do yourself, or hire a dev to do. There's no interest from @haraka/core to add such a feature.
