### ISSUE TITLE
Document SMTPS port

### ISSUE THREAD

**Issue by mildsunrise** [haraka/Haraka#2772]
The `smtps_port` option was added in #2268 / #2269. However the option was not documented because use of STMPS was *not* encouraged, and STARTTLS was the way to go.

However RFC 8314 now recommends STMPS over STARTTLS (#2522). We should document:

 - that setting `listen` to the special port 465 creates an SMTPS server instead of a regular one.
 - that the above 'special port' can be changed with `smtps_port` (i.e. if no root)

**Comment by msimerson** [comment]
Agreed, PR welcome.

**Comment by msimerson** [comment]
This was noted in docs/plugins/relay.md
