### ISSUE TITLE
haraka-ldap

### ISSUE THREAD

**Issue by ViNNu9** [haraka/Haraka#2781]
### Im getting the issue with haraka-ldap

[ERROR] [-] [auth/auth_ldap] This plugin has moved. See https://github.com/haraka/haraka-plugin-auth-ldap
##### Installed and tryed
npm install -g haraka-plugin-ldap
npm install -g haraka-pulging-auth-ldap

#### when i want send mail using authentication with ldap its showing an error:

*** Host did not advertise authentication 
im getting above error  

#### Please help me get the issue resolved as soon as possible

**Comment by msimerson** [comment]
Add the plugin name `auth-ldap` to your config/plugins file. Remove the `ldap` entry.

**Comment by ViNNu9** [comment]
I have added but still showing same error and another doubt where i have to remove ldap entry

**Comment by ViNNu9** [comment]
### Yes Its working!!!!!!!!
