### ISSUE TITLE
Pool doesn't respect smtp_forward domain_selector=mail_from if hosts and port are the same

### ISSUE THREAD

**Issue by ajimix** [haraka/Haraka#2788]
### system info

Haraka | Haraka.js — Version: 2.8.25
 --- | :---
Node | v12.16.1
OS | Linux redacted 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1d  10 Sep 2019

### Expected behavior

When using the following example script (check below in "Steps to reproduce"), I expect emails sent from user@domain1.com to be sent using domain1.com settings, and emails sent from user@domain2.com to be sent with domain2.com settings regardless of how fast the emails are sent or if the hosts and ports in the config are the same.

### Observed behavior

If the emails are sent slow, waiting between emails (so the pool is closed), the behavior is correct, every email is sent accordingly with the right settings. If instead the emails are sent quick one after the other, the same connection pool is used and the second email is sent using the settings from the first email as the smtp connection pool is being reused.

### Steps to reproduce

Enable smtp_forward plugin and create the following config smtp_forward.ini:

```
domain_selector=mail_from

[domain1.com]
enable_tls=true
auth_type=plain
host=smtp.samehost.com
port=587
auth_user=postmaster1@somehost.com
auth_pass=some_password1

[domain2.com]
enable_tls=true
auth_type=plain
host=smtp.samehost.com
port=587
auth_user=postmaster2@somehost.com
auth_pass=some_password2
```

Then try to send an email that will be forwarded, first using user@domain1.com and then send with user@domain2.com. The second email will reuse the open pool and will incorrectly use the settings of the first email.

**Comment by ajimix** [comment]
After digging in the code, I found the problem.

The problem is here: https://github.com/haraka/Haraka/blob/master/smtp_client.js#L298

It's creating the name of the pool based on `${port}:${host}:${pool_timeout}`. So if settings share the same host port and timeout, the pool is being shared.

As a temporary solution what I did is to use a different pool_timeout for each one like the following:

```
domain_selector=mail_from

[domain1.com]
enable_tls=true
auth_type=plain
host=smtp.samehost.com
port=587
auth_user=postmaster1@somehost.com
auth_pass=some_password1
timeout=300

[domain2.com]
enable_tls=true
auth_type=plain
host=smtp.samehost.com
port=587
auth_user=postmaster2@somehost.com
auth_pass=some_password2
timeout=301
```

This makes the pool unique per host and solves the problem, but would be nice to be able to do this without tricks. Maybe the auth_user can be used as pool identifier as well, something like: `${port}:${host}:${pool_timeout}:${auth_user}` so this is solved.

By the way, my use case of this is using Mailgun as a sending server. They only have one host and port but they have different users for each domain

**Comment by msimerson** [comment]
> Maybe the auth_user can be used as pool identifier as well, something like: ${port}:${host}:${pool_timeout}:${auth_user} so this is solved.

Sounds quite reasonable. A PR is welcome.

**Comment by ajimix** [comment]
@msimerson done #2789

Thanks for the great work!

**Comment by msimerson** [comment]
Hello @ajimix, sorry the delay in replying. The test suite is now failing in your PR (see the Checks tab in your PR). If you dig into the log messages, you'll find the failing tests. You can more quickly test just the smtp client locally with this command: `./run_tests tests/smtp_client.js`

**Comment by ajimix** [comment]
@msimerson I've checked the logs and there are a lot of unrelated test errors. Things like certificates failing and connections failing. Are those errors really related to the change I did? I just changed a single line of code that shouldn't fire all those errors as the line I changed covers all cases, when there is an auth user and when there isn't.
To be honest I don't even know where to start solving all those errors which seem to be unrelated. Is it possible the CI failed? Can it be triggered again?

**Comment by msimerson** [comment]
Most aren’t test failures, they are “expected errors” being logged, with a passing test. The TLS code does validity testing of certs while loading them. Ignore those and look only at the failing tests.

Use the command I showed you above to run only the tests you broke.

**Comment by ajimix** [comment]
@msimerson ok now is green. Thanks for your help :)
