### ISSUE TITLE
tls error "spawn openssl enoent" - setup on windows

### ISSUE THREAD

**Issue by HoehensteigerGames** [haraka/Haraka#2790]
System: Windows Server 2019
Node: V12.6

I try to setup the haraka smtp server on my windows. Everything is working fine. But if i try to implement the tls module, i got an error:
![grafik](https://user-images.githubusercontent.com/58444802/79942480-3857d680-8467-11ea-8c7d-fd548bbfaa68.png)

What i have done:
1. I enabled the plugin tls
![grafik](https://user-images.githubusercontent.com/58444802/79943110-5eca4180-8468-11ea-9d50-a4003ede49c4.png)
2. I generated with open ssl the two .pem cert (public and private).
![grafik](https://user-images.githubusercontent.com/58444802/79943040-35a9b100-8468-11ea-8b87-60e6862f0bb4.png)
3. I set the key path in the tls.ini
![grafik](https://user-images.githubusercontent.com/58444802/79943011-20cd1d80-8468-11ea-9f40-e0737dc9d027.png)

i have done everything like in the documentation: https://haraka.github.io/manual/plugins/tls.html

Could you please help me?

**Comment by msimerson** [comment]
This sounds a lot like #2786. Have a look there and see if that doesn't help you.

**Comment by msimerson** [comment]
No response, closing. Reopen if you haven't resolved your issue.
