### ISSUE TITLE
Plugin : whitelisting domains and email address for specific user

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [haraka/Haraka#2794]
Is there any plugin in Haraka which we can use to whitelist domains and email address for specific users. Like different users may contain different whitelist of domains and email address.

**Comment by msimerson** [comment]
I use the [access](https://github.com/haraka/haraka-plugin-access) plugin for that.

**Comment by SpoortiPalakshaiah** [comment]
@msimerson does that plugin gives separate whitelisting for different users? I thought it is used for whitelisting or blacklisting for all the users.

**Comment by msimerson** [comment]
Oh sorry, I didn't read your question carefully enough. There isn't a plugin specifically to do what you want. The closest you can get today is using the SpamAssassin plugin. Combine that with the SA plugin for Squirrelmail and you can let your users white and blacklist users.
