### ISSUE TITLE
accounting_files plugin not working

### ISSUE THREAD

**Issue by Abdeljalil0Cyclo** [haraka/Haraka#2798]
Hello ,
I tried to work with the plugin haraka -h accounting files but it's not working
haraka doesn't recognize it

[CRIT] [-] [core] Caught exception: "Loading plugin accounting_files failed: No plugin with this name found"

https://github.com/acharkizakaria/haraka-plugin-accounting-files/blob/master/README.md

https://github.com/haraka/Haraka/blob/master/Plugins.md

**Comment by msimerson** [comment]
Try using the name `accounting-files` in config/plugins.

**Comment by smartdev10** [comment]
yes that was fixed README file should be updated

**Comment by Abdeljalil0Cyclo** [comment]
yes this is the fix the README file should be updated thank you
