### ISSUE TITLE
change the Received-header with different costum hostname

### ISSUE THREAD

**Issue by dcaizued** [haraka/Haraka#2803]
### system info

Haraka | Haraka.js — Version: 2.8.25
 --- | :--- 
Node | v12.16.3
OS | Linux 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"; 
openssl | OpenSSL 1.1.1c FIPS  28 May 2019

Hi i would like to use multiple hostname multiple ips , by default haraka uses the hostname in config/me and therefor the Received header is set is to the hostname

how to change the Received-header ?? 
how can i change it with a hook?

can you some one help please

**Comment by celesteking** [comment]
You can't unless you code it in.

**Comment by dcaizued** [comment]
i found out that [https://github.com/haraka/haraka-plugin-vmta](haraka-plugin-vmta) deos that , depends on the ip and host you use to send the received header changes

**Comment by celesteking** [comment]
Glad you've found a solution. Let's close the issue if there's nothing to add.
