### ISSUE TITLE
Header is empty in Data Hook

### ISSUE THREAD

**Issue by GRite** [haraka/Haraka#2804]
Hello All,

the header object is empty in the data hook. Is there any way to get header information on data hook?

Thanks for your help.

**Comment by msimerson** [comment]
No, the remote hasn't sent the message contents yet. Only envelope information is available.

**Comment by msimerson** [comment]
Use the `data_post` hook instead.

**Comment by GRite** [comment]
Hey msimerson,

thanks for your answer. Maybe you have another answer for me. I need to modify some content of the mail message after I get the response of a get request. My problem is that the important information for the get requests are in the header or in the mail body and if I send the request at body filter, the body filter function completed before the response is received.

How can I solve that the function waits for the response?

Thanks for your help and the Haraka Mail Server is awesome.
