### ISSUE TITLE
Can't send emails

### ISSUE THREAD

**Issue by kast0r** [haraka/Haraka#2805]
### system info
Haraka | Haraka.js — Version: 2.8.25
 --- | :---
Node | v8.10.0
OS | Linux SERVER 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1  11 Sep 2018

### Expected behavior

I'm trying to set Haraka as an internal relay server and right now the problem is :

I am able to test the server from external source, but when I try to send email from internal to internal, I get this error. Which means nothing for now. 

[NOTICE] [414FF837-3A96-48A6-8879-AAAE1B781F6A] [core] connect ip=10.99.11.6 port=42928 local_ip=:: local_port=25
[INFO] [414FF837-3A96-48A6-8879-AAAE1B781F6A] [helo.checks] multi: true, skip:proto_mismatch(private), host_mismatch(private)
[NOTICE] [414FF837-3A96-48A6-8879-AAAE1B781F6A.1] [core] sender <idrac-R710-1@dialoginsight.com> code=CONT msg=""
[INFO] [414FF837-3A96-48A6-8879-AAAE1B781F6A.1] [core]  hook=rcpt plugin=rcpt_to.in_host_list function=hook_rcpt params=<arbernard@dialoginsight.com> retval=OK msg=""
[NOTICE] [414FF837-3A96-48A6-8879-AAAE1B781F6A.1] [core] recipient <arbernard@dialoginsight.com> code=OK msg="" sender=idrac-R710-1@dialoginsight.com
[NOTICE] [414FF837-3A96-48A6-8879-AAAE1B781F6A.1] [core] message mid="" size=288 rcpts=1/0/0 delay=0.015 code=CONT msg=""
[NOTICE] [414FF837-3A96-48A6-8879-AAAE1B781F6A.1] [core] queue code=CONT msg=" (414FF837-3A96-48A6-8879-AAAE1B781F6A.1)"
[INFO] [414FF837-3A96-48A6-8879-AAAE1B781F6A.1] [core] client [10.99.11.6] half closed connection
[NOTICE] [414FF837-3A96-48A6-8879-AAAE1B781F6A.1] [core] disconnect ip=10.99.11.6 rdns=NXDOMAIN helo=dialoginsight.com relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=288 lr="451  (414FF837-3A96-48A6-8879-AAAE1B781F6A.1)" time=0.228

### Steps to reproduce

I want to be able to send emails from internal to internal as from external to internal. Everything looks well configured. I have TLS, Auth Flat_File, and it works when I use MXTOOLBOX email relay tester.

Do I need to post more log ?

Thanks a lot !

**Comment by msimerson** [comment]
The logs reflect that the message is being queued by Haraka. If the next hop is an internal host, you need to make sure that Haraka can find it, either by configuring DNS properly or configuring a plugin that returns the correct value on the get_mx hook.
