### ISSUE TITLE
Syntax error during STARTTLS

### ISSUE THREAD

**Issue by gramakri** [haraka/Haraka#2808]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | 27033702cce526bb95
Node | v12.16.2
OS | Linux 7cdbd7f0a196 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

OpenSSL 1.1.1g  21 Apr 2020

### Expected behavior

STARTTLS should works

### Observed behavior

STARTTLS gets a Syntax error response

### Steps to reproduce

1. When contacting mx00.1and1.fr, we get a syntax error when issuing a STARTTLS.
2. Per the logs, everything seems correct but wondering if anyone had any hints.
3. I can reproduce this consistently
4. openssl s_client --debug -starttls smtp -crlf -connect 212.227.15.41:25 works fine

```
[DEBUG] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound]  hook=get_mx plugin=queue/smtp_forward function=get_mx params=van-away.com retval=CONT msg=""
[INFO] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] Looking up A records for: mx00.1and1.fr
[INFO] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] Attempting to deliver to: 212.227.15.41:25 (0) (23)
[INFO] [-] [core] [outbound] [outbound::25:212.227.15.41:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:212.227.15.41:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [DD24E53C-AD51-4EFF-A06E-F2E3491D8D8B] [core] [outbound] created
[INFO] [-] [core] [outbound] acquired socket DD24E53C-AD51-4EFF-A06E-F2E3491D8D8B for outbound::25:212.227.15.41:undefined:50
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] S: 220 kundenserver.de (mxeue012) Nemesis ESMTP Service ready\r\n
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] C: EHLO my.<redacted>
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] S: 250-kundenserver.de Hello my.<redacted> [54.37.96.209]\r\n
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] S: 250-SIZE 157286400\r\n
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] S: 250 STARTTLS\r\n
[DEBUG] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] Trying TLS for domain: van-away.com, host: 212.227.15.41
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] C: STARTTLS
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] S: 500 Syntax error, command unrecognized\r\n
[PROTOCOL] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] C: RSET
[INFO] [DDE5533A-8C97-4675-B204-DD1D1526E4D1.1.1] [outbound] bouncing mail: 500 Syntax error, command unrecognized
```

**Comment by gramakri** [comment]
This is a server issue and not Haraka issue. Sorry, for the noise.

I am able to reproduce this with openssl CLI itself. My mistake was that I was running the CLI from another server and it worked there. But running it on the same server as Haraka makes it fail. I am guessing this is some poorly implemented IP blacklisting.

**Comment by msimerson** [comment]
Is the version of OpenSSL the same on both machines you tested from?
