### ISSUE TITLE
Adding extra recipient for inbound mails

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [haraka/Haraka#2817]
Hello @msimerson I wanted to add a recipient for the inbound mails in Haraka. I tried writing a plugin like
 
```js
const Address = require('address-rfc2821').Address;
exports.hook_rcpt = function( next, connection){
        connection.transaction.rcpt_to.push(new Address('<some_recipient@example.com>'));
        this.loginfo(connection.transaction.rcpt_to);
        return next();
};
```
System info
Haraka version -> 2.8.25
Node version -> v12.16.2
OS -> Linux

Expected behavior
Mail being sent to both the recipients ( specified by sender as well as recipient added through plugin)

Observed behavior
Mail is delivered only to the recipient specified by the sender.  `connection.transaction.rcpt_to` contains both the addresses
but the mail is not delivered to both the addresses.

**Comment by msimerson** [comment]
Hrmmm, I have a faded memory of trying this once. I don't remember the solution but try this and see if it makes a difference.

```js
const Address = require('address-rfc2821').Address;
exports.hook_rcpt = function( next, connection){
    const extra_rcpt = new Address('<some_recipient@example.com>');
    connection.transaction.rcpt_to.push(extra_rcpt);
    connection.rcpt_incr(extra_rcpt, 'accept');
    // this.loginfo(connection.transaction.rcpt_to);
    next();
};
```
