### ISSUE TITLE
Settings and address for bouncing message

### ISSUE THREAD

**Issue by Taxman972** [haraka/Haraka#2819]
When I try to send an email to an address which doesn't exist Haraka try to send me an notification but
this email is rejected with these providers (yahoo, live, orange, gandi) and gmail flag it as spam.

That only happen for bouncing notification email not normal emails.

Any idea  how to succed ?

**Comment by superman20** [comment]
I've had similar issues and part of the problem is detailed in #1907.  You'll have to do some testing to determine if you have the same issue or something else entirely.

**Comment by Taxman972** [comment]
@superman20 Thanks for your help. 

I thought of something like that and inspected the `hmail.js` to understand why the file `outbound.bounce_message` isn't used for the from field. On line 1250 there is `const from = new Address ('<>');` and it looks like impossible to change to another address.

For me it's a bug the file `outbound.bounce_message` should be used.

**Comment by baudehlo** [comment]
If you don't send a bounce from <> you can end up with a mail loop.

(This probably doesn't help your issue, but that's why it's hard coded to
that)

**Comment by msimerson** [comment]
I don't see anything to do here. Closing as stale.
