### ISSUE TITLE
Q: How to deliver to two outbound destinations?

### ISSUE THREAD

**Issue by tino** [haraka/Haraka#2820]
My current setup is that I deliver local `lmtp` to Arhiveopteryx. I would like to now *also* forward all mail to my new @hey.com account. I've tried this with a second plugin, like https://github.com/chadsmith/haraka-alias-forward, but I can't seem to make both work. I assume that only one of the two `queue` hooks should call `next(OK)`, and the earlier one should just call `next()`. Is that correct?

What would be the right way to set this up?

PS. I tried asking on IRC on https://webchat.freenode.net/ but always got logged out, never saw an answer and can also not find archives anywhere...

**Comment by msimerson** [comment]
> I assume that only one of the two queue hooks should call next(OK), and the earlier one should just call next(). Is that correct?

Yes, that's correct.

> What would be the right way to set this up?

That plugin you are using removes the primary recipient from the transaction. If you just comment out that line, I think you'll get the behavior you want (delivery to both the expected and the aliased addresses).
