### ISSUE TITLE
smtp_forward multiple domain

### ISSUE THREAD

**Issue by Dinip** [haraka/Haraka#2821]
### system info
Haraka | Haraka.js — Version: 2.8.25
 --- | :--- 
Node | v12.17.0
OS | Linux mail.domain.tld5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 GNU/Linux

### Expected behavior
I'm currently using [poste.io](https://poste.io/) as my mailserver which uses haraka. It has a GUI to configure the "simple" stuff but the configs can also be changed via CLI. Until now I was just using 1 domain and sending the mails via mailgun using the default smtp route config to route all the mails to mailgun's smtp server. Now I want to add another domain, which will also send mails via mailgun (could be other provider) and I need to set a smtp route for that domain. I was searching and I found the smtp_forward plugin which seems like that could achieve what I wan't. I tried to configure it with the help of the docs but it keeps sending the emails directly from my mail server ip.
![image](https://user-images.githubusercontent.com/8941012/87258598-c22ea300-c49c-11ea-9185-d555f9f07f10.png)

### Steps to reproduce
This is my smtp_forward.ini that is inside the config folder. My plugins config is the following which includes queue/smtp_forward:
`                                                                                    
status_http
poste
known-senders
stats
guard
hello_block
block_bad_connections
limits
srs
geoip
log
relay
tls
redis
auth/poste
rcpt_database
dovecot_quota
attachment
strict_from
privacy
inspection
dkim_sign
queue/lmtp
queue/smtp_forward
watch
limit`
![image](https://user-images.githubusercontent.com/8941012/87258483-c6a68c00-c49b-11ea-9db2-9e6ca573443b.png)

I'm definitely missing something here...

**Comment by analogic** [comment]
You should use vanilla Haraka if you want to use smtp_forward. Poste.io will not work with smtp_forward because routing behaviour is simplified and highly customized...
