### ISSUE TITLE
MX record giving timeout

### ISSUE THREAD

**Issue by durai145** [haraka/Haraka#2823]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

echo "Haraka | $(haraka -v)"; echo " --- | :--- "; echo "Node | $(node -v)"; echo "OS | $(uname -a)"; echo "openssl | $(openssl version)"

**Comment by durai145** [comment]
root@columbarian:~# swaks -f auth@matter-in-motion.org -t velocityzen@gmail.com
=== Trying gmail-smtp-in.l.google.com:25...

**Comment by durai145** [comment]
*** Error connecting to gmail-smtp-in.l.google.com:25:
*** 	IO::Socket::INET6: connect: timeout

**Comment by msimerson** [comment]
Your provider is blocking port 25 output. This is not a Haraka issue.
