### ISSUE TITLE
550 issue for a SMTP relay

### ISSUE THREAD

**Issue by Fred2VOX** [haraka/Haraka#2824]
### system info

Haraka | Haraka.js — Version: 2.8.24
 --- | :--- 
Node | v12.18.2
OS | Linux ip-22-0-0-43 5.4.0-1017-aws #17-Ubuntu SMP Fri Jun 19 17:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1f  31 Mar 2020

### Expected behavior
Hi,
I've deployed the following architecture on AWS:
- a set of instances interacting with the end-user, then sending some emails thru a local sendmail, configured as smart host,
- a centralized email server, targetting by the sendmails and in charge to sign and send the emails to the recipients. This instance hosts an Haraka instance configured as outgoing smtp.

My issue is: all emails pushed by the sendmails to Haraka are refused: 550 I cannot deliver mail for <...@....com>.

I certainly miss something, but I don't figure what. 

Thanks in advance

### Observed behavior
`
[NOTICE] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] connect ip=.... port=46670 local_ip=... local_port=5870

[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running connect_init hooks
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running connect_init hook in relay plugin
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [relay] checking ... in relay_acl_allow
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core]  hook=connect_init plugin=relay function=acl params="" retval=CONT msg=""
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running connect_init_respond
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running lookup_rdns hooks
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running connect hooks
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running connect hook in relay plugin
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core]  hook=connect plugin=relay function=pass_relaying params="" retval=CONT msg=""
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] S: 220 smtp..... ESMTP Haraka/2.8.24 ready
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] C: EHLO ip-.....eu-west-1.compute.internal state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running ehlo hooks
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running capabilities hooks
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running capabilities hook in tls plugin
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core]  hook=capabilities plugin=tls function=advertise_starttls params="" retval=CONT msg=""
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] running capabilities hook in auth/flat_file plugin
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [auth/flat_file] Auth disabled for insecure public connection
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core]  hook=capabilities plugin=auth/flat_file function=hook_capabilities params="" retval=CONT msg=""
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] S: 250-smtp.voxvalue.fr Hello ip-.....eu-west-1.compute.internal [....]Haraka is at your service.
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] S: 250-PIPELINING
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] S: 250-8BITMIME
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] S: 250-SMTPUTF8
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] S: 250 SIZE 0
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58] [core] C: MAIL From:<administrator@....> SIZE=3934 BODY=8BITMIME state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] running mail hooks
[NOTICE] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] sender <administrator@....> code=CONT msg=""
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] S: 250 sender <administrator@...> OK
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] C: RCPT To:<....@....> state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] running rcpt hooks
[NOTICE] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] recipient <...@...> code=OK msg="" sender=administrator@...
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] S: 550 I cannot deliver mail for <...@...>
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] C: DATA state=1
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] S: 503 RCPT required first
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] C: RSET state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] running rset hooks
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] S: 250 OK
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] running reset_transaction hooks
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] C: RSET state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] running rset hooks
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] S: 250 OK
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.1] [core] C: MAIL From:<> BODY=8BITMIME state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] running mail hooks
[NOTICE] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] sender <> code=CONT msg=""
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] S: 250 sender <> OK
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] C: RCPT To:<administrator@...> state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] running rcpt hooks
[NOTICE] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] recipient <administrator@...> code=OK msg="" sender=""
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] S: 550 I cannot deliver mail for <administrator@voxvalue.fr>
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] C: DATA state=1
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] S: 503 RCPT required first
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] C: RSET state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] running rset hooks
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] S: 250 OK
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] running reset_transaction hooks
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] C: QUIT state=1
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] running quit hooks
[PROTOCOL] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] S: 221 smtp.... closing connection. Have a jolly good day.
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] client has disconnected
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] running disconnect hooks
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] client has disconnected
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] running disconnect hook in tls plugin
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] client has disconnected
[DEBUG] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core]  hook=disconnect plugin=tls function=hook_disconnect params="" retval=CONT msg=""
[NOTICE] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] disconnect ip=... rdns=ip-....eu-west-1.compute.internal helo=ip-....eu-west-1.compute.internal relay=N early=N esmtp=Y tls=N pipe=N errors=2 txns=2 rcpts=0/0/2 msgs=0/0/0 bytes=0 lr="503 RCPT required first" time=0.073
`

Here are the activated plugins:

redis
relay
tls
auth/flat_file
data.headers
dkim_sign
limit

**Comment by msimerson** [comment]
You need to configure Haraka to enable relaying for your sendmail hosts.

**Comment by Fred2VOX** [comment]
Hi @msimerson 
I did it par configuring the plugin relay for all (testing and validation purpose, safe into a closed area)(cf. log lines, from 3 to 6). 
Do i need that sendmail connect to Haraka over TLS systematically (not the case for now)?
Thanks

**Comment by msimerson** [comment]
````
[NOTICE] [3A01AF0D-1996-4C0F-B3DD-C23407427E58.2] [core] disconnect ip=... rdns=ip-....eu-west-1.compute.internal helo=ip-....eu-west-1.compute.internal relay=N early=N esmtp=Y tls=N pipe=N errors=2 txns=2 rcpts=0/0/2 msgs=0/0/0 bytes=0 lr="503 RCPT required first" time=0.073
````

See the `relay=N` bit in the connection summary? That means relaying wasn't active for that connection. Once you have relaying set up properly, Haraka will accept emails to any recipient from the relaying host.

**Comment by Fred2VOX** [comment]
Hi @msimerson 
Thanks for the support. Effectively, the TLS upport is required for relay.
