### ISSUE TITLE
A need for more docs

### ISSUE THREAD

**Issue by ahmed-com** [haraka/Haraka#2825]
First of all thanks for the huge effort that was put into this project .

receiving emails with haraka is straightforward enough, but when it comes to creating a node server that sends emails, even a very simple one, I can't find anything but [Configuring Haraka For Outbound Email](https://haraka.github.io/manual/tutorials/SettingUpOutbound.html) & [Outbound Mail with Haraka](https://haraka.github.io/manual/Outbound.html) , which do not even show an example of such plugin.

Also in the end of [Outbound Mail with Haraka](https://haraka.github.io/manual/Outbound.html) , it gives an example of the "outbound module" which I literally can't find any documentation for it on the entire [internet](https://www.google.com/search?q=haraka+outbound+module) , even though it seems like exactly what I need.

**Comment by msimerson** [comment]
Haraka is a MTA/MSA. For an app that sends emails from node.js, you want to use [nodemailer](https://www.npmjs.com/package/nodemailer)

**Comment by ahmed-com** [comment]
Thank you,
I didn't know what MTA/MSA meant, nor I do fully understand some of the terminology I encountered while using haraka.
That might not be relevant to haraka, but I would really appreciate it if you would consider pointing me to some resources to learn more, maybe a book about mail servers and protocols.

**Comment by msimerson** [comment]
Hrmmm. The canonical book that most SMTP people cut their teeth on has to be Sendmail, but I wouldn't recommend that today. Most all the reading I do about internet email today is reading RFCs. I suppose a good starting place today might be [SMTP](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol) and then follow the links and read up on all of them. Haraka won't make much sense without understanding SMTP.

**Comment by ahmed-com** [comment]
Thanks alot for the suggestion, I've been reading a lot of blogs lately . One site that've been really helpful in terms of understanding the role that haraka plays and what is MTA is [mail trap](https://blog.mailtrap.io/category/email-dev-and-infrastructure/)
