### ISSUE TITLE
SPF checks fails when mail sent to Gmail

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#2829]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.13
 --- | :--- 
Node | v6.10.3
OS | Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

As of now, I am using older version of haraka, planning to upgrading to latest and use new version.

**i have tried to explain below what problem i am facing**

We have a various application from where we need to send internal and various notification mails (from different from-mail). for that we are sending through haraka using smpt. which we have setup as outbound relay.

Issue we are facing is email delivering to gmail, SPF check is getting failed. after checking email headers it is realised that SPF check is getting validate on client IP which is not designate to sender domain.

Since we are sending through Haraka, i have written plugin to modify return path so that SPF checks should work correctly,  and this was working fine till a months back , I noticed this when our infra team reported this.

email sent/originated form (phpmailer)
client originated IP : 13.23.23.72 (say)
from-mail : xyz@mycompany.com
return-path : abc=xyz@myharaka.com
IP : (say)103.21.31.4 (haraka server public IP from where mail is getting originated )
and in TXT record for myharaka.com
"v=spf1 ip4:103.21.31.0/24 include:_spf.google.com ~all"

spf=softfail (google.com: domain of transitioning bounce+170918-si-ss=mycompany.com@myharaka.com does not designate 13.23.23.72 as permitted sender) smtp.mailfrom="bounce+170918-si-ss=mycompany.com@myharaka.com"
Return-Path: <bounce+170918-si-ss=mycompany.com@myharaka.com>
Received: from myharaka.com (outbound-email-1.myharaka.com. [103.21.31.4])
        by mx.google.com with ESMTPS id u184si53101pfu.249.2020.07.30.21.10.07
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 30 Jul 2020 21:10:08 -0700 (PDT)

Here 13.23.23.72 is client IP not the haraka server ip, I am not sure how SPF check is behaving like this. earlier it used to get validate with haraka server IP.

there is two **Recieved** header in mail while receiving at gmail.
One from client from where email is originated (with client IP in header) and 
One is from haraka server (with Haraka outbound server IP in header).

Earlier also it was the same case with 2 **Recieved** Headers,  it used to work. 

Can any one suggest how can i tackle this to get SPF check successful by gmail. 
I have verified using test tool for SPF validation (have specified Haraka server IP 103.21.31.4 and domain myharaka.com) it works fine. SPF check gets PASS 

I was thinking if i can modify the client IP with Haraka Server IP in mail header before sending can solve this, 

Is it right approach and possible to do?  What is better way to handle this..    Please suggest.

**Comment by msimerson** [comment]
That seems unusual. I wouldn't put it past Google to start inspecting previous `Received` headers, but I haven't seen it happen. I just sent a couple test emails via a couple routes to gmail and inspected the headers. In both cases, gmail seems to only apply SPF to the route it's receiving from (ie, my Haraka server).

I wouldn't try fudging IPs in the received header, I'd instead try just removing the initial Received header and see what happens.

**Comment by ajay-psd** [comment]
yes, removing the initial Received header looks better option.  will check this and see how it works.

Thanks.

**Comment by msimerson** [comment]
Stale. Closing for now. Follow up and reopen if necessary.
