### ISSUE TITLE
Haraka Hardware Requirement for 300.000 Email per Day

### ISSUE THREAD

**Issue by raihan519** [haraka/Haraka#2832]
## system info
```
Haraka | Haraka.js — Version: 2.8.25
 --- | :--- 
Node | v12.14.1
OS | Linux haraka 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1  11 Sep 2018
```

## The Purpose
I want to send 300.000 email per day with my Haraka

## The Problem
But i'm confused about the hardware specification for sending that much email with my Haraka.

## The Question
Can someone inform me the hardware minimum requirement for my Haraka to send 300.000 email per day?
RAM :
CPU Core :

**Comment by Dexus** [comment]
For that you don't need very much HW, I send 500k with a VPS 2 Core, 8GB Ram.

**Comment by raihan519** [comment]
Hi Dexus,

Noted, and thank you so much for the infomation.
