### ISSUE TITLE
Release: 2.8.26

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2848]
- [x] Start a N-week quiet period (started Nov 17th)
- [x] Update [haraka-tld](https://github.com/haraka/haraka-tld)
- [x] Draft a release on the [releases page](https://github.com/haraka/Haraka/releases) (Save draft)
- Create a PR with: #2860 
    - [x] Updated [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md)
    - [x] Bumped version in [package.json](https://github.com/haraka/Haraka/blob/master/package.json)
    - [x] Update release date in [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md)
- [x] `npm publish` (Dec 1)
- [x] Post `Changes` file on the draft release
- [x] publish the release 
- [x] update [haraka's wikipedia page](https://en.wikipedia.org/wiki/Haraka_(software))
- [ ] Email the mailing list
- [ ] Publish a blog post

**Comment by weyert** [comment]
Any plans to do a release?

**Comment by msimerson** [comment]
Yes, it's in [slow] motion.

**Comment by baudehlo** [comment]
Isn't it already released? I saw it on npm

**Comment by msimerson** [comment]
Yep, but you publish the blog post and email the list.
