### ISSUE TITLE
smtp forward to mail chimp - how to.

### ISSUE THREAD

**Issue by wpoosanguansit** [haraka/Haraka#285]
Hi, I have decided to use Harak for inbound mail and redirect them to their final destination via third party smtp hosts - mail chimp.  I looked at the plugin smtp forward and proxy.  However I do not see any usename and password to be configured?  How do I set those to connect to the outside services?  Thanks for your help.

**Comment by gziskind** [comment]
I am finding that the smtp forward with auth is not working. It looks like it is never sending the user/password information when I do a LOGDATA log level. It just jumps right into sending the mail from and rcpt to commands. Has this been confirmed to be fixed?

**Comment by gziskind** [comment]
Just figured out the issue, when you pass smtp credentials in the smtp_forward.ini file, it seems it extracts only the properties under the [main] ini category and the properties under the [auth] header are ignored, however the smtp_forward plugin checks config.auth to find smtp credentials, which would not be there. I fixed it by adding the auth properties to the config files that are extracted by the smtp_forward plugin

**Comment by salvop** [comment]
I have the same problem, do you submitted patches to the repository?

**Comment by gziskind** [comment]
No but i just submitted a pull request with the code that fixes the problem

**Comment by sym786** [comment]
I am facing the same issue from many days but not able to fix it. So if you fix it then please let me know what I need to make changes in files so I can able to send mail it. The logs show below error "[queue/smtp_forward] S: 554 5.7.1 <m@xyz.com>: Relay access denied\r\n"

**Comment by smfreegard** [comment]
sym786: please open a new issue as this one is closed, and then show the contents of your smtp_forward.ini file in it.
