### ISSUE TITLE
Building a better community for Haraka and SMTP.

### ISSUE THREAD

**Issue by sahilpohare** [haraka/Haraka#2852]
Haraka although really powerful, is really daunting for newcomers and has a steep learning curve. This scares away many people. Even the resources and documentation are not adequate. Except for a few blogs and "one" youtube video there is nothing much to refer to or read. I would suggest adding more examples to the official Haraka documentation and creating an active channel for communication for developers like a discord or a slack server. 
I believe Haraka has potential to can become a great community not unlike that of modern frameworks.

**Comment by celesteking** [comment]
There's [documentation](https://haraka.github.io/) as specified in this repo's description. 
Most newcomers don't know why they came here and why they need this particular software. For those people, it's better to look somewhere else. Using Haraka (instead of NodeMailer or commercially available services like AWS SES, Sendgrid, etc.) requires complete understanding of what that specific person is trying to achieve. 
Support channels are specified right in README. There's also [SO with Haraka tag](https://stackoverflow.com/questions/tagged/haraka). Contributions are welcome.

**Comment by baudehlo** [comment]
I'd be open to a Slack channel. I find myself in IRC less and less. But it
would be on the agreement to move the IRC channel over, not to keep it,
because just adding one more place to have to answer questions isn't
reasonable.

**Comment by celesteking** [comment]
please do the needful  https://slack.com/ssb/get-started#/create

We could set up an interlink b/w irc & slack, but not sure how that would affect the questions quality, as ppl on irc tend to come, ask a question and then leave in a couple of minutes, while their question @ slack would still remain visible, unless the bot would revoke the question... anyway, needs thoughtful consideration.

**Comment by baudehlo** [comment]
I'd like to hear a few opinions first before going ahead. I know Matt and
Steve have been on IRC a long time (same as myself) so I don't know how
happy they would be with the change to slack - I'm not a huge fan on it
being a commercial service, but they've been good stewards for free
accounts for a long time so I assume it'll be fine.

**Comment by msimerson** [comment]
I hadn’t used IRC in a decade when I started using it for Haraka. IRC isn’t useful to me. It favors immediacy and the IRC logging service we had went away, so there’s no way to catch up on what I missed. I’m spending less of my life parked at a desk so when I do have time to spend on Haraka, browsing the open issues on GitHub and SO are better channels for me.

Matt

**Comment by celesteking** [comment]
https://github.com/discourse/discourse in case we want to multiply entities without necessity (SO with haraka tag already exists)

**Comment by KingNoosh** [comment]
Perhaps https://spectrum.chat/ or https://gitter.im/ too if we're still thinking about this?

I had to ditch IRC as I just needed a break from it.

**Comment by ShubhamNandi** [comment]
IRC is not that convenient I would prefer Discord or Slack

**Comment by smfreegard** [comment]
I haven't been on IRC in ages and I found it a PITA with people expecting immediacy and who thought it was fine to send endless PMs to the channel ops.

I'm working for a different company now and although I still use Haraka, it's a very different use case than before.

I'm in Slack all day, so it's far more likely that I'll answer a question here or there on Slack than IRC or Discord.

**Comment by celesteking** [comment]
I have created Slack Workspace which [is joinable via this link](https://communityinviter.com/apps/harakaserver/public-inviter) .
Let's transfer the ownership to whomever of the core team has a bit more free time than the others.

**Comment by msimerson** [comment]
We have haraka.mail@gmail.com that gets forwarded to the Haraka core committers. Can we make that the "owner?"

**Comment by celesteking** [comment]
Have just realized that Github beta'ed so-called "Team Discussions", which is a clone of SO, but is put next to the "Issues" tab for convenience. It's also funny how [Github](https://github.community/) itself is using Discourse.
