### ISSUE TITLE
Send bounce notification from http POST 

### ISSUE THREAD

**Issue by leonardoborlot** [haraka/Haraka#2854]
### system info

Hi guys, im using haraka in poste.io package. 

Im looking for any plugin ou addon to send me a POST every time when an email return as a Rejected or Bounce message.

I know about the monitored email box to recive this mensages, but I need a http request to integrate may anothe platform.

If we don´t found any soluction about this We wanna sponsor for any one build it for us.

Thanks

**Comment by baudehlo** [comment]
I don't think anything like this exists yet, but it's relatively simple to implement. Have a look at how haraka-mailinglist handles bounces: https://github.com/baudehlo/haraka-mailinglist

I'm going to close since it's not a bug, but if anyone wants to take you up on that offer they still can.

**Comment by msimerson** [comment]
I'd be interested in writing that for you but I'm busy until sometime early next year.

**Comment by leonardoborlot** [comment]
Waiting for you :)
