### ISSUE TITLE
XOAuth2 Smarthost Authentication

### ISSUE THREAD

**Issue by jkroepke** [haraka/Haraka#2857]
Microsoft deprecate legacy authentication on MS Exchange Online.

This means, SMTP clients must login through SSO/OAuth2 Workflow.

It's planned to provide a OAuth2 based auth workflow like SMTP XOAUTH2?

**Comment by baudehlo** [comment]
We have no immediate plans to do this, we rely on contributions from outsiders for this kind of thing.
