### ISSUE TITLE
Non SMTP outbound

### ISSUE THREAD

**Issue by jkroepke** [haraka/Haraka#2858]
Hi,

I would like to ask if it's possible to change the transport of outgoing mail via plugin.

Haraka have a good support for queue and filtering but I would like to send outgoing mail trough an HTTP Rest API instead SMTP.

This is possible?

**Comment by baudehlo** [comment]
It's entirely possible. It was designed that way. Write a plugin that hooks into `queue_outbound`.

**Comment by jkroepke** [comment]
Do you know an example?
