### ISSUE TITLE
NPM install on Ubuntu Focal (20.04.1)

### ISSUE THREAD

**Issue by gaia** [haraka/Haraka#2864]
### system info
fresh Ubuntu Focal (20.04.1) install.
fresh node v15.2.1 install (via `curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -`)

### Expected behavior
normal installation

### Observed behavior
![image](https://user-images.githubusercontent.com/87547/100034456-0cac1e80-2db1-11eb-9322-27bc20c8574a.png)

```
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:309:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:329:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1055:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
```

### Steps to reproduce
see image

**Comment by msimerson** [comment]
I suspect that you have python 3.x installed instead of 2.7. Node.js requires python 2.7 to build any compiled modules like iconv.

**Comment by gaia** [comment]
i didn't see that python 2.7 required. that did it. thank you!
