### ISSUE TITLE
How can i rewrite mail_from in plugin

### ISSUE THREAD

**Issue by rogereiddir** [haraka/Haraka#2880]
i am using haraka now as a MSA the server that sends the email has port25 installed on it
i am using smtp_forward plugin to do that but i having hard time figuring out how to change mail from always takes the original domain

**Comment by msimerson** [comment]
duplicate of #2511

**Comment by msimerson** [comment]
See #485

**Comment by rogereiddir** [comment]
Hello @msimerson  , that solution is not working for me because when i change the mail_from , smtp_forward fails because it depends on mail_from , to figure out which server to forward the email to , is there a way the configure smtp_forward plugin by IP not by mail_from

**Comment by rogereiddir** [comment]
can somebody help me on this?

**Comment by rogereiddir** [comment]
this is how i did it for any body struggling

e```
xports.register = function () {
  const plugin = this
  plugin.register_hook('queue_outbound','edit_mail_headers');
}

exports.edit_mail_headers = function (next ,connection) {
  const returnPath = connection.transaction.header.get('return-path');
  if(returnPath){
    const user = returnPath.split('@')[0]
    const domain = returnPath.split('@')[1]
    connection.transaction.mail_from.original_host = `${domain}`
    connection.transaction.mail_from.user = `${user}`
  }else{
    connection.transaction.mail_from.original_host = "<>"
    connection.transaction.mail_from.user = ""
  }
  next();
}
```
