### ISSUE TITLE
Reboot loop on sending outbound mails

### ISSUE THREAD

**Issue by tyranron** [haraka/Haraka#2883]
**Describe the bug**
Using the Haraka server for outbound mails, it crashes with a critical error during DNS lookup, starts again, and crashes again, and so in a loop.

**Expected behavior**
The server should not crash.

**Observed behavior**
Crashes with the following log:
```
[CRIT] [-] [core] TypeError: addresses is not iterable
[CRIT] [-] [core]     at QueryReqWrap.callback (/usr/local/lib/node_modules/Haraka/node_modules/haraka-net-utils/index.js:425:24)
[CRIT] [-] [core]     at QueryReqWrap.onresolve [as oncomplete] (node:dns:203:10)
[NOTICE] [-] [core] Shutting down
[NOTICE] [-] [core] worker 1040 exited with error code: 1
```

**Comment by tyranron** [comment]
I've inspected that file and it doesn't contain [this line from `master`](https://github.com/haraka/haraka-net-utils/blob/063a989f3ba1ce3f22a24a9516b442f5474e7c90/index.js#L425).

Strange... I've installed latest Haraka version via `npm install -g Haraka@2.8.26`.

**Comment by tyranron** [comment]
So, that's duplicate of https://github.com/haraka/haraka-net-utils/pull/58.

**Comment by tyranron** [comment]
Reverting to 2.8.25 fixes the issue.

Is any new release is planned soon?

**Comment by msimerson** [comment]
I reinstalled Haraka yesterday after releasing a newer haraka-net-utils and 2.8.26 got the newer version without the DNS failures. When exactly did you install 2.8.26?

> Is any new release is planned soon?

You mean like #2879 ?

**Comment by tyranron** [comment]
@msimerson 

> You mean like #2879 ?

Yup.

> When exactly did you install 2.8.26?

I use <https://github.com/instrumentisto/rust-docker-image>. I guess, I need just rebuild the image.

**Comment by tyranron** [comment]
@msimerson yup, after rebuild the issue has gone. Thank you for the tip. Will keep in mind that dependecies are not locked and can be upgraded by rebuilding.
