### ISSUE TITLE
Cant make haraka send mail to any domain

### ISSUE THREAD

**Issue by savelmtr** [haraka/Haraka#2884]
My problem would sound dumb, but I can't solve it.
I choose haraka to use instead of postfix, cause it can work as non-root container in docker.
But when i started it and tried to send a test email I've got a very strange result.
I tested it by `swaks` and at first by command `./swaks -s localhost -t savelmtr@gmail.com -f from_me@mail.ru`
So then I got a message `550 I cannot deliver mail for savelmtr@gmail.com`
Ok, then I add domains 'gmail.com' and 'mail.ru' to host_list -- and `swaks` made it ok. But hell no! I've never got test email to my gmail account -- that's the problem.

I'm discouraged. What shall I do? Please, help!

**Comment by justinbaltazar** [comment]
What does the console say when you try sending emails to Gmail? It's possible you're not properly setting up your domain with SPF/DMARC records. 

https://support.google.com/mail/answer/81126#authentication

**Comment by savelmtr** [comment]
> What does the console say when you try sending emails to Gmail? It's possible you're not properly setting up your domain with SPF/DMARC records.
> 
> https://support.google.com/mail/answer/81126#authentication

Console output:
```
savelmtr@savelmtr-Inspiron-7577:~/new_web/test/my_blog/haraka$ ./swaks -s localhost -t savelmtr@gmail.com -f from_me@mail.ru
=== Trying localhost:25...
=== Connected to localhost.
<-  220 885472e5755d ESMTP Haraka/2.8.26 ready
 -> EHLO savelmtr-Inspiron-7577
<-  250-885472e5755d Hello [172.17.0.1]Haraka is at your service.
<-  250-PIPELINING
<-  250-8BITMIME
<-  250-SMTPUTF8
<-  250 SIZE 0
 -> MAIL FROM:<from_me@mail.ru>
<-  250 sender <from_me@mail.ru> OK
 -> RCPT TO:<savelmtr@gmail.com>
<-  250 recipient <savelmtr@gmail.com> OK
 -> DATA
<-  354 go ahead, make my day
 -> Date: Sun, 27 Dec 2020 14:54:30 +0300
 -> To: savelmtr@gmail.com
 -> From: from_me@mail.ru
 -> Subject: test Sun, 27 Dec 2020 14:54:30 +0300
 -> Message-Id: <20201227145430.007837@savelmtr-Inspiron-7577>
 -> X-Mailer: swaks v20201014.0 jetmore.org/john/code/swaks/
 -> 
 -> This is a test mailing
 -> 
 -> 
 -> .
<** 451  (58E9FD19-9030-4316-AD28-73010D785AC1.1)
 -> QUIT
<-  221 885472e5755d closing connection. Have a jolly good day.
=== Connection closed with remote host.
```

And stdout in container:
```
[WARN] [-] [dnsbl] zone 'zen.spamhaus.org' did not respond to test point (null)
[NOTICE] [58E9FD19-9030-4316-AD28-73010D785AC1] [core] connect ip=172.17.0.1 port=49438 local_ip=:: local_port=8025
[INFO] [58E9FD19-9030-4316-AD28-73010D785AC1] [helo.checks] multi: true, skip:proto_mismatch(private), host_mismatch(private)
[NOTICE] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [core] sender <from_me@mail.ru> code=CONT msg=""
[INFO] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [core]  hook=rcpt plugin=rcpt_to.in_host_list function=hook_rcpt params=<savelmtr@gmail.com> retval=OK msg=""
[NOTICE] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [core] recipient <savelmtr@gmail.com> code=OK msg="" sender=from_me@mail.ru
[NOTICE] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [core] message mid=<20201227145430.007837@savelmtr-Inspiron-7577> size=284 rcpts=1/0/0 delay=0.005 code=CONT msg=""
[INFO] [-] [core] [smtp_client_pool] [2555:localhost:300:no_user] dispense() clients=1 available=0
[INFO] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [queue/smtp_forward] forwarding to localhost:2555
[WARN] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [queue/smtp_forward] D9FE4531-0209-42F9-97FC-1E8B606A93CD: [localhost:2555] SMTP connection errored Error: connect ECONNREFUSED 127.0.0.1:2555
[NOTICE] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [core] queue code=CONT msg=" (58E9FD19-9030-4316-AD28-73010D785AC1.1)"
[ERROR] [-] [core] backend failure: localhost:2555 - D9FE4531-0209-42F9-97FC-1E8B606A93CD: [localhost:2555] SMTP connection errored Error: connect ECONNREFUSED 127.0.0.1:2555
[NOTICE] [58E9FD19-9030-4316-AD28-73010D785AC1.1] [core] disconnect ip=172.17.0.1 rdns=NXDOMAIN helo=savelmtr-Inspiron-7577 relay=N early=N esmtp=Y tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=284 lr="451  (58E9FD19-9030-4316-AD28-73010D785AC1.1)" time=0.092
```

I just dont know what does it mean. In my gmail caaount the email doesnt appear even in "spam".

What shall I do?

**Comment by savelmtr** [comment]
Maybe I should start haraka only on servers which already is linked to a domain?
I would just make some tests of it before, you know...
Maybe anybody can give me some tip where should I dig?

**Comment by msimerson** [comment]
> then I add domains 'gmail.com' and 'mail.ru' to host_list

Nope, unless those domains are "local" and you want Haraka to queue mail for them, don't add them to host_list. Instead, you want to enable relaying from your mail client, so that you can AUTH (via user/pass or IP). Then you can send to any host.

**Comment by savelmtr** [comment]
Ok, I enabled `tls` plugin, added `.pem` files, also enabled `auth/flat_file` plugin, created `auth_flat_file.ini` with this text inside:
```
[core]
methods=PLAIN,LOGIN,CRAM-MD5

[users]
user1=password1
```
But then I run command `./swaks --to savelmtr@google.com --from me@example.com --auth PLAIN -au user1 -ap password1 --header-X-Test "test email"`, I got a strange problem:
```
=== Trying aspmx.l.google.com:25...
=== Connected to aspmx.l.google.com.
<-  220 mx.google.com ESMTP n131si8037757lfd.236 - gsmtp
 -> EHLO savelmtr-Inspiron-7577
<-  250-mx.google.com at your service, [46.242.14.141]
<-  250-SIZE 157286400
<-  250-8BITMIME
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-PIPELINING
<-  250-CHUNKING
<-  250 SMTPUTF8
*** Host did not advertise authentication
 -> QUIT
<-  221 2.0.0 closing connection n131si8037757lfd.236 - gsmtp
=== Connection closed with remote host.

```

Whad am I doing wrond?
