### ISSUE TITLE
Command parsing failed: MAIL FROM containing +

### ISSUE THREAD

**Issue by pekapl** [haraka/Haraka#2885]
**Describe the bug**
When MAIL FROM address contain + (plus sign) error occures: 501-Command parsing failed

**Expected behavior**
MAIL FROM should be accepted as valid.

**Observed behavior**
Problem occures when address-rfc2821 is installed in version 1.2.0 (npm install executed today).
After forcing address-rfc2821 version to 1.1.3 problem no longer occures.

SMTP session:
=== Trying foo.bar...
=== Connected to foo.bar.
<-  220 foo.bar ESMTP
 -> EHLO bar.foo
<-  250-foo.bar Hello Unknown [x.x.x.x]Haraka is at your service.
<-  250-PIPELINING
<-  250-8BITMIME
<-  250-SMTPUTF8
<-  250-SIZE 128000000
<-  250 STARTTLS
 -> MAIL FROM:`<boun+ces@test.com>`
<** 501-Command parsing failed
<** 501 Error: Syntax error at line 1 col 6:
 -> QUIT
<-  
<-  1 `<boun+ces@test.com>`
<-                ^
<-  
<-  Unexpected "+". Instead, I was expecting to see one of the following:
<-  
<-  A character matching /[0-9A-Za-z!#$%&'*\-/=?^_`{|}~\u0080-\uFFFF/]/ based on:
<-      Atom$ebnf$1 → Atom$ebnf$1 ● /[0-9A-Za-z!#$%&'*\-/=?^_`{|}~\u0080-\uFFFF/]/
<-      Atom →  ● Atom$ebnf$1
<-      Dot_string →  ● Atom Dot_string$ebnf$1
<-      Local_part →  ● Dot_string
<-      Mailbox →  ● Local_part "@" non_local_part
<-      Path → "<" Path$ebnf$1 ● Mailbox ">"
<-      main →  ● Path
<-  A "." based on:
<-      Dot_string$ebnf$1$subexpression$1 →  ● "." Atom
<-      Dot_string$ebnf$1 → Dot_string$ebnf$1 ● Dot_string$ebnf$1$subexpression$1
<-      Dot_string → Atom ● Dot_string$ebnf$1
<-      Local_part →  ● Dot_string
<-      Mailbox →  ● Local_part "@" non_local_part
<-      Path → "<" Path$ebnf$1 ● Mailbox ">"
<-      main →  ● Path
<-  A "@" based on:
<-      Mailbox → Local_part ● "@" non_local_part
<-      Path → "<" Path$ebnf$1 ● Mailbox ">"
<-      main →  ● Path
<-  
<-  221 foo.bar closing connection. Have a jolly good day.

**Steps To Reproduce**
Install haraka with address-rfc2821 1.2.0, no mail hooks required.

**System Info:**

Haraka | Haraka.js — Version: 2.8.26
 --- | :--- 
Node | v12.18.4
OS | Linux foo.bar 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
openssl | OpenSSL 1.1.1d  10 Sep 2019

**Additional context**
Package.json lists address-rfc2821 as dependency with version ^1.1.3. 
My guess is that npm installed 1.2.0 as "compatible".

**Comment by msimerson** [comment]
Fixed with release of address-rfc2821 v1.2.1.
