### ISSUE TITLE
How to deny sending for local ip address to a specific domain

### ISSUE THREAD

**Issue by rogereiddir** [haraka/Haraka#2892]
Hello @msimerson  I have configured haraka with smtp_forward plugin to forward email to another MTA , but when the remote MTA is down , haraka tries to send with the local IP which i don't want ,

so  what i want is the master server forwards to remote MTA another server which i configured , when the message is deferred i dont want Haraka to send using local IP/domain

any idea how to do that please

**Comment by msimerson** [comment]
> haraka tries to send with the local IP which i don't want

I'm not sure what you mean here. For domains that you want forwarded, **only** configure them to accept mail via the smtp_forward plugin. If the remote is unavailable, then Haraka will defer the messages and not queue them at all. If Haraka is queueing them, then you have something else configured to accept mail for that/those domain(s). Provide details.

**Comment by rogereiddir** [comment]
master IP = 1.1.1.1
remote MTA = 2.2.2.2

@msimerson  master IP forwards to MTA via the smtp_forward plugin , when 2.2.2.2 is unavailable , like you said it is deferred , when it tries again it doesn't try to forward it again to the same MTA 1.1.1.1 , it actually uses the master IP 1.1.1.1 which i never want to send emails with , i don't know why it does this is my version of plugin
https://gist.github.com/rogereiddir/1a94fbbc48e6ede54f86899ee5f8e5c0

**Comment by msimerson** [comment]
smtp_forward is complicated. Please read #1472 and #1847.  Both provide some insight into issues surrounding smtp_forward -vs- outbound mail routing.

**Comment by rogereiddir** [comment]
my current solution to this 

```
exports.register = function () {
    const plugin = this;
    plugin.register_hook('deferred', 'deferred');
}

exports.deferred = function (next, hmail, domain) {
    next(OK)
}
```
