### ISSUE TITLE
Force queue delivery via -qunstick not working as intended

### ISSUE THREAD

**Issue by matt4545** [haraka/Haraka#2894]
If I run this:
`/usr/lib/node_modules/Haraka/bin/haraka --qstat  -c /opt/haraka-submission`
I get the following output:

`loaded TLD files: 1=1528 2=8564 3=2448
loaded 8787 Public Suffixes
{ queue_dir: '/data/queue/submission', queue_count: 139 }
`
Now, if I want to force the queue delivery:
`/usr/lib/node_modules/Haraka/bin/haraka --qunstick  -c /opt/haraka-submission/`
I get the following output:

`error: qunstick option requires config path`

Any thoughts? Pretty sure I am just IGNORANT lol.

**Comment by msimerson** [comment]
Switch the order of CLI args:

````
haraka -c /data --qunstick
loaded TLD files: 1=1508 2=8565 3=2448
loaded 8995 Public Suffixes
250 Command sent for execution. Check Haraka logs for results.
````
