### ISSUE TITLE
Still can't make haraka send any mail

### ISSUE THREAD

**Issue by savelmtr** [haraka/Haraka#2895]
I don't know, what am I doing wrong, but I still can't send email from my localhost to my gmail account using haraka.

For now I've already enabled `tls` plugin, added `.pem` files, also enabled `auth/flat_file` plugin, created `auth_flat_file.ini` with this text inside:
```
[core]
methods=PLAIN,LOGIN,CRAM-MD5

[users]
user1=password1
```
But then I run command `./swaks --to savelmtr@google.com --from me@example.com --auth PLAIN -au user1 -ap password1 --header-X-Test "test email"`, I got a strange problem:
```
=== Trying aspmx.l.google.com:25...
=== Connected to aspmx.l.google.com.
<-  220 mx.google.com ESMTP n131si8037757lfd.236 - gsmtp
 -> EHLO savelmtr-Inspiron-7577
<-  250-mx.google.com at your service, [46.242.14.141]
<-  250-SIZE 157286400
<-  250-8BITMIME
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-PIPELINING
<-  250-CHUNKING
<-  250 SMTPUTF8
*** Host did not advertise authentication
 -> QUIT
<-  221 2.0.0 closing connection n131si8037757lfd.236 - gsmtp
=== Connection closed with remote host.
```
Whad am I doing wrond?

**Comment by savelmtr** [comment]
Also with curl:
```
curl --url "localhost:25" --user "user1:password1" --mail-from "noreply@savelmtr.io" --mail-rcpt "savelmtr@gmail.com" -F subject="HELLO!"

220 cc70ffbdec67 ESMTP Haraka/2.8.27 ready
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
500 Unrecognized command
```

**Comment by msimerson** [comment]
I believe you are using Haraka where you should be using something else. For a general purpose app to send emails, you should be using [nodemailer](https://nodemailer.com). For a general purpose MTA, you should be using postfix, exim, or sendmail. When you have reached the end of the abilities of those standard tools and wish to extend the MTA with your own custom code, then come back and kick Haraka's tires.
