### ISSUE TITLE
IP based certificate selection

### ISSUE THREAD

**Issue by Juerd** [haraka/Haraka#2907]
**Is your feature request related to a problem? Please describe.**
Not all connecting hosts will support SNI. The classic solution is to select the certificate by IP address instead of hostname. Haraka does not appear to support that.

In addition, in cases where a dedicated IP address is available per certificate (or group of certificates), it would be preferrable if SNI would only be matched against the certificates of that specific IP, to keep the (superficial) illusion that they are different servers.

**Describe the solution you'd like**
A way to limit certificates (and accompanying private keys) to specific IP addresses, e.g. in `tls.ini`:
```
cert[2001:db8::1][]=/etc/...
key[2001:db8::1][]=/etc/...
cert[2001:db8::2][]=/etc/...
key[2001:db8::2][]=/etc/...
cert[198.51.100.1][]=/etc/...
key[198.51.100.1][]=/etc/...
cert[198.51.100.2][]=/etc/...
key[198.51.100.2][]=/etc/...
```
or in `config/tls`:
```
config/tls/2001:db8::11/file1.pem
config/tls/2001:db8::12/file2a.pem
config/tls/2001:db8::12/file2b.pem
config/tls/198.51.100.11/file1.pem
config/tls/198.51.100.12/file2a.pem
config/tls/198.51.100.12/file2b.pem
```

Or even a syntax where the IP is in the filename:
```
cert[]=/etc/.../somecert-BIND_IP=2001:db8::1.pem
```
```
config/tls/somecert-BIND_IP=2001:db8::11.pem
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by msimerson** [comment]
Prior to me adding SNI support, Haraka supported exactly one TLS certificate. I wanted SNI support so I contributed it. IP based virtual hosting is a niche feature for a MTA and the only path I see towards inclusion in Haraka is if you contribute it.
