### ISSUE TITLE
Encountered an error

### ISSUE THREAD

**Issue by wjinbo** [haraka/Haraka#2909]
[CRIT] [-] [core] TypeError: cfg.listen.split is not a function
[CRIT] [-] [core]     at Object.Server.get_listen_addrs (/usr/local/Haraka/server.js:286:32)
[CRIT] [-] [core]     at Object.Server.setup_smtp_listeners (/usr/local/Haraka/server.js:408:16)
[CRIT] [-] [core]     at Object.Server.createServer (/usr/local/Haraka/server.js:334:16)
[CRIT] [-] [core]     at Object.<anonymous> (/usr/local/Haraka/haraka.js:83:8)
[CRIT] [-] [core]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[CRIT] [-] [core]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[CRIT] [-] [core]     at Module.load (internal/modules/cjs/loader.js:928:32)
[CRIT] [-] [core]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[CRIT] [-] [core]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[CRIT] [-] [core]     at internal/main/run_main_module.js:17:47

node haraka.js    

After the operation,

How to solve it?

**Comment by celesteking** [comment]
your `listen=` is wrong in `smtp.ini`

**Comment by wjinbo** [comment]
After executing NPM install，The following error occurred，I hope I can get your help，Thank you very much





make: Leaving directory '/usr/local/Haraka/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.18.0-80.el8.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/Haraka/node_modules/iconv
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-21T12_16_20_403Z-debug.log


    





wl515230506@163.com
 
From: celesteking
Date: 2021-01-21 18:53
To: haraka/Haraka
CC: wjinbo; Author
Subject: Re: [haraka/Haraka] Encountered an error (#2909)
your listen= is wrong in smtp.ini

**Comment by wjinbo** [comment]
@celesteking listen = 25 and listen = 587,All not line

**Comment by msimerson** [comment]
Look at the syntax in the [default smtp.ini file](https://github.com/haraka/Haraka/blob/master/config/smtp.ini) for reference.
