### ISSUE TITLE
log level of 'data after disconnect' message

### ISSUE THREAD

**Issue by celesteking** [haraka/Haraka#2938]
I'd like to tone down the log level of: ` [WARN] [xx] [core] data after disconnect from xx`. This is a frequent occurrence over here because we tend to kick the bad hosts out in a forceful manner:
```
[core] S: 554 Your host [xx] is banned
[core] disconnect ip=xx rdns=NXDOMAIN helo="" relay=N ...etc
[core] data after disconnect from xx
```
I couldn't find the code that actually closes the socket, so I'm wondering whether receiving data after it's been kicked is actually an expected event and shouldn't be logged with WARN level. 
I would do the same myself if a door was abruptly shut right in front of my face.

**Comment by teknologista** [comment]
same question here. Any news ?
