### ISSUE TITLE
Usage of vulnerable version of bower module in http folder

### ISSUE THREAD

**Issue by mallikde-kore** [haraka/Haraka#2949]
### Issues with bower@1.8.8:

1. It is using deprecated request module.(moderate)
2. It is using vulnerable version of configstore module.(high)
3. It is using vulnerable versions of handlebars, jquery, jquery-ui, tar-fs.(critical)
 
Suggestions:
1. All the critical vulnerabilities were fixed in bower latest V1.8.12. So, please upgrade the bower module to 1.8.12.
2. Try to move the modules from custom location(http folder) to main package.json.

**Comment by msimerson** [comment]
bower has already been removed in #2891
