### ISSUE TITLE
Haraka does not reload changed files

### ISSUE THREAD

**Issue by wioxjk** [haraka/Haraka#2950]
Hi,

I am trying to understand why Haraka is not autoreloading configfiles when they are not edited by a editor on localhost.

I have tried sharing configs on a NFS-share, Gluster Volume and pulling it from an rsync-daemon but the autoreloading is not triggered. How does it work?

If I edit a file on localhost, I get the following:

```
inotifywait -r -e modify,attrib,close_write,move,create,delete /srv/haraka-outbound/config
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/srv/haraka-outbound/config/ CREATE 4913
```

But if localhost pulls the files from a remote rsync-server:
```
inotifywait -r -e modify,attrib,close_write,move,create,delete /srv/haraka-outbound/config
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/srv/haraka-outbound/config/ ATTRIB,ISDIR
```

Is this the reason that haraka does not see the changes to the files?
What is the recommended approach to sync configs between servers?

**Comment by msimerson** [comment]
File watching in Haraka is has some limitations due to the [node.js implementations](https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_fs_watch_filename_options_listener). Our code for file change watching is in the [haraka-config](haraka/haraka-config) module.

**Comment by celesteking** [comment]
file reload by polling has been implemented in https://github.com/haraka/haraka-config/pull/58
