### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by chandruv21** [haraka/Haraka#2953]
Hello, guys. 
            I'm new to Haraka Mail Server. Haraka has been successfully installed in Ubuntu 20.04 and it is working fine. 
I have one request: how can I include a warning message if emails are received from external domains such as gmail, outlook, and so on?

Thank you in Advance

Regards,
Chandrashekar B

**Comment by msimerson** [comment]
write a plugin that inspects the `mail_from` hook. Inside the plugin, check if the domain matches your criteria and then fire off your alert however you see fit.
