### ISSUE TITLE
Haraka accepts unauthorized senders on port 587

### ISSUE THREAD

**Issue by wioxjk** [haraka/Haraka#2955]
Hi,

I am not sure where to start. But I am running a cluster of several Haraka servers for outgoing emails is configured to accept emails over port 587 and authentication (auth_flat_file.ini) and also accepts emails over port 25 without auth.

However, I discovered that Haraka accepts senders over port 587 without authentication too. Why? 
Does the config between port 25 and 587 collide somehow?

Why is this happening?

**Comment by baudehlo** [comment]
Needs logs.

**Comment by wioxjk** [comment]
Hi,

Sorry for not responding, but I found the issue.
It was a configuration error, due to a load-balancer (Netscaler) that is running in front of the Haraka servers.

Haraka just sees the local IP of the load-balancer and not the Remote IP connecting to it. And therefore just accepts it as defined in relay_acl_allow.

**Comment by msimerson** [comment]
If your kid balancer supports haproxy protocol, you can get Haraka the remote IP.
