### ISSUE TITLE
Lock dependencies or get rid of `*` version ranges for reproducibility

### ISSUE THREAD

**Issue by tyranron** [haraka/Haraka#2960]
Is it possible to maintain `.lock` file for `package.json` in this repository, or at least to omit [`*` and `>=` version ranges in `package.json`](https://github.com/haraka/Haraka/blob/2.8.27/package.json) if not?

It's quite bothers that builds are not reproducible and running the same command `npm install -g Haraka@2.8.27` in different points of time can result in breaking changes as some plugin may be broken due to breaking changes or regressions. This also introduces problems for downstreams (like [`instrumentisto/haraka` Docker image](https://github.com/instrumentisto/haraka-docker-image)), where minor patch bump can have subtle [unexpected consequences](https://github.com/instrumentisto/haraka-docker-image/blob/v2.8.26-node15-r1/CHANGELOG.md#2826-node15-r1--2020-12-22) for workloads using version ranges.

To simplify burden of tracking/updating/upgrading dependencies we could leverage the [dependabot](https://dependabot.com/).

**Comment by msimerson** [comment]
It's possible, but IMO, it's not desirable. Our release cadence is sporadic (when someone wearing a release hat has spare cycles) and the benefit for issues like this is offset by having 'known insecure' dependencies continue to be installed for weeks or months after the last release.

**Comment by tyranron** [comment]
@msimerson then the second option with using only carret version ranges `^` should work for you. It will consider patch/minor versions (so security fixes too), but also will preserve against transitive BC breaks.

**Comment by msimerson** [comment]
Fair enough, I have enabled dependabot. Your PR that uses `>=` and/or `^` versions is welcome.
