### ISSUE TITLE
Feature request: Expose SNICallback as a plugin hook

### ISSUE THREAD

**Issue by andris9** [haraka/Haraka#2968]
This would enable plugin-managed vanity MX domain names. There could be a plugin hook that is run on SNICallback. If the hook returns a secure context object then use it, otherwise go with the default.

I use such a system with WildDuck IMAP and ZoneMta MSA servers - there is a [central certificate system](https://docs.wildduck.email/api/#operation/updateTLSCertificate) that manages and renews Let’s Encrypt certificates. Whenever a SNI connection is established the certificate is pulled from that central system instead of using fixed certificates stored on disk.

**Comment by msimerson** [comment]
a PR is welcome. I've looked at your TLS work and you did a nicer job than we have.

**Comment by andris9** [comment]
I tried to do something like this but ran into an obstacle. In general what I'd like the SNICallback to look like would be something like this:

```js
function SNICallback (servername, sniDone) {
    plugins.run_hooks('sni', pluginObject, ( ctx )=>{
        if (ctx){
            return sniDone(null, ctx);
        }

        if (ctxByHost[servername] === undefined) servername = '*';
        sniDone(null, ctxByHost[servername]);
    });
}
```

The problem is I can't figure out what to use as the plugin object? SNICallback method has no bound context.

**Comment by msimerson** [comment]
A currently open PR exports `SNICallback` from tls_socket. (It also cleans up that file significantly, but that's a different issue). `certsByHost` was already exported. That same open PR turns `certsByHost` into a [haraka-note](https://www.npmjs.com/package/haraka-notes) but that's mostly just cleaning up JS object get/set safeguards.

Plugins have access to `haraka_require`, so they can do crazy like `const tls_socket = haraka_require('tls_socket')`.

Now, this isn't an endorsement or anything, but that should make it possible to:

```js
exports.register = function () {
  const tls_socket = haraka_require('tls_socket')
  tls_socket.SNICallback = (servername, sniDone) => {
    // do some stuff
    sniDone(null, context)
  }
}
```

**Comment by msimerson** [comment]
moved to [wiki/TODO](https://github.com/haraka/Haraka/wiki/TODO)
