### ISSUE TITLE
feature request: smtp banner hostname virtualization

### ISSUE THREAD

**Issue by Adhvin** [haraka/Haraka#2978]
Hi

I have been trying to use our domain name in smtp banner receiver greetings, but by default haraka uses the server hostname in haraka/config/me.

I removed the hostname from haraka/config/me but still its showing the server hostname

how to change the smtp receiver greeting? and how can i add it?

```
telnet mx.domain.com 25
Trying our.domain.ip...
Connected to mx.domain.com.
Escape character is '^]'.
220 serv.hostname.com ESMTP Haraka/2.8.27 ready
quit
```

Can someone please help.

**Comment by Adhvin** [comment]
If we give our domain name, only the domain name we give will show itself. If it does telnet to other domains on that server how it will show its domain.

**Comment by msimerson** [comment]
@superman20 is right, you can accomplish this via a plugin.
