### ISSUE TITLE
lots more async/await

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2979]
Now that all maintained versions of node.js support async/await, our code base could benefit from the replacement of many callbacks and promises with async and await.

**Comment by shivamchourasia4** [comment]
Hey there @msimerson , I would like to do this.
You can assign it to me.

**Comment by msimerson** [comment]
Hmm, I can't assign it to you, probably b/c you haven't contributed to the repo yet. Go ahead and create your first PR with a small handful of updates file. After we get it landed, I might be able to assign this to you.

PS: We have many thousands of lines of code. The scale of the task might be best tackled by more than one person.

**Comment by MuraraAllan** [comment]
I can help on this one

How to proceed? 2 3 files per PR referenced to the issue?

**Comment by msimerson** [comment]
Proceed in any sensible way that you see fit. As I've taken baby-steps toward this, I've tackled portions of the internal libraries so that I didn't have to change the plugins for APIs at all. At some point, this will be done for internal libs and we'll be due for a major version bump of Haraka that replaces callbacks in plugins with promises / async / await.

**Comment by msimerson** [comment]
[Here](https://github.com/haraka/haraka-net-utils/pull/67) is an example of what we'd like to see. That PR lightly refactors the function, is still fully compatible with callbacks, and now works perfectly with promises. And it includes tests for the new promises.
