### ISSUE TITLE
Providing a fallback mx

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/Haraka#2989]
I am using this hook to provide the mx for outbound emails.
```
exports.hook_get_mx = (next, hmail, domain) => {
  const mx = {
    priority: 0,
    exchange: '<exchange>',
    auth_user: '<user>',
    auth_pass: '<pass>',
    port: 587
  }
  return next(OK, mx);
}
```

However, sometimes the MX I provided fails. What would be the best mechanism to provide a fallback for those cases?

Many thanks!

**Comment by wioxjk** [comment]
Maybe [this ](https://www.npmjs.com/package/haraka-plugin-graveyard)is what you are looking for?

**Comment by AuspeXeu** [comment]
Thanks, this looks quite promising! I assume instead of hooking into `deferred` for `DENYSOFT` issues, I could hook into `bounce` for 'hard' errors?

**Comment by wioxjk** [comment]
> Thanks, this looks quite promising! I assume instead of hooking into `deferred` for `DENYSOFT` issues, I could hook into `bounce` for 'hard' errors?

Can't really answer your question sadly. Since I am looking into getting a "fallback MX/Graveyard MX" to work.
Since Haraka is unable to establish a connection to servers with self-signed certificates - I am looking into getting those mails put on a graveyard server postfix server with a more relaxed policy but with DANE enabled.

**Comment by AuspeXeu** [comment]
Why would you use a self-signed certificate in the first place? Nowadays, you can get a signed one so easily.

**Comment by wioxjk** [comment]
> Why would you use a self-signed certificate in the first place? Nowadays, you can get a signed one so easily.

Well, good question. I have pointed it out several times to the admins of the sites - but since they are administrated by the government - they refuse to acknowledge the problem. So we need to comply with it.
One way, is to provide a fallback MX.

**Comment by AuspeXeu** [comment]
You cannot install their root CA instead?
