### ISSUE TITLE
No contact

### ISSUE THREAD

**Issue by d351r3d** [haraka/Haraka#2996]
I have some questions about Haraka and I have no idea how to access IRC since I'm not a wizard. I want to get a contact email so someone who is knowledgeable about it can answer some questions.

**Comment by baudehlo** [comment]
You can ask here, or join our slack at https://harakaserver.slack.com/

**Comment by CaveMailer** [comment]
I want to join the Slack but that link says I don't have an account in that workspace. Can you please share another link from which I can join the Slack?

**Comment by baudehlo** [comment]
https://join.slack.com/t/harakaserver/shared_invite/zt-z64icva9-zIHaHaRyQg0fESWcgx2iYg

Link will work for 30 days
