### ISSUE TITLE
Custom DSN objects don't work well in queue and queue_outbound hooks

### ISSUE THREAD

**Issue by gene-hightower** [haraka/Haraka#2998]
**Describe the bug**
There is code in queue_outbound_respond and queue_respond that assumes msg is a string, when passed a DSN object it ends up using returning "xxx [object Object] (uuid)" type strings.
When msg is an array I think you're going to have problems, too.

The errant bit of code code looks like this:
` ${msg} (${this.transaction.uuid})`
Inside an interpolated string.

It's helpfully adding the uuid to the message string. Except if the msg is *not* a string but a DSN object.
This kind of error is much harder to make when using TypeScript.

**Expected behavior**
I expect the custom DSN objects using the haraka-dsn plugin should work the same for each hook.

**Observed behavior**
The message gets "[object Object]" in place of all that info in the DSN.

**Steps To Reproduce**
Create a plugin that uses hook_queue or hook_queue_outbound, call next(DENY, new DSN(...)); and observe the returned SMTP error message.

**System Info:**
This node 14 I think on Linux. The Haraka version is the head of the git repo.

**Additional context**
I think it would be enough to just check if typeof msg === 'string' or whatever before appending the uuid.

**Comment by gene-hightower** [comment]
Maybe I just need the right toString() function that joins all the lines with an appropriate separator.

**Comment by baudehlo** [comment]
Reopening until there's a PR.
