### ISSUE TITLE
Haraka refuses to send email to SMTP-servers with self-signed certificates

### ISSUE THREAD

**Issue by wioxjk** [haraka/Haraka#3001]
Hi,
One of our customer refuses to get a valid certificate to their mailserver. 
Is there a possibility to let Haraka "talk" to that server anyway?

Some background - the Swedish Government uses selfsigned, expired certificates. And many of our customers rely on emailing them.
https://ssl-tools.net/mailservers/regeringen.se

And it does not seems like the servers are accepting emails via plaintext either.

**Comment by msimerson** [comment]
Haraka does not, by default, require validated TLS certificates. Any certificate will do.
