### ISSUE TITLE
Facebook emails not arriving at mail sever

### ISSUE THREAD

**Issue by nhCoder** [haraka/Haraka#3005]
I have installed Haraka mail server on ubuntu 18. Pointed my domain dinebeast.com 's MX and A records to the machine IP. I m getting emails from every website except Facebook and Instagram. I have also set up SPF, DMARC DNS records as well but facebook emails arent arriving on my mail server. My haraka plugin code is here

```
exports.hook_data = function (next, connection) {
  connection.transaction.parse_body = true;
  next();
};

exports.hook_queue = function (next, connection) {
  
  this.loginfo("got your email.....");

  let transaction = connection.transaction;

   next(OK);

};
```
I m confused I think I'm missing some DNS records. I googled and found that Some valid hosts (facebook.com, hotmail.com) use a generic HELO hostname that resolves but doesn't contain the IP that is connecting. If their rDNS passed, and their HELO hostname is in the same domain. Is there a problem with HELO checks, please guide me. Thanks

**Comment by msimerson** [comment]
Read the logs to see what is happening.
