### ISSUE TITLE
transaction.set_banner() only working if html is in request

### ISSUE THREAD

**Issue by ranjanmishra07** [haraka/Haraka#3006]
Hi ,
transaction.set_banner(text, html) is only working when html is provided .

if text is provided only the banner is set as text .
if html is provided the banner is set as html.

How can i set an html banner always irrespective of the content .

Also headers do not come in transaction object in hook_data . How can we access headers in hook_data.

It would be really helpful if i can get some help here as i am stuck on it from long time .

For reference i am using like this-> 

```js
exports.hook_data = function (next, connection) {
    connection.transaction.parse_body = true;
    connection.transaction.set_banner('Text banner', '<p style="color:RED;"><span>Html banner</span></p>');

    next();
}
```

Thanks

**Comment by msimerson** [comment]
> Also headers do not come in transaction object in hook_data . How can we access headers in hook_data.

You cannot. During the `data` hook, the client hasn't sent the message so you cannot access the headers. You can only do that in `data_post`.
