### ISSUE TITLE
Can Haraka run safely on a hardware cluster with a shared FS?

### ISSUE THREAD

**Issue by DoobleD** [haraka/Haraka#3013]
Hi,

I was wondering if Haraka can be ran on multiple servers concurrently without issue, assuming all servers access a shared file system (like NFS) for configuration files and email queue?

**Comment by celesteking** [comment]
We're doing exactly that on cephfs over here, except for a couple of dirs like queue, logs & so on which are supposed to be local anyway.
Just note that HK won't see config updates from made by other hosts unless config polling is enabled.

**Comment by DoobleD** [comment]
Thank you for that feedback @celesteking, very helpful! We're now thinking about having config files on the local drive too. I'm still not sure about queues though. As for logs, writing is slower when it's on the shared drive (obviously), but nothing too bad either.

Apart from the performance aspect, is there any danger in having a queue on a shared drive? Could multiple HK servers try to deliver emails in the queue at the same time for instance, delivering the email multiple times?

**Comment by baudehlo** [comment]
> Could multiple HK servers try to deliver emails in the queue at the same
time for instance, delivering the email multiple times?

In theory no, it's been written hopefully in a way this shouldn't happen.
However it doesn't have tests to ensure it works right, so you're in the
wild west there if you try it.

**Comment by DoobleD** [comment]
Thanks @baudehlo, that's great. We may give it a try. If we do and issues arise I'll provide some feedback for other people curious about this. Closing.

**Comment by thenitai** [comment]
We have four HK servers all running with a shared drive. Processing over 500k emails/day.
