### ISSUE TITLE
Can Haraka queue outbound mail to stores like MongoDB instead of disk?

### ISSUE THREAD

**Issue by CheyenneForbes** [haraka/Haraka#3016]
If not yet possible, does the plugin structure allow this functionality to be built?

**Comment by thenitai** [comment]
Already done with our plugin. Check it out at https://github.com/Helpmonks/haraka-plugin-mongodb

**Comment by baudehlo** [comment]
I don't think there's enough plugin hooks to do this (technically you could
override queue_outbound and implement your own outbound module, but it's
not an easy task to write outbound mail sending code).

Potentially you might be able to hack this by overriding
outbound/hmail's HMailItem class with your own (probably a subclass), and
make sure yours is loaded somehow (by doing
`require('outbound/hmail').HMailItem = YourHMailItem`). You'll have to
override every method that uses the fs and/or path modules to use Mongo
instead.

Would love to see someone make this work.
