### ISSUE TITLE
Unable to install Haraka on Rocky Linux 8

### ISSUE THREAD

**Issue by croessner** [haraka/Haraka#3017]
**Describe the bug**
I tried to install Haraka on Rocky Linux 8. Unfortunately I get lots of errors.

**Expected behavior**
Cleanly install Haraka

**Observed behavior**
Install process fails.

**Steps To Reproduce**
1. Install Rocky Linux 8 or any other RHEL compatible linux version 8.
2. dnf module enable nodejs:16
3. dnf module install nodejs:16
4. npm -g config set user root
5. npm install -g Haraka

Result:

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/Haraka/node_modules/iconv
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                                ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Linux 4.18.0-348.7.1.el8_5.x86_64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/Haraka/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/Haraka/node_modules/iconv
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-24T12_40_55_342Z-debug.log
```

**System Info:**

Haraka |
 --- | :---
Node | v16.13.1
OS | Linux mx.roessner-net.de 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Tue Dec 21 19:02:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1k  FIPS 25 Mar 2021

cat /etc/rocky-release                                                                                               127 ↵
Rocky Linux release 8.5 (Green Obsidian)

**Additional context**

[2022-01-24T12_40_55_342Z-debug.log](https://github.com/haraka/Haraka/files/7925627/2022-01-24T12_40_55_342Z-debug.log)

**Comment by wioxjk** [comment]
`npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
`
Python3 installed?

**Comment by kmpm** [comment]
I have the same issue and since python2 was sunsetted at Januari 1 2020 my hope is that python3 would not be an inssue in 2022.

**Comment by msimerson** [comment]
/me sighs. `iconv` has been the source of many failed Haraka installs, for a long long time. 

Apparently, per [iconv](https://github.com/bnoordhuis/node-iconv/issues/200) it's an upstream node.js issue that affects anything that builds with node-gyp.

**Comment by msimerson** [comment]
I have found a reasonable workaround for this, declare a dependency on a newer version of node-gyp.
