### ISSUE TITLE
Haraka doesn't correctly handle failed plain auth in smtp_client.js

### ISSUE THREAD

**Issue by kayrus** [haraka/Haraka#3020]
**Describe the bug**

While testing the smtp_forward plugin I noticed that plain auth doesn't work correctly, when auth is failed and considers the connection as successful keeping the connection in a pool.

First call to the backend returns:

```
550 5.7.8 Error: authentication failed: authentication failure
```

Further calls to the same backend return:

```
450 4.7.0 <unknown[192.168.1.2]>: Client host rejected: You need to authenticate first
```

**Expected behavior**

Haraka must not put the failed connection into a pool.

**Observed behavior**

Haraka puts the failed connection into a client connections pool.

smtp_client calls greeting event twice, which causes unexpected second `EHLO` command being sent.
After both two `EHLO` commands are sent, haraka sends `AUTH PLAIN` command, but the server (postfix) sends a reply to the second `EHLO` command with 250 return code, therefore Haraka thinks that `AUTH PLAIN` was successful.

Here are my data debug logs: https://gist.github.com/kayrus/aa77cbcd032e7c7d7c0631ce39804945

**Steps To Reproduce**

I'm using smtp_forward plugin with config:

```ini
host=smtp.local
port=587
max_connections=10
enable_tls=true
auth_type=plain
auth_user=my-login
auth_pass=bad_password
enable_outbound=true
```

**System Info:**

```
Haraka | Haraka.js — Version: 2.8.28
 --- | :--- 
Node | v10.24.1
OS | Linux my-host 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1f  31 Mar 2020
```

**Additional context**

Adding the patch below solves an issue:

```diff
diff --git a/smtp_client.js b/smtp_client.js
index fa52d6f0..7270524b 100644
--- a/smtp_client.js
+++ b/smtp_client.js
@@ -444,6 +444,7 @@ exports.get_client_plugin = (plugin, connection, c, callback) => {
         smtp_client.on('xclient', helo);
 
         function on_secured () {
+            if (secured) return;
             secured = true;
             smtp_client.secured = true;
             smtp_client.emit('greeting', 'EHLO');
```

**Comment by feisuzhu** [comment]
This is affecting me too, please release a new version T_T

**Comment by msimerson** [comment]
I agree. I was thinking that it's time to cut a new release.
