### ISSUE TITLE
smtp_proxy doesn't handle emails when backend is unavailable

### ISSUE THREAD

**Issue by kayrus** [haraka/Haraka#3023]
**Describe the bug**

When backend is unavailable, haraka crashes.

**Expected behavior**

Haraka must successfully acknowledge the email and retry to deliver it later.

**Observed behavior**

Haraka crashes: https://gist.github.com/kayrus/728a7b121a72902cff0b644e869d57d7

**Steps To Reproduce**

Configure haraka to use smtp_proxy with a hostname, which is not available due to temp network issues.
Try to send an email.

**System Info:**

Haraka | Haraka.js — Version: 2.8.28
 --- | :--- 
Node | v10.24.1
OS | Linux kay-hp 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1f  31 Mar 2020

**Comment by msimerson** [comment]
I just perused through the code in smtp_proxy, and then smtp_client, and host_pool, and I don't see any DNS resolution functions in there. Which to my mind means that hostnames in the config will not work. At all. One must use IP addresses. The documentation and configs do not make this clear.

**Comment by kayrus** [comment]
@msimerson

> I don't see any DNS resolution functions in there

That's weird. If you configure Haraka with a hostname, that can be resolved, it works. IMHO documenting that there should be only an IP is not a solution. Backend servers can listen TLS sockets, therefore Haraka should be able to resolve a hostname to verify the cert to establish a TLS connection.

**Comment by msimerson** [comment]
Hi @kayrus , any chance you can test the changes in #3286 and see if that helps?

**Comment by kayrus** [comment]
@msimerson unfortunately no, I haven't used haraka since 2y. We tried to onboard haraka as a proxy/queue solution in our project, but the amount of showstoppers I found led to our own custom solution which we're actively using right now.
