### ISSUE TITLE
Syntax error in haraka-net-utils/index.js

### ISSUE THREAD

**Issue by masoodrahim** [haraka/Haraka#3031]
### system info

Haraka | Haraka.js — Version: 2.8.28
 --- | :---
Node | v12.22.5
OS | Linux smtp2 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
openssl | OpenSSL 1.1.1m  14 Dec 2021

### Expected behavior
Haraka service will not start due to a syntax error.  

### Observed behavior
/usr/local/lib/node_modules/Haraka/node_modules/haraka-net-utils/index.js:361
    async.parallel([ resolve4, resolve6 ], function (err, async_list) {
        if (!ips.size && errors?.length) return reject(errors)
                                ^

SyntaxError: Unexpected token '.'

Removed the question mark from 'errors?' and it worked.

**Comment by msimerson** [comment]
That's because you're using node 12. The package.json specifies:

```json
  "engines": {
    "node": ">= v14.18.2"
  },
```

Install node.js 14, or stick with the npm published version of Haraka, which should install an older version of haraka-net-utils.

**Comment by msimerson** [comment]
I'll reopen if neither of the suggestions works for you.

**Comment by masoodrahim** [comment]
Thanks for the quick reply. Can you let me know how to stick with the with the npm published version of Haraka? Npm was installed via apt-get.

**Comment by msimerson** [comment]
IIRC, you specify a version you want like this: `npm install haraka@2.8.26`

I looked in the changes and it appears we started using optional chaining in the haraka-net-utils included in 2.8.27.

**Comment by masoodrahim** [comment]
Thank you, if I stick with my patched file and run node 12 which is bundled with Debian 11.2, am I asking for trouble regarding the stability of Haraka?

**Comment by msimerson** [comment]
You can look in the Changes.md file in Haraka and see what has changed. If any of the changes affect you, you can port them. Or just figure out how to install a newer version of node on Debian 11. Instructions are at [Nodesource](https://github.com/nodesource/distributions/blob/master/README.md)

**Comment by msimerson** [comment]
Regarding stability, Haraka is generally quite stable, but SMTP has a broad surface area so there's loads of room for sharp edges.
