### ISSUE TITLE
Issue with message_stream in 2.8.28

### ISSUE THREAD

**Issue by thenitai** [haraka/Haraka#3043]
Hi,

We are processing millions of emails a day and just set up a new server with 2.8.28.

However, we randomly see an error with this version of:

connection.transaction.message_stream is not defined (null of undefined)

In short, the connection.transaction is empty.

Going back to 2.8.27 solves the issue. I don't have a clear test case as this is completely random.

We tested with Node 14.18.2 and with Node 16.14.2 (though, it more happens under v16).

**Comment by msimerson** [comment]
2.8.28 release (from npm) or 2.8.28 from git (master)?

This is the type of error discussed in #2732 (and others before). We have improved upon it in a couple PRs that are linked to in that issue (including one that PR that isn't in a release yet).

**Comment by thenitai** [comment]
From NPM. Sorry, I didn't see the other posts. Should we try with a specific pull or?

**Comment by msimerson** [comment]
I'm running from `master` on my own server and would recommend trying that. Worst case, you can always fall back to 2.8.27, right? 

If running from master helps, we should probably cut a release. If you're still seeing the issue after deploying, then we need to find out exactly why.

**Comment by msimerson** [comment]
Any update here?

**Comment by msimerson** [comment]
Closing as inactive. Reopen if the issue persists in the Haraka from `master`.

**Comment by msimerson** [comment]
Are you using 2.8.28 release or 2.8.28 from git?

Matt
