### ISSUE TITLE
Basic question...but how do you log to console from a plugin, but OUTSIDE of an exported function?

### ISSUE THREAD

**Issue by shadowsocksquestions** [haraka/Haraka#3055]
Environment details here, although not really relevant for this questions:

Haraka | Haraka.js — Version: 2.8.28
 --- | :--- 
Node | v18.0.0
OS | Linux me-VirtualBox 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1j  16 Feb 2021

Here is the code I have - I know that code outside of the exported functions is executed, since writing data to a file works...though I can't seem to figure out how to log, to the console, if it's possible

```
//I tried a few approaches, but couldn't get any to work
console.log("A random message")
this.logdebug("A random message");
logdebug("A random message");
logger.logdebug("A random message");
logger.logdebug("A random message", connection, plugin);
etc etc etc


exports.hook_data = (next, connection) => {
    // enable mail body parsing
    connection.transaction.parse_body = true;
    next();
}

exports.hook_data_post = function (next, connection) {
    this.loginfo(connection.transaction.body.bodytext);
    //todo: get to, from & other relevant fields
    next();
}
```

So if anyone can let me know how to do this, I'd appreciate it.

**Comment by msimerson** [comment]
Using logger.log* works fine, just be cognizant of your current loglevel (works like syslog), which determines if that particular level of logging gets emitted.

**Comment by shadowsocksquestions** [comment]
@msimerson 

Ok, I got it. Seems I needed to require("./logger") (I haven't done much with Node before). I thought logger was a global object, since it isn't mentioned that you need to import an external file in the docs (https://haraka.github.io/core/Logging_API/)
