### ISSUE TITLE
Programmatically select relevant TLS key/certs

### ISSUE THREAD

**Issue by immjs** [haraka/Haraka#3072]
### Is your feature request related to a problem? Please describe.

I need to programmatically select the relevant TLS key/certs and apply them to the upcoming TLS socket

### Describe the solution you'd like

I would like a hook that you call for me to gather the relevant TLS keys/certs

### Describe alternatives you've considered

I've considered using the `config/tls` directory but am unsure whether it would work with wildcards.

**Comment by msimerson** [comment]
moved to [wiki/TODO](https://github.com/haraka/Haraka/wiki/TODO)

Also, using `config/tls` does work with wildcard certs.
