### ISSUE TITLE
Haraka installation stuck at http fetch GET 200 https://registry.npmjs.org/moment/-/moment-2.29.4.tgz 7284ms (cache miss)

### ISSUE THREAD

**Issue by avi333learn** [haraka/Haraka#3083]
I was trying to install Haraka in my digital ocean droplet that runs on Ubuntu 20.04.4 LTS, npm version 8.17.0 and node version v16.16.0. I tried installating multiple times but stuck at same point that is

>  ( ##################) ⠏ reify:moment: http fetch GET 200 https://registry.npmjs.org/moment/-/moment-2.29.4.tgz 7284ms (cache miss)

I tried doing `apt update && apt upgrade` , I rebooted it, done `apt clean`, `apt remove`, `apt autoclean`, `apt autoremove` and even cleaned npm cahce using `npm cache clear --force` but still same problem.
Kindly, provide a solution.

**Comment by msimerson** [comment]
I'm unable to duplicate this issue when installing Haraka (from HEAD and from npm) in a VM running Ubuntu 20.04.5.
