### ISSUE TITLE
running haraka for plugin creation throws iconv error

### ISSUE THREAD

**Issue by rickersilva** [haraka/Haraka#3093]
Hi, I'm following the steps to create a plugin. I got stuck at running haraka -c at the plgin proyect folder.

First, `sudo haraka -c path/to/project` said haraka command not found. 
after that I tried only `haraka -c .`, since I was right at the project folder which is in my user folder.
![image](https://user-images.githubusercontent.com/6293792/191140479-2d4f8a58-0ea9-4667-af7f-a571d8dbda62.png)

So I tried `npm install iconv `but that throw even more errors.
![image](https://user-images.githubusercontent.com/6293792/191140531-056ba89e-65c9-473f-aeef-27074a83ae04.png)

What could I be missing with iconv, is it iconv really the problem? I also run `npm update -g`, just for the sake but nothing changed.

**Comment by msimerson** [comment]
You failed to provide the information necessary for us to help you. OS. Version. Node.js version. Getting iconv to compile requires a working node-gyp, and that sometimes presents obstacles.

**Comment by rickersilva** [comment]
Sorry msimerson.

My nodejs version is 18.8.0 
Ubuntu 20.04.5 LTS

My Ubuntu is running on a WSL (Windows Subsystem for Linux) version 2.

FYI when I run haraka from my haraka installation it runs good and I have tested the email with swaks and it run good. The plugin project is in my user folder but haraka is in /tmp/

Thank you

**Comment by msimerson** [comment]
You might find our CI config for [Windows](https://github.com/haraka/.github/blob/master/.github/workflows/windows.yml) to be helpful. A little bit of futzing is required to get node-gyp to work with different Windows versions.

**Comment by rickersilva** [comment]
I'm on Ubuntu, anyway, not Windows. Think of it as a virtualized ubuntu

**Comment by rickersilva** [comment]
I'm gonna check that. What about the iconv?

**Comment by msimerson** [comment]
`iconv` is a required module. When `node-gyp` is working correctly, then iconv will install without error.

**Comment by rickersilva** [comment]
Ok, I run `sudo install -g node-gyp` and apparently it was ok.
![image](https://user-images.githubusercontent.com/6293792/191162429-7b407e52-306c-4c13-8dc8-5fc9873615dd.png)

however, running haraka plugin still throws error with iconv. and installation of iconv doesn't work. I tried as root but as root haraka doens't run. I'm a bit noob in this I guess. Are this steps in the documentation intended to be run as root?

**Comment by rickersilva** [comment]
> `iconv` is a required module. When `node-gyp` is working correctly, then iconv will install without error.

Is there anyway to vlaidate ig node-gyp is working correctly?

**Comment by rickersilva** [comment]
I didn't solve this, but I tried again in a virtualized Ubuntu, latest version to this date and it worked just fine.  Or at least no problems with node-gyp or whatsoever. 

So my guess is that of you are using WSL for this purposes, it wont work. Try the real deal.

The problem now is that the log is not stored anywhere or I'm not looking at the right file. Since no one seem to be checking this anymore, I hope this helps you.
