### ISSUE TITLE
plugin project folder location

### ISSUE THREAD

**Issue by rickersilva** [haraka/Haraka#3098]
While trying to run the plugin I found some errors when Haraka was trying to load some plugins. I checked only the project plugin was enabled in the plugins file in the config folder of the plugin project.

I have haraka-demo and haraka-plugins folders side by side in /tmp/. ¿Is it ok to locate the folders like that or they have to be organized in some special way?

**Comment by msimerson** [comment]
> I have haraka-demo and haraka-plugins folders side by side in /tmp/. 

I'm not sure what you mean here. Haraka plugins can be files in `./Haraka/plugins/my-great-plugin/` or as NPM modules, installed in `./Haraka/node_modules/haraka-plugin-my-great-plugin/`.
