### ISSUE TITLE
Where are plugin logs saved?

### ISSUE THREAD

**Issue by rickersilva** [haraka/Haraka#3099]
4I just run the plugin, and there was no errors. apparently.

Running haraka on the plugin project folder throws a warning for smtp.ini unset and two errors related to TLS because I have not created unsigned certificates in the plugin.

however, haraka starts and  works. When I run the swaks command it shows this.1
![Captura de pantalla 2022-09-22 200304](https://user-images.githubusercontent.com/6293792/191875712-f91b9b2a-d8bd-409c-950d-6b532e56c0d3.png)

I checked the loglevel file created in the process but there is nothing appart from LOGDEBUG and in hostlist only the result of the echo command.

**Comment by msimerson** [comment]
Typically /var/log/haraka.log. Unless you have a logging plugin enabled, such as syslog. If so, check that plugins config to see where.
