### ISSUE TITLE
Socket closes unexpectedly 

### ISSUE THREAD

**Issue by vladtreny** [haraka/Haraka#3101]
**Describe the bug**
Hello, I am not user, but sender to this server.

And I see in the logs, that the server hangs here.
 
Last logs
'250 recipient <****> OK',
'354 go ahead, make my day'

After that, I start writing data to socket and it closes, instead of further communicating.
I've never seen this issue on other servers.

**Expected behavior**
Receive error if something failed

**Observed behavior**
Socket just closes after writing to it

**System Info:**
ESMTP Haraka/2.8.20 ready

**Comment by msimerson** [comment]
The server is old (v 2.8.20) and not updated. Track down the admin and suggest they update their server.
