### ISSUE TITLE
Need to change charset or encoding for MIME part

### ISSUE THREAD

**Issue by gene-hightower** [haraka/Haraka#3110]
**Is your feature request related to a problem? Please describe.**

Using a body filter, you can replace the contents of a MIME part, but
not the content-type or the encoding. This can be a problem if you get
a text/plain part with charset="us-ascii" but you want to change it to
UTF-8.

Sometimes, a message will come in with charset="us-ascii" but containing UTF-8 data.

**Describe the solution you'd like**

A way to replace the MIME part, with a new content-type and encoding.

**Describe alternatives you've considered**

Not sure what alternatives are available.

**Comment by msimerson** [comment]
Short of submitting a PR to add this to Haraka, I'm closing this as stale and out-of-scope.
