### ISSUE TITLE
AMP Mailer

### ISSUE THREAD

**Issue by Ghasiram** [haraka/Haraka#3116]
We are just exploring the haraka to use as smtp server to receive and submit email so just wanted to know if we can send AMP mailer using haraka and if yes then what changes we need to made at haraka level.

**Comment by baudehlo** [comment]
We will need to be told what an AMP mailer is first.

**Comment by baudehlo** [comment]
Oh, looks like AMP email is this abomination: https://amp.dev/about/email

Haraka doesn't care about the email content. That's on you. Closing.

**Comment by Ghasiram** [comment]
Thank you @baudehlo  for your quick response. We have tested AMP Maier using haraka with node npm mail parser but mailparser is treating AMP mailer as attachment. 

If will be great help if you can help us in this or share any sample from which we can read and we can use haraka.

Thank you once again.
