### ISSUE TITLE
dkim_verify fails to find DKIM record, thinks it's just a TXT record.

### ISSUE THREAD

**Issue by hperrin** [haraka/Haraka#3148]
**Describe the bug**
Upon receipt of an email sent from the same system, the dkim_verify plugin is failing to find the DKIM key in the DNS records. It reports that it is ignoring it as a TXT record.

**Expected behavior**
dkim_verify should understand the record.

**Observed behavior**
Here is the log output:

```
[DEBUG] [-] [dkim_verify] @dev.port87.com: DNS lookup oct2021._domainkey.dev.port87.com (timeout= 29s)
[DEBUG] [-] [dkim_verify] @dev.port87.com: ignoring TXT record: v=DKIM1;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA10uf0NZ1Wn5GLWckB0TvONGAH8aZkFMErmwo9IS94ExrxqXpc8O6lUAbYRYSF2uRcLkPtlnK8lYdF3JjRbXt0RGx35UjF/5XWlS6103qG0ybCXO8kOiuoWszIzjKklMKiHq+D+E8S7F34NqRFD9nY5bsSDZbQrAq+Wdz/OkUs8qn29BFG/sfWF9whGWgfENtKp6uwBOQM,nCCOPS3dObcLw5OsNALmhsuy6Kx4PfkqDDD1u2K7qQm4XXrQsKo6n5O1sM8kLcO1ZmnjzllTb00O8tM7IhhUBv/KvMNye1dpnM8S7v7Mb9j0uXj9fNdAd4CpDVsvU1iLB6H3UT2JQRnPQIDAQAB                                                          
[DEBUG] [-] [dkim_verify] {"identity":"@dev.port87.com","selector":"oct2021","domain":"dev.port87.com","result":"invalid"}
[INFO] [54C26F57-A59F-49A4-BADA-054E6549D426.1] [dkim_verify] identity="@dev.port87.com" domain="dev.port87.com" selector="oct2021" result=invalid  (no key for signature)
[ERROR] [54C26F57-A59F-49A4-BADA-054E6549D426.1] [dkim_verify] dev.port87.com (no key for signature)
```

**Steps To Reproduce**
I'm not sure exactly how to reproduce this behavior. Here is a copy of my DKIM record from CloudFlare's DNS:

```
v=DKIM1;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA10uf0NZ1Wn5GLWckB0TvONGAH8aZkFMErmwo9IS94ExrxqXpc8O6lUAbYRYSF2uRcLkPtlnK8lYdF3JjRbXt0RGx35UjF/5XWlS6103qG0ybCXO8kOiuoWszIzjKklMKiHq+D+E8S7F34NqRFD9nY5bsSDZbQrAq+Wdz/OkUs8qn29BFG/sfWF9whGWgfENtKp6uwBOQMnCCOPS3dObcLw5OsNALmhsuy6Kx4PfkqDDD1u2K7qQm4XXrQsKo6n5O1sM8kLcO1ZmnjzllTb00O8tM7IhhUBv/KvMNye1dpnM8S7v7Mb9j0uXj9fNdAd4CpDVsvU1iLB6H3UT2JQRnPQIDAQAB
```

**System Info:**

Haraka | Haraka.js — Version: 3.0.0
 --- | :--- 
Node | v16.19.0
OS | Linux dev.port87.com 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Additional context**
The debug statement comes from this line:
https://github.com/haraka/Haraka/blob/master/dkim.js#L307

Here is the DKIM signature from the message:

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple;
        d=dev.port87.com; s=oct2021;
        h=from:subject:date:message-id:to:mime-version;
        bh=vWC1aXwKmP/4ijDvWqQqRFK6LiJg2oTbsiNXWfUyNMg=;
        b=jnNv6sU/rjNXZRcJ1tfK1VIMQBM4vkf3dZaTKQeSF4GNE8RnoK3+Z+IqtmMFnPLD0yCGglt6ZX
        B/9KHDTz0pEnMmgLoIizt4bT8vs+7uzml6uAnoi7GJHkr8DppkyznaiPVZ8U+5cITvo8mZkfJwAh
        OJp6r353WXNxqjMzO3v/03+Eppe5KAoVNvBzy3GpHJJoo80wnLJ99T12CQ6ok/4/LZaMQ4OCSMaw
        1Cx545ip6r/EZcNWl6XZxGInDEzJijLI9IFNXnVNajEa9myCUU93TZ07dGX3H+HAMjGiLSjqJXxA
        VDeHzXQ41/q+RY3dffU4ODIl3DAEC1/pPvfQLnSg==
```

**Comment by hperrin** [comment]
I added a `console.log` right before that line in my local copy:

```
console.log(JSON.stringify(record));
```

And I got this:

```
["v=DKIM1;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA10uf0NZ1Wn5GLWckB0TvONGAH8aZkFMErmwo9IS94ExrxqXpc8O6lUAbYRYSF2uRcLkPtlnK8lYdF3JjRbXt0RGx35UjF/5XWlS6103qG0ybCXO8kOiuoWszIzjKklMKiHq+D+E8S7F34NqRFD9nY5bsSDZbQrAq+Wdz/OkUs8qn29BFG/sfWF9whGWgfENtKp6uwBOQM","nCCOPS3dObcLw5OsNALmhsuy6Kx4PfkqDDD1u2K7qQm4XXrQsKo6n5O1sM8kLcO1ZmnjzllTb00O8tM7IhhUBv/KvMNye1dpnM8S7v7Mb9j0uXj9fNdAd4CpDVsvU1iLB6H3UT2JQRnPQIDAQAB"]
```

I think that would explain it. It's not a string there, it's an array. I don't know why my particular setup results in it being an array though.

**Comment by hperrin** [comment]
I'm not exactly sure how this does work, because Node's DNS API is supposed to give back an array of arrays, not an array of strings.

https://nodejs.org/docs/latest-v16.x/api/dns.html#dnsresolvetxthostname-callback

I changed line 304 to:

```js
for (const recordSegments of res) {
  const record = recordSegments.join('');
```

and it works now.

**Comment by msimerson** [comment]
Very good sluething @hperrin. That fix looks correct to me. Care to submit a PR with it?

**Comment by hperrin** [comment]
Found the commit where this was introduced, just a few days ago. :)

https://github.com/haraka/Haraka/commit/5fa95fa2390197a85eb838281edb7be1fba27018#diff-8e9ea789c14c1e20da4d4b8bb8d8db4a2907caf8a1edf579249bddae8b55fdc8

**Comment by hperrin** [comment]
> Very good sluething @hperrin. That fix looks correct to me. Care to submit a PR with it?

Yep, I'll do that.

**Comment by msimerson** [comment]
Oh dear! The comment led me astray. It should have said, "node 0.11+" or something to that effect. It looked very much like a sunset note.

**Comment by hperrin** [comment]
> Oh dear! The comment led me astray. It should have said, "node 0.11+" or something to that effect. It looked very much like a sunset note.

Yes, that comment was very misleading! I was just having a conversation with my dad about comments sometimes being worse than not having them. xD

PR: https://github.com/haraka/Haraka/pull/3149

**Comment by msimerson** [comment]
> I don't know why my particular setup results in it being an array though.

It's not your setup in particular. I don't remember exactly, but a long time ago (in the 0.4 and 0.6 days), node.js returned TXT records as a string. It had something to do with the c-ares lib in use. Anyway, that caused a number of problems and it was eventually solved by always returning TXT as an array. Probably in version 0.11.
