### ISSUE TITLE
High number of DNS lookup failures

### ISSUE THREAD

**Issue by mr-karan** [haraka/Haraka#3154]
**Describe the bug**

We send a large batch of emails regularly (50-70k/min) and after upgrading to 3.0.0 we're observing high number of DNS Lookup failures. On grepping the logs, we can see a huge spike in the following log entries

- `450 - DNS lookup failure: [gmail.com](http://gmail.com/)`
- `550 - Tried all MXs [gmail.com](http://gmail.com/)` 

This has started to come only after upgrading to 3.0.0. On checking the release notes, I think this may be related to disabling of a connection pool (https://github.com/haraka/Haraka/pull/3113, https://github.com/haraka/Haraka/pull/3115). At such a high throughput of emails, concurrent DNS lookups could be erroring out.

https://github.com/haraka/Haraka/blob/master/outbound/hmail.js#L323-L335

**Expected behavior**

I expect that with "pooled connections", connection for an outbound mail to a particular IP/domain will be held and a DNS lookup will not need to happen for the lifetime of the connection in the pool (`pool_timeout` value). So, effectively one DNS lookup every `50s` (default `pool_timeout` value) v/s 50k DNS lookup/min as now there's no pool so a DNS resolution happens for each email.

Could this be a cause of worry for large scale setups like ours? What are the workarounds? 

**Observed behavior**

High number of DNS lookup failures

**System Info:**

```
Haraka | Haraka.js — Version: 3.0.0
 --- | :--- 
Node | v19.4.0
OS | Linux alertsmailer-192.168.41.254 5.4.0-1055-aws #58~18.04.1-Ubuntu SMP Wed Jul 28 03:04:50 UTC 2021 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1n  15 Mar 2022
```

**Comment by msimerson** [comment]
Yes, axing connection pooling could be the cause behind this. The simplest solution is to run a local DNS cache.

**Comment by analogic** [comment]
You should definitely use local DNS at this level of volume - generating 1k packets per second might be seen as attempt to DoS...

**Comment by mr-karan** [comment]
Alright, noted. Well we didn't have a local DNS cache setup up until now, because connection pooling addressed the need for this.

Thanks for the help! I can close this, if SMTP connection pooling isn't coming back in future (although I really hoped it did, but it's fine either way :))

**Comment by msimerson** [comment]
It may come back, but it probably won't return quickly. The assumptions baked into the pool module we were using weren't a good match for SMTP and creates several . If pooling does return, it'll be because someone either extended the pooling module, or because someone writes a SMTP specific pooling module.
