### ISSUE TITLE
hook_ehlo is called twice

### ISSUE THREAD

**Issue by lnedry** [haraka/Haraka#3160]
**Describe the bug**

hook_ehlo gets called twice for every EHLO.

**Expected behavior**

hook_ehlo should only get called once for each EHLO.

**Steps To Reproduce**

I created this plugin to demonstrate this issue:

```
exports.hook_ehlo = function (next, connection, helo) {
    connection.loginfo(this, 'EHLO TEST');
    return next();
}

exports.hook_helo = function (next, connection, helo) {
    connection.loginfo(this, 'HELO TEST');
    return next();
}

```

**System Info:**

Haraka | Haraka.js — Version: 2.8.28
 --- | :--- 
Node | v16.19.0
OS | Linux mx 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
openssl | OpenSSL 1.1.1n  15 Mar 2022

**Additional context**

For each HELO, hook_helo is run once and hook_ehlo is run once.

**Comment by msimerson** [comment]
Where are the logs that demonstrate the issue?

**Comment by baudehlo** [comment]
Are we sure this isn't just a case of STARTTLS?

**Comment by msimerson** [comment]
Not at all, that's why I asked for logs.

**Comment by lnedry** [comment]
Upon further inspection, it does appear to be STARTTLS. I'll reopen if I find evidence to the contrary.
