### ISSUE TITLE
Haraka Problem SSL routines:ssl_choose_client_version:unsupported protocol

### ISSUE THREAD

**Issue by fred614** [haraka/Haraka#3163]
Hello,

For information
Haraka 2.8.28  inside a pod image node:14 under openshift cluster 4.11

Sometimes I get this error randomly 1 to 3 times a day and not every day

client TLS error: Error: 140237707908928:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1958:

how to get more information to find the problem?

Regards

**Comment by msimerson** [comment]
Node 14 is support ended on 2023-02-16, and we don't support it either. The issue is likely that your mail server is failing TLS negotiation with another MTA. The solution is upgrading your version of node.
