### ISSUE TITLE
Docs broken?

### ISSUE THREAD

**Issue by darkpixel** [haraka/Haraka#3173]
I've tried in Chrome and Firefox.  The documentation at https://haraka.github.io/getting_started is b0rked.

The "Core", "Tutorial" and "Plugins" links don't work in either browser.  Tried with all extensions (i.e. adblock) disabled.  Clicking on them does nothing.

![Screenshot from 2023-04-25 17-26-32](https://user-images.githubusercontent.com/158380/234436136-d31cfcb2-c12f-46f1-b50e-1e0d7f5463ee.png)

**Comment by sent** [comment]
Hello,

This is should be fixed, looks like docus bug, sigh sigh.

Thanks!
