### ISSUE TITLE
Slack link on website is not working

### ISSUE THREAD

**Issue by NogginBox** [haraka/Haraka#3187]
On the [Haraka Community page](https://haraka.github.io/community) there is a link to join your slack group.

I tried to follow this link on your website homepage to ask a question on Slack:

The link's href is: **https://communityinviter.com/apps/harakaserver/public-inviter**

This redirects you to **https://communityinviter.com/** and not able to join your slack group.

Do you still have a slack group? I've just found the Github discussions section. Perhaps this should be called out on the community page.

**Comment by msimerson** [comment]
Aye, I was always a reluctant participant in IRC and Slack so I'm not "In The Know" but I think the Slack channel has been extremely quiet for a long time. I've removed it from that page.

**Comment by celesteking** [comment]
Just in case someone wants to join Slack channel again, https://communityinviter.com/apps/harakaserver/public-inviter is working again.
