### ISSUE TITLE
Dependency updates break v2 engine support

### ISSUE THREAD

**Issue by GeekOfAges** [haraka/Haraka#3198]
**Describe the bug**

We run latest version 2.8 of Haraka in production on node v12.22.12

Version 2.9.19 package states that it's compatible with node `>= v6.14.1`, but after recent re-roll of the instance and thus - fresh Haraka install, Haraka failed to start up due to nullish coalescing operator (`?.`) being used by `haraka-*` dependencies that are installed with `>=` or `*` version spec.

**Expected behavior**

A fresh install of package that supports engine works on supported engine

**Steps To Reproduce**

Install 2.8.19 on node version 12.22.12 and attempt to run it

**Additional context**

Haraka started up and ran after manually installing the following packages at fixed versions

- haraka-tld@1.0.30
- haraka-net-utils@1.3.7
- haraka-results@2.1.0

**Proposed solution**

Publish new patch version of v2 with versions fixed to last compatible.

**Comment by msimerson** [comment]
We dropped node v6 support in v2.8.25. Apologies, but the node organization doesn't support node v6 and neither do we. If you wish to put the effort into creating a PR, I'll merge it against a new v6 branch and publish.
