### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by ralphholzmann** [haraka/Haraka#32]
Looking for the best way to dynamically set configs based on environment. For example, executing haraka with the command `NODE_ENV=dev node haraka -c smtp` would set the listening port to 2525, whereas `NODE_ENV=prod node haraka -c smtp` would set the listening port to the default 25. Since the supported types of configs are all "flat" in some sense, there's no way to make this dynamic. What do you suggest?

Thanks,

Ralph

**Comment by randunel** [comment]
Working with separate directories and symlinks for now, but this is a ping, perhaps you will reconsider it at some point @baudehlo

**Comment by krzysztofantczak** [comment]
Ping from 2017, whats up with that? This is the first place i found when googling after this issue. Is it possible now?

**Comment by baudehlo** [comment]
No. We never considered it important because separate config directories works just fine.

**Comment by krzysztofantczak** [comment]
Not really containers friendly. Perhaps this use case is more up to date now? In docker times? For example, i would like to override certain hosts settings for various plugins either by ENV or by code, how can i achieve that now? Possible?

**Comment by baudehlo** [comment]
You'd have to have something write the config out on/before startup using the given environment variables.
