### ISSUE TITLE
spamassassin: Cannot read properties of null (reading 'message_stream')

### ISSUE THREAD

**Issue by LuisCampos97** [haraka/Haraka#3230]
**Describe the bug**

I have Haraka with **spamassassin** plugin. When I send an email to haraka email server, i have this error in the console:

```bash
TypeError: Cannot read properties of null (reading 'message_stream')\n    at Socket.<anonymous> (/home/api-mailserver/node_modules/Haraka/plugins/spamassassin.js:288:26)\n    at Socket.emit (node:events:525:35)\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1263:10)
```

Can someone please help me and see if I’m doing something wrong?

**System Info:**

Haraka | Haraka.js — Version: 3.0.2
 --- | :--- 
Node | v16.14.0
OS | Linux luis 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by LuisCampos97** [comment]
@superman20 I think the error may have resulted from your pull request #2967. Do you think you can help me with this?

**Comment by superman20** [comment]
Based on the information you presented, I don't see the connection to my pull request.  My changes did not alter the socket connect function in any meaningful way.  It looks like the message_stream object is null on line 288.  I have no idea how that might happen but could indicate a problem somewhere else or in a prior plugin.  Maybe some others could chime in on how to start debugging how the message_stream might get to be null.  Or perhaps you could track the state of the message_stream object through the mail delivery process to discover where it gets null'd.

**Comment by msimerson** [comment]
We need more information (think: log entries) to have any chance to diagnose this. I'm closing, but if you're still having the issue and can provide more information, we can re-open.
