### ISSUE TITLE
npm install -g Haraka installs haraka-plugin-spf 1.2.0 when latest is 1.2.3

### ISSUE THREAD

**Issue by sriccio** [haraka/Haraka#3259]
**Describe the bug**

npm install -g Haraka installs haraka-plugin-spf 1.2.0 when latest is 1.2.3

**Expected behavior**

latest version of the spf plugin installed

**Observed behavior**

1.2.0 version is installed

**Steps To Reproduce**

npm install -g Haraka

**System Info:**

Haraka | Haraka.js — Version: 3.0.2
 --- | :--- 
Node | v20.10.0
OS | Linux mx1-ng 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Additional context**

The installed Haraka package.json has spf version locked to 1.2.0 

root@mx1-ng:/usr/lib/node_modules/Haraka# grep spf /usr/lib/node_modules/Haraka/package.json 
    "haraka-plugin-spf": "1.2.0",

**Comment by sriccio** [comment]
I discovered this being it by the bug fixed here:
https://github.com/haraka/haraka-plugin-spf/issues/13

Which is fixed in 1.2.2 :)

**Comment by msimerson** [comment]
The commit is already merged. You have two solutions:
1. install from github repo (eg: `npm install haraka/Haraka`)
2. wait for #3256

**Comment by sriccio** [comment]
Hello Matt,

Oh okay, glad to know it's in the pipe ! Thanks a lot.

Kind regards

**Comment by sriccio** [comment]
Just a question though, is there a specific reason why this plugin dependency is pinned to a specific version `"haraka-plugin-spf": "1.2.3"` and not `"haraka-plugin-spf": "^1.2.3"`

Thanks :)

**Comment by msimerson** [comment]
Oversight. It should be the latter
