### ISSUE TITLE
Changing connect timeout of outgoing connections

### ISSUE THREAD

**Issue by sriccio** [haraka/Haraka#3281]
**Describe the bug**

I'm trying to find a way to change the connection timeout of outgoing transactions. Default is 30 seconds and too long for some usages.

**Expected behavior**

Timeout option in smtp_client.js to be taken into account, but seems it's not (or maybe i'm doing something wrong)

**Observed behavior**

It stays to the default 30 seconds

It seems that this parameter is lost on it's way to the socket connect function:
https://github.com/haraka/Haraka/blob/2075b94bc4e100c54302346082b01a0e1f37c295/smtp_client.js#L35

I would guess that this is lost here::
https://github.com/haraka/Haraka/blob/2075b94bc4e100c54302346082b01a0e1f37c295/line_socket.js#L40

**System Info:**

Haraka | Haraka.js — Version: 3.0.3
 --- | :--- 
Node | v20.11.1
OS | Linux mx1-ng 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by msimerson** [comment]
Can you test this patch?

```diff
diff --git a/smtp_client.js b/smtp_client.js
index 2fb8f710..ede9861a 100644
--- a/smtp_client.js
+++ b/smtp_client.js
@@ -33,7 +33,7 @@ class SMTPClient extends events.EventEmitter {
         super();
         this.uuid = utils.uuid();
         this.connect_timeout = parseInt(opts.connect_timeout) || 30;
-        this.socket = opts.socket || line_socket.connect(opts.port, opts.host);
+        this.socket = opts.socket || line_socket.connect({ host: opts.host, port: opts.port, timeout: this.connect_timeout });
         this.socket.setTimeout(this.connect_timeout * 1000);
         this.socket.setKeepAlive(true);
         this.state = STATE.IDLE;
```
