### ISSUE TITLE
Outbound - Fallback to MX's IPv4 when the MX's IPv6 is bogus

### ISSUE THREAD

**Issue by sriccio** [haraka/Haraka#3314]
Hello,

**Is your feature request related to a problem? Please describe.**
I noticed that when a recipient MX has both IPv6 and IPv4 entries, and that the IPv6 entry is bogus, Haraka doesn't try to connect to the IPv4 address.

Example of bogus MX:
```
~# host mx.bogus.tld 1.1.1.1

mx.bogus.tld has address 1.2.3.4
mx.bogus.tld has IPv6 address fe80::d250:99ff:feda:9100 <- unroutable
```

**Describe the solution you'd like**
For a given MX having both IPv4 and IPv6 entries, first try IPv6 and if it can't connect, fallback to IPv4 before tempfailing and announcing "Tried all MXs"

**Describe alternatives you've considered**
To avoid the issue I locally overwrote the target MX IP address (through our unbound resolver) to remove the IPv6 entry so the outgoing mail can be delivered.

**Additional context**
Of course it would be much better that the remote MX admin fix their IPv6 issue, but still, that could be handful to fallback to IPv4 to avoid having to locally patch how the MX resolves.

**Comment by msimerson** [comment]
> Describe the solution you'd like
> For a given MX having both IPv4 and IPv6 entries, first try IPv6 and if it can't connect, fallback to IPv4 before tempfailing and announcing "Tried all MXs"

This is how I expect outbound to work.

What version of Haraka are you running?

**Comment by sriccio** [comment]
Hello @msimerson,

On this particular server we are running `Haraka.js — Version: 3.0.2` at the moment.

Kind regards
