### ISSUE TITLE
Spamhause warning

### ISSUE THREAD

**Issue by ravivgolov** [haraka/Haraka#3317]
Hi

How I fix this issue: 
```
[WARN] [-] [dnsbl] zone 'zen.spamhaus.org' did not respond to test point (null)
[WARN] [-] [dnsbl] disabling zone 'zen.spamhaus.org'
```

And I have another question: I want to configure the spam filter as effectively as possible. Could you please instruct me on the best configuration for filtering spam?

How I configure to rate limit maximum 300 per hour per sender?

So far I configured:
rspamd(Should i use SpamAssassin instead? or both?)
bounce with the following settings:
```
[check]
reject_all=false
single_recipient=true
empty_return_path=true
bad_rcpt=true
bounce_spf=true
non_local_msgid=true

[reject]
single_recipient=true
empty_return_path=true
bounce_spf=false
non_local_msgid=false
```
spf plugin to check and reject outgoing spf if not present in the DNS of the domain

Hope to get advice from experience users, I want to keep the IP reputation as much as possible good.
Thanks.

**Comment by msimerson** [comment]
> How I fix this issue:

By assuring your server has reliable DNS.
