### ISSUE TITLE
Bounces not working for me

### ISSUE THREAD

**Issue by ravivgolov** [haraka/Haraka#3321]
Hello

I have configured the bounce plugin(the default settings).

I received a bounce message from Gmail once regarding DMARC. Since then, I have fixed the DMARC and other records. I haven't received any more bounces. However, emails are not arriving at either my Outlook.com account or my DirectAdmin IMAP server. Why are the bounces not working?

I have tested the email delivery system and found that emails sent from Haraka to the Gmail account are being delivered to the inbox without any issues. Furthermore, the records of all emails sent and received are accurate. As an example, I sent an email to a non-existent Outlook account from my Gmail account and received a bounce-back message stating that the recipient does not exist. However, when I attempted to send an email using Haraka, I did not receive any notification or error message.
<img width="236" alt="Screenshot 2024-04-17 123624" src="https://github.com/haraka/Haraka/assets/99405975/f6f01503-5c23-4dde-b2a3-d350de3cdb04">

**Comment by ravivgolov** [comment]
For example, I try to send to this non-existent email: 
```
outlook_981BB3DD7841F1C2@outlook.com
Date: Wed, 17 Apr 2024 11:49:41 +0000
 -> To: outlook_981BB3DD7841F1C2@outlook.com
 -> From: user@test.com
 -> Subject: Test DKIM signing
 -> Message-Id: <20240417114941.051930@relay.test.com>
 -> X-Mailer: swaks v20201014.0 jetmore.org/john/code/swaks/
 ->
 -> This is a test mailing
 ->
 ->
 -> .
<-  250 Message Queued (271F5C46-8A4B-4996-9291-FCAAA8E57021.1)
 -> QUIT
<-  221 relay.test.com closing connection. Have a jolly good day.
```


I don't receive a bounce message, how to solve this?(I have enabled the bounce plugin)

**Comment by msimerson** [comment]
Nobody can help you because you haven't provided nearly enough information. The answers you seek are likely in your haraka logs.

**Comment by ravivgolov** [comment]
One thing I don't find how to read the logs of haraka including outbound, can you show me example? As I said the bounce message not showing in the output when I use swaks, I see message queued but no fail output showing. 
Only once I saw bouncing message once I didn't have dkim key and Google rejected my message.

All I can see is Karma in redis and outbound failure messages on queue folder. Where is the rest?
I tried also enable outbound-logger.

**Comment by ravivgolov** [comment]
I just noticed haraka not saving logs anywhere except Karama and some more plugins into redis.
I had to enable outbound-logger with file log.

How do I change this to log into redis instead?

**Comment by msimerson** [comment]
Start here: https://haraka.github.io/core/Logging

**Comment by ravivgolov** [comment]
The guide provides zero information on how to read the logs. I enabled Daemonize(smtp.ini) and the Outbound Logger to access the logs, but I couldn't find any other explanation elsewhere on how to interpret them.
