### ISSUE TITLE
How to customize Message-ID suffix

### ISSUE THREAD

**Issue by cod1ingcoding** [haraka/Haraka#3377]
### System Info
Haraka | Haraka.js — Version: 3.0.3
 --- | :---
Node | v18.17.1
OS | Linux XXX 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
openssl | OpenSSL 1.1.1n  15 Mar 2022

I read the documentation which states that `config/me` can set the hostname for the message-ID suffix. However, I entered content into file `config/me`, but the message-ID suffix of the received email still uses the content from the `/etc/hostname` file. How can I fix this or did I misunderstand something?

**Comment by msimerson** [comment]
> I read the documentation 

Where?

**Comment by cod1ingcoding** [comment]
> > I read the documentation
> 
> Where?

I misunderstood. I am using the MUA and Haraka on the same server, and the Message-Id header comes from the MUA. 
jetmore/swaks#101

**Comment by cod1ingcoding** [comment]
> > I read the documentation
> 
> Where?

I misunderstood. I am using the MUA and Haraka on the same server, and the Message-Id header comes from the MUA. 
jetmore/swaks#101
