### ISSUE TITLE
Files in repo are covered by .gitignore rules

### ISSUE THREAD

**Issue by comex** [haraka/Haraka#3379]
As of 138993a31, .gitignore contains a line that just says `queue`.  That ignores any directory called `queue` anywhere in the repo.  But several such directories exist within the repo:

```
docs/plugins/queue
plugins/queue
test/plugins/queue
test/queue
```

There is also the directory `test/installation/node_modules`, which is covered by the (older) `node_modules` rule.

From Git's perspective, having files/directories be checked into the repo but also be covered by gitignore rules is not the end of the world.  Existing files are still checked out as usual, and changes to them are tracked as usual.  But any new files added in those directories won't show up in `git status`.

More problematically, certain popular tools like [`ripgrep`](https://github.com/BurntSushi/ripgrep) and [`fd`](https://github.com/sharkdp/fd) automatically ignore gitignored files, making them semi-invisible when trying to search the repo.

It's probably best to change .gitignore to not cover any files checked into the repo.

**Comment by msimerson** [comment]
Any chance we can expect you to open a PR that corrects this?
