### ISSUE TITLE
 Failed to setup listeners: listen EADDRINUSE

### ISSUE THREAD

**Issue by ghost** [haraka/Haraka#361]
In the last step installation gives me such an error. 
I think the problem might be with the path I setup for haraka_test. Shall it be the pass to my Haraka folder?

**Comment by serv** [comment]
+1 @gilesbutler

**Comment by smfreegard** [comment]
FYI - and to anyone else reading this.  

If you want to run a daemon on port 25 (or any port < 1024).  Then you must start the daemon as root as on UNIX, ports < 1024 require root privs as they are considered privileged ports.  Ports > 1024 can be bound by any user.

Once you bind to the port - you can drop privs afterwards, which is what Haraka does if you provide a user in smtp.ini.

See https://www.debian-administration.org/article/386/Running_network_services_as_a_non-root_user for other alternatives.

**Comment by Manishjodhani** [comment]
I have  same issue and i'm running on port 587..?
and there were no any other process listening on 587.
Help me out???

**Comment by baudehlo** [comment]
There obviously is some other process listening on port 587. There's no
other way that error can occur. If it's linux try: `sudo netstat -nlp |
grep 587`
