### ISSUE TITLE
run and send email to gmail with haraka outbound

### ISSUE THREAD

**Issue by linkvn** [haraka/Haraka#408]
Hi, i'm newbie in nodejs and need help much. 
I want to build a host mail use haraka to send notification email to users. when i run test command with swaks, haraka send email to yahoo mail succesful, but not with gmail. What's wrong in my config? And how to run mail server forever (when i close ssh session)? here's console screen
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] connect ip=123.30.136.88                                                                              port=57282 local_ip=:: local_port=587
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running lookup_rdns hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running connect hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running connect hook in dn                                                                             sbl plugin
[DEBUG] [-] [dnsbl] looking up: 88.136.30.123.zen.spamhaus.org.
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] hook=connect plugin=dnsbl                                                                              function=hook_connect params="" retval=CONT msg=""
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 220 vps.123.30.136.8                                                                             8 ESMTP Haraka 2.2.8 ready
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] C: EHLO vps.123.30.136.                                                                             88 state=1
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running ehlo hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running capabilities hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running capabilities hook                                                                              in auth/flat_file plugin
[ERROR] [-] [core] Unvalid line in config file '/var/www/html/nhatkybe_vn/nodejs                                                                             /haraka/config/auth_flat_file.ini': no-reply@nhatkybe.com=nhatkybe_com
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] hook=capabilities plugin=a                                                                             uth/flat_file function=hook_capabilities params="" retval=CONT msg=""
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 250-vps.123.30.136.8                                                                             8 Hello vps [123.30.136.88], Haraka is at your service.
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 250-PIPELINING
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 250-8BITMIME
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 250-SIZE 500000
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 250 AUTH CRAM-MD5
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] C: AUTH CRAM-MD5 state=                                                                             1
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running unrecognized_comma                                                                             nd hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running unrecognized_comma                                                                             nd hook in auth/flat_file plugin
[INFO] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [auth/flat_file] ticket: <4f8d1.14                                                                             37078a1f0@vps.123.30.136.88>
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 334 PDRmOGQxLjE0Mzcw                                                                             NzhhMWYwQHZwcy4xMjMuMzAuMTM2Ljg4Pg==
[INFO] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] hook=unrecognized_command p                                                                             lugin=auth/flat_file function=hook_unrecognized_command params="AUTH" retval=OK                                                                              msg=""
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] C: aW5mb0BuaGF0a3liZS5j                                                                             b20gYTlkYmE4Nzk5NDFjYjNmMTUzMzQ1YjQwMjYyM2IzNTk= state=1
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running unrecognized_comma                                                                             nd hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] running unrecognized_comma                                                                             nd hook in auth/flat_file plugin
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] S: 235 Authentication s                                                                             uccessful
[INFO] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] hook=unrecognized_command p                                                                             lugin=auth/flat_file function=hook_unrecognized_command params="aW5mb0BuaGF0a3li                                                                             ZS5jb20gYTlkYmE4Nzk5NDFjYjNmMTUzMzQ1YjQwMjYyM2IzNTk=" retval=OK msg=""
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96] [core] C: MAIL FROM:<info@nhat                                                                             kybe.com> state=1
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running mail hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running mail hook in mai                                                                             l_from.is_resolvable plugin
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [mail_from.is_resolvable] nhatk                                                                             ybe.com: MX => queryMx ENODATA
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [mail_from.is_resolvable] nhatk                                                                             ybe.com: A => 123.30.136.88
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] hook=mail plugin=mail_fr                                                                             om.is_resolvable function=hook_mail params="info@nhatkybe.com" retval=CONT msg                                                                             =""
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running mail hook in mai                                                                             l_from.access plugin
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [mail_from.access] checking inf                                                                             o@nhatkybe.com against mail_from.access.whitelist
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [mail_from.access] checking inf                                                                             o@nhatkybe.com against mail_from.access.blacklist
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] hook=mail plugin=mail_fr                                                                             om.access function=mail_from_access params="info@nhatkybe.com" retval=CONT msg                                                                             =""
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] sender <info@nhatkybe.c                                                                             om> code=CONT msg=""
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] S: 250 sender <info@n                                                                             hatkybe.com> OK
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] C: RCPT TO:<nguyentun                                                                             glinh87@gmail.com> state=1
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running rcpt hooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running rcpt hook in rcp                                                                             t_to.in_host_list plugin
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [rcpt_to.in_host_list] Checking                                                                              if nguyentunglinh87@gmail.com host is in host_lists
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [rcpt_to.in_host_list] checking                                                                              gmail.com against vps.123.30.136.88
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [rcpt_to.in_host_list] checking                                                                              gmail.com against nhatkybe.com
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [rcpt_to.in_host_list] checking                                                                              gmail.com against 123.30.136.88
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] hook=rcpt plugin=rcpt_to                                                                             .in_host_list function=hook_rcpt params="nguyentunglinh87@gmail.com" retval=CO                                                                             NT msg=""
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running rcpt hook in rcp                                                                             t_to.access plugin
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [rcpt_to.access] checking nguye                                                                             ntunglinh87@gmail.com against rcpt_to.access.whitelist
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [rcpt_to.access] checking nguye                                                                             ntunglinh87@gmail.com against rcpt_to.access.blacklist
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] hook=rcpt plugin=rcpt_to                                                                             .access function=rcpt_to_access params="nguyentunglinh87@gmail.com" retval=CON                                                                             T msg=""
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running rcpt_ok hooks
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] recipient <nguyentungli                                                                             nh87@gmail.com> code=CONT msg="" sender="info@nhatkybe.com"
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] S: 250 recipient <ngu                                                                             yentunglinh87@gmail.com> OK
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] C: DATA state=1
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running data hooks
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] S: 354 go ahead, make                                                                              my day
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running data_post hooks
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] message mid="" size=232                                                                              rcpts=1/0/0 delay=0 code=CONT msg=""
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running queue_outbound h                                                                             ooks
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] queue code=CONT msg=""
[INFO] [-] [core] [outbound] Sending email as with a transaction
[INFO] [-] [core] [outbound] Adding missing Message-Id header
[INFO] [-] [core] [outbound] Processing domain: gmail.com
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running queue_ok hooks
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] queue code=CONT msg="Me                                                                             ssage Queued (51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1)"
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] S: 250 Message Queued                                                                              (51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1)
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running reset_transactio                                                                             n hooks
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] C: QUIT state=1
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running quit hooks
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] S: 221 vps.123.30.136                                                                             .88 closing connection. Have a jolly good day.
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] running disconnect hooks
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [core] disconnect ip=123.30.13                                                                             6.88 rdns="vps" helo="vps.123.30.136.88" relay=Y early=N esmtp=Y tls=N pipe=N tx                                                                             ns=1 rcpts=1/0/0 msgs=1/0/0 bytes=232 lr="" time=0.73
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] running send_email h                                                                             ooks
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] Sending mail: 138916                                                                             1391054_0_8419_5561.vps.123.30.136.88
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] running get_mx hooks
[INFO] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] Looking up A records                                                                              for: gmail-smtp-in.l.google.com
[INFO] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] Attempting to deliver                                                                              to: 173.194.79.26:25 (0) (0)
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 220 mx.google.                                                                             com ESMTP ai8si9331793pad.241 - gsmtp\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] C: EHLO vps.123.3                                                                             0.136.88
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250-mx.google.                                                                             com at your service, [123.30.136.88]\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250-SIZE 35882                                                                             577\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250-8BITMIME\r                                                                             \n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250-STARTTLS\r                                                                             \n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250-ENHANCEDST                                                                             ATUSCODES\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250 CHUNKING\r                                                                             \n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] C: MAIL FROM:<inf                                                                             o@nhatkybe.com>
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250 2.1.0 OK a                                                                             i8si9331793pad.241 - gsmtp\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] C: RCPT TO:<nguye                                                                             ntunglinh87@gmail.com>
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250 2.1.5 OK a                                                                             i8si9331793pad.241 - gsmtp\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] C: DATA
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 354  Go ahead                                                                              ai8si9331793pad.241 - gsmtp\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] C: .
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] S: 250 2.0.0 OK 1                                                                             389161420 ai8si9331793pad.241 - gsmtp\r\n
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] C: QUIT
[NOTICE] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] delivered file=1389                                                                             161391054_0_8419_5561.vps.123.30.136.88 domain="gmail.com" host="gmail-smtp-in.l                                                                             .google.com" ip=173.194.79.26 response="OK 1389161420 ai8si9331793pad.241 - gsmt                                                                             p" delay=2.927 fails=0
[DEBUG] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] running delivered ho                                                                             oks
[PROTOCOL] [51DE505A-C5B4-4ED3-9FA0-45ED43F49E96.1] [outbound] Received data aft                                                                             er stopping processing: 221 2.0.0 closing connection ai8si9331793pad.241 - gsmtp                                                                             \r\n

**Comment by harmansingh2908** [comment]
Hi, i'm newbie in nodejs and need help regarding send attachment files using haraka. to every domain...

i AM using this code for send mail..

var outbound = require('./outbound');

var plugin = this;

var to = 'user@example.com';
var from = 'sender@example.com';

var contents = [
    "From: " + from,
    "To: " + to,
    "MIME-Version: 1.0",
    "Content-type: text/plain; charset=us-ascii",
    "Subject: Some subject here",
    "",
    "Some email body here",
    ""].join("\n");

var outnext = function (code, msg) {
    switch (code) {
        case DENY:  plugin.logerror("Sending mail failed: " + msg);
                    break;
        case OK:    plugin.loginfo("mail sent");
                    next();
                    break;
        default:    plugin.logerror("Unrecognised return code from sending email: " + msg);
                    next();
    }
};

outbound.send_email(from, to, contents, outnext);

it is working. But how we can send attachment files with outbound Emails.

**Comment by Dexus** [comment]
Hi @harmansingh2908 

you need to build multipart mail body and encode the attatchments. If you dont know how you have to syntax you mail body read the RFCs about mails... or use [nodemailer](https://github.com/andris9/Nodemailer) or [mailcomposer](https://github.com/andris9/mailcomposer) witch will do send/create the mail for you

**Comment by harmansingh2908** [comment]
how to use mailComposer with haraka.is there any example.please send me some example
Actualy i want  to send mail with attachment

**Comment by azeddineModellium** [comment]
Hi @harmansingh2908 

when i run the your script to send emails i got "TypeError: plugin.logerror is not a function"
any suggestion ?
