### ISSUE TITLE
multiple outbound IPs

### ISSUE THREAD

**Issue by pedroaxl** [haraka/Haraka#442]
Hello guys,

First of all congrats for Haraka. I ran a startup with an email marketing app. We first made the infrastructure using Postfix, then we start using the sending infrastructure of another company. Now we are studying implementing our own infrastructure. I was thinking about developing a simple MTA (we need only to send emails) using Node.js and Redis, but now I found Haraka and it looks like it will perfectly fit our needs :)

Right now I am searching for more information on using multiple outbound IPs. I noticed on the announce of v2.1.0 that it's possible to do it through the mx_hook, but I am a little confused about how. 

thanks

**Comment by manjeshpv** [comment]
@pedroaxl can you please share plugin source code url?

**Comment by ikolubr** [comment]
@pedroaxl, it would be nice if you could share the plugin.
Thank you,
