### ISSUE TITLE
Outbound: treat mails to local domains with connection.relaying set to true as local mails...

### ISSUE THREAD

**Issue by abhas** [haraka/Haraka#471]
Currently what's happenning is that the outbound plugin considers any mail that has `connection.relaying` set to `true` as an outgoing mail - even if the mail is destined to a local domain.

I discovered this while trying to debug LMTP deliveries with dovecot while sending a mail from a client using authentication. LMTP would just not get called if I authenticated to send mail. However, if I disabled SMTP AUTH in my client, then LMTP deliveries would happen just fine.

**Comment by baudehlo** [comment]
This has been fixed by adding the option `enable_outbound` to `smtp_forward` and `proxy`. Closing.
