### ISSUE TITLE
Configure Haraka as outbound server with Auth for PHPMail 5.1

### ISSUE THREAD

**Issue by schamane** [haraka/Haraka#51]
I have configured Haraka as a simple outbound smtp server with flat_file authentification. Wrote small PHP app to test sending outgoing mails with SMTP Auth. If i use Pear PHP Mail module with Sasl_Auth - everything works. It seems to use CRAM-MD5.

Wordpress, which use PHPMail 5.1  http://phpmailer.sourceforge.net dont want to send any mails.

```
       The SMTP debugging output is shown below:
       SMTP -> FROM SERVER:220 telestrekoza.com ESMTP Haraka 0.8.0 ready
       SMTP -> FROM SERVER: 250-Haraka says hi localhost [127.0.0.1]
       250-PIPELINING
       250-8BITMIME
       250-SIZE 500000
       250 AUTH CRAM-MD5
       SMTP -> ERROR: AUTH not accepted from server: 500 Unrecognized command
       SMTP -> FROM SERVER:250 OK
       SMTP Error: Could not authenticate.
```

Thats what i get as trace:

```
     [NOTICE] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB got connection from: 127.0.0.1
     [DEBUG] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB running lookup_rdns hooks
     [DEBUG] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB running connect hooks
     [DEBUG] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB running ehlo hooks
     [DEBUG] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB running capabilities hooks
     [DEBUG] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB running capabilities hook in auth/flat_file plugin
     [DEBUG] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB running unrecognized_command hooks
     [DEBUG] 36DAAB35-27D8-47FE-86CD-80EDBFBA6FCB running unrecognized_command hook in auth/flat_file plugin
```

Hanaka  0.8.0 installed with npm

**Comment by ajay-psd** [comment]
Facing same issue while connecting from remote host, sending mail from local host is working fine.
I have googled and tried many options but couldn not able to figure out where is the problem.
I am using self signed certificate

Kindly Suggest what could be reason for this, how can i resolve this.

below logs is for reference

SMTP CLIENT LOG:

SMTP -> FROM SERVER:220 mydomain.com ESMTP Haraka 2.6.1 ready
<br />SMTP -> FROM SERVER: 250-mydomain.com Hello remotehost.com [54.254.21.x], Haraka is at your service.
250-PIPELINING
250-8BITMIME
250 SIZE 26214400
<br />SMTP -> ERROR: AUTH not accepted from server: 500 Unrecognized command
<br />SMTP -> FROM SERVER:250 OK
<br />SMTP Error: Could not authenticate.

haraka log
[NOTICE] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] connect ip=remoteip port=48063 local_ip=:: local_port=587
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running lookup_rdns hooks
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running connect hooks
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] S: 220 mydomain.com ESMTP Haraka 2.6.1 ready
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] C: EHLO localhost.localdomain state=1
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running ehlo hooks
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running capabilities hooks
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running capabilities hook in auth/flat_file plugin
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [auth/flat_file] Auth disabled for insecure public connection
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] hook=capabilities plugin=auth/flat_file function=hook_capabilities params="" retval=CONT msg=""
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] S: 250-mydomain.com Hello remotedomain.com [54.254.211.170], Haraka is at your service.
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] S: 250-PIPELINING
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] S: 250-8BITMIME
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] S: 250 SIZE 26214400
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] C: AUTH LOGIN state=1
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running unrecognized_command hooks
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running unrecognized_command hook in auth/flat_file plugin
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="AUTH" retval=CONT msg=""
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] S: 500 Unrecognized command
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] C: RSET state=1
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running rset hooks
[PROTOCOL] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] S: 250 OK
[INFO] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] client [54.254.211.170] half closed connection
[DEBUG] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] running disconnect hooks
[NOTICE] [71BAB65C-B181-4816-AC1E-DE34A88B1EA2] [core] disconnect ip=remoteip rdns="remotedomainname.com" helo="localhost.localdomain" relay=N early=N esmtp=Y tls=N pipe=N errors=1 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="500 Unrecognized command" time=0.261

**Comment by msimerson** [comment]
@ajay-psd , Haraka does not advertise (nor accept) AUTH unless the connection is secured. Make sure to enable the `tls` plugin and then have your client upgrade the connection first with STARTTLS.

**Comment by ajay-psd** [comment]
<earlier I though tls plugin works by default>.
I have enabled the tls in config/plugin now and it started working.  

Thank you so much!

**Comment by PawanMakadia** [comment]
Thanks @ajay-psd I was stuck in this for long.
