### ISSUE TITLE
Make email body processing easier

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#567]
Everyone seems to stumble when processing mail body text with Haraka.

The problem is Haraka presents a raw version of the MIME structure tree to the developer. Most people just want the visible text and/or html part, not mess around with the tree structure.

We should have a library (or function) that makes it easier to traverse the body parts and extract the required information.

**Comment by msimerson** [comment]
@baudehlo , " add get_body_html() and get_body_text() functions"

**Comment by KingNoosh** [comment]
Is this still wanted? If so I can take a look at this!

**Comment by msimerson** [comment]
Yes, else we'd have closed the issue. :)

**Comment by msimerson** [comment]
moved to [wiki/TODO](https://github.com/haraka/Haraka/wiki/TODO)
