### ISSUE TITLE
Splitting Transactions

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#573]
Encompassing issue for splitting transactions.

**Comment by Dexus** [comment]
This must still be open? 
Ref: merged PR smtp_client per-domain routes #671

**Comment by msimerson** [comment]
@Dexus , yes. The issue is only partially resolved (in the case of #671, that only works for messages with a single recipient.

**Comment by Dexus** [comment]
ah ok thx for the info :)

**Comment by baudehlo** [comment]
Seems like this should be closed. Making smtp_forward default to sending outbound mail helped a bit.

Re-open if still an issue we need to consider. Otherwise it seems too hard to fix generically.
