### ISSUE TITLE
Convert to using iconv-lite

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#604]
https://github.com/ashtuchkin/iconv-lite

Faster than iconv. And probably works under 0.11+

Downside is error handling looks a bit iffy.

**Comment by Dexus** [comment]
@smfreegard @baudehlo 
I think it can be closed because of incompatibility with standards and functions that needed.

**Comment by msimerson** [comment]
Tested in #605, and opted against. Should this remain open?

**Comment by baudehlo** [comment]
Probably not. It was necessary until iconv converted to using Nan.
