### ISSUE TITLE
How to do "on behalf" or "via" email

### ISSUE THREAD

**Issue by flycatr** [haraka/Haraka#657]
Hi, I love Haraka project so much. The simplicity of the program is amazing. Compare to Postfix which is older than Haraka, I cannot find much example and tutorial from the Internet to my problem. 

I would like Haraka to send email on behalf of my users(same method used by MailChimp, Aweber, Critsend, etc.). So when the email arrive at `Someone` inbox, the header will looks like this:

```
Delivered-To: someone@gmail.com
Return-Path: <bounce@companyserver.com>
...
From: user@example.com
Reply-To: user@example.com
To: <someone@gmail.com>
...
Sender: "Company X Server" <no-reply@companyserver.com>
...
```

... and the email client (e.g Gmail) will show something like this:
`user@example.com` **via** `mail.companyserver.com`.

I already enable `tls`, `auth/flat_file` and `dkim`, but still cannot do `on behalf/via` thing. Please help.

**Comment by harishworks** [comment]
@smfreegard For gmail this approach fails, it still have "Return-Path: <secretary@example.com>" and Received-SPF: softfail, which is bad. I will be grateful if you can suggest further pointers?

I am thinking to update connection.transaction.mail_from.address() in my plugin, is this a good approach?

**Comment by harishworks** [comment]
@smfreegard , It was just impatience, it works fine.
