### ISSUE TITLE
451 Queuing declined or disabled

### ISSUE THREAD

**Issue by cnrx** [haraka/Haraka#68]
Hi there,

I am getting a "451 Queuing declined or disabled, try later" error while attempting to send an email from a user (using LOGIN) listed in auth_flat_file to another (external account).

Starting up Haraka version 0.8.0
[INFO] Loading plugins
[INFO] Loading plugin: auth/flat_file
[DEBUG] registered hook capabilities to auth/flat_file.hook_capabilities
[DEBUG] registered hook unrecognized_command to auth/flat_file.hook_unrecognized_command
[INFO] Loading plugin: rcpt_to.in_host_list
[DEBUG] registered hook rcpt to rcpt_to.in_host_list.hook_rcpt
[DEBUG] [server] running init_master hooks
[NOTICE] Listening on port 587
[INFO] [outbound] Loading outbound queue from /home/haraka_mail_server/haraka/queue

The sender validates fine:
[PROTOCOL] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 S: 250 sender OK

and so does the recipient:
[PROTOCOL] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 S: 250 recipient ok

Haraka then proceeds:
[DEBUG] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 running data hooks
[PROTOCOL] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 S: 354 go ahead, make my day
[DATA] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 C: Date: Tue, 13 Sep 2011 11:47:10 UT
...blah blah blah (message data)
...blah blah blah (message data)
...blah blah blah (message data)
[DEBUG] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 running data_post hooks
[DEBUG] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 running queue hooks
[PROTOCOL] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3.1 S: 451 Queuing declined or disabled, try later
[PROTOCOL] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3 C: QUIT
[DEBUG] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3 running quit hooks
[PROTOCOL] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3 S: 221 closing connection. Have a jolly good day.
[DEBUG] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3 running disconnect hooks
[DEBUG] CDE57FCF-FC69-48F1-B6D9-EB69D86AD5D3 closing client

I tried the test_queue plugin and it placed the message successfully at the /tmp directory.

I am running the process whilst loged in at the root account:
root@Node11:/home/haraka_mail_server/haraka# haraka -c ./
(also tried the full path - also tried from within /root/haraka_mail_server --another test installation)

I have even CHMOD'ed the directory /home/haraka_mail_server/haraka/queue to 777, just in case...

The only plugins I am running are:
auth/flat_file
rcpt_to.in_host_list
(including regex for the recipients)

PS: If I use the plugin relay_all, the message goes out without any issues...

Any ideas? Am I missing something somewhere?

-Best regards

**Comment by AanchalChugh** [comment]
Even I got the same error.. and even I tried with swaks but still the error exists. Can you suggest what may be wrong.
