### ISSUE TITLE
domain reputation DB

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#696]
Along with URIBL, [WoT](https://www.mywot.com) would make another excellent check against incoming email.

**Comment by msimerson** [comment]
[PhishTank](https://www.phishtank.com/developer_info.php) is focused exclusively on phishing but it has a downloading database, making it a viable source of data to check URLs against.

**Comment by msimerson** [comment]
Another one is [Spam404](http://www.spam404.com/domain-blacklist.html). I don't see a data URL, but it appears it'd be pretty easy to scrape the web pages and maintain a local copy of the domain list.

**Comment by msimerson** [comment]
[Artists against 419](http://www.aa419.org/) provides their DB via SOAP, so it could be sucked into a local DB and queried against as well.

**Comment by smfreegard** [comment]
PhishTank data is included in SURBL IIRC.

**Comment by msimerson** [comment]
> PhishTank data is included in SURBL IIRC

And ClamAV UNOFFICIAL.

**Comment by msimerson** [comment]
for future reference: https://github.com/davidandgoliath/domain-profiler

**Comment by baudehlo** [comment]
This ticket seems redundant. I'm going to close - re-open if you think it's important.
