### ISSUE TITLE
make rate_limit plugin smarter

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#754]
# bounces

Increment counters for every user that records the number of invalid recipients they've mailed to, by listening on the bounce hook.
# auth requests

Increment counters every time an IP attempts to authenticate. Basically, make the current back-off mechanism persist across connections. ~~(Once done, remove this feature from `karma` plugin.)~~

**Comment by Dexus** [comment]
@msimerson @smfreegard 
can this be closed or is this a open task?

**Comment by msimerson** [comment]
It's still open. The limit plugin does some of that "smarter" work but the rate_limit plugin also needs additional work.
