### ISSUE TITLE
dnsls plugin timeout problem on latest version

### ISSUE THREAD

**Issue by alvinlaw** [haraka/Haraka#777]
I got a new timeout problem for the github checkout version, while this is not happen on the npm installed version. I am sending a testing email from gmail.

[NOTICE] [-] [core] Listening on :::25
[DEBUG] [-] [server] running init_master hooks
[INFO] [-] [core] [outbound] Loading outbound queue from /root/Haraka/queue
[DEBUG] [-] [dnsbl] looking up: 2.0.0.127.zen.spamhaus.org.
[NOTICE] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] connect ip=209.85.212.169 port=59317 local_ip=:: local_port=25
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] running lookup_rdns hooks
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] running connect hooks
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] running connect hook in access plugin
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] checking 209.85.212.169 against connect.rdns_access.whitelist
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] checking 209.85.212.169 against connect.rdns_access.whitelist_regex
[DEBUG] [-] [access] checking 209.85.212.169 against undefined
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] checking mail-wi0-f169.google.com against connect.rdns_access.whitelist
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] checking mail-wi0-f169.google.com against connect.rdns_access.whitelist_regex
[DEBUG] [-] [access] checking mail-wi0-f169.google.com against undefined
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] checking 209.85.212.169 against connect.rdns_access.blacklist_regex
[DEBUG] [-] [access] checking 209.85.212.169 against undefined
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] checking mail-wi0-f169.google.com against connect.rdns_access.blacklist_regex
[DEBUG] [-] [access] checking mail-wi0-f169.google.com against undefined
[INFO] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] pass:unlisted(conn)
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] hook=connect plugin=access function=rdns_access params="" retval=CONT msg=""
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] running connect hook in access plugin
[INFO] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [access] pass:unlisted(conn), connect:any
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] hook=connect plugin=access function=any params="" retval=CONT msg=""
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] running connect hook in dnsbl plugin
[INFO] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [dnsbl] connnect_first
[DEBUG] [-] [dnsbl] looking up: 169.212.85.209.zen.spamhaus.org.

[CRIT] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] Plugin dnsbl timed out on hook connect - make sure it calls the callback
[INFO] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] hook=connect plugin=dnsbl function=connect_first params="" retval=DENYSOFT msg="plugin timeout"
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] running deny hooks
[PROTOCOL] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] S: 421 plugin timeout
[INFO] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] client [209.85.212.169] half closed connection
[DEBUG] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] running disconnect hooks
[NOTICE] [77B397AA-32D8-4121-91DB-65E8D075BCF2] [core] disconnect ip=209.85.212.169 rdns="mail-wi0-f169.google.com" helo="" relay=N early=N esmtp=N tls=N pipe=N txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="421 plugin timeout" time=30.388

**Comment by steowens** [comment]
I just installed Haraka using apt-get install, is it possible that I am using piece of software that has this bug?  How can I fix it?
