### ISSUE TITLE
Add TLS DANE support

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#779]
Draft:  https://datatracker.ietf.org/doc/draft-ietf-dane-smtp-with-dane/

Requires DNSSEC support which is missing in the stock Node DNS API, but is available from https://github.com/getdnsapi/getdns-node which is the Node bindings to the getdns library which is part of the Unbound project.

**Comment by Synchro** [comment]
Apparently Germany will be requiring DNSSEC and DANE as part of the new EU GDPR regulations coming into force in May 2018, so this will be very welcome.

**Comment by smfreegard** [comment]
> Apparently Germany will be requiring DNSSEC and DANE as part of the new EU GDPR regulations coming into force in May 2018, so this will be very welcome.

Given that there are a lot of DNSSEC issues and roots that aren't signed yet, this would seem to be rather a rash decision IMO.

The issue with DANE is that it requires TLSA records and Node has no lookup in its DNS API for this yet.

To do this now would require using the external getdns library: https://github.com/getdnsapi/getdns

I'm yet to find anyone that publishes TLSA records so that I can test anything though....

**Comment by ge-fa** [comment]
@smfreegard posteo.de publishes TLSA records, in case you're still searching for a provider to test with / against.

**Comment by msimerson** [comment]
migrated to [wiki](https://github.com/haraka/Haraka/wiki)
