### ISSUE TITLE
a way to upgrade $haraka_install/config

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#824]
@baudehlo said:
* proposal: smtp.ini encodes the Haraka version... Then we can give a warning that config may be out of date and also provide a command for upgrading config.
* when we run haraka -i, we generate an SHA dump file of all config files, then an upgrade command can check that and know if a file was changed.

I was thinking config/.checksums

**Comment by baudehlo** [comment]
Fixed by the new config loading changes. Closing.
