### ISSUE TITLE
Warn if someone directly runs haraka.js, or uses an unknown loglevel

### ISSUE THREAD

**Issue by PAStheLoD** [haraka/Haraka#845]
Hello!

I don't know whether it's a feature or a bug, but somehow we ended up running haraka.js and then got really upset when it simply ignored the -c argument. Though it worked if we chdir-ed into the directory.

So, maybe dummy-proofing it wouldn't hurt :)

The same goes for using a loglevel that's not configured in logger.js. (Currently I tried this with 2.5.)

And thanks for this amazingly handy SMTP server.

**Comment by baudehlo** [comment]
Not sure how we could detect that we didn't run bin/haraka instead. I guess maybe there could be something in process.argv we could look at? The problem being that haraka.js is called by bin/haraka.

Also what exactly happens with the unknown log levels? (That should probably be a separate issue)

**Comment by PAStheLoD** [comment]
I'd just set a global variable in bin/haraka, and if that's not detected in haraka.js, I'd gently warn the user.


Interestingly, no log output was produced. (I set INFO, but 2.5 needs LOGINFO.) Opened #846

**Comment by msimerson** [comment]
Admittedly, I read this rather quickly, but does this help?

```js
#!/usr/bin/env node
console.log(process.argv);
```
````
$ node show_argv.js 
[ 'node', '/Users/matt/show_argv.js' ]
````
